/* ball.c -- Ski Resort destructible-and-area-broadcast handler.
 *
 * Source: SKIRESRT.DLL  FUN_801019d8.
 *
 * Same shape as HD_TransfBoxBroadcast but with state code 0 (a
 * "release" or "reset" -- the gondola Ball_1 / Ball_2 swings free
 * when the support transformer is destroyed rather than entering an
 * "off" state).
 *
 * MED.
 */
#include <stdint.h>

extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern void Object_SetState(int obj, int state);

uint32_t SR_BallDestroy(int obj, uint32_t mode, void *impactCtx)
{
    if (mode == 3 || mode != 8) {
        Damage_FromImpulse((uint32_t *)(intptr_t)obj, (int *)impactCtx);
    }
    int killed = Damage_AccumulateOrFire((uint32_t *)(intptr_t)obj, (uint16_t)(uintptr_t)impactCtx);
    if (killed == 0) return 0;

    int32_t px = *(int32_t *)(obj + 0x48);
    int32_t pz = *(int32_t *)(obj + 0x50);
    if (px < 0) px += 0xffff;
    if (pz < 0) pz += 0xffff;
    int16_t rect[4] = {
        (int16_t)((uint32_t)px >> 16),
        (int16_t)((uint32_t)pz >> 16),
        1, 1,
    };
    Object_SetState((int)(uintptr_t)rect, 0);
    return 0xffffffffu;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SKIRESRT.DLL FUN_801019d8  (from analysis/dll/SKIRESRT/decomp/801019d8.c) --- */
// addr: 0x801019d8  name: FUN_801019d8

undefined4 FUN_801019d8(int param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  undefined2 local_10;
  undefined2 local_e;
  undefined2 local_c;
  undefined2 local_a;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  uVar2 = 0;
  if (iVar1 != 0) {
    iVar1 = *(int *)(param_1 + 0x48);
    local_10 = (undefined2)((uint)iVar1 >> 0x10);
    if (iVar1 < 0) {
      local_10 = (undefined2)((uint)(iVar1 + 0xffff) >> 0x10);
    }
    iVar1 = *(int *)(param_1 + 0x50);
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0xffff;
    }
    local_e = (undefined2)((uint)iVar1 >> 0x10);
    local_c = 1;
    local_a = 1;
    FUN_80024718/*0x80024718*/(&local_10,0);
    uVar2 = 0xffffffff;
  }
  return uVar2;
}

#endif  /* GHIDRA REF */
