/* gondola_position.c -- Ski Resort gondola path-position interpolate.
 *
 * Source: SKIRESRT.DLL  FUN_801005e0.
 *
 * Sets the gondola's world position based on a packed 16.16 path-t
 * parameter (param_2):
 *   - if t is in the cable section (& 0x7fff < 0x7000), linearly
 *     interpolate between the two adjacent waypoints on the cable.
 *     Each waypoint is rotated into world coords via GTE_RotateLong-
 *     MatTrans against the path-piece's local matrix.
 *   - else (t >= 0xf000), it's at the terminal pulley: compute the
 *     midpoint of the two pulley anchor points and project a circular
 *     offset using the cos/sin LUT at -0x7ff9f84c/4a.
 *
 * Stores world pos at param_1+0x48/0x4c/0x50, yaw at +0x42.
 *
 * MED.
 */
#include <stdint.h>

extern int  GondolaPath_FindPiece(int piece, uint32_t pickFlag);   /* FUN_8001b038 */
extern void GTE_RotateLongMatTrans(uint32_t *mat, int *src, int *dst);
extern void Object_RefitAABB(int self);
extern uint32_t _DAT_800659fc;

void SK_GondolaPosition(int self, uint16_t t)
{
    *(uint16_t *)(self + 0x46) = t;

    if ((t & 0x7fff) < 0x7000) {
        int tu = (int)(int16_t)t;
        if (tu < 0) tu = 0xfffff000 - tu;
        int *prev = *(int **)(_DAT_800659fc + 0x80);
        int *cur  = (int *)**(int **)(_DAT_800659fc + 0x80);
        while (cur != NULL && (uint32_t)cur[3] < (uint32_t)tu) {
            prev = cur;
            cur  = (int *)*cur;
        }
        int p0  = prev[2];
        int yaw = *(int16_t *)(p0 + 0x42);
        int p1  = cur[2];
        uint32_t frac = ((tu - prev[3]) * 0x100) / (uint32_t)(cur[3] - prev[3]);
        if (yaw < 0) yaw = -yaw;
        uint32_t pick0 = (yaw > 0x400) ? 0x8001u : 0x8000u;
        int wp0 = GondolaPath_FindPiece(p0, pick0);
        int a[4]; int b[4];
        GTE_RotateLongMatTrans((uint32_t *)(intptr_t)(p0 + 0x10), (int *)(intptr_t)(wp0 + 4), a);
        int yaw2 = *(int16_t *)(p1 + 0x42);
        if (yaw2 < 0) yaw2 = -yaw2;
        uint32_t pick1 = (yaw2 > 0x400) ? 0x8001u : 0x8000u;
        if ((int)((uint32_t)t << 16) >= 0) pick1 ^= 1u;
        int wp1 = GondolaPath_FindPiece(p1, pick1);
        GTE_RotateLongMatTrans((uint32_t *)(intptr_t)(p1 + 0x10), (int *)(intptr_t)(wp1 + 4), b);
        int dx = (b[0] - a[0]) * frac; if (dx < 0) dx += 0xff;
        *(int *)(self + 0x48) = a[0] + (dx >> 8);
        int dy = (b[1] - a[1]) * frac; if (dy < 0) dy += 0xff;
        *(int *)(self + 0x4c) = a[1] + (dy >> 8);
    }
    /* Pulley anchor section (independent of above): */
    int base = (t < 0xf000u) ? -0x7ffa0000 : *(int *)(_DAT_800659fc + 0x80);
    int pulley = *(int *)(*(int *)(*(int *)(base + 0x59fc) + 0x88) + 8);
    int p0 = GondolaPath_FindPiece(pulley, 0x8000);
    int p1 = GondolaPath_FindPiece(pulley, 0x8001);
    int mid[3];
    mid[0] = (*(int *)(p0 + 4) + *(int *)(p1 + 4)) / 2;
    mid[1] = (*(int *)(p0 + 8) + *(int *)(p1 + 8)) / 2;
    int dx = *(int *)(p1 + 4) - *(int *)(p0 + 4);
    mid[2] = (*(int *)(p0 + 0xc) + *(int *)(p1 + 0xc)) / 2;
    GTE_RotateLongMatTrans((uint32_t *)(intptr_t)(pulley + 0x10), mid, mid);
    uint32_t yaw = (uint32_t)(-(int16_t)t / 2);
    if (t < 0xf000u) yaw += 0x800;
    *(int16_t *)(self + 0x42) = (int16_t)yaw;
    int sinX = *(int16_t *)((yaw & 0xfff) * 4 + -0x7ff9f84a) * dx;
    if (sinX < 0) sinX += 0x1fff;
    *(int *)(self + 0x48) = mid[0] + (sinX >> 13);
    *(int *)(self + 0x4c) = mid[1];
    int cosX = *(int16_t *)((*(uint16_t *)(self + 0x42) & 0xfff) * 4 + -0x7ff9f84c) * dx;
    if (cosX < 0) cosX += 0x1fff;
    *(int *)(self + 0x50) = mid[2] - (cosX >> 13);
    Object_RefitAABB(self);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SKIRESRT.DLL FUN_801005e0  (from analysis/dll/SKIRESRT/decomp/801005e0.c) --- */
// addr: 0x801005e0  name: FUN_801005e0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801005e0(int param_1,ushort param_2)

{
  int *piVar1;
  int *piVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  undefined4 uVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int local_48;
  int local_44;
  int local_38;
  int local_34;
  int local_28;
  int local_24;
  int local_20;
  
  *(ushort *)(param_1 + 0x46) = param_2;
  if ((param_2 & 0x7fff) < 0x7000) {
    uVar3 = (uint)(short)param_2;
    if ((int)uVar3 < 0) {
      uVar3 = 0xfffff000 - uVar3;
    }
    piVar1 = *(int **)(_DAT_800659fc + 0x80);
    for (piVar2 = (int *)**(int **)(_DAT_800659fc + 0x80);
        (piVar2 != (int *)0x0 && ((uint)piVar2[3] < uVar3)); piVar2 = (int *)*piVar2) {
      piVar1 = piVar2;
    }
    iVar7 = piVar1[2];
    iVar4 = (int)*(short *)(iVar7 + 0x42);
    iVar9 = piVar2[2];
    uVar3 = ((uVar3 - piVar1[3]) * 0x100) / (uint)(piVar2[3] - piVar1[3]);
    if (iVar4 < 0) {
      iVar4 = -iVar4;
    }
    uVar6 = 0x8000;
    if (0x400 < iVar4) {
      uVar6 = 0x8001;
    }
    iVar4 = FUN_8001b038/*0x8001b038*/(iVar7,uVar6);
    GTE_RotateLongMatTrans/*0x80043408*/(iVar7 + 0x10,iVar4 + 4,&local_48);
    iVar4 = (int)*(short *)(iVar9 + 0x42);
    if (iVar4 < 0) {
      iVar4 = -iVar4;
    }
    uVar5 = 0x8000;
    if (0x400 < iVar4) {
      uVar5 = 0x8001;
    }
    if (-1 < (int)((uint)param_2 << 0x10)) {
      uVar5 = uVar5 ^ 1;
    }
    iVar4 = FUN_8001b038/*0x8001b038*/(iVar9,uVar5);
    GTE_RotateLongMatTrans/*0x80043408*/(iVar9 + 0x10,iVar4 + 4,&local_38);
    iVar4 = (local_38 - local_48) * uVar3;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xff;
    }
    *(int *)(param_1 + 0x48) = local_48 + (iVar4 >> 8);
    iVar4 = (local_34 - local_44) * uVar3;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xff;
    }
    *(int *)(param_1 + 0x4c) = local_44 + (iVar4 >> 8);
  }
  iVar4 = -0x7ffa0000;
  if (0xefff < param_2) {
    iVar4 = *(int *)(_DAT_800659fc + 0x80);
  }
  iVar8 = *(int *)(*(int *)(*(int *)(iVar4 + 0x59fc) + 0x88) + 8);
  iVar7 = FUN_8001b038/*0x8001b038*/(iVar8,0x8000);
  iVar9 = FUN_8001b038/*0x8001b038*/(iVar8,0x8001);
  local_28 = (*(int *)(iVar7 + 4) + *(int *)(iVar9 + 4)) / 2;
  local_24 = (*(int *)(iVar7 + 8) + *(int *)(iVar9 + 8)) / 2;
  iVar4 = *(int *)(iVar9 + 4) - *(int *)(iVar7 + 4);
  local_20 = (*(int *)(iVar7 + 0xc) + *(int *)(iVar9 + 0xc)) / 2;
  GTE_RotateLongMatTrans/*0x80043408*/(iVar8 + 0x10,&local_28,&local_28);
  uVar3 = -(int)(short)param_2 / 2;
  if (param_2 < 0xf000) {
    uVar3 = uVar3 + 0x800;
  }
  *(short *)(param_1 + 0x42) = (short)uVar3;
  iVar7 = *(short *)((uVar3 & 0xfff) * 4 + -0x7ff9f84a) * iVar4;
  if (iVar7 < 0) {
    iVar7 = iVar7 + 0x1fff;
  }
  *(int *)(param_1 + 0x48) = local_28 + (iVar7 >> 0xd);
  *(int *)(param_1 + 0x4c) = local_24;
  iVar4 = *(short *)((*(ushort *)(param_1 + 0x42) & 0xfff) * 4 + -0x7ff9f84c) * iVar4;
  if (iVar4 < 0) {
    iVar4 = iVar4 + 0x1fff;
  }
  *(int *)(param_1 + 0x50) = local_20 - (iVar4 >> 0xd);
  FUN_8001d708/*0x8001d708*/(param_1);
  return;
}

#endif  /* GHIDRA REF */
