/* gondola.c -- Ski Resort gondola / lift moving platform integrator.
 *
 * Source: SKIRESRT.DLL  FUN_80101050.
 *
 * Variant of HD_DamLeverTick: every non-mode-2 tick syncs this carrier
 * from its linked gondola/chair object at +0x78, optionally integrating
 * local velocity first. When the linked chair reaches its detach window,
 * the callback releases the carrier, schedules the linked chair, and
 * bumps the global ski-lift cooldown.
 *
 * Used by gondola_1, liftpole_1, liftstation_1, Ball_1/2 (the
 * spinning lift wheels).
 *
 * MED confidence.
 */
#include <stdint.h>

extern void FUN_80020890(uint32_t *obj, int timer);
extern void gap_80031294(uint32_t *self);
extern uint8_t DAT_80065c28[];
extern uint32_t _DAT_800659fc;

static int32_t mips_addu_i32(int32_t a, int32_t b)
{
    return (int32_t)((uint32_t)a + (uint32_t)b);
}

static int32_t rtz_shift_i32(int32_t v, unsigned sh, int32_t bias)
{
    if (v < 0) v = mips_addu_i32(v, bias);
    return v >> sh;
}

uint32_t FUN_80101050(uint32_t *obj, int mode)
{
    if (mode != 2) {
        uint32_t zStep = 0x10000;
        if ((obj[0] & 1u) != 0) {
            obj[9] = (uint32_t)mips_addu_i32((int32_t)obj[9],
                rtz_shift_i32((int32_t)obj[0x20], 7, 0x7f));
            obj[10] = (uint32_t)mips_addu_i32((int32_t)obj[10],
                rtz_shift_i32((int32_t)obj[0x21], 7, 0x7f));
            zStep = (uint32_t)rtz_shift_i32((int32_t)obj[0x22], 7, 0x7f);
            obj[11] = (uint32_t)mips_addu_i32((int32_t)obj[11], (int32_t)zStep);
        }

        uint32_t *linked = (uint32_t *)(uintptr_t)obj[0x1e];
        uint16_t linkedT = *(uint16_t *)((uint8_t *)linked + 0x46);
        obj[4] = linked[4];
        obj[5] = linked[5];
        obj[6] = linked[6];
        obj[7] = linked[7];
        obj[8] = linked[8];
        obj[9] = linked[9];
        obj[10] = linked[10];
        obj[11] = linked[11];
        obj[0x12] = linked[9];
        obj[0x13] = linked[10];
        obj[0x14] = linked[11];
        obj[10] = (uint32_t)mips_addu_i32((int32_t)obj[10], (int32_t)(zStep | 0x5000u));

        if (*(uint16_t *)((uint8_t *)linked + 0x0a) == 0x2c &&
            (int16_t)linkedT < 0x6001 &&
            linkedT < 0xe001) {
            int status = (int16_t)*(uint16_t *)((uint8_t *)obj + 6);
            uint32_t flags = *(uint32_t *)(DAT_80065c28 + ((~status) * 0x18) + 8);
            if ((flags & 0x1000000u) == 0)
                return 0;
            if (linkedT < 0x1001)
                return 0;
            if ((int16_t)linkedT < -0x6fff)
                return 0;
        }

        linked[0x20] = 0;
        linked[0] |= 0x20u;
        FUN_80020890(linked, 0x78);
        gap_80031294(obj);
        obj[0x20] = 0;
        obj[0] = (obj[0] & 0xfeffffddu) | 8u;
        obj[0x21] = 0x5f5;
        obj[0x22] = 0x47800;
    }

    obj[0] |= 2u;
    *(uint16_t *)(uintptr_t)(_DAT_800659fc + 0xa2) = 0x3c;
    return 0;
}

uint32_t SR_GondolaTick(uint32_t *obj, int mode)
{
    return FUN_80101050(obj, mode);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SKIRESRT.DLL FUN_80101050  (from analysis/dll/SKIRESRT/decomp/80101050.c) --- */
// addr: 0x80101050  name: FUN_80101050

undefined4 FUN_80101050(uint *param_1,int param_2)

{
  ushort uVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  uint *puVar5;
  uint uVar6;
  uint uVar7;
  
  if ((param_2 == 0) || (iVar2 = -0x7ffa0000, param_2 != 2)) {
    uVar3 = 0x10000;
    if ((*param_1 & 1) != 0) {
      uVar3 = param_1[0x20];
      if ((int)uVar3 < 0) {
        uVar3 = uVar3 + 0x7f;
      }
      uVar4 = param_1[0x21];
      param_1[9] = param_1[9] + ((int)uVar3 >> 7);
      if ((int)uVar4 < 0) {
        uVar4 = uVar4 + 0x7f;
      }
      uVar3 = param_1[0x22];
      param_1[10] = param_1[10] + ((int)uVar4 >> 7);
      if ((int)uVar3 < 0) {
        uVar3 = uVar3 + 0x7f;
      }
      uVar3 = (int)uVar3 >> 7;
      param_1[0xb] = param_1[0xb] + uVar3;
    }
    puVar5 = (uint *)param_1[0x1e];
    uVar1 = *(ushort *)((int)puVar5 + 0x46);
    uVar4 = puVar5[5];
    uVar6 = puVar5[6];
    uVar7 = puVar5[7];
    param_1[4] = puVar5[4];
    param_1[5] = uVar4;
    param_1[6] = uVar6;
    param_1[7] = uVar7;
    uVar4 = puVar5[9];
    uVar6 = puVar5[10];
    uVar7 = puVar5[0xb];
    param_1[8] = puVar5[8];
    param_1[9] = uVar4;
    param_1[10] = uVar6;
    param_1[0xb] = uVar7;
    uVar4 = puVar5[10];
    uVar6 = puVar5[0xb];
    param_1[0x12] = puVar5[9];
    param_1[0x13] = uVar4;
    param_1[0x14] = uVar6;
    param_1[10] = param_1[10] + (uVar3 | 0x5000);
    if (((*(short *)((int)puVar5 + 10) == 0x2c) && ((short)uVar1 < 0x6001)) &&
       (*(ushort *)((int)puVar5 + 0x46) < 0xe001)) {
      if ((*(uint *)(~(int)*(short *)((int)param_1 + 6) * 0x18 + -0x7ff9a3d0) & 0x1000000) == 0) {
        return 0;
      }
      if (*(ushort *)((int)puVar5 + 0x46) < 0x1001) {
        return 0;
      }
      if ((short)uVar1 < -0x6fff) {
        return 0;
      }
    }
    puVar5[0x20] = 0;
    *puVar5 = *puVar5 | 0x20;
    FUN_80020890/*0x80020890*/(puVar5,0x78);
    func_0x80031294(param_1);
    iVar2 = -0x1000023;
    puVar5 = param_1 + 0x20;
    param_1[0x20] = 0;
    *param_1 = *param_1 & 0xfeffffdd | 8;
    param_1[0x21] = 0x5f5;
    if ((int)((uint)uVar1 << 0x10) < 0) {
      puVar5 = (uint *)0x1;
    }
    puVar5[2] = 0x47800;
  }
  iVar2 = *(int *)(iVar2 + 0x59fc);
  *param_1 = *param_1 | 2;
  *(undefined2 *)(iVar2 + 0xa2) = 0x3c;
  return 0;
}

#endif  /* GHIDRA REF */
