/* lift.c -- Ski Resort lift station event handler.
 *
 * Source: SKIRESRT.DLL  FUN_80101284.
 *
 * Per-event dispatch:
 *   mode 3 (collision with weapon): if collider state == 3 and we
 *     have a paired ski-lift attached at obj[0x20], swap the collider
 *     to that paired object and trigger its tick callback with mode 3.
 *   mode 8: damage circular hit.
 *   mode 2: clear flag bit 0x20.
 *   mode 6 / 1 (init / re-init): claim a slot in the global lift
 *     register at _DAT_800659fc+0x98 (up to 2 simultaneous lifts) and
 *     set roll angle to 0x800 if slot index = 1.
 *
 * MED.
 */
#include <stdint.h>

extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern int8_t *_DAT_800659fc;

uint32_t SR_LiftStation(uint32_t *self, int mode, uint32_t *impulse)
{
    switch (mode) {
    case 3: {
        uint32_t collider = impulse[0];
        if (*(int8_t *)(collider + 4) == 3 && self[0x20] != 0) {
            impulse[0] = self[0x20];
            typedef int16_t (*TickFn)(uint32_t, int);
            TickFn fn = *(TickFn *)(collider + 100);
            if (fn != NULL) fn(collider, 3);
        }
        Damage_FromImpulse(self, (int *)impulse);
        /* fall through */
    }
    case 8:
        Damage_AccumulateOrFire(self, (uint16_t)(uintptr_t)impulse);
        /* fall through */
    case 2:
        self[0] &= ~0x20u;
        /* fall through */
    case 6:
    case 1: {
        int registerSlot = (*(int *)((uintptr_t)_DAT_800659fc + 0x98) != 0);
        self[0] |= 0x108u;
        *(uint32_t **)((uintptr_t)_DAT_800659fc + registerSlot * 4 + 0x98) = self;
        *(uint16_t *)((uint8_t *)self + 0x42) = (uint16_t)(registerSlot << 0xb);
        return 0;
    }
    default:
        return 0;
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SKIRESRT.DLL FUN_80101284  (from analysis/dll/SKIRESRT/decomp/80101284.c) --- */
// addr: 0x80101284  name: FUN_80101284

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80101284(uint *param_1,undefined4 param_2,uint *param_3)

{
  bool bVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  
  switch(param_2) {
  case 3:
    uVar4 = *param_3;
    if ((*(char *)(uVar4 + 4) == '\x03') && (param_1[0x20] != 0)) {
      *param_3 = param_1[0x20];
      if (*(code **)(uVar4 + 100) != (code *)0x0) {
        (**(code **)(uVar4 + 100))(uVar4,3);
      }
    }
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
  case 8:
    FUN_80022320/*0x80022320*/(param_1,param_3);
  case 2:
    *param_1 = *param_1 & 0xffffffdf;
  case 6:
  case 1:
    iVar2 = _DAT_800659fc;
    iVar3 = *(int *)(_DAT_800659fc + 0x98);
    *param_1 = *param_1 | 0x108;
    bVar1 = iVar3 != 0;
    *(uint **)(iVar2 + (uint)bVar1 * 4 + 0x98) = param_1;
    *(ushort *)((int)param_1 + 0x42) = (ushort)bVar1 << 0xb;
    return 0;
  default:
    return 0;
  }
}

#endif  /* GHIDRA REF */
