/* misc.c -- Ski Resort small object handlers.
 *
 * Source: SKIRESRT.DLL
 *   FUN_80101424 -- SR_InstallDefaultTick: on mode-1 (init), bind the
 *                   per-tick callback to the generic SUB_800223dc
 *                   (the default "respond to children" behaviour).
 *   FUN_80101390 -- SR_InsertSortedByY: insert an object into a
 *                   Y-sorted linked list (so the lift station can
 *                   process objects from lowest to highest).
 *   FUN_80102094 -- SR_SnowMachineHit: collision-based event broadcast
 *                   that flips an event id between 0x200 and 0x201
 *                   based on whether the object is "above" the
 *                   level's midpoint -- this is the snowfall trigger.
 *
 * HIGH-MED across all three.
 */
#include <stdint.h>

extern void SUB_800223dc(void);
extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern int  FUN_8002239c(uint32_t *self, int32_t *impulse);
extern uint32_t FUN_80022320(uint32_t *self, uint32_t amount);
extern int  Effects_QueueSnow(int obj);    /* FUN_8003fc94 */
extern void *Object_Pool_Alloc2(void);     /* func_0x80022c54 */
extern int   Object_BroadcastEvent2(int eventId, int eventArg);  /* func_0x80021924 */

extern int8_t  *_DAT_800659fc;
extern uint32_t _DAT_80065b34, _DAT_80065b38;
extern int32_t  DAT_80102154;

void SR_InstallDefaultTick(int obj, int mode)
{
    if (mode == 1) Object_SetCallbackPsxSlot((void *)(uintptr_t)obj, (uintptr_t)&SUB_800223dc);
}

uint32_t FUN_80101424(int obj, int mode)
{
    SR_InstallDefaultTick(obj, mode);
    return 0;
}

void SR_InsertSortedByY(int obj)
{
    uint32_t *newNode = Object_Pool_Alloc2();
    int **list = *(int ***)(_DAT_800659fc + 0x80);
    int *tail = list;
    int *cur  = (int *)list[0];
    if (cur != NULL) {
        int *prev;
        do {
            prev = cur;
            if (*(int *)(obj + 0x50) <= *(int *)(tail[2] + 0x50)) break;
            cur = (int *)*prev;
            tail = prev;
        } while ((int *)*prev != NULL);
    }
    int *next = (int *)tail[1];
    *next = (int)(uintptr_t)newNode;
    tail[1] = (int)(uintptr_t)newNode;
    newNode[0] = (uintptr_t)tail;
    newNode[1] = (uintptr_t)next;
}

void FUN_80101390(int obj)
{
    SR_InsertSortedByY(obj);
}

uint32_t SR_SnowMachineHit(int obj, uint32_t mode, void *impact)
{
    if (mode != 8)
        FUN_8002239c((uint32_t *)(uintptr_t)(uint32_t)obj, (int32_t *)impact);
    int hit = FUN_80022320((uint32_t *)(uintptr_t)(uint32_t)obj, (uint32_t)(uintptr_t)impact);
    if (hit == 0) return 0;
    if (Effects_QueueSnow(obj) != 0) return 0;
    DAT_80102154++;
    if ((DAT_80102154 & 1) == 0) return 0;
    int evt = ((_DAT_80065b34 + _DAT_80065b38) >> 1u < (uint32_t)*(int32_t *)(obj + 0x48))
              ? 0x201 : 0x200;
    return (uint32_t)Object_BroadcastEvent2(9, evt);
}

uint32_t FUN_80102094(int obj, uint32_t mode, void *impact)
{
    return SR_SnowMachineHit(obj, mode, impact);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80101424  (from analysis/dll/SKIRESRT/decomp/80101424.c) --- */
// addr: 0x80101424  name: FUN_80101424

undefined4 FUN_80101424(int param_1,int param_2)

{
  if (param_2 == 1) {
    *(undefined1 **)(param_1 + 100) = &SUB_800223dc;
  }
  return 0;
}

/* --- ? FUN_80101390  (from analysis/dll/SKIRESRT/decomp/80101390.c) --- */
// addr: 0x80101390  name: FUN_80101390

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_80101390(int param_1)

{
  undefined4 *puVar1;
  int *piVar2;
  int *piVar3;
  int *piVar4;
  
  puVar1 = (undefined4 *)FUN_80022c54/*0x80022c54*/();
  piVar4 = *(int **)(_DAT_800659fc + 0x80);
  if ((int *)*piVar4 != (int *)0x0) {
    piVar2 = (int *)*piVar4;
    do {
      piVar3 = piVar2;
      if (*(int *)(param_1 + 0x50) <= *(int *)(piVar4[2] + 0x50)) break;
      piVar2 = (int *)*piVar3;
      piVar4 = piVar3;
    } while ((int *)*piVar3 != (int *)0x0);
  }
  piVar2 = (int *)piVar4[1];
  *piVar2 = (int)puVar1;
  piVar4[1] = (int)puVar1;
  *puVar1 = piVar4;
  puVar1[1] = piVar2;
  return;
}

/* --- ? FUN_80102094  (from analysis/dll/SKIRESRT/decomp/80102094.c) --- */
// addr: 0x80102094  name: FUN_80102094

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int FUN_80102094(int param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  iVar2 = 0;
  if ((iVar1 != 0) && (iVar2 = FUN_8003fc94/*0x8003fc94*/(param_1), iVar2 == 0)) {
    DAT_80102154 = DAT_80102154 + 1;
    iVar2 = 0;
    if ((DAT_80102154 & 1) != 0) {
      uVar3 = 0x200;
      if ((uint)(_DAT_80065b34 + _DAT_80065b38) >> 1 < *(uint *)(param_1 + 0x48)) {
        uVar3 = 0x201;
      }
      iVar2 = FUN_80021924/*0x80021924*/(9,uVar3);
    }
  }
  return iVar2;
}

#endif  /* GHIDRA REF */
