/* snow_emit.c -- Ski Resort snowflake emitter (rate-limited).
 *
 * Source: SKIRESRT.DLL  FUN_80101efc.
 *
 * On mode 9 (= "snowflake-tick"), if our spawn id matches the event's
 * param_3 (selecting only the chosen emitter) AND the global emitter
 * concurrency counter at _DAT_800659fc+0x94 is below 24, spawns a
 * 0x98-byte child snowflake of the parent's kind (+0xa) with random
 * rotation, scaled-down LOD (0x93c/0x1000 = ~57%), spawnId 1000, and
 * status flags 0x180.
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t V8_RandNext(void);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int size, int flags);
extern void Object_RandomizeRotation(uint32_t *obj);
extern int8_t *_DAT_800659fc;

uint32_t SR_SnowEmit(uint32_t *self, int mode, int eventId)
{
    if (mode != 1) {
        if (mode != 9) return 0;
        if (eventId != *(int16_t *)((uintptr_t)self + 6)) return 0;
        if (*(int32_t *)((uintptr_t)_DAT_800659fc + 0x94) > 0x17) return 0;

        uint32_t *p = Object_Pool_AllocFromBank((void *)(uintptr_t)self[0x16],
            *(uint16_t *)((uintptr_t)self + 0xa), 0x98, 0);
        Object_RandomizeRotation(p);
        int32_t lod = (int32_t)p[0x15] * 0x93c;
        if (lod < 0) lod += 0xfff;
        p[0x15] = (uint32_t)(lod >> 12);
        *(uint16_t *)((uintptr_t)p + 6) = 1000;
        *(uint8_t *)((uintptr_t)p + 9) = (uint8_t)V8_RandNext();
        *(uint16_t *)(p + 3) = *(uint16_t *)((uintptr_t)self + 0xe);
        p[0] |= 0x180u;
        p[0x12] = self[0x12];
        p[0x13] = self[0x13];
        p[0x14] = self[0x14];
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SKIRESRT.DLL FUN_80101efc  (from analysis/dll/SKIRESRT/decomp/80101efc.c) --- */
// addr: 0x80101efc  name: FUN_80101efc

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80101efc(uint *param_1,int param_2,int param_3)

{
  undefined1 uVar1;
  uint *puVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  
  if (param_2 != 1) {
    if (param_2 != 9) {
      return 0;
    }
    if (param_3 != *(short *)((int)param_1 + 6)) {
      return 0;
    }
    if (0x17 < *(int *)(_DAT_800659fc + 0x94)) {
      return 0;
    }
    puVar2 = (uint *)FUN_8001ac44/*0x8001ac44*/(param_1[0x16],*(undefined2 *)((int)param_1 + 10),0x98,0);
    FUN_8001dc1c/*0x8001dc1c*/(puVar2);
    iVar3 = puVar2[0x15] * 0x93c;
    if (iVar3 < 0) {
      iVar3 = iVar3 + 0xfff;
    }
    puVar2[0x15] = iVar3 >> 0xc;
    *(undefined2 *)((int)puVar2 + 6) = 1000;
    uVar1 = FUN_80017160/*0x80017160*/();
    *(undefined1 *)((int)puVar2 + 9) = uVar1;
    *(undefined2 *)(puVar2 + 3) = *(undefined2 *)((int)param_1 + 0xe);
    *puVar2 = *puVar2 | 0x180;
    uVar4 = param_1[0x13];
    uVar5 = param_1[0x14];
    puVar2[0x12] = param_1[0x12];
    puVar2[0x13] = uVar4;
    puVar2[0x14] = uVar5;
    puVar2[0x19] = (uint)FUN_80101a94;
    puVar2[0x21] = 0xfffff415;
    iVar3 = puVar2[0x15] * 0x3243;
    if (iVar3 < 0) {
      iVar3 = iVar3 + 0xfff;
    }
    *(short *)(puVar2 + 0x25) = (short)(0x1000000 / (iVar3 >> 0xc));
    FUN_8001d708/*0x8001d708*/(puVar2);
    FUN_800202f4/*0x800202f4*/(puVar2);
    *(int *)(_DAT_800659fc + 0x94) = *(int *)(_DAT_800659fc + 0x94) + 1;
  }
  *param_1 = *param_1 | 0x22;
  return 0;
}

#endif  /* GHIDRA REF */
