/* debris_throw.c -- OilField destructible debris-throw handler.
 *
 * Source: OILFIELD.DLL  FUN_80100e78.
 *
 * On collision (mode 3, 8) tests via Damage_FromImpulse / circular.
 * Mode 1/6/non-matched falls through to spawning debris from a
 * pre-recorded list.
 *
 * Spawn loop:
 *   1. Pick kind from obj+0x80 (which holds the next debris-kind index).
 *   2. Allocate 0x98-byte child from parent's bank.
 *   3. Copy parent matrix + scale by 0xc00 (4.12 fixed = ~0.75x).
 *   4. Randomize rotation; set spawnId 1000; install tick callback
 *      FUN_80100a30 (the per-debris physics).
 *   5. Initial vy = 0xfffff415 (= -0xbeb -- upward toss).
 *   6. Inverse-distance scale at +0x4a from radius via 0x1000000 / r.
 *   7. Object_RegisterDebris (FUN_8003e76c) chains it onto the world.
 *
 * MED.
 */
#include <stdint.h>

extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int size, int flags);
extern void Object_CopyMatrixFromBone(void *outMatrix, int parent, int bonePtr);   /* FUN_8001d68c */
extern void Object_RandomizeRotation(uint32_t *obj);   /* FUN_8001dc1c */
extern void Object_RegisterDebris(uint32_t *obj);      /* FUN_8003e76c */
extern void Object_RegisterInScene(uint32_t *obj);      /* FUN_800202f4 */
extern void Object_DefaultDispatch(uint32_t *obj, int mode, uint32_t arg);  /* SUB_800223dc */
extern uint32_t FUN_80100a30(int self, int mode, int *arg);

static uint32_t scale_4_12(int32_t v, int32_t factor)
{
    int32_t r = v * factor;
    if (r < 0) r += 0xfff;
    return (uint32_t)(r >> 12);
}

void OF_DebrisThrow(int self, uint32_t mode, void *impactCtx)
{
    int size = (int)(intptr_t)impactCtx;
    int hit = 0;

    if (mode == 3 || (mode != 8 && (mode > 3 || mode == 1 || mode == 6))) {
        if (mode == 3 || mode == 8) {
            if (mode == 3) Damage_FromImpulse((uint32_t *)(intptr_t)self, (int *)impactCtx);
            hit = Damage_AccumulateOrFire((uint32_t *)(intptr_t)self, (uint16_t)(uintptr_t)impactCtx);
            size = 0x98;
            if (hit) goto spawn;
        }
        *(uint32_t *)(self + 0x80) =
            (uint32_t)*(uint16_t *)(*(int *)(self + 0x38) + 10);   /* first kind */
    }

spawn:
    {
        uint32_t *child = Object_Pool_AllocFromBank(
            (void *)(uintptr_t)*(uint32_t *)(self + 0x58),
            *(uint16_t *)(self + 0x80), size, 8);
        Object_CopyMatrixFromBone(child + 4, self,
            **(int **)(self + 0x58) + *(int *)(self + 0x80) * 0x1c + 0x1c);
        Object_RandomizeRotation(child);
        child[0x15] = scale_4_12((int32_t)child[0x15], 0xc00);
        *(uint16_t *)((uint8_t *)child + 6) = 1000;
        Object_SetCallbackPsxSlot(child, (uintptr_t)&FUN_80100a30);
        child[0x21] = 0xfffff415u;       /* vy = -0xbeb (upward) */

        int32_t r = (int32_t)child[0x15] * 0x3243;
        if (r < 0) r += 0xfff;
        r >>= 12;
        if (r != 0) {
            *(int16_t *)(child + 0x25) = (int16_t)(0x1000000 / r);
        }

        uint16_t parentAttr = *(uint16_t *)(self + 0xe);
        *(uint16_t *)(child + 3) = parentAttr;
        child[0] |= 0x88u;

        Object_RegisterDebris(child);
        Object_RegisterInScene(child);
        Object_SetCallbackPsxSlot((void *)(intptr_t)self, (uintptr_t)&Object_DefaultDispatch);
    }
}

void FUN_80100e78(int self, uint32_t mode, void *impactCtx)
{
    OF_DebrisThrow(self, mode, impactCtx);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- OILFIELD.DLL FUN_80100e78  (from analysis/dll/OILFIELD/decomp/80100e78.c) --- */
// addr: 0x80100e78  name: FUN_80100e78

void FUN_80100e78(int param_1,uint param_2,undefined4 param_3)

{
  undefined2 uVar1;
  int iVar2;
  uint *puVar3;
  
  if (param_2 == 3) {
LAB_80100ecc:
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
LAB_80100ee0:
    iVar2 = FUN_80022320/*0x80022320*/(param_1,param_3);
    param_3 = 0x98;
    if (iVar2 != 0) goto LAB_80100f18;
  }
  else if (((3 < param_2) || (param_2 != 1)) && (param_2 != 6)) {
    if (param_2 != 8) goto LAB_80100ecc;
    goto LAB_80100ee0;
  }
  *(uint *)(param_1 + 0x80) = (uint)*(ushort *)(*(int *)(param_1 + 0x38) + 10);
LAB_80100f18:
  puVar3 = (uint *)FUN_8001ac44/*0x8001ac44*/(*(undefined4 *)(param_1 + 0x58),*(undefined2 *)(param_1 + 0x80),
                                   param_3,8);
  FUN_8001d68c/*0x8001d68c*/(puVar3 + 4,param_1,
                  **(int **)(param_1 + 0x58) + *(int *)(param_1 + 0x80) * 0x1c + 0x1c);
  FUN_8001dc1c/*0x8001dc1c*/(puVar3);
  iVar2 = puVar3[0x15] * 0xc00;
  if (iVar2 < 0) {
    iVar2 = iVar2 + 0xfff;
  }
  puVar3[0x15] = iVar2 >> 0xc;
  *(undefined2 *)((int)puVar3 + 6) = 1000;
  uVar1 = *(undefined2 *)(param_1 + 0xe);
  puVar3[0x19] = (uint)FUN_80100a30;
  puVar3[0x21] = 0xfffff415;
  iVar2 = puVar3[0x15] * 0x3243;
  *(undefined2 *)(puVar3 + 3) = uVar1;
  *puVar3 = *puVar3 | 0x88;
  if (iVar2 < 0) {
    iVar2 = iVar2 + 0xfff;
  }
  *(short *)(puVar3 + 0x25) = (short)(0x1000000 / (iVar2 >> 0xc));
  FUN_8003e76c/*0x8003e76c*/(puVar3);
  FUN_800202f4/*0x800202f4*/(puVar3);
  *(undefined1 **)(param_1 + 100) = &SUB_800223dc;
  return;
}

#endif  /* GHIDRA REF */
