/* pipe_end.c -- Oil Fields pipe_end / OilPump child spawner.
 *
 * Source: OILFIELD.DLL  FUN_80100870.
 *
 * Allocates a 0x9c-byte projectile, copies the parent's rotation
 * matrix (parent[4..7]) and pos (parent[8..0xb]) into the child,
 * then snaps the child's posY to the terrain height under it.
 * Configures: tick=FUN_80100668, LOD radius 0x40000, type 7,
 * sub-state 10, mesh=DAT_801000a8, texture=DAT_80101148, lifetime
 * counter 4.
 *
 * Used by `pipe_end_1` / `OilPump_1` for the secondary oil
 * spray effect after primary destruction.
 *
 * MED confidence.
 */
#include <stdint.h>

extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern uint32_t *Object_Pool_Alloc(uint32_t size);
extern int32_t Terrain_HeightAt(uint32_t x, uint32_t z);
extern void FUN_800202f4(uint32_t *obj);                  /* Object_RegisterInScene */
extern void FUN_80020890(uint32_t *obj, int timer);        /* Object_SchedulePostEvent */
extern int FUN_8002239c(uint32_t *self, int32_t *impulse); /* Damage_FromImpulse */
extern uint32_t FUN_80022320(uint32_t *self, uint32_t amount);
extern int FUN_8004410c(void);
extern void FUN_8004483c(int voice, uint32_t bank, int sfx, const void *pos);
extern void *FUN_80100668;
extern uint32_t _DAT_800658fc;
extern uint8_t DAT_801000a8[];
extern uint8_t DAT_80101148[];

static uint32_t *OF_PipeEndSpawnChild(uint32_t *parent)
{
    uint32_t *c = Object_Pool_Alloc(0x9c);
    c[4] = parent[4];
    c[5] = parent[5];
    c[6] = parent[6];
    c[7] = parent[7];
    c[8]  = parent[8];
    c[9]  = parent[9];
    c[10] = parent[10];
    c[11] = parent[11];
    /* Snap to terrain. */
    c[10] = (uint32_t)Terrain_HeightAt(c[9], c[11]);

    Object_SetCallbackPsxSlot(c, (uintptr_t)&FUN_80100668);
    c[0x15] = 0x40000;
    *((int8_t *)c + 4) = 7;
    *((uint16_t *)c + 6) = 10;
    c[0x17] = (uintptr_t)DAT_801000a8;
    c[0x26] = (uintptr_t)DAT_80101148;
    *((uint16_t *)c + 0x41) = 4;     /* +0x82 i16 */
    c[0x21] = 0x200;
    c[0] |= 0x184u;
    c[0x22] = 0xfffffa00u;
    c[0x23] = 0;

    FUN_800202f4(c);
    FUN_80020890(c, 0x3c);
    FUN_80020890(parent, 0x384);
    FUN_8004483c(FUN_8004410c(), _DAT_800658fc, 0x3b, c + 9);
    return c;
}

uint32_t FUN_80100870(uint32_t *parent, uint32_t mode, int32_t *impulse)
{
    if (mode != 3) {
        if (mode == 8)
            goto damage_amount;
        OF_PipeEndSpawnChild(parent);
    }

    FUN_8002239c(parent, impulse);

damage_amount:
    if (FUN_80022320(parent, (uint32_t)(uintptr_t)impulse) != 0
        && (parent[0] & 1u) == 0)
    {
        FUN_80020890(parent, 0xf0);
        parent[0x1d] = 0;
    }
    return 0;
}

void OF_PipeEndSpawn(uint32_t *parent)
{
    (void)OF_PipeEndSpawnChild(parent);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- OILFIELD.DLL FUN_80100870  (from analysis/dll/OILFIELD/decomp/80100870.c) --- */
// addr: 0x80100870  name: FUN_80100870

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100870(uint *param_1,uint param_2,undefined4 param_3)

{
  uint *puVar1;
  undefined4 uVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  
  if (param_2 != 3) {
    if (((3 < param_2) || (param_2 != 2)) && (param_2 == 8)) goto LAB_801009e0;
    puVar1 = (uint *)FUN_8001d470/*0x8001d470*/(0x9c);
    uVar4 = param_1[5];
    uVar5 = param_1[6];
    uVar6 = param_1[7];
    puVar1[4] = param_1[4];
    puVar1[5] = uVar4;
    puVar1[6] = uVar5;
    puVar1[7] = uVar6;
    uVar4 = param_1[9];
    uVar5 = param_1[10];
    uVar6 = param_1[0xb];
    puVar1[8] = param_1[8];
    puVar1[9] = uVar4;
    puVar1[10] = uVar5;
    puVar1[0xb] = uVar6;
    uVar4 = Terrain_HeightAt/*0x80025400*/(puVar1[9],puVar1[0xb]);
    puVar1[10] = uVar4;
    puVar1[0x19] = (uint)FUN_80100668;
    puVar1[0x15] = 0x40000;
    *(undefined1 *)(puVar1 + 1) = 7;
    *(undefined2 *)(puVar1 + 3) = 10;
    puVar1[0x17] = (uint)&DAT_801000a8;
    puVar1[0x26] = (uint)&DAT_80101148;
    *(undefined2 *)((int)puVar1 + 0x82) = 4;
    puVar1[0x21] = 0x200;
    *puVar1 = *puVar1 | 0x184;
    puVar1[0x22] = 0xfffffa00;
    puVar1[0x23] = 0;
    FUN_800202f4/*0x800202f4*/(puVar1);
    FUN_80020890/*0x80020890*/(puVar1,0x3c);
    FUN_80020890/*0x80020890*/(param_1,900);
    uVar2 = FUN_8004410c/*0x8004410c*/();
    param_3 = 0x3b;
    FUN_8004483c/*0x8004483c*/(uVar2,_DAT_800658fc,0x3b,puVar1 + 9);
  }
  FUN_8002239c/*0x8002239c*/(param_1,param_3);
LAB_801009e0:
  iVar3 = FUN_80022320/*0x80022320*/(param_1,param_3);
  if ((iVar3 != 0) && ((*param_1 & 1) == 0)) {
    FUN_80020890/*0x80020890*/(param_1,0xf0);
    param_1[0x1d] = 0;
  }
  return 0;
}

#endif  /* GHIDRA REF */
