/* rig_destroy.c -- Oil Field rig_1 destruction broadcast.
 *
 * Source: OILFIELD.DLL  FUN_80101028.
 *
 * On damage collision: takes hit, computes 1x1 cell at obj's world
 * (x, z), broadcasts state 0x8f80 (= "ruins") via Object_SetState,
 * then walks the global obstacle chain (DAT_80065a50) and clears
 * flag bit 2 on every entry whose spawnId matches our spawnId --
 * essentially "find all my siblings and mark them as no-longer-active".
 *
 * MED.
 */
#include <stdint.h>

extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern void Object_SetState(int obj, int state);
extern int32_t **_DAT_80065a50;

uint32_t OF_RigDestroy(int obj, uint32_t mode, void *impact)
{
    int hit = 0;
    if ((mode == 3 || mode != 8) && (hit = Damage_FromImpulse((uint32_t *)(intptr_t)obj, (int *)impact)) != 0)
        goto fire;
    if ((hit = Damage_AccumulateOrFire((uint32_t *)(intptr_t)obj, (uint16_t)(uintptr_t)impact)) == 0)
        return 0;

fire: {
    int32_t px = *(int32_t *)(obj + 0x48);
    int32_t pz = *(int32_t *)(obj + 0x50);
    if (px < 0) px += 0xffff;
    if (pz < 0) pz += 0xffff;
    int16_t rect[4] = {
        (int16_t)((uint32_t)px >> 16),
        (int16_t)((uint32_t)pz >> 16),
        1, 1,
    };
    Object_SetState((int)(uintptr_t)rect, 0x8f80);
}

    /* Walk obstacle chain, clear "active" bit on all matching spawnIds. */
    int32_t *node = (int32_t *)_DAT_80065a50[0];
    int32_t **prev = _DAT_80065a50;
    while (node != NULL) {
        uint32_t *payload = (uint32_t *)(uintptr_t)prev[2];
        if (*(int16_t *)((uintptr_t)payload + 6) == *(int16_t *)(obj + 6)) {
            payload[0] &= ~2u;
        }
        prev = (int32_t **)node;
        node = (int32_t *)*node;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- OILFIELD.DLL FUN_80101028  (from analysis/dll/OILFIELD/decomp/80101028.c) --- */
// addr: 0x80101028  name: FUN_80101028

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80101028(int param_1,int param_2,undefined4 param_3)

{
  int *piVar1;
  int *piVar2;
  int *piVar3;
  int iVar4;
  uint *puVar5;
  undefined2 local_10;
  undefined2 local_e;
  undefined2 local_c;
  undefined2 local_a;
  
  if ((((param_2 == 3) || (param_2 != 8)) && (iVar4 = FUN_8002239c/*0x8002239c*/(param_1,param_3), iVar4 != 0))
     || (iVar4 = FUN_80022320/*0x80022320*/(param_1,param_3), iVar4 != 0)) {
    iVar4 = *(int *)(param_1 + 0x48);
    local_10 = (undefined2)((uint)iVar4 >> 0x10);
    if (iVar4 < 0) {
      local_10 = (undefined2)((uint)(iVar4 + 0xffff) >> 0x10);
    }
    iVar4 = *(int *)(param_1 + 0x50);
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xffff;
    }
    local_e = (undefined2)((uint)iVar4 >> 0x10);
    local_c = 1;
    local_a = 1;
    FUN_80024718/*0x80024718*/(&local_10,0x8f80);
    piVar3 = (int *)*_DAT_80065a50;
    piVar2 = _DAT_80065a50;
    while (piVar1 = piVar3, piVar1 != (int *)0x0) {
      puVar5 = (uint *)piVar2[2];
      if (*(short *)((int)puVar5 + 6) == *(short *)(param_1 + 6)) {
        *puVar5 = *puVar5 & 0xfffffffd;
      }
      piVar2 = piVar1;
      piVar3 = (int *)*piVar1;
    }
  }
  return 0;
}

#endif  /* GHIDRA REF */
