/* rig_init.c -- Oil Fields rig_1 init.
 *
 * Source: OILFIELD.DLL  FUN_801001cc.
 *
 * On mode-1 (init), allocates a child object (size 0x24, type 0x80,
 * flags 8) from the vehicle pool at _DAT_800737d8 via FUN_8001ac44,
 * zeroes the child's +0x5c (last-state slot), sets the child's roll
 * angle via `V8_RandNext() * parent_x_extent >> 15` (random spin
 * offset), then attaches the child to the parent via FUN_8001b038
 * (alloc bone slot) + FUN_8001b2fc (link). Installs the default per-
 * tick handler SUB_800223dc and sets parent flag 0x4 (active). Then
 * unconditionally falls through to the default handler.
 *
 * Used by `rig_1`, `pipe_end_1`, `OilPump_1` -- all the same physics
 * (random initial yaw, then default child-management).
 *
 * MED.
 */
#include <stdint.h>

extern int   Object_Pool_AllocFromBank(void *bank, int type, int u, int flags);  /* FUN_8001ac44 */
extern uint32_t V8_RandNext(void);
extern int   Bone_AllocSlot(uint32_t *obj, int slot);     /* FUN_8001b038 */
extern void  Bone_AttachChild(uint32_t *obj, int slot, int child);  /* FUN_8001b2fc */
extern void  SUB_800223dc(void);
extern void  Object_DefaultDispatch(uint32_t *obj, int mode, uint32_t arg);  /* func_0x800223dc */

extern void **_DAT_800737d8;

void OF_RigInit(uint32_t *obj, int mode, uint32_t arg)
{
    if (mode == 1) {
        int child = Object_Pool_AllocFromBank(_DAT_800737d8, 0x24, 0x80, 8);
        *(int *)(child + 0x5c) = 0;
        int extent = **(int **)((uintptr_t)_DAT_800737d8 + 4);
        *(int16_t *)(child + 0x46) = (int16_t)((int)V8_RandNext() * extent >> 15);
        int slot = Bone_AllocSlot(obj, 0x8000);
        Bone_AttachChild(obj, slot, child);
        obj[0x19] = (uintptr_t)SUB_800223dc;
        obj[0]  |= 4u;
    }
    Object_DefaultDispatch(obj, mode, arg);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- OILFIELD.DLL FUN_801001cc  (from analysis/dll/OILFIELD/decomp/801001cc.c) --- */
// addr: 0x801001cc  name: FUN_801001cc

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801001cc(uint *param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  
  if (param_2 == 1) {
    iVar1 = FUN_8001ac44/*0x8001ac44*/(_DAT_800737d8,0x24,0x80,8);
    *(undefined4 *)(iVar1 + 0x5c) = 0;
    iVar2 = FUN_80017160/*0x80017160*/();
    *(short *)(iVar1 + 0x46) = (short)(iVar2 * **(int **)(_DAT_800737d8 + 4) >> 0xf);
    uVar3 = FUN_8001b038/*0x8001b038*/(param_1,0x8000);
    FUN_8001b2fc/*0x8001b2fc*/(param_1,uVar3,iVar1);
    param_1[0x19] = (uint)&SUB_800223dc;
    *param_1 = *param_1 | 4;
  }
  func_0x800223dc(param_1,param_2,param_3);
  return;
}

#endif  /* GHIDRA REF */
