/* sphere.c -- Oil Fields gas-sphere collision handler.
 *
 * Source: OILFIELD.DLL  FUN_80100540.
 *
 * Handles the destructible gas-storage sphere (sphere_1). State
 * transitions:
 *
 *   mode 2 (init):  set sub-state 0x3c on a placeholder, then 0xf0
 *                   on the parent, queue an explosion sound (sfx 0x3b
 *                   via Audio_PlaySfxAtPos), and allocate the bone
 *                   slot pair for the child gas-cloud effect.
 *   mode 1:         allocate the bone slot (without the sound).
 *   mode 3 / 8:     collision tests.
 *   default:        same as mode 2 (init / re-init).
 *
 * On any successful circular collision (after either path), if the
 * gas-cloud child still exists at obj+0x74, set its sub-state to 0
 * (active explosion frame), promote the parent to sub-state 0xf0,
 * and clear obj+0x74 so the gas-cloud isn't re-triggered.
 *
 * MED confidence.
 */
#include <stdint.h>

extern void Object_SetSubState(int obj, int sub);    /* FUN_80020890 */
extern uint32_t SfxChannel_Acquire(void);             /* FUN_8004410c */
extern void Audio_PlaySfxAtPos(uint32_t ch, uint32_t bank, int sfxId, int posXyzAddr);  /* FUN_8004483c */
extern int  Bone_AllocSlot(int parent, uint16_t slotKey);    /* FUN_8001b038 */
extern int  Collision_AgainstTerrain(int obj, int impact);
extern int  Collision_Circular(int obj, int impact);
extern uint32_t _DAT_800658fc;

uint32_t OF_SphereTick(int obj, uint32_t mode, void *impact)
{
    int gasCloudObj = 2;

    if (mode == 2 || mode == 1 || mode == 3 || mode == 8) {
        if (mode == 2) goto initOrSpawn;
        if (mode == 1) goto bindSlot;
        if (mode == 8) goto checkCircular;
        Collision_AgainstTerrain(obj, (int)(intptr_t)impact);
        goto checkCircular;
    }

initOrSpawn:
    Object_SetSubState(gasCloudObj, 0x3c);
    Object_SetSubState(obj, 0xf0);
    {
        uint32_t ch = SfxChannel_Acquire();
        Audio_PlaySfxAtPos(ch, _DAT_800658fc, 0x3b, obj + 0x24);
    }
bindSlot:
    {
        int slot = Bone_AllocSlot(obj, 0x8000);
        *(int *)(obj + 0x70) = slot;
        *(int *)(obj + 0x74) = slot;
    }
checkCircular:
    {
        int hit = Collision_Circular(obj, (int)(intptr_t)impact);
        if (hit != 0 && *(int *)(obj + 0x74) != 0) {
            Object_SetSubState(*(int *)(obj + 0x74), 0);
            Object_SetSubState(obj, 0xf0);
            *(int *)(obj + 0x74) = 0;
        }
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- OILFIELD.DLL FUN_80100540  (from analysis/dll/OILFIELD/decomp/80100540.c) --- */
// addr: 0x80100540  name: FUN_80100540

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100540(int param_1,uint param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = 2;
  if (param_2 == 2) {
LAB_80100594:
    FUN_80020890/*0x80020890*/(iVar1,0x3c);
    FUN_80020890/*0x80020890*/(param_1,0xf0);
    uVar2 = FUN_8004410c/*0x8004410c*/();
    param_3 = 0x3b;
    FUN_8004483c/*0x8004483c*/(uVar2,_DAT_800658fc,0x3b,iVar1 + 0x24);
LAB_801005e0:
    uVar2 = FUN_8001b038/*0x8001b038*/(param_1,0x8000);
    *(undefined4 *)(param_1 + 0x70) = uVar2;
    *(undefined4 *)(param_1 + 0x74) = uVar2;
  }
  else {
    if ((param_2 < 3) && (param_2 == 1)) goto LAB_801005e0;
    if (param_2 != 3) {
      iVar1 = 0;
      if (param_2 == 8) goto LAB_80100614;
      goto LAB_80100594;
    }
  }
  FUN_8002239c/*0x8002239c*/(param_1,param_3);
LAB_80100614:
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  if ((iVar1 != 0) && (*(int *)(param_1 + 0x74) != 0)) {
    FUN_80020890/*0x80020890*/(*(int *)(param_1 + 0x74),0);
    FUN_80020890/*0x80020890*/(param_1,0xf0);
    *(undefined4 *)(param_1 + 0x74) = 0;
  }
  return 0;
}

#endif  /* GHIDRA REF */
