/* steam_rig.c -- Oil Fields steam-vent rig periodic emit.
 *
 * Source: OILFIELD.DLL  FUN_80100668.
 *
 * Sibling to rig_emit.c (FUN_801002b0) but uses a different child-
 * particle layout. Per-tick:
 *   - countdown at self+0x80 decrements; on -1 spawn a steam puff:
 *       * pool-alloc puff via func_0x80040378(self+0x98 bank)
 *       * orientation taken from a 0x1000-entry sin/cos table at
 *         -0x7ff9f84c.. (4.12-fixed unit circle) indexed by 12 bits
 *         from the RNG
 *       * velocity X/Z scaled by self+0x84 (per-rig strength)
 *       * Y velocity = self+0x88 + (rand() * self+0x88 >> 15) jitter
 *       * tick callback puff[0x19] = 0x80040470 (puff-tick)
 *       * play world FX via FUN_8001d4f0
 *     reload countdown from self+0x82
 *   - Each child @+0x38 -> +0x34 chain: pos += vel (offsets +0x24..2c
 *     and +0x88..90)
 *   - Object_RetireDeferred(self) if mode==0
 *
 * mode dispatch:
 *   0  -- per-tick (above)
 *   2  -- damage-applied (sets cooldown sentinel 0xffff)
 *   3  -- impactor collision; if impactor.kind == 2 ring-flash and
 *         apply damage at &DAT_80100090
 *
 * MED.
 */
#include <stdint.h>

extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern void *Generic_PoolAlloc(uint32_t bank);                   /* func_0x80040378 */
extern int   Rand255(void);                                      /* FUN_80017160 */
extern void  Object_BumpSubstate_Or_FX(int obj);                 /* FUN_8001d4f0 */
extern void  Object_RetireDeferred(int self);                    /* FUN_800205f8 */
extern void  FX_RingFlash(int imp, void *p, int spawnXyz);       /* FUN_800176f8 */
extern void  Damage_TouchImpactor(int imp);                      /* FUN_8002c3ac */
extern uint8_t DAT_80100090;
extern const int16_t g_v8_sincostbl[8192];
extern int LAB_8004042c(int obj, int event, int param3);

uint32_t OF_SteamRig(int self, uint32_t mode, int *arg)
{
    uint32_t hit = 2;
    if (mode == 2) goto seal;
    if (mode != 3) {
            int16_t cd = *(int16_t *)(self + 0x80) - 1;
            *(int16_t *)(self + 0x80) = cd;
            if (cd == -1) {
                uint32_t *puff = (uint32_t *)Generic_PoolAlloc(*(uint32_t *)(self + 0x98));
                if (puff != NULL) {
                    int aimIdx = Rand255() & 0xfff;
                    *puff |= 0x410u;
                    int sx = *(int *)(self + 0x84) * g_v8_sincostbl[aimIdx * 2 + 0];
                    if (sx < 0) sx += 0xfff;
                    puff[0x22] = sx >> 12;
                    int sz = *(int *)(self + 0x84) * g_v8_sincostbl[aimIdx * 2 + 1];
                    if (sz < 0) sz += 0xfff;
                    puff[0x24] = sz >> 12;
                    int r2 = Rand255();
                    int v  = *(int *)(self + 0x88);
                    puff[9] = puff[10] = puff[0xb] = 0;
                    Object_SetCallbackPsxSlot(puff, (uintptr_t)&LAB_8004042c);
                    puff[0x23] = v + ((r2 * v) >> 15);
                    Object_BumpSubstate_Or_FX(self);
                }
                *(int16_t *)(self + 0x80) = *(int16_t *)(self + 0x82);
            }
            for (int c = *(int *)(self + 0x38); c != 0; c = *(int *)(c + 0x34)) {
                *(int *)(c + 0x24) += *(int *)(c + 0x88);
                *(int *)(c + 0x28) += *(int *)(c + 0x8c);
                *(int *)(c + 0x2c) += *(int *)(c + 0x90);
            }
            Object_RetireDeferred(self);
            hit = 0;
    }
    if (arg == NULL) return 0;
    int imp = *arg;
    if (*(uint8_t *)(imp + 4) != hit) return 0;
    FX_RingFlash(imp, &DAT_80100090, self + 0x48);
    Damage_TouchImpactor(imp);
seal:
    *(uint16_t *)(self + 0x80) = 0xffff;
    return 0;
}

uint32_t FUN_80100668(int self, uint32_t mode, int *arg)
{
    return OF_SteamRig(self, mode, arg);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- OILFIELD.DLL FUN_80100668  (from analysis/dll/OILFIELD/decomp/80100668.c) --- */
// addr: 0x80100668  name: FUN_80100668

undefined4 FUN_80100668(int param_1,uint param_2,int *param_3)

{
  short sVar1;
  uint uVar2;
  uint *puVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  uint extraout_v1;
  
  uVar6 = 2;
  if (param_2 != 2) {
    uVar2 = 3;
    if (((param_2 < 3) && (uVar2 = 0, param_2 == 0)) || (param_2 != uVar2)) {
      sVar1 = *(short *)(param_1 + 0x80) + -1;
      *(short *)(param_1 + 0x80) = sVar1;
      if (sVar1 == -1) {
        puVar3 = (uint *)func_0x80040378(*(undefined4 *)(param_1 + 0x98));
        if (puVar3 != (uint *)0x0) {
          uVar6 = FUN_80017160/*0x80017160*/();
          iVar4 = (uVar6 & 0xfff) * 4;
          *puVar3 = *puVar3 | 0x410;
          iVar5 = *(int *)(param_1 + 0x84) * (int)*(short *)(iVar4 + -0x7ff9f84c);
          if (iVar5 < 0) {
            iVar5 = iVar5 + 0xfff;
          }
          puVar3[0x22] = iVar5 >> 0xc;
          iVar5 = *(int *)(param_1 + 0x84) * (int)*(short *)(iVar4 + -0x7ff9f84a);
          if (iVar5 < 0) {
            iVar5 = iVar5 + 0xfff;
          }
          puVar3[0x24] = iVar5 >> 0xc;
          iVar5 = FUN_80017160/*0x80017160*/();
          iVar4 = *(int *)(param_1 + 0x88);
          puVar3[0xb] = 0;
          puVar3[10] = 0;
          puVar3[9] = 0;
          puVar3[0x19] = 0x80040470;
          puVar3[0x23] = iVar4 + (iVar5 * iVar4 >> 0xf);
          FUN_8001d4f0/*0x8001d4f0*/(param_1);
        }
        *(undefined2 *)(param_1 + 0x80) = *(undefined2 *)(param_1 + 0x82);
      }
      for (iVar5 = *(int *)(param_1 + 0x38); iVar5 != 0; iVar5 = *(int *)(iVar5 + 0x34)) {
        param_3 = *(int **)(iVar5 + 0x8c);
        *(int *)(iVar5 + 0x24) = *(int *)(iVar5 + 0x24) + *(int *)(iVar5 + 0x88);
        *(int *)(iVar5 + 0x28) = *(int *)(iVar5 + 0x28) + (int)param_3;
        *(int *)(iVar5 + 0x2c) = *(int *)(iVar5 + 0x2c) + *(int *)(iVar5 + 0x90);
      }
      FUN_800205f8/*0x800205f8*/(param_1);
      uVar6 = extraout_v1;
    }
    iVar5 = *param_3;
    if (*(byte *)(iVar5 + 4) != uVar6) {
      return 0;
    }
    FUN_800176f8/*0x800176f8*/(iVar5,&DAT_80100090,param_1 + 0x48);
    FUN_8002c3ac/*0x8002c3ac*/(iVar5);
  }
  *(undefined2 *)(param_1 + 0x80) = 0xffff;
  return 0;
}

#endif  /* GHIDRA REF */
