/* manhole_spawn.c -- Casino City manhole_1 / Burger_sign_1 spawn helper.
 *
 * Source: CASNOCTY.DLL  FUN_801004e8.
 *
 * On mode 2 (re-trigger from a state machine), spawns a child object
 * (size 0x9c) copying the parent's rotation matrix and pos, snapping
 * to the terrain. The child:
 *   - LOD radius 0x40000 (large draw distance)
 *   - state byte 7
 *   - mesh from DAT_80100094 (manhole cover texture)
 *   - lifetime counter 4 (animation frames)
 *   - sub-state 0x200
 *   - status flags 0x184 (active + collidable + animated)
 *   - vx = -0x800, vz = 0 (sliding sideways)
 *   - tick callback = FUN_801002bc (manhole physics in this same DLL)
 *
 * Then Object_RegisterInScene + sub-state set to 0x3c + parent
 * "cleanup spawn" (FUN_8001ac08).
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t *Object_Pool_Alloc(uint32_t size);
extern int32_t Terrain_HeightAt(uint32_t x, uint32_t z);
extern void Object_RegisterInScene(uint32_t *obj);
extern void Object_SetSubState(int obj, int sub);
extern void Object_CleanupSpawn(uint32_t *parent);   /* FUN_8001ac08 */
extern uint32_t FUN_801002bc;
extern uint8_t  DAT_80100094[];

uint32_t CC_ManholeSpawn(uint32_t *parent, uint32_t mode, int *impulse)
{
    if (mode != 2) return 0;

    uint32_t *p = Object_Pool_Alloc(0x9c);
    p[4] = parent[4];
    p[5] = parent[5];
    p[6] = parent[6];
    p[7] = parent[7];
    p[8]  = parent[8];
    p[9]  = parent[9];
    p[10] = parent[10];
    p[11] = parent[11];
    p[10] = (uint32_t)Terrain_HeightAt(p[9], p[11]);

    p[0x19] = (uintptr_t)&FUN_801002bc;
    p[0x15] = 0x40000;
    *((int8_t *)p + 4) = 7;
    p[0x17] = (uintptr_t)DAT_80100094;
    *((uint16_t *)p + 0x41) = 4;
    p[0x21] = 0x200;
    *(int16_t *)(p + 3) = (int16_t)mode;
    p[0] |= 0x184u;
    p[0x22] = 0xfffff800u;   /* vx = -0x800 */
    p[0x23] = 0;

    Object_RegisterInScene(p);
    Object_SetSubState((int)(uintptr_t)p, 0x3c);
    Object_CleanupSpawn(parent);
    (void)impulse;
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- CASNOCTY.DLL FUN_801004e8  (from analysis/dll/CASNOCTY/decomp/801004e8.c) --- */
// addr: 0x801004e8  name: FUN_801004e8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_801004e8(uint *param_1,uint param_2,int *param_3)

{
  uint *puVar1;
  undefined4 uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  
  if (param_2 == 2) {
LAB_8010057c:
    puVar1 = (uint *)FUN_8001d470/*0x8001d470*/(0x9c);
    uVar3 = param_1[5];
    uVar4 = param_1[6];
    uVar5 = param_1[7];
    puVar1[4] = param_1[4];
    puVar1[5] = uVar3;
    puVar1[6] = uVar4;
    puVar1[7] = uVar5;
    uVar3 = param_1[9];
    uVar4 = param_1[10];
    uVar5 = param_1[0xb];
    puVar1[8] = param_1[8];
    puVar1[9] = uVar3;
    puVar1[10] = uVar4;
    puVar1[0xb] = uVar5;
    uVar3 = Terrain_HeightAt/*0x80025400*/(puVar1[9],puVar1[0xb]);
    puVar1[10] = uVar3;
    puVar1[0x19] = (uint)FUN_801002bc;
    puVar1[0x15] = 0x40000;
    *(undefined1 *)(puVar1 + 1) = 7;
    puVar1[0x17] = (uint)&DAT_80100094;
    *(undefined2 *)((int)puVar1 + 0x82) = 4;
    puVar1[0x21] = 0x200;
    *(short *)(puVar1 + 3) = (short)param_2;
    *puVar1 = *puVar1 | 0x184;
    puVar1[0x22] = 0xfffff800;
    puVar1[0x23] = 0;
    FUN_800202f4/*0x800202f4*/(puVar1);
    FUN_80020890/*0x80020890*/(puVar1,0x3c);
    FUN_8001ac08/*0x8001ac08*/(param_1);
    FUN_800207c4/*0x800207c4*/(param_1);
    uVar2 = FUN_8004410c/*0x8004410c*/();
    FUN_8004483c/*0x8004483c*/(uVar2,_DAT_800658fc,0x3b,param_1 + 0x12);
  }
  else {
    if ((param_2 < 3) && (param_2 == 1)) goto LAB_801006a8;
    if ((param_2 == 3) || (param_2 != 5)) {
      if (*(char *)(*param_3 + 4) != '\x02') {
        return 0;
      }
      *param_1 = *param_1 | 0x20;
      FUN_80020890/*0x80020890*/(param_1,0xf);
      goto LAB_8010057c;
    }
  }
  FUN_8001d708/*0x8001d708*/(param_1);
  *param_1 = *param_1 & 0xffffffdf;
  FUN_800207f8/*0x800207f8*/();
LAB_801006a8:
  *param_1 = 0x100;
  *(undefined1 *)(param_1 + 1) = 3;
  return 0;
}

#endif  /* GHIDRA REF */
