/* misc.c -- Casino City small object handlers.
 *
 * Source: CASNOCTY.DLL
 *   FUN_80101ca8 -- CC_GenericCleanup: same shape as HD_TransformerCleanup
 *                   (mode 7 stashes to FX pool, then Heap_Free).
 *   FUN_80100168 -- CC_BurgerSignReset: mode 5 plays an audio cue via
 *                   FUN_80044ac8; reuses obj's draw-prim slot via
 *                   FUN_8001add0 with size 0x24, sets state flag 0x34,
 *                   installs FUN_800223dc as the new per-tick callback.
 *
 * MED confidence.
 */
#include <stdint.h>

extern void *Object_Pool_Alloc(uint32_t size);
extern void  Heap_Free(void *p);
extern void  Audio_PlaySfxRelative(uint32_t bank, int sfxId, void *posXyz);  /* func_0x80044ac8 */
extern void  Object_FreeAndUnhook(void *p);
extern void  Object_RebindPrim(uint32_t *obj, uint32_t bank, int size, int flags);  /* FUN_8001add0 */

extern int8_t *_DAT_800659fc;
extern uint32_t _DAT_800658fc;
extern uint32_t _DAT_800737d8;
extern uint32_t FUN_800223dc;

uint32_t CC_GenericCleanup(void *obj, int mode)
{
    if (mode != 1) {
        if (mode != 7) return 0;
        *(void **)(_DAT_800659fc + 0x58) = obj;
        Object_Pool_Alloc(0x80);
    }
    Heap_Free(obj);
    return 0xffffffffu;
}

uint32_t CC_BurgerSignReset(uint32_t *obj, int mode)
{
    if (mode != 1) {
        if (mode != 5) return 0;
        Audio_PlaySfxRelative(_DAT_800658fc, 0x3b, obj + 0x12);
    }
    uint32_t status = 0x80020000;
    if (((int8_t *)obj)[8] != 0) {
        Object_FreeAndUnhook((void *)(uintptr_t)obj[0xc]);
        obj[0xc] = 0;
        Object_RebindPrim(obj, _DAT_800737d8, 0x24, 8);
        status = obj[0] | 0x34;
        obj[0] = status;
    }
    obj[0x19] = status + 0x23dc;
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80101ca8  (from analysis/dll/CASNOCTY/decomp/80101ca8.c) --- */
// addr: 0x80101ca8  name: FUN_80101ca8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80101ca8(undefined4 param_1,int param_2)

{
  undefined4 extraout_v1;
  
  if (param_2 != 1) {
    if (param_2 != 7) {
      return 0;
    }
    *(undefined4 *)(_DAT_800659fc + 0x58) = param_1;
    FUN_8001d470/*0x8001d470*/(0x80);
    param_1 = extraout_v1;
  }
  Heap_Free/*0x80045088*/(param_1);
  return 0xffffffff;
}

/* --- ? FUN_80100168  (from analysis/dll/CASNOCTY/decomp/80100168.c) --- */
// addr: 0x80100168  name: FUN_80100168

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100168(uint *param_1,int param_2)

{
  uint uVar1;
  
  if (param_2 != 1) {
    if (param_2 != 5) {
      return 0;
    }
    func_0x80044ac8(_DAT_800658fc,0x3b,param_1 + 0x12);
  }
  uVar1 = 0x80020000;
  if ((char)param_1[2] != '\0') {
    FUN_8001bddc/*0x8001bddc*/(param_1[0xc]);
    param_1[0xc] = 0;
    FUN_8001add0/*0x8001add0*/(param_1,_DAT_800737d8,0x24,8);
    uVar1 = *param_1 | 0x34;
    *param_1 = uVar1;
  }
  param_1[0x19] = uVar1 + 0x23dc;
  return 0;
}

#endif  /* GHIDRA REF */
