/* palm_spawn.c -- Casino City pelican / palm-tree projectile spawner.
 *
 * Source: CASNOCTY.DLL  FUN_80100bd0.
 *
 * Allocates a 0x9c-byte projectile, configures it for the Casino City
 * level's pelicana_1 / palm1_1 throwables:
 *   - state byte +0x96 = 0x12 (kind 18, palm coconut?)
 *   - lifetime +0x82 = 4 ticks
 *   - sub-state +0xc = 2
 *   - lifespan counter +0x21 = 0x200 (frames)
 *   - draw bank @+0x26 = vehicle template bank
 *   - initial velocity vx = -0x600, vz = 0 (lateral throw)
 *   - state flags |= 0xa4 (active + animated + collidable)
 * Attaches as a bone child of the spawner via FUN_8001b038 + 8001b2fc,
 * then registers in the post-update queue via FUN_80020744.
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t *Object_Pool_Alloc(uint32_t size);
extern int  Bone_AllocSlot(uint32_t parent, uint16_t slotKey);
extern void Bone_AttachChild(uint32_t parent, int slot, uint32_t *child);
extern void Object_RegisterPostUpdate(uint32_t *obj);   /* FUN_80020744 */
extern void *FUN_80100a9c;                              /* per-tick callback */
extern uint32_t _DAT_800737d8;

void CC_PalmSpawn(uint32_t parent, uint16_t slotKey)
{
    uint32_t *p = Object_Pool_Alloc(0x9c);
    p[0x19] = (uintptr_t)&FUN_80100a9c;
    p[0]  |= 0xa4u;
    *(uint16_t *)((uint8_t *)p + 0x96) = 0x12;
    *(uint16_t *)((uint8_t *)p + 0x82) = 4;
    *(uint16_t *)(p + 3) = 2;
    p[0x21] = 0x200;
    p[0x26] = _DAT_800737d8;
    p[0x22] = 0xfffffa00u;   /* vx = -0x600 (lateral throw) */
    p[0x23] = 0;             /* vz = 0 */

    int slot = Bone_AllocSlot(parent, slotKey);
    Bone_AttachChild(parent, slot, p);
    Object_RegisterPostUpdate(p);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- CASNOCTY.DLL FUN_80100bd0  (from analysis/dll/CASNOCTY/decomp/80100bd0.c) --- */
// addr: 0x80100bd0  name: FUN_80100bd0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_80100bd0(undefined4 param_1,undefined2 param_2)

{
  uint uVar1;
  uint *puVar2;
  undefined4 uVar3;
  
  puVar2 = (uint *)FUN_8001d470/*0x8001d470*/(0x9c);
  puVar2[0x19] = (uint)FUN_80100a9c;
  *puVar2 = *puVar2 | 0xa4;
  uVar1 = _DAT_800737d8;
  *(undefined2 *)((int)puVar2 + 0x96) = 0x12;
  *(undefined2 *)((int)puVar2 + 0x82) = 4;
  *(undefined2 *)(puVar2 + 3) = 2;
  puVar2[0x21] = 0x200;
  puVar2[0x26] = uVar1;
  puVar2[0x22] = 0xfffffa00;
  puVar2[0x23] = 0;
  uVar3 = FUN_8001b038/*0x8001b038*/(param_1,param_2);
  FUN_8001b2fc/*0x8001b2fc*/(param_1,uVar3,puVar2);
  FUN_80020744/*0x80020744*/(puVar2);
  return;
}

#endif  /* GHIDRA REF */
