/* spawner.c -- Casino City random-direction spawner (palm coconut, etc.).
 *
 * Source: CASNOCTY.DLL  FUN_80100a9c.
 *
 * Decrements an i16 spawn-countdown at obj+0x80. When it reaches -1,
 * spawns a 0xa0-byte child (kind from obj+0x96, bank from obj+0x98)
 * with random aim:
 *   - aimIdx = V8_RandNext() & 0xfff   (uniform 0..4095 cone)
 *   - vx = scaled(obj+0x84 base × sin(aimIdx))
 *   - vz = scaled(obj+0x84 base × cos(aimIdx))
 *   - vy = obj+0x88 ± random(15-bit) × obj+0x88 (gentle vertical jitter)
 *   - status flags |= 0x4b4 (projectile + collidable + animated)
 *   - tick callback at constant absolute address 0x800404c4 (an EXE-
 *     side projectile post-tick we'll resolve in pass 3).
 *   - position copied from parent's effective matrix (parent
 *     Matrix_ComposeParentChain).
 * Then the countdown reloads from obj+0x82.
 *
 * Used by pelicana_1, palm1_1, blimp_1 -- all spawn random-aim
 * projectiles at a fixed cadence.
 *
 * MED confidence.
 */
#include <stdint.h>

extern uint32_t V8_RandNext(void);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int u, int flags);
/* PSY-Q (sin, cos) interleaved LUT @ 0x800607b4 -- see canynlnd/spawner.c
 * for the Ghidra-DAT-misnaming note. */
extern const int16_t g_v8_sincostbl[8192];
extern uint8_t *Matrix_ComposeParentChain(int obj);   /* FUN_8001d624 */
extern void     Object_RegisterInScene(uint32_t *obj);

static uint32_t scale_4_12_signed(int32_t v, int32_t factor)
{
    int32_t r = v * factor;
    if (r < 0) r += 0xfff;
    return (uint32_t)(r >> 12);
}

uint32_t CC_RandomFire(int obj, int mode)
{
    if (mode != 0) return 0;
    int16_t  *countdown = (int16_t *)(intptr_t)(obj + 0x80);
    int16_t   prev = *countdown;
    *countdown = (int16_t)(prev - 1);
    if (prev != 0) return 0;     /* will fire on the next call when prev was -1; matches Ghidra "==-1" via "==0 before decrement" inversion */

    uint32_t *child = Object_Pool_AllocFromBank(
        (void *)(uintptr_t)*(uint32_t *)(obj + 0x98),
        *(uint16_t *)(obj + 0x96), 0xa0, 8);
    uint32_t aimIdx = V8_RandNext() & 0xfff;
    child[0] |= 0x4b4u;

    int16_t sin = g_v8_sincostbl[aimIdx * 2 + 0];
    int16_t cos = g_v8_sincostbl[aimIdx * 2 + 1];
    child[0x22] = scale_4_12_signed(*(int32_t *)(obj + 0x84), sin);
    child[0x24] = scale_4_12_signed(*(int32_t *)(obj + 0x84), cos);

    uint32_t rand1 = V8_RandNext();
    child[0x23] = (uint32_t)(*(int32_t *)(obj + 0x88)
                             + ((int32_t)rand1 * *(int32_t *)(obj + 0x88) >> 15));

    uint8_t *m = Matrix_ComposeParentChain(obj);
    child[9]  = *(uint32_t *)(m + 0x14);
    child[10] = *(uint32_t *)(m + 0x18);
    child[11] = *(uint32_t *)(m + 0x1c);
    child[0x19] = 0x800404c4;       /* main-EXE projectile tick */

    Object_RegisterInScene(child);

    /* Reload countdown. */
    *countdown = *(int16_t *)(obj + 0x82);
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- CASNOCTY.DLL FUN_80100a9c  (from analysis/dll/CASNOCTY/decomp/80100a9c.c) --- */
// addr: 0x80100a9c  name: FUN_80100a9c

undefined4 FUN_80100a9c(int param_1,int param_2)

{
  short sVar1;
  uint *puVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  
  if ((param_2 == 0) &&
     (sVar1 = *(short *)(param_1 + 0x80) + -1, *(short *)(param_1 + 0x80) = sVar1, sVar1 == -1)) {
    puVar2 = (uint *)FUN_8001ac44/*0x8001ac44*/(*(undefined4 *)(param_1 + 0x98),*(undefined2 *)(param_1 + 0x96)
                                     ,0xa0,8);
    uVar3 = FUN_80017160/*0x80017160*/();
    iVar4 = (uVar3 & 0xfff) * 4;
    *puVar2 = *puVar2 | 0x4b4;
    iVar5 = *(int *)(param_1 + 0x84) * (int)*(short *)(iVar4 + -0x7ff9f84c);
    if (iVar5 < 0) {
      iVar5 = iVar5 + 0xfff;
    }
    puVar2[0x22] = iVar5 >> 0xc;
    iVar5 = *(int *)(param_1 + 0x84) * (int)*(short *)(iVar4 + -0x7ff9f84a);
    if (iVar5 < 0) {
      iVar5 = iVar5 + 0xfff;
    }
    puVar2[0x24] = iVar5 >> 0xc;
    iVar5 = FUN_80017160/*0x80017160*/();
    puVar2[0x23] = *(int *)(param_1 + 0x88) + (iVar5 * *(int *)(param_1 + 0x88) >> 0xf);
    iVar5 = FUN_8001d624/*0x8001d624*/(param_1);
    uVar3 = *(uint *)(iVar5 + 0x18);
    uVar6 = *(uint *)(iVar5 + 0x1c);
    puVar2[9] = *(uint *)(iVar5 + 0x14);
    puVar2[10] = uVar3;
    puVar2[0xb] = uVar6;
    puVar2[0x19] = 0x800404c4;
    FUN_800202f4/*0x800202f4*/();
    *(undefined2 *)(param_1 + 0x80) = *(undefined2 *)(param_1 + 0x82);
  }
  return 0;
}

#endif  /* GHIDRA REF */
