/* spawner2.c -- another Casino City projectile spawner pair.
 *
 * Source: CASNOCTY.DLL
 *   FUN_80101a90 -- CC_RandomScatterTick: countdown-driven spawn that
 *                   scatters projectiles in a 2D random-square cone
 *                   around the parent's +0x54 radius. Same idiom as
 *                   CC_RandomFire but using uniform-square rather than
 *                   cos/sin cone.
 *   FUN_80101bb8 -- CC_BoneSpawn: generic per-bone child constructor
 *                   (size 0x9c, with audio cue 1 played at spawn).
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t V8_RandNext(void);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int u, int flags);
extern void Object_RandomizeRotation(uint32_t *m);
extern void Object_RegisterInScene(uint32_t *obj);
extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern void FUN_80020890(uint32_t *obj, int sub);
extern uint32_t SfxChannel_Acquire(void);
extern void Audio_PlaySfxAtPosVar(uint32_t ch, uint32_t bank, int sfxId, void *pos);
extern void Object_BumpSubstate_Or_FX(int obj);   /* FUN_8001d4f0 */
extern void Damage_Apply(void *obj);              /* FUN_800205f8 */
extern int LAB_8003e80c(int obj, int event, int param3);

uint32_t CC_RandomScatterTick(int obj, uint32_t mode)
{
    if (mode != 2) {
        uint32_t gate = 5;
        if ((mode < 3 && (gate = 0, mode == 0)) || mode != gate) {
            int16_t *countdown = (int16_t *)(intptr_t)(obj + 0x80);
            int16_t next = (int16_t)(*countdown - 1);
            *countdown = next;
            if (next == -1) {
                uint32_t *child = Object_Pool_AllocFromBank(
                    (void *)(uintptr_t)*(uint32_t *)(obj + 0x98),
                    *(uint16_t *)(obj + 0x96), 0x80, 8);

                int32_t r = *(int32_t *)(obj + 0x54);
                *(int32_t *)((uint8_t *)child + 0x28) = 0;
                *(int32_t *)((uint8_t *)child + 0x24) =
                    ((int)V8_RandNext() * 2 * r >> 15) - r;
                r = *(int32_t *)(obj + 0x54);
                Object_SetCallbackPsxSlot(child, (uintptr_t)&LAB_8003e80c);
                *(int32_t *)((uint8_t *)child + 0x2c) =
                    ((int)V8_RandNext() * 2 * r >> 15) - r;
                Object_BumpSubstate_Or_FX(obj);
                *countdown = *(int16_t *)(obj + 0x82);
            }
            if (*(int *)(obj + 0x38) != 0)
                return 0;
            Damage_Apply((void *)(uintptr_t)(uint32_t)obj);
        }
        *(uint32_t *)(obj + 0x60) = 0;
    }
    *(uint16_t *)(obj + 0x80) = 0xffff;
    return 0;
}

uint32_t FUN_80101a90(int obj, uint32_t mode)
{
    return CC_RandomScatterTick(obj, mode);
}

uint32_t *CC_BoneSpawn(uint32_t *parentPos, uint32_t bank, uint16_t kind,
                       uint16_t animSlot, uint16_t spriteSlot, uint32_t lifetime)
{
    uint32_t *c = Object_Pool_AllocFromBank((void *)(uintptr_t)bank, kind, 0x9c, 8);
    Object_RandomizeRotation(c + 4);
    c[9]  = parentPos[0];
    c[10] = parentPos[1];
    c[11] = parentPos[2];
    Object_SetCallbackPsxSlot(c, (uintptr_t)&FUN_80101a90);
    c[0x15] = 0x8000;
    c[0x26] = bank;
    *(uint16_t *)((uint8_t *)c + 0x96) = animSlot;
    c[0] |= 0xa4u;
    *(uint16_t *)((uint8_t *)c + 0x82) = spriteSlot;
    Object_RegisterInScene(c);
    FUN_80020890(c, (int)lifetime);
    uint32_t ch = SfxChannel_Acquire();
    Audio_PlaySfxAtPosVar(ch, *(uint32_t *)(bank + 8), 1, parentPos);
    return c;
}

uint32_t *FUN_80101bb8(uint32_t *parentPos, uint32_t bank, uint16_t kind,
                       uint16_t animSlot, uint16_t spriteSlot, uint32_t lifetime)
{
    return CC_BoneSpawn(parentPos, bank, kind, animSlot, spriteSlot, lifetime);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80101a90  (from analysis/dll/CASNOCTY/decomp/80101a90.c) --- */
// addr: 0x80101a90  name: FUN_80101a90

undefined4 FUN_80101a90(int param_1,uint param_2)

{
  short sVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  
  if (param_2 != 2) {
    uVar2 = 5;
    if (((param_2 < 3) && (uVar2 = 0, param_2 == 0)) || (param_2 != uVar2)) {
      sVar1 = *(short *)(param_1 + 0x80) + -1;
      *(short *)(param_1 + 0x80) = sVar1;
      if (sVar1 == -1) {
        iVar3 = FUN_8001ac44/*0x8001ac44*/(*(undefined4 *)(param_1 + 0x98),*(undefined2 *)(param_1 + 0x96),0x80
                                ,8);
        iVar4 = FUN_80017160/*0x80017160*/();
        iVar5 = *(int *)(param_1 + 0x54);
        *(undefined4 *)(iVar3 + 0x28) = 0;
        *(int *)(iVar3 + 0x24) = (iVar4 * 2 * iVar5 >> 0xf) - iVar5;
        iVar4 = FUN_80017160/*0x80017160*/();
        iVar5 = *(int *)(param_1 + 0x54);
        *(undefined4 *)(iVar3 + 100) = 0x8003e80c;
        *(int *)(iVar3 + 0x2c) = (iVar4 * 2 * iVar5 >> 0xf) - iVar5;
        FUN_8001d4f0/*0x8001d4f0*/(param_1);
        *(undefined2 *)(param_1 + 0x80) = *(undefined2 *)(param_1 + 0x82);
      }
      if (*(int *)(param_1 + 0x38) != 0) {
        return 0;
      }
      FUN_800205f8/*0x800205f8*/(param_1);
    }
    *(undefined4 *)(param_1 + 0x60) = 0;
  }
  *(undefined2 *)(param_1 + 0x80) = 0xffff;
  return 0;
}

/* --- ? FUN_80101bb8  (from analysis/dll/CASNOCTY/decomp/80101bb8.c) --- */
// addr: 0x80101bb8  name: FUN_80101bb8

uint * FUN_80101bb8(uint *param_1,uint param_2,undefined2 param_3,undefined2 param_4,
                   undefined2 param_5,undefined4 param_6)

{
  uint *puVar1;
  undefined4 uVar2;
  uint uVar3;
  uint uVar4;
  
  puVar1 = (uint *)FUN_8001ac44/*0x8001ac44*/(param_2,param_3,0x9c,8);
  FUN_80016da8/*0x80016da8*/(puVar1 + 4);
  uVar3 = param_1[1];
  uVar4 = param_1[2];
  puVar1[9] = *param_1;
  puVar1[10] = uVar3;
  puVar1[0xb] = uVar4;
  puVar1[0x19] = (uint)FUN_80101a90;
  puVar1[0x15] = 0x8000;
  puVar1[0x26] = param_2;
  *(undefined2 *)((int)puVar1 + 0x96) = param_4;
  *puVar1 = *puVar1 | 0xa4;
  *(undefined2 *)((int)puVar1 + 0x82) = param_5;
  FUN_800202f4/*0x800202f4*/(puVar1);
  FUN_80020890/*0x80020890*/(puVar1,param_6);
  uVar2 = FUN_8004410c/*0x8004410c*/();
  FUN_800447e8/*0x800447e8*/(uVar2,*(undefined4 *)(param_2 + 8),1,param_1);
  return puVar1;
}

#endif  /* GHIDRA REF */
