/* spawner.c -- Canyonlands "boulder/projectile launcher" entry point.
 *
 * Source: CANYNLND.DLL  FUN_80100940.
 *
 * On mode 9 (= "fire-now"), spawns a child object (size 0x98, type
 * given by the parent's animation slot index at +0xa). Configuration:
 *
 *   - LOD/scale: parent[0x15] (max-LOD radius?) is multiplied by 0x93c
 *     and divided by 0x1000 (4.12-fixed shrink) so the child is
 *     ~36% the parent's size.
 *   - spawnId: 1000 (= "level-spawned projectile").
 *   - randomised offsets: per-call random rotation, random pad byte at
 *     +9 (sound variation index).
 *   - status flags: |= 0x488 (active + projectile + collidable).
 *   - position: copied from parent[0x12..0x14] (parent's posXYZ).
 *   - tick callback: FUN_80100244 (the per-frame physics loop for
 *     these projectiles, also in CANYNLND.DLL).
 *   - initial vy = 0xfffff415 (= -0xbeb, upward).
 *   - initial vx, vz: looked up in a 4096-entry sin/cos trig table
 *     at address 0x80060db4 (in the main EXE's read-only data),
 *     keyed by `(parent_heading + ((rand<<8)>>15) - 0x80) & 0xfff`,
 *     each entry being two i16 (sin, cos) scaled by 0xbeb / 0x1000.
 *
 * MED confidence. Pass 3 should:
 *   - identify the DAT_80060db4 trig table as the standard PSY-Q
 *     rsin/rcos lookup
 *   - rename FUN_8001dc1c -> Object_RandomizeRotation
 *   - finalize the cone-aim formula
 */
#include <stdint.h>

extern uint32_t V8_RandNext(void);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int u, int flags);  /* FUN_8001ac44 */
extern void  Object_RandomizeRotation(uint32_t *obj);   /* FUN_8001dc1c */
extern uint32_t FUN_80100244;                            /* per-tick callback */
/* PSY-Q (sin, cos) interleaved LUT at SLUS:0x800607b4 -- 4096 i16 pairs.
 * Ghidra's pseudo-C named this "DAT_80060db4" (a hex misinterpretation
 * of the signed-i32 form -0x7ff9f84c, which is the real address
 * 0x800607b4). The MIPS at FUN_80100940 @0x80100a60-0x80100a64 loads
 * `lui 0x8006; addiu 0x7b4` = 0x800607b4 = table BASE, then indexes
 * `lh @ base + (aimIdx & 0xfff)*4`, i.e. sin = base[aimIdx*2+0],
 * cos = base[aimIdx*2+1]. */
extern const int16_t g_v8_sincostbl[8192];

static uint32_t scale_4_12(int32_t v, int32_t factor)
{
    int32_t r = v * factor;
    if (r < 0) r += 0xfff;
    return (uint32_t)(r >> 12);
}

uint32_t CL_Launcher(uint32_t *parent, uint32_t mode, uint32_t *impulse)
{
    if (mode == 7)  goto sharedTail;
    if (mode == 1)  goto initTail;
    if (mode != 9)  return 0;
    if ((parent[0] & 1u) != 0) return 0;     /* already active -- don't double-fire */

    /* mode 9: fire */
    uint16_t kind = *(uint16_t *)((uint8_t *)parent + 0xa);
    uint32_t *child = Object_Pool_AllocFromBank((void *)(uintptr_t)parent[0x16], kind, 0x98, 0);

    uint32_t rand0 = V8_RandNext();
    int16_t  parentHeading = *(int16_t *)((uint8_t *)parent + 0x42);

    Object_RandomizeRotation(child);
    child[0x15] = scale_4_12((int32_t)child[0x15], 0x93c);
    *(uint16_t *)((uint8_t *)child + 6) = 1000;        /* spawnId */
    ((uint8_t *)child)[9] = (uint8_t)V8_RandNext();    /* sound variant */
    child[0] |= 0x488u;

    uint16_t kindLo = *(uint16_t *)((uint8_t *)parent + 0xe);
    *(uint16_t *)((uint8_t *)child + 0xe) = kindLo;
    *(uint16_t *)(child + 3) = kindLo;

    child[0x12] = parent[0x12];   /* posX */
    child[0x13] = parent[0x13];   /* posY */
    child[0x14] = parent[0x14];   /* posZ */
    child[0x19] = (uintptr_t)&FUN_80100244;
    child[0x21] = 0xfffff415u;    /* vy = -0xbeb (upward) */

    /* Aim cone: angle = parentHeading + random[-128..127], wrap 0..0xfff. */
    int aimIdx = (((int)parentHeading + (((int)rand0 << 8) >> 15)) - 0x80) & 0xfff;
    int16_t sin = g_v8_sincostbl[aimIdx * 2 + 0];
    int16_t cos = g_v8_sincostbl[aimIdx * 2 + 1];
    child[0x20] = scale_4_12(sin, 0xbeb);
    child[0x22] = scale_4_12(cos, 0xbeb);

    impulse = child;
sharedTail:
initTail:
    /* mode-7 cleanup + mode-1 init tail registers the new child with
     * the world list via Object_BindLifecycle/Object_BindFinalize
     * (same idiom as wildwest/dynamite_keg.c case 1). */
    (void)impulse;
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- CANYNLND.DLL FUN_80100940  (from analysis/dll/CANYNLND/decomp/80100940.c) --- */
// addr: 0x80100940  name: FUN_80100940

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100940(uint *param_1,uint param_2,uint *param_3)

{
  short sVar1;
  undefined2 uVar2;
  undefined1 uVar3;
  int iVar4;
  int iVar5;
  undefined4 uVar6;
  uint uVar7;
  uint uVar8;
  
  if (param_2 != 7) {
    if ((param_2 < 8) && (param_2 == 1)) goto LAB_80100bbc;
    if (param_2 != 9) {
      return 0;
    }
    if ((*param_1 & 1) != 0) {
      return 0;
    }
    param_3 = (uint *)FUN_8001ac44/*0x8001ac44*/(param_1[0x16],*(undefined2 *)((int)param_1 + 10),0x98,0);
    iVar4 = FUN_80017160/*0x80017160*/();
    sVar1 = *(short *)((int)param_1 + 0x42);
    FUN_8001dc1c/*0x8001dc1c*/(param_3);
    iVar5 = param_3[0x15] * 0x93c;
    if (iVar5 < 0) {
      iVar5 = iVar5 + 0xfff;
    }
    param_3[0x15] = iVar5 >> 0xc;
    *(undefined2 *)((int)param_3 + 6) = 1000;
    uVar3 = FUN_80017160/*0x80017160*/();
    *(undefined1 *)((int)param_3 + 9) = uVar3;
    uVar2 = *(undefined2 *)((int)param_1 + 0xe);
    *param_3 = *param_3 | 0x488;
    *(undefined2 *)((int)param_3 + 0xe) = uVar2;
    *(undefined2 *)(param_3 + 3) = uVar2;
    uVar7 = param_1[0x13];
    uVar8 = param_1[0x14];
    param_3[0x12] = param_1[0x12];
    param_3[0x13] = uVar7;
    param_3[0x14] = uVar8;
    param_3[0x19] = (uint)FUN_80100244;
    param_3[0x21] = 0xfffff415;
    iVar5 = (((int)sVar1 + ((iVar4 << 8) >> 0xf)) - 0x80U & 0xfff) * 4;
    iVar4 = *(short *)(iVar5 + -0x7ff9f84c) * 0xbeb;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xfff;
    }
    param_3[0x20] = iVar4 >> 0xc;
    iVar4 = *(short *)(iVar5 + -0x7ff9f84a) * 0xbeb;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xfff;
    }
    param_3[0x22] = iVar4 >> 0xc;
    iVar4 = param_3[0x15] * 0x3243;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xfff;
    }
    *(short *)(param_3 + 0x25) = (short)(0x1000000 / (iVar4 >> 0xc));
    FUN_8003e76c/*0x8003e76c*/(param_3);
    FUN_8001d708/*0x8001d708*/(param_3);
    FUN_800202f4/*0x800202f4*/(param_3);
    FUN_8001b0c4/*0x8001b0c4*/(param_3);
    uVar6 = FUN_8004410c/*0x8004410c*/();
    FUN_8004483c/*0x8004483c*/(uVar6,_DAT_800658fc,9,param_3 + 9);
    FUN_80020890/*0x80020890*/(param_1,300);
    FUN_8001fe50/*0x8001fe50*/(&DAT_801012a0,param_3);
    DAT_801012ac = DAT_801012ac + 1;
  }
  iVar4 = FUN_8001d470/*0x8001d470*/(0x80);
  *(uint **)(iVar4 + 0x58) = param_1;
  *(short *)(iVar4 + 10) = (short)param_3;
LAB_80100bbc:
  *param_1 = *param_1 | 0x22;
  return 0;
}

#endif  /* GHIDRA REF */
