/* effects.c -- particle / spark / explosion spawn helpers.
 *
 * Source: SLUS_005.10
 *   FUN_8003fc50  -- Effects_SpawnExplosion(obj)
 *                    Polls FUN_8003fbc8 for an available effect slot;
 *                    if available, spawns one at obj+0x58's bank.
 *                    Returns 1 if spawned, 0 otherwise.
 *   FUN_8003fc94  -- Effects_QueueSnow(obj)
 *                    Walks the parent->children chain rooted at obj+0x58
 *                    via the bone-template's +0x36 next-link, counting
 *                    nodes whose flags byte == 0xff. Returns count.
 *   FUN_8003fd24  -- Effects_SpawnParticleAtParent(parent, kind)
 *                    Allocates a 0x80-byte particle prim from the
 *                    vehicle bank, sets pos to parent's pos
 *                    (parent[0..2]), installs LAB_8003e80c as the tick
 *                    callback, marks state 0x34 (active).
 *
 * MED confidence.
 */
#include <stdint.h>

extern uint32_t Effects_PollFreeSlot(void);                /* FUN_8003fbc8 */
extern void     Effects_BindSlot(int obj, void *bank, uint16_t slot);  /* FUN_8003fac4 */
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int u, int flags);
extern int LAB_8003e80c(int obj, int event, int param3); /* effect_death_ticks.c */
extern int LAB_8003e7b4(int obj, int event, int param3);
extern void FUN_8002036c(uint32_t *obj);
extern uintptr_t DAT_800737d8;
extern uint32_t _DAT_800737d8;
extern void **_DAT_800737d8_ptr;
extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);

static inline uintptr_t obj_ptr32(uintptr_t base, uint32_t off)
{
    return (uintptr_t)*(uint32_t *)(base + off);
}

static inline void obj_write32(uintptr_t base, uint32_t off, uintptr_t value)
{
    *(uint32_t *)(base + off) = (uint32_t)value;
}

int Effects_SpawnExplosion(int obj)
{
    uint32_t slot = Effects_PollFreeSlot();
    if (slot == 0) return 0;
    Effects_BindSlot(obj, (void *)obj_ptr32((uintptr_t)obj, 0x58), (uint16_t)slot);
    return 1;
}

int Effects_QueueSnow(int obj)
{
    uintptr_t bank = obj_ptr32((uintptr_t)obj, 0x58);
    uintptr_t bone = obj_ptr32(bank, 0);
    uint16_t next = *(uint16_t *)(bone + *(uint16_t *)(uintptr_t)(obj + 10) * 0x1c + 0x36);
    int count = 0;
    while (next != 0xffff) {
        uintptr_t node = bone + next * 0x1c;
        uint16_t flags = *(uint16_t *)(node + 0x1c);
        if ((flags >> 8) == 0xff && flags != 0xffff) {
            next = *(uint16_t *)(node + 0x36);
            count++;
            continue;
        }
        next = *(uint16_t *)(node + 0x34);
    }
    return count;
}

uint32_t *Effects_SpawnParticleAtParent(uint32_t *parent, uint16_t kind)
{
    uint32_t *p = Object_Pool_AllocFromBank((void *)DAT_800737d8, kind, 0x80, 8);
    *((int8_t *)p + 4) = 1;
    p[0] = 0x34;
    p[0x12] = parent[0];
    p[0x13] = parent[1];
    p[0x14] = parent[2];
    Object_SetCallbackPsxSlot(p, (uintptr_t)&LAB_8003e80c);
    uint32_t child = p[0x0e];
    while (child != 0) {
        Object_SetCallbackPsxSlot((void *)(uintptr_t)child, (uintptr_t)&LAB_8003e7b4);
        child = *(uint32_t *)(uintptr_t)(child + 0x34);
    }
    FUN_8002036c(p);
    return p;
}

/* Hex-name alias for Effects_SpawnExplosion. */
int FUN_8003fc50(int obj) { return Effects_SpawnExplosion(obj); }
int FUN_8003fc94(int obj) { return Effects_QueueSnow(obj); }
uint32_t *FUN_8003fd24(uint32_t *parent, uint16_t kind)
{
    return Effects_SpawnParticleAtParent(parent, kind);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8003fc50  (from analysis/SLUS_005.10/decomp/8003fc50.c) --- */
// addr: 0x8003fc50  name: FUN_8003fc50

bool FUN_8003fc50(int param_1)

{
  uint uVar1;
  
  uVar1 = FUN_8003fbc8();
  if (uVar1 != 0) {
    FUN_8003fac4(param_1,*(undefined4 *)(param_1 + 0x58),uVar1 & 0xffff);
  }
  return uVar1 != 0;
}

/* --- SLUS_005.10 FUN_8003fbc8  (from analysis/SLUS_005.10/decomp/8003fbc8.c) --- */
// addr: 0x8003fbc8  name: FUN_8003fbc8

uint FUN_8003fbc8(int param_1)

{
  ushort uVar1;
  uint uVar2;
  int iVar3;
  
  iVar3 = **(int **)(param_1 + 0x58);
  uVar1 = *(ushort *)(iVar3 + (uint)*(ushort *)(param_1 + 10) * 0x1c + 0x36);
  while( true ) {
    uVar2 = (uint)uVar1;
    if (uVar2 == 0xffff) {
      return 0;
    }
    uVar1 = *(ushort *)(iVar3 + uVar2 * 0x1c + 0x1c);
    if ((uVar1 >> 8 == 0xff) && (uVar1 != 0xffff)) break;
    uVar1 = *(ushort *)(iVar3 + uVar2 * 0x1c + 0x34);
  }
  return uVar2;
}

/* --- SLUS_005.10 FUN_8003fc94  (from analysis/SLUS_005.10/decomp/8003fc94.c) --- */
// addr: 0x8003fc94  name: FUN_8003fc94

int FUN_8003fc94(int param_1)

{
  ushort uVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  
  iVar5 = **(int **)(param_1 + 0x58);
  uVar1 = *(ushort *)(iVar5 + (uint)*(ushort *)(param_1 + 10) * 0x1c + 0x36);
  iVar4 = 0;
  while (uVar2 = (uint)uVar1, uVar2 != 0xffff) {
    iVar3 = iVar5 + uVar2 * 0x1c;
    uVar1 = *(ushort *)(iVar3 + 0x1c);
    if ((uVar1 >> 8 == 0xff) && (uVar1 != 0xffff)) {
      uVar1 = *(ushort *)(iVar3 + 0x36);
      iVar4 = iVar4 + 1;
    }
    else {
      uVar1 = *(ushort *)(iVar5 + uVar2 * 0x1c + 0x34);
    }
  }
  return iVar4;
}

/* --- SLUS_005.10 FUN_8003fd24  (from analysis/SLUS_005.10/decomp/8003fd24.c) --- */
// addr: 0x8003fd24  name: FUN_8003fd24

undefined4 * FUN_8003fd24(undefined4 *param_1,undefined2 param_2)

{
  undefined4 *puVar1;
  int iVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  
  puVar1 = (undefined4 *)FUN_8001ac44(DAT_800737d8,param_2,0x80,8);
  *(undefined1 *)(puVar1 + 1) = 1;
  *puVar1 = 0x34;
  uVar3 = param_1[1];
  uVar4 = param_1[2];
  puVar1[0x12] = *param_1;
  puVar1[0x13] = uVar3;
  puVar1[0x14] = uVar4;
  iVar2 = puVar1[0xe];
  *(uintptr_t *)((uint8_t *)puVar1 + 0x64) = (uintptr_t)&LAB_8003e80c;
  for (; iVar2 != 0; iVar2 = *(int *)(iVar2 + 0x34)) {
    *(undefined1 **)(iVar2 + 100) = &LAB_8003e7b4;
  }
  FUN_8002036c(puVar1);
  return puVar1;
}

/* --- SLUS_005.10 FUN_8003fac4  (from analysis/SLUS_005.10/decomp/8003fac4.c) --- */
// addr: 0x8003fac4  name: FUN_8003fac4

void FUN_8003fac4(uint *param_1,int *param_2,ushort param_3)

{
  undefined4 uVar1;
  int iVar2;
  int iVar3;
  undefined1 auStack_40 [32];
  
  iVar3 = *param_2 + (uint)param_3 * 0x1c + 0x1c;
  uVar1 = FUN_8001d68c(auStack_40,param_1,iVar3);
  uVar1 = FUN_8003f4a0(param_2,*(undefined2 *)(iVar3 + 0x1a),uVar1,1);
  if ((*(short *)(iVar3 + 0x16) == -0x5556) || (*(short *)(iVar3 + 0x16) == 0)) {
    FUN_8003f89c(param_1,param_2,(uint)param_3,uVar1);
  }
  else {
    iVar2 = FUN_8001d470(0x80);
    *(int **)(iVar2 + 0x58) = param_2;
    *(ushort *)(iVar2 + 10) = param_3;
    *(undefined1 **)(iVar2 + 100) = &LAB_8003fa78;
    *(uint **)(iVar2 + 0x74) = param_1;
    *(undefined4 *)(iVar2 + 0x38) = uVar1;
    *param_1 = *param_1 | 0x8000;
    FUN_80020890(iVar2,*(undefined2 *)(iVar3 + 0x16));
  }
  return;
}

#endif  /* GHIDRA REF */
