/* gte_rotate.c -- high-precision GTE rotate helpers.
 *
 * Source: SLUS_005.10
 *   FUN_8004316c  -- GTE_RotateSV(src, dst)        rotate a 16-bit svector
 *   FUN_80043248  -- GTE_RotateLong(src, dst)      rotate a 32-bit long vector
 *                                                  (17.15 -- split-int-frac)
 *   FUN_80043358  -- GTE_RotateLongMat(m, src, dst)  same + load matrix
 *   FUN_80043408  -- GTE_RotateLongMatTrans         + translation
 *   FUN_800434d0  -- GTE_RotatePacked(scratch, packedXYZ)
 *   FUN_8004352c  -- GTE_RotateLongMtxLow(m, src, dst)
 *   FUN_8004366c  -- GTE_LoadMatrixPacked(packedMat)
 *
 * Vigilante 8 uses a packed 17.15 vector format for world coords:
 *   v[0..2] is each axis as a 32-bit value where:
 *     hi 17 bits = signed integer part   (extracted via >> 15)
 *     lo 15 bits = fractional part        (extracted via & 0x7fff)
 *
 * The hi-precision rotate splits the vector into integer + fractional,
 * transforms each separately through the GTE's matrix, then sums:
 *     dst = (frac_rotated) + (int_rotated * 8)
 *
 * The `* 8` factor is because the GTE's `sf=0` mode shifts the result
 * left by 3 (the +3 bias the chip applies when output goes to IR after
 * accumulator). This effectively keeps the same 17.15 packing through
 * the transform.
 *
 * The GTE_LoadMatrixPacked helper reorders a five-u32 packed matrix
 * (each u32 holds two adjacent matrix entries) into the GTE's six
 * matrix registers in one shot.
 *
 * HIGH confidence: all of these match the canonical PSY-Q hi-precision
 * vector transform pattern. The math is bit-exact because every step
 * runs on the GTE -- the wrapper just feeds inputs and reads outputs.
 *
 * Bit-exact: do NOT inline the GTE ops as plain C. See gte.h.
 */
#include <stdint.h>
#include "structs.h"
#include "gte.h"

/* NOTE: GTE_RotateLong, GTE_RotateLongMat, GTE_RotateLongMatTrans,
 * GTE_LoadMatrixPacked and the FUN_80043248/358/408/366c aliases are now
 * defined in src/physics/gte_long_vec.c with the correct gte_stMAC1/2/3
 * read-back pattern.  Only GTE_RotateSV (FUN_8004316c) lives here since
 * that function is not covered by gte_long_vec.c. */

extern void     gte_ldv0 (const SVECTOR *v);
extern int32_t  gte_stIR1(void);
extern int32_t  gte_stIR2(void);
extern int32_t  gte_stIR3(void);
extern void     gte_rtv0_b(void);

/* HIGH: rotate a 16-bit SVECTOR through the current GTE matrix.
 * Source: SLUS_005.10  FUN_8004316c */
SVECTOR *GTE_RotateSV(const SVECTOR *src, SVECTOR *dst)
{
    gte_ldv0(src);
    gte_rtv0_b();
    dst->vx = (int16_t)gte_stIR1();
    dst->vy = (int16_t)gte_stIR2();
    dst->vz = (int16_t)gte_stIR3();
    return dst;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8004316c  (from analysis/SLUS_005.10/decomp/8004316c.c) --- */
// addr: 0x8004316c  name: FUN_8004316c

undefined2 * FUN_8004316c(SVECTOR *param_1,undefined2 *param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  
  gte_ldv0(param_1);
  gte_rtv0_b();
  uVar1 = gte_stIR1();
  uVar2 = gte_stIR2();
  uVar3 = gte_stIR3();
  *param_2 = (short)uVar1;
  param_2[1] = (short)uVar2;
  param_2[2] = (short)uVar3;
  return param_2;
}

/* --- SLUS_005.10 FUN_80043248  (from analysis/SLUS_005.10/decomp/80043248.c) --- */
// addr: 0x80043248  name: FUN_80043248

int * FUN_80043248(uint *param_1,int *param_2)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  
  iVar4 = (int)*param_1 >> 0xf;
  iVar5 = (int)param_1[1] >> 0xf;
  iVar6 = (int)param_1[2] >> 0xf;
  gte_ldsv_(iVar4,iVar5,iVar6);
  uVar1 = *param_1 & 0x7fff;
  uVar2 = param_1[1] & 0x7fff;
  gte_rtir_sf0_b();
  uVar3 = param_1[2] & 0x7fff;
  read_mt(iVar4,iVar5,iVar6);
  gte_ldsv_(uVar1,uVar2,uVar3);
  gte_rtir_b();
  read_mt(uVar1,uVar2,uVar3);
  *param_2 = uVar1 + iVar4 * 8;
  param_2[1] = uVar2 + iVar5 * 8;
  param_2[2] = uVar3 + iVar6 * 8;
  return param_2;
}

/* --- SLUS_005.10 FUN_80043358  (from analysis/SLUS_005.10/decomp/80043358.c) --- */
// addr: 0x80043358  name: FUN_80043358

int * FUN_80043358(undefined4 *param_1,uint *param_2,int *param_3)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  
  gte_ldR11R12(*param_1);
  gte_ldR13R21(param_1[1]);
  gte_ldR22R23(param_1[2]);
  gte_ldR31R32(param_1[3]);
  gte_ldR33(param_1[4]);
  iVar4 = (int)*param_2 >> 0xf;
  iVar5 = (int)param_2[1] >> 0xf;
  iVar6 = (int)param_2[2] >> 0xf;
  gte_ldsv_(iVar4,iVar5,iVar6);
  uVar1 = *param_2 & 0x7fff;
  uVar2 = param_2[1] & 0x7fff;
  gte_rtir_sf0_b();
  uVar3 = param_2[2] & 0x7fff;
  read_mt(iVar4,iVar5,iVar6);
  gte_ldsv_(uVar1,uVar2,uVar3);
  gte_rtir_b();
  read_mt(uVar1,uVar2,uVar3);
  *param_3 = uVar1 + iVar4 * 8;
  param_3[1] = uVar2 + iVar5 * 8;
  param_3[2] = uVar3 + iVar6 * 8;
  return param_3;
}

/* --- SLUS_005.10 FUN_80043408  (from analysis/SLUS_005.10/decomp/80043408.c) --- */
// addr: 0x80043408  name: FUN_80043408

int * FUN_80043408(undefined4 *param_1,uint *param_2,int *param_3)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  
  gte_ldR11R12(*param_1);
  gte_ldR13R21(param_1[1]);
  gte_ldR22R23(param_1[2]);
  gte_ldR31R32(param_1[3]);
  gte_ldR33(param_1[4]);
  gte_ldsv_((int)*param_2 >> 0xf,(int)param_2[1] >> 0xf,(int)param_2[2] >> 0xf);
  uVar1 = *param_2 & 0x7fff;
  uVar2 = param_2[1] & 0x7fff;
  uVar3 = param_2[2] & 0x7fff;
  gte_rtir_sf0_b();
  iVar4 = param_1[5];
  iVar5 = param_1[6];
  iVar6 = param_1[7];
  gte_ldtr(iVar4,iVar5,iVar6);
  read_mt(iVar4,iVar5,iVar6);
  gte_ldsv_(uVar1,uVar2,uVar3);
  gte_rtirtr_b();
  read_mt(uVar1,uVar2,uVar3);
  *param_3 = uVar1 + iVar4 * 8;
  param_3[1] = uVar2 + iVar5 * 8;
  param_3[2] = uVar3 + iVar6 * 8;
  return param_3;
}

/* --- SLUS_005.10 FUN_800434d0  (from analysis/SLUS_005.10/decomp/800434d0.c) --- */
// addr: 0x800434d0  name: FUN_800434d0

void FUN_800434d0(undefined4 param_1,int param_2)

{
  gte_ldVXY0(param_2);
  gte_ldVZ0(param_2 + 4);
  FUN_8004366c();
  gte_rtv0_b();
  gte_stIR1();
  gte_stIR2();
                    /* WARNING: Treating indirect jump as return */
  gte_stIR3();
  return;
}

/* --- SLUS_005.10 FUN_8004352c  (from analysis/SLUS_005.10/decomp/8004352c.c) --- */
// addr: 0x8004352c  name: FUN_8004352c

int * FUN_8004352c(undefined4 param_1,uint *param_2,int *param_3)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  
  FUN_8004366c();
  iVar4 = (int)*param_2 >> 0xf;
  iVar5 = (int)param_2[1] >> 0xf;
  iVar6 = (int)param_2[2] >> 0xf;
  gte_ldsv_(iVar4,iVar5,iVar6);
  uVar1 = *param_2 & 0x7fff;
  uVar2 = param_2[1] & 0x7fff;
  gte_rtir_sf0_b();
  uVar3 = param_2[2] & 0x7fff;
  read_mt(iVar4,iVar5,iVar6);
  gte_ldsv_(uVar1,uVar2,uVar3);
  gte_rtir_b();
  read_mt(uVar1,uVar2,uVar3);
  *param_3 = uVar1 + iVar4 * 8;
  param_3[1] = uVar2 + iVar5 * 8;
  param_3[2] = uVar3 + iVar6 * 8;
                    /* WARNING: Treating indirect jump as return */
  return param_3;
}

/* --- SLUS_005.10 FUN_8004366c  (from analysis/SLUS_005.10/decomp/8004366c.c) --- */
// addr: 0x8004366c  name: FUN_8004366c

undefined8 FUN_8004366c(uint *param_1)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  
  uVar1 = *param_1 & 0xffff;
  uVar3 = param_1[1] & 0xffff;
  gte_ldR11R12(uVar1 | param_1[1] - uVar3);
  uVar2 = param_1[2] & 0xffff;
  gte_ldR31R32(uVar3 | param_1[2] - uVar2);
  uVar3 = param_1[3] & 0xffff;
  uVar1 = *param_1 - uVar1 | uVar3;
  uVar2 = param_1[3] - uVar3 | uVar2;
  gte_ldR13R21(uVar1);
  gte_ldR22R23(uVar2);
  gte_ldR33(param_1[4]);
  return CONCAT44(uVar2,uVar1);
}

#endif  /* GHIDRA REF */
