/* mat_abs_load.c -- load absolute-value of packed matrix into GTE.
 *
 * Source: SLUS_005.10  FUN_800436c8.
 *
 * Takes a packed 5-u32 matrix (same layout as GTE_LoadMatrixPacked)
 * and loads it into the GTE registers with every i16 component
 * replaced by its absolute value. The negation pattern includes the
 * "flip if MSB set after the negate" step (`uVar ^= 0xffff`) which
 * handles INT_MIN saturation in a way that matches the chip's
 * absolute-value semantics exactly.
 *
 * Used (presumably) for axis-aligned bound box checks where the
 * matrix's *magnitudes* alone matter -- e.g. projecting an AABB
 * extent onto an arbitrary rotation.
 *
 * HIGH confidence on the operation; MED on the intended call site.
 */
#include <stdint.h>

extern void gte_ldR11R12(uint32_t v);
extern void gte_ldR13R21(uint32_t v);
extern void gte_ldR22R23(uint32_t v);
extern void gte_ldR31R32(uint32_t v);
extern void gte_ldR33   (uint32_t v);

static inline uint32_t absi16_pair(uint32_t v)
{
    uint32_t r = v;
    if ((int32_t)r < 0)         r = -r;
    if ((int32_t)(r << 16) < 0) r ^= 0xffff;
    return r;
}

uint64_t GTE_LoadMatrixPackedAbs(const uint32_t *m)
{
    uint32_t a = absi16_pair(m[0]);
    uint32_t b = absi16_pair(m[1]);
    uint32_t c = absi16_pair(m[2]);
    uint32_t d = absi16_pair(m[3]);
    int32_t  e = (int32_t)(int16_t)m[4];
    if (e < 0) e = -e;

    gte_ldR11R12(a);
    gte_ldR13R21(b);
    gte_ldR22R23(c);
    gte_ldR31R32(d);
    gte_ldR33   ((uint32_t)e);
    return ((uint64_t)e << 32) | d;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800436c8  (from analysis/SLUS_005.10/decomp/800436c8.c) --- */
// addr: 0x800436c8  name: FUN_800436c8

undefined8 FUN_800436c8(uint *param_1)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  
  uVar1 = *param_1;
  uVar2 = param_1[1];
  uVar4 = param_1[2];
  if ((int)uVar1 < 0) {
    uVar1 = -uVar1;
  }
  if ((int)(uVar1 << 0x10) < 0) {
    uVar1 = uVar1 ^ 0xffff;
  }
  gte_ldR11R12(uVar1);
  if ((int)uVar2 < 0) {
    uVar2 = -uVar2;
  }
  uVar1 = param_1[3];
  if ((int)(uVar2 << 0x10) < 0) {
    uVar2 = uVar2 ^ 0xffff;
  }
  gte_ldR13R21(uVar2);
  if ((int)uVar4 < 0) {
    uVar4 = -uVar4;
  }
  iVar3 = (int)(short)param_1[4];
  if ((int)(uVar4 << 0x10) < 0) {
    uVar4 = uVar4 ^ 0xffff;
  }
  gte_ldR22R23(uVar4);
  if ((int)uVar1 < 0) {
    uVar1 = -uVar1;
  }
  if ((int)(uVar1 << 0x10) < 0) {
    uVar1 = uVar1 ^ 0xffff;
  }
  gte_ldR31R32(uVar1);
  if (iVar3 < 0) {
    iVar3 = -iVar3;
  }
  gte_ldR33(iVar3);
  return CONCAT44(iVar3,uVar1);
}

#endif  /* GHIDRA REF */
