/* matrix_chain.c -- compose parent-chain matrices for hierarchical objects.
 *
 * Source: SLUS_005.10  FUN_8001d624.
 *
 * Walks an object's parent chain (linked via FUN_8001d5a0 which returns
 * obj->parent or NULL). For each parent, composes the parent's
 * matrix with the running result via PSY-Q's CompMatrixLV, accumulating
 * into the scratch slot at DAT_8006f640. Returns a pointer to the
 * final accumulated matrix (or the original object's matrix if it has
 * no parents).
 *
 * Used by hierarchical objects (e.g. crane base + crane arm + crane
 * hook, or a level door + hinge transform). Each part's draw position
 * is the product of all parent transforms.
 *
 * HIGH confidence.
 */
#include <stdint.h>
#include "structs.h"

extern int   Object_Parent(int obj);                 /* FUN_8001d5a0 */
extern MATRIX *CompMatrixLV(MATRIX *a, MATRIX *b, MATRIX *out);
MATRIX DAT_8006f640;

MATRIX *Matrix_ComposeParentChain(int obj)
{
    MATRIX *m = (MATRIX *)(intptr_t)(obj + 0x10);
    for (;;) {
        obj = Object_Parent(obj);
        if (obj == 0) break;
        CompMatrixLV((MATRIX *)(intptr_t)(obj + 0x10), m, &DAT_8006f640);
        m = &DAT_8006f640;
    }
    return m;
}

/* Hex-name alias. */
MATRIX *FUN_8001d624(int obj) { return Matrix_ComposeParentChain(obj); }

/* ================================================================
 * FUN_8001d68c -- Matrix_ComposeRelativeToObject
 *
 * Build a matrix `param_1` that is the composition of the parent
 * chain of `param_2` with the object-local transform of `param_3`
 * (built via Matrix_FromObjectTransform / FUN_8001b07c into param_1).
 *
 * Final result is written to param_1 via CompMatrixLV.
 *
 * HIGH confidence (direct Ghidra port).
 * ================================================================ */
extern MATRIX *FUN_8001b07c(MATRIX *out, int obj);    /* Matrix_FromObjectTransform */

void FUN_8001d68c(MATRIX *param_1, int param_2, int param_3)
{
    MATRIX *m0 = FUN_8001d624(param_2);
    MATRIX *m1 = FUN_8001b07c(param_1, param_3);
    CompMatrixLV(m0, m1, param_1);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001d624  (from analysis/SLUS_005.10/decomp/8001d624.c) --- */
// addr: 0x8001d624  name: FUN_8001d624

MATRIX * FUN_8001d624(int param_1)

{
  MATRIX *m1;
  
  m1 = (MATRIX *)(param_1 + 0x10);
  while( true ) {
    param_1 = FUN_8001d5a0(param_1);
    if (param_1 == 0) break;
    CompMatrixLV((MATRIX *)(param_1 + 0x10),m1,(MATRIX *)&DAT_8006f640);
    m1 = (MATRIX *)&DAT_8006f640;
  }
  return m1;
}

#endif  /* GHIDRA REF */
