/* sound_position.c -- compute pan/volume from a 3D sound source position.
 *
 * Source: SLUS_005.10
 *   FUN_800449bc  -- SfxPan_For3DPos(srcPos) -> u32 LR-volume pair
 *                    (used for instantaneous SFX placement).
 *   FUN_800446dc  -- SfxPan_For3DPosDelayed(srcPos)
 *                    (used for delayed/queued SFX where the panning
 *                    follows the projectile rather than the impact.)
 *
 * Each function:
 *   1. Transforms the source pos through the world->camera matrix at
 *      DAT_8006f680 via GTE_RotateLongMatTrans -- gets a camera-space
 *      vector.
 *   2. Branches on g_splitScreenMode (iRam00000010):
 *        0 (1P)  -> SfxPan_From1P_Camera{Stereo,Mono} based on
 *                   cRam000005a8 (output-mode flag: 0=stereo, !=0=mono).
 *        else    -> 2P-specific variant (not detailed here; the same
 *                   structure but uses split-screen camera basis).
 *
 * Returns a u32 packing (lvol << 16 | rvol) suitable for direct
 * use with SPU voice volume registers.
 *
 * Bit-exact: the camera-space transform is delegated to GTE so the
 * saturation matches the chip. Pan curve constants live in the inner
 * helpers (FUN_800448ec / FUN_80044890 / FUN_80044600 / FUN_800445b8)
 * still in auto/ -- pass 3 unifies them.
 *
 * MED-HIGH confidence.
 */
#include <stdint.h>
#include "structs.h"

extern void GTE_RotateLongMatTrans(const MATRIX *m, void *posXyz, void *outXyz);  /* FUN_80043408 */
extern uint32_t FUN_800448ec(const void *xyz);
extern int      FUN_80044890(const void *xyz);
extern uint32_t FUN_80044600(const void *xyz);
extern int      FUN_800445b8(const void *xyz);

extern MATRIX  DAT_8006f680;
extern int32_t iRam00000010;     /* g_splitScreenMode */
extern int8_t  cRam000005a8;     /* output-mode flag */

static inline uint32_t mono_to_pair(int v)
{
    /* The arithmetic ((v << 16) >> 16) + v << 16 forms a pair where both
     * halves equal v -- the canonical mono-output volume pair. */
    return (uint32_t)((v * 0x10000 >> 0x10) + v * 0x10000);
}

uint32_t SfxPan_For3DPos(void *srcPos)
{
    uint8_t camSpace[16];
    GTE_RotateLongMatTrans(&DAT_8006f680, srcPos, camSpace);
    if (iRam00000010 == 0) {
        if (cRam000005a8 == 0) return FUN_800448ec(camSpace);
        return mono_to_pair(FUN_80044890(camSpace));
    }
    /* 2P split-screen path -- pass 3 finishes. */
    return 0;
}

uint32_t SfxPan_For3DPosDelayed(void *srcPos)
{
    uint8_t camSpace[16];
    GTE_RotateLongMatTrans(&DAT_8006f680, srcPos, camSpace);
    if (iRam00000010 == 0) {
        if (cRam000005a8 == 0) return FUN_80044600(camSpace);
        return mono_to_pair(FUN_800445b8(camSpace));
    }
    return 0;
}

/* FUN_ aliases so callers that use the raw address name link correctly. */
uint32_t FUN_800449bc(void *srcPos) { return SfxPan_For3DPos(srcPos); }
uint32_t FUN_800446dc(void *srcPos) { return SfxPan_For3DPosDelayed(srcPos); }

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800449bc  (from analysis/SLUS_005.10/decomp/800449bc.c) --- */
// addr: 0x800449bc  name: FUN_800449bc

uint FUN_800449bc(undefined4 param_1)

{
  short sVar1;
  short sVar2;
  int iVar3;
  uint uVar4;
  undefined1 auStack_28 [16];
  undefined1 auStack_18 [16];
  
  FUN_80043408(&DAT_8006f680,param_1,auStack_28);
  if (iRam00000010 == 0) {
    if (cRam000005a8 == '\0') {
      uVar4 = FUN_800448ec(auStack_28);
    }
    else {
      iVar3 = FUN_80044890(auStack_28);
      uVar4 = (iVar3 * 0x10000 >> 0x10) + iVar3 * 0x10000;
    }
  }
  else {
    FUN_80043408(&DAT_8006f6a0,param_1,auStack_18);
    if (cRam000005a8 == '\0') {
      iVar3 = FUN_80044890(auStack_28);
      sVar1 = FUN_80044890(auStack_18);
      uVar4 = iVar3 << 0x10 | (int)sVar1;
    }
    else {
      sVar1 = FUN_80044890(auStack_28);
      sVar2 = FUN_80044890(auStack_18);
      iVar3 = (int)sRam000008e4;
      if ((int)sVar1 + (int)sVar2 < (int)sRam000008e4) {
        iVar3 = (int)sVar1 + (int)sVar2;
      }
      uVar4 = iVar3 * 0x10001;
    }
  }
  return uVar4;
}

/* --- SLUS_005.10 FUN_800446dc  (from analysis/SLUS_005.10/decomp/800446dc.c) --- */
// addr: 0x800446dc  name: FUN_800446dc

uint FUN_800446dc(undefined4 param_1)

{
  short sVar1;
  short sVar2;
  int iVar3;
  uint uVar4;
  undefined1 auStack_28 [16];
  undefined1 auStack_18 [16];
  
  FUN_80043408(&DAT_8006f680,param_1,auStack_28);
  if (iRam00000010 == 0) {
    if (cRam000005a8 == '\0') {
      uVar4 = FUN_80044600(auStack_28);
    }
    else {
      iVar3 = FUN_800445b8(auStack_28);
      uVar4 = (iVar3 * 0x10000 >> 0x10) + iVar3 * 0x10000;
    }
  }
  else {
    FUN_80043408(&DAT_8006f6a0,param_1,auStack_18);
    if (cRam000005a8 == '\0') {
      iVar3 = FUN_800445b8(auStack_28);
      sVar1 = FUN_800445b8(auStack_18);
      uVar4 = iVar3 << 0x10 | (int)sVar1;
    }
    else {
      sVar1 = FUN_800445b8(auStack_28);
      sVar2 = FUN_800445b8(auStack_18);
      iVar3 = (int)sRam000008e4;
      if ((int)sVar1 + (int)sVar2 < (int)sRam000008e4) {
        iVar3 = (int)sVar1 + (int)sVar2;
      }
      uVar4 = iVar3 * 0x10001;
    }
  }
  return uVar4;
}

/* --- SLUS_005.10 FUN_800448ec  (from analysis/SLUS_005.10/decomp/800448ec.c) --- */
// addr: 0x800448ec  name: FUN_800448ec

uint FUN_800448ec(int *param_1)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  
  iVar1 = FUN_80016a20();
  uVar2 = 0;
  if (iVar1 < 0x200000) {
    iVar3 = -iVar1 + 0x200000;
    if (iVar3 < 0) {
      iVar3 = -iVar1 + 0x200fff;
    }
    iVar3 = (iVar3 >> 0xc) * (int)sRam000008e4;
    if (iVar3 < 0) {
      iVar3 = iVar3 + 0x1ff;
    }
    if (iVar1 == 0) {
      iVar1 = 0;
    }
    else {
      iVar1 = (*param_1 << 0xc) / iVar1;
    }
    iVar4 = (0x1000 - iVar1) * (iVar3 >> 9);
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0x1fff;
    }
    iVar1 = (iVar1 + 0x1000) * (iVar3 >> 9);
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0x1fff;
    }
    uVar2 = iVar4 >> 0xd | (iVar1 >> 0xd) << 0x10;
  }
  return uVar2;
}

/* --- SLUS_005.10 FUN_80044890  (from analysis/SLUS_005.10/decomp/80044890.c) --- */
// addr: 0x80044890  name: FUN_80044890

int FUN_80044890(void)

{
  int iVar1;
  
  iVar1 = FUN_80016a20();
  if (0x200000 - iVar1 < 0) {
    iVar1 = 0;
  }
  else {
    iVar1 = (0x200000 - iVar1 >> 0xc) * (int)sRam000008e4;
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0x1ff;
    }
    iVar1 = (iVar1 << 7) >> 0x10;
  }
  return iVar1;
}

/* --- SLUS_005.10 FUN_80044600  (from analysis/SLUS_005.10/decomp/80044600.c) --- */
// addr: 0x80044600  name: FUN_80044600

uint FUN_80044600(int *param_1)

{
  int iVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  
  iVar1 = FUN_80016a20();
  iVar2 = iVar1 + 0x200000;
  if (iVar2 < 0) {
    iVar2 = iVar1 + 0x200fff;
  }
  iVar2 = ((int)sRam000008e4 << 9) / (iVar2 >> 0xc);
  gte_ldLZCS(iVar1);
  iVar3 = gte_stLZCR();
  uVar4 = 0xc;
  if ((int)(iVar3 - 1U) < 0xc) {
    uVar4 = iVar3 - 1U;
  }
  if (iVar1 == 0) {
    iVar1 = 0;
  }
  else {
    iVar1 = (*param_1 << (uVar4 & 0x1f)) / (iVar1 >> (0xc - uVar4 & 0x1f));
  }
  iVar3 = (0x1000 - iVar1) * iVar2;
  if (iVar3 < 0) {
    iVar3 = iVar3 + 0x1fff;
  }
  iVar2 = (iVar1 + 0x1000) * iVar2;
  if (iVar2 < 0) {
    iVar2 = iVar2 + 0x1fff;
  }
  return iVar3 >> 0xd | (iVar2 >> 0xd) << 0x10;
}

/* --- SLUS_005.10 FUN_800445b8  (from analysis/SLUS_005.10/decomp/800445b8.c) --- */
// addr: 0x800445b8  name: FUN_800445b8

int FUN_800445b8(void)

{
  int iVar1;
  int iVar2;
  
  iVar1 = FUN_80016a20();
  iVar2 = iVar1 + 0x200000;
  if (iVar2 < 0) {
    iVar2 = iVar1 + 0x200fff;
  }
  return (int)(short)(((int)sRam000008e4 << 9) / (iVar2 >> 0xc));
}

/* --- SLUS_005.10 FUN_80043408  (from analysis/SLUS_005.10/decomp/80043408.c) --- */
// addr: 0x80043408  name: FUN_80043408

int * FUN_80043408(undefined4 *param_1,uint *param_2,int *param_3)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  
  gte_ldR11R12(*param_1);
  gte_ldR13R21(param_1[1]);
  gte_ldR22R23(param_1[2]);
  gte_ldR31R32(param_1[3]);
  gte_ldR33(param_1[4]);
  gte_ldsv_((int)*param_2 >> 0xf,(int)param_2[1] >> 0xf,(int)param_2[2] >> 0xf);
  uVar1 = *param_2 & 0x7fff;
  uVar2 = param_2[1] & 0x7fff;
  uVar3 = param_2[2] & 0x7fff;
  gte_rtir_sf0_b();
  iVar4 = param_1[5];
  iVar5 = param_1[6];
  iVar6 = param_1[7];
  gte_ldtr(iVar4,iVar5,iVar6);
  read_mt(iVar4,iVar5,iVar6);
  gte_ldsv_(uVar1,uVar2,uVar3);
  gte_rtirtr_b();
  read_mt(uVar1,uVar2,uVar3);
  *param_3 = uVar1 + iVar4 * 8;
  param_3[1] = uVar2 + iVar5 * 8;
  param_3[2] = uVar3 + iVar6 * 8;
  return param_3;
}

#endif  /* GHIDRA REF */
