/* sphere_test.c -- light/proximity attenuation against an object's cone.
 *
 * Source: LOAD.DLL  FUN_80100fa8.
 *
 * Tests a world-space sample against the object's orientation cone and
 * distance falloff. Used by LOAD.DLL draw-time per-vertex lighting.
 *
 * HIGH-MED.
 */
#include <stdint.h>

extern int32_t Sphere_Test(uintptr_t probe, const int16_t *packed); /* func_0x80016810 */
extern int32_t Vec3_Length(const int32_t *v);                     /* FUN_80016a20 */
extern int16_t *Vec3_Project(int32_t *v, int16_t *out);           /* FUN_80016b08 */

static int32_t rtz_shift12(int32_t v)
{
    if (v < 0) v += 0xfff;
    return v >> 12;
}

uint32_t Sphere_TestWithBacktrack(uintptr_t obj, int *probePos, uintptr_t probe)
{
    int16_t packed[3];
    packed[0] = *(int16_t *)(obj + 0x12);
    packed[1] = *(int16_t *)(obj + 0x18);
    packed[2] = *(int16_t *)(obj + 0x1e);

    int32_t cone = Sphere_Test(probe, packed);
    if (cone >= 0) return 0;

    int32_t delta[3];
    delta[0] = probePos[0] - *(int32_t *)(obj + 0x48);
    delta[1] = probePos[1] - *(int32_t *)(obj + 0x4c);
    delta[2] = probePos[2] - *(int32_t *)(obj + 0x50);

    int32_t dist = Vec3_Length(delta);
    int16_t dir[4];
    uintptr_t dirProbe = (uintptr_t)Vec3_Project(delta, dir);
    int32_t dirCone = Sphere_Test(dirProbe, packed);
    if (dirCone < 0) dirCone += 0xfff;

    int32_t outer = *(int32_t *)(obj + 0x88);
    int32_t inner = *(int32_t *)(obj + 0x84);
    int32_t maxCone = (uint16_t)*(uint16_t *)(obj + 0x8e);
    int32_t minCone = (uint16_t)*(uint16_t *)(obj + 0x8c);
    int32_t angle = dirCone >> 12;

    if ((uint32_t)dist >= (uint32_t)outer) return 0;
    if (maxCone <= angle) return 0;

    int32_t distFade = outer - dist;
    int32_t distDen = (uint32_t)(outer - inner) >> 12;
    uint32_t distScale = (distDen != 0) ? (uint32_t)distFade / (uint32_t)distDen : 0x1000u;
    if (distScale > 0x1000u) distScale = 0x1000u;

    int32_t coneFade = (maxCone - angle) << 12;
    int32_t coneDen = maxCone - minCone;
    int32_t coneScale = (coneDen != 0) ? coneFade / coneDen : 0x1000;
    if (coneScale > 0x1000) coneScale = 0x1000;

    int32_t v = rtz_shift12(rtz_shift12(-cone) * (int32_t)distScale);
    v = rtz_shift12(v * coneScale);
    v = rtz_shift12(v * (uint16_t)*(uint16_t *)(obj + 0x90));
    return (uint32_t)(uint16_t)v;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- LOAD.DLL FUN_80100fa8  (from analysis/dll/LOAD/decomp/80100fa8.c) --- */
// addr: 0x80100fa8  name: FUN_80100fa8

undefined4 FUN_80100fa8(int param_1,int *param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  undefined2 local_40;
  undefined2 local_3e;
  undefined2 local_3c;
  int local_38;
  int local_34;
  int local_30;
  undefined1 auStack_28 [8];
  
  local_40 = *(undefined2 *)(param_1 + 0x12);
  local_3e = *(undefined2 *)(param_1 + 0x18);
  local_3c = *(undefined2 *)(param_1 + 0x1e);
  iVar1 = func_0x80016810(param_3,&local_40);
  if (iVar1 < 0) {
    local_38 = *param_2 - *(int *)(param_1 + 0x48);
    local_34 = param_2[1] - *(int *)(param_1 + 0x4c);
    local_30 = param_2[2] - *(int *)(param_1 + 0x50);
    FUN_80016a20/*0x80016a20*/(&local_38);
    uVar2 = FUN_80016b08/*0x80016b08*/(&local_38,auStack_28);
    func_0x80016810(uVar2,&local_40);
  }
  return 0;
}

#endif  /* GHIDRA REF */
