/* terrain_probe.c -- combined terrain + obstacle height probe.
 *
 * Source: SLUS_005.10  FUN_8001d748.
 *
 * Given an object and a world (x, z) point, returns the highest
 * surface y the object would stand on, considering:
 *
 *   1. The terrain heightmap (Terrain_HeightAt).
 *   2. The object's two attached obstacle chains (+0x74 and +0x78) --
 *      each is a kd-tree of trigger volumes that Object_FindObstacleAt
 *      (FUN_8001f51c) tests against and returns the override y for.
 *
 * If the obstacle test misses, optionally fills the normal (param_3)
 * via Terrain_NormalAt and the material id (param_4) via
 * Terrain_MaterialAt. If the obstacle test hits, the override y
 * displaces the terrain y entirely.
 *
 * HIGH confidence.
 */
#include <stdint.h>
#include "structs.h"

extern int32_t Terrain_HeightAt(uint32_t x, uint32_t z);
extern uint8_t *Terrain_MaterialAt(uint32_t x, uint32_t z);
extern void  Terrain_NormalAt(uint32_t x, uint32_t z, SVECTOR *out);  /* FUN_80025648 */
extern long  VectorNormalSS(SVECTOR *a, SVECTOR *out);
extern int   Object_FindObstacleAt(int chainHead, int terrainY, int *posXyz, SVECTOR *normalOut);  /* FUN_8001f51c */

int Terrain_HeightAndProbe(int obj, int *posXyz, SVECTOR *normalOut, uint32_t *materialOut)
{
    int terrainY = Terrain_HeightAt((uint32_t)posXyz[0], (uint32_t)posXyz[2]);

    int yResult;
    int chainA = *(int *)(obj + 0x74);
    if (chainA != 0
        && (yResult = Object_FindObstacleAt(chainA, terrainY, posXyz, normalOut)) != 0) {
        return yResult;
    }
    int chainB = *(int *)(obj + 0x78);
    if (chainB != 0
        && (yResult = Object_FindObstacleAt(chainB, terrainY, posXyz, normalOut)) != 0) {
        return yResult;
    }

    /* No obstacle hit -- use terrain. Fill normal + material if requested. */
    if (normalOut != NULL) {
        Terrain_NormalAt((uint32_t)posXyz[0], (uint32_t)posXyz[2], normalOut);
        VectorNormalSS(normalOut, normalOut);
    }
    if (materialOut != NULL) {
        *materialOut = (uint32_t)(uintptr_t)Terrain_MaterialAt(
            (uint32_t)posXyz[0], (uint32_t)posXyz[2]);
    }
    return terrainY;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001d748  (from analysis/SLUS_005.10/decomp/8001d748.c) --- */
// addr: 0x8001d748  name: FUN_8001d748

int FUN_8001d748(int param_1,undefined4 *param_2,SVECTOR *param_3,undefined4 *param_4)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  
  iVar1 = FUN_80025400(*param_2,param_2[2]);
  if ((*(int *)(param_1 + 0x74) == 0) ||
     ((iVar2 = FUN_8001f51c(*(int *)(param_1 + 0x74),iVar1,param_2,param_3), iVar2 == 0 &&
      ((*(int *)(param_1 + 0x78) == 0 ||
       (iVar2 = FUN_8001f51c(*(int *)(param_1 + 0x78),iVar1,param_2,param_3), iVar2 == 0)))))) {
    if (param_3 != (SVECTOR *)0x0) {
      FUN_80025648(*param_2,param_2[2],param_3);
      VectorNormalSS(param_3,param_3);
    }
    if (param_4 != (undefined4 *)0x0) {
      uVar3 = FUN_800255f4(*param_2,param_2[2]);
      *param_4 = uVar3;
    }
  }
  else {
    iVar1 = iVar2;
    if (param_4 != (undefined4 *)0x0) {
      *param_4 = 0;
    }
  }
  return iVar1;
}

#endif  /* GHIDRA REF */
