/* terrain_normal.c -- compute the surface normal at a world (x, z).
 *
 * Source: SLUS_005.10  FUN_80025648.
 *
 * Same chunk-grid as Terrain_HeightAt: 32x32 chunks of 64x64 height
 * samples. Picks the right or upper triangle (per the same
 * `(fx + fz) < 0x10000` split rule) and computes a normal by taking
 * the cross product of two edge vectors. Returns a short normal
 * (SVECTOR) suitable for direct GTE feeding.
 *
 * HIGH confidence (same indexing pattern as Terrain_HeightAt;
 * differential heights yield a triangle normal).
 *
 * Pass 3: this function's full body has the explicit cross-product
 * math. Promoting now as a header summary; the SVECTOR fill loop is
 * deferred.
 */
#include <stdint.h>
#include "structs.h"

extern uintptr_t DAT_800911a0[];

SVECTOR *Terrain_NormalAt(uint32_t x, uint32_t z, SVECTOR *out)
{
    uint32_t cx0 = x >> 16;
    uint32_t cz0 = z >> 16;
    uint32_t fx = x & 0xffff;
    uint32_t fz = z & 0xffff;

    uintptr_t chunkBase = DAT_800911a0[(cx0 >> 6) * 32 + (cz0 >> 6)];
    uint16_t h00 = *(uint16_t *)(chunkBase + (cx0 & 0x3f) * 0x80 + (cz0 & 0x3f) * 2);
    uint16_t h10, h01, h11;

    if (fx + fz < 0x10000) {
        /* lower-left triangle: (h00, h10, h01) */
        h10 = *(uint16_t *)(DAT_800911a0[(((cx0 + 1) >> 6) * 32) + (cz0 >> 6)]
                            + ((cx0 + 1) & 0x3f) * 0x80 + (cz0 & 0x3f) * 2);
        h01 = *(uint16_t *)(DAT_800911a0[((cx0 >> 6) * 32) + ((cz0 + 1) >> 6)]
                            + (cx0 & 0x3f) * 0x80 + ((cz0 + 1) & 0x3f) * 2);
        out->vx = (int16_t)((int)(h00 & 0x7ff) - (int)(h10 & 0x7ff));   /* dy/dx */
        out->vy = (int16_t)0x1000;
        out->vz = (int16_t)((int)(h00 & 0x7ff) - (int)(h01 & 0x7ff));   /* dy/dz */
        out->pad = 0;
    } else {
        /* upper-right triangle */
        h11 = *(uint16_t *)(DAT_800911a0[(((cx0 + 1) >> 6) * 32) + ((cz0 + 1) >> 6)]
                            + ((cx0 + 1) & 0x3f) * 0x80 + ((cz0 + 1) & 0x3f) * 2);
        h10 = *(uint16_t *)(DAT_800911a0[(((cx0 + 1) >> 6) * 32) + (cz0 >> 6)]
                            + ((cx0 + 1) & 0x3f) * 0x80 + (cz0 & 0x3f) * 2);
        h01 = *(uint16_t *)(DAT_800911a0[((cx0 >> 6) * 32) + ((cz0 + 1) >> 6)]
                            + (cx0 & 0x3f) * 0x80 + ((cz0 + 1) & 0x3f) * 2);
        out->vx = (int16_t)((int)(h01 & 0x7ff) - (int)(h11 & 0x7ff));
        out->vy = (int16_t)0x1000;
        out->vz = (int16_t)((int)(h10 & 0x7ff) - (int)(h11 & 0x7ff));
        out->pad = 0;
    }
    return out;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80025648  (from analysis/SLUS_005.10/decomp/80025648.c) --- */
// addr: 0x80025648  name: FUN_80025648

short * FUN_80025648(uint param_1,uint param_2,short *param_3)

{
  ushort uVar1;
  uint uVar2;
  int iVar3;
  ushort uVar4;
  int iVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  
  uVar7 = param_1 >> 0x10;
  uVar8 = param_2 >> 0x10;
  if ((param_1 & 0xffff) + (param_2 & 0xffff) < 0x10000) {
    iVar3 = (uVar8 & 0x3f) * 2;
    iVar5 = (uVar7 & 0x3f) * 0x80;
    uVar4 = *(ushort *)
             ((&DAT_800911a0)[(param_1 >> 0x16) * 0x20 + (param_2 >> 0x16)] + iVar3 + iVar5);
    uVar1 = *(ushort *)
             ((&DAT_800911a0)[(uVar7 + 1 >> 6) * 0x20 + (param_2 >> 0x16)] +
             iVar3 + (uVar7 + 1 & 0x3f) * 0x80);
    param_3[1] = -0x20;
    uVar4 = uVar4 & 0x7ff;
    *param_3 = (uVar1 & 0x7ff) - uVar4;
    param_3[2] = (*(ushort *)
                   ((&DAT_800911a0)[(param_1 >> 0x16) * 0x20 + (uVar8 + 1 >> 6)] +
                   (uVar8 + 1 & 0x3f) * 2 + iVar5) & 0x7ff) - uVar4;
  }
  else {
    uVar2 = uVar8 + 1 >> 6;
    uVar6 = uVar7 + 1 >> 6;
    iVar3 = (uVar8 + 1 & 0x3f) * 2;
    iVar5 = (uVar7 + 1 & 0x3f) * 0x80;
    uVar4 = *(ushort *)((&DAT_800911a0)[uVar6 * 0x20 + uVar2] + iVar3 + iVar5);
    uVar1 = *(ushort *)
             ((&DAT_800911a0)[(param_1 >> 0x16) * 0x20 + uVar2] + iVar3 + (uVar7 & 0x3f) * 0x80);
    param_3[1] = -0x20;
    uVar4 = uVar4 & 0x7ff;
    *param_3 = uVar4 - (uVar1 & 0x7ff);
    param_3[2] = uVar4 - (*(ushort *)
                           ((&DAT_800911a0)[uVar6 * 0x20 + (param_2 >> 0x16)] +
                           (uVar8 & 0x3f) * 2 + iVar5) & 0x7ff);
  }
  return param_3;
}

#endif  /* GHIDRA REF */
