/* terrain_init.c -- initialize the terrain chunk pool with a flat world.
 *
 * Source: SLUS_005.10  FUN_800251fc.
 *
 * Called at level-load time before terrain chunks are streamed in. It:
 *
 *   1. Frees all 64 (0x40) currently-held chunk pointers in
 *      DAT_8007a8a0[64].
 *   2. Allocates a single 0x3000-byte "empty chunk" containing:
 *        - 0x2000 bytes of u16 height samples initialised to 0x45ff
 *          (≈1535 -- the engine's flat-world height)
 *        - 0x1000 bytes of u8 material indices initialised to 0
 *   3. Stores that pointer in slot [0] and zeroes slots [1..63].
 *   4. Points every entry of the 32x33 chunk-index table DAT_800911a0
 *      at the empty chunk, so any Terrain_HeightAt query returns
 *      0x45ff.
 *   5. Reinitialises two object template arrays:
 *        UNK_80092220 -- 0x900 entries of stride 0x1c (templates with
 *                        byte[3]=6, byte[7]=0x30).
 *        UNK_8007a9a0 -- 0x800 entries of stride 0x28 (templates with
 *                        byte[3]=9, byte[7]=0x34, byte[0x13]=0x34,
 *                        byte[0x1f]=0x34).
 *   6. Latches the supplied half-word parameter into uRam0000082c
 *      (presumably the level id).
 *
 * MED confidence: the geometry constants are taken verbatim; the meaning
 * of UNK_80092220 / UNK_8007a9a0 entries (likely instance templates for
 * world objects + collision primitives) needs pass-2 cross-reference.
 */
#include <stdint.h>

extern void *Heap_Free(void *p);
extern void *Heap_AllocOrRetry(uint32_t n);

extern uintptr_t DAT_8007a8a0[64];
extern uintptr_t DAT_800911a0[];        /* 32 * 33 entries (out-of-bounds row is alias) */
extern uint8_t   UNK_80092220[];
extern uint8_t   UNK_8007a9a0[];
extern uint16_t  uRam0000082c;
extern uint32_t  uRam00000814;

void Terrain_InitFlatWorld(uint16_t levelId)
{
    /* Step 1: free any existing chunk pointers. */
    uRam00000814  = 0;
    uRam0000082c  = levelId;
    for (int i = 0; i < 64; i++) {
        if (DAT_8007a8a0[i] != 0) Heap_Free((void *)DAT_8007a8a0[i]);
    }

    /* Step 2-3: allocate one shared "empty" chunk. */
    uint8_t *empty = (uint8_t *)Heap_AllocOrRetry(0x3000);
    DAT_8007a8a0[0] = (uintptr_t)empty;
    for (int i = 1; i < 64; i++) DAT_8007a8a0[i] = 0;

    /* Heights: 0x45ff for the entire 0x2000-byte (64x64 u16) region. */
    for (int row = 0; row < 64; row++) {
        for (int col = 0; col < 64; col++) {
            *(uint16_t *)(empty + row * 0x80 + col * 2) = 0x45ff;
            empty[0x2000 + row * 0x40 + col] = 0;
        }
    }

    /* Step 4: point every chunk-index entry at the empty chunk. */
    for (int row = -1; row < 33; row++) {
        for (int col = 0; col < 32; col++) {
            DAT_800911a0[row * 32 + col] = (uintptr_t)empty;
        }
    }

    /* Step 5a: 0x900 templates of stride 0x1c. */
    for (uint32_t i = 0; i < 0x900; i++) {
        uint8_t *t = &UNK_80092220[i * 0x1c];
        t[3] = 6;
        t[7] = 0x30;
    }

    /* Step 5b: 0x800 templates of stride 0x28. */
    for (uint32_t i = 0; i < 0x800; i++) {
        uint8_t *t = &UNK_8007a9a0[i * 0x28];
        t[3]    = 9;
        t[7]    = 0x34;
        t[0x13] = 0x34;
        t[0x1f] = 0x34;
    }
    /* Pass 2: function continues with two more init loops -- left as
     * UNKNOWN until the affected templates are reverse-mapped. */
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800251fc  (from analysis/SLUS_005.10/decomp/800251fc.c) --- */
// addr: 0x800251fc  name: FUN_800251fc

void FUN_800251fc(undefined2 param_1)

{
  int iVar1;
  undefined4 *puVar2;
  undefined *puVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  uint uVar8;
  int *piVar9;
  undefined *p1;
  
  iVar6 = 0;
  piVar9 = &DAT_8007a8a0;
  uRam00000814 = 0;
  uRam0000082c = param_1;
  do {
    if (*piVar9 != 0) {
      FUN_80045088();
    }
    iVar6 = iVar6 + 1;
    piVar9 = piVar9 + 1;
  } while (iVar6 < 0x40);
  iVar6 = FUN_800116f4(0x3000);
  iVar7 = 1;
  puVar2 = &DAT_8007a8a4;
  DAT_8007a8a0 = iVar6;
  do {
    *puVar2 = 0;
    iVar7 = iVar7 + 1;
    puVar2 = puVar2 + 1;
  } while (iVar7 < 0x40);
  iVar7 = 0;
  do {
    iVar4 = 0;
    iVar5 = iVar7 << 7;
    do {
      iVar1 = iVar4 + iVar7 * 0x40;
      iVar4 = iVar4 + 1;
      *(undefined2 *)(iVar6 + iVar5) = 0x45ff;
      *(undefined1 *)(iVar6 + iVar1 + 0x2000) = 0;
      iVar5 = iVar5 + 2;
    } while (iVar4 < 0x40);
    iVar7 = iVar7 + 1;
  } while (iVar7 < 0x40);
  iVar7 = -1;
  do {
    iVar5 = 0;
    iVar4 = iVar7 << 7;
    do {
      *(int *)((int)&DAT_800911a0 + iVar4) = iVar6;
      iVar5 = iVar5 + 1;
      iVar4 = iVar4 + 4;
    } while (iVar5 < 0x20);
    iVar7 = iVar7 + 1;
  } while (iVar7 < 0x21);
  uVar8 = 0;
  puVar3 = &UNK_80092220;
  do {
    puVar3[3] = 6;
    puVar3[7] = 0x30;
    uVar8 = uVar8 + 1;
    puVar3 = puVar3 + 0x1c;
  } while (uVar8 < 0x900);
  uVar8 = 0;
  puVar3 = &UNK_8007a9a0;
  do {
    puVar3[3] = 9;
    puVar3[7] = 0x34;
    puVar3[0x1f] = 0x34;
    puVar3[0x13] = 0x34;
    uVar8 = uVar8 + 1;
    puVar3 = puVar3 + 0x28;
  } while (uVar8 < 0x800);
  uVar8 = 0;
  puVar3 = &UNK_8008e9a0;
  do {
    puVar3[3] = 0xc;
    puVar3[7] = 0x3c;
    uVar8 = uVar8 + 1;
    puVar3 = puVar3 + 0x34;
  } while (uVar8 < 0x20);
  iVar6 = 0;
  puVar3 = &DAT_800910c0;
  p1 = &DAT_800910d8;
  do {
    puVar3[3] = 5;
    puVar3[7] = 0x28;
    p1[3] = 5;
    p1[7] = 0x28;
    MargePrim(puVar3,p1);
    p1 = p1 + 0x30;
    iVar6 = iVar6 + 1;
    puVar3 = puVar3 + 0x30;
  } while (iVar6 < 2);
  return;
}

#endif  /* GHIDRA REF */
