/* b17_hit.c -- AIRGRAVE b17_1 spin + hit-response state machine.
 *
 * Source: AIRGRAVE.DLL  FUN_801014d0.
 *
 * Two main modes:
 *   mode 0 (per-tick): rotate the parent's child object (obj[0xe])
 *     by +0x22 around its yaw axis (faster than the radar's +0x11).
 *     If a hit impulse arrives (param_3 != NULL), spark.
 *   mode 3 (hit-response): if the impulser is a Player vehicle in
 *     "weapon-fire" state and we're visible (flag 0x80), spawn a
 *     spark + play sfx 2, then create a new "B-17 down" event object
 *     via FUN_8001ffd4 with id 0x71, and link it to the impulser
 *     (or its current target) at offset +0xa4.
 *
 * MED confidence.
 */
#include <stdint.h>

extern void ImpactSparks_Spawn(void *obj);     /* FUN_8001d708 */
extern int  Object_FrameCounterBump(int payload, uint16_t arg);  /* FUN_8001f9cc */
extern uint32_t SfxChannel_Acquire(void);                          /* FUN_8004410c */
extern void Audio_PlaySfxAtPosVar(uint32_t ch, uint32_t bank, int sfxId, void *pos);  /* FUN_800447e8 */
extern uint32_t *Object_FastList_Insert_TypedId(int listSentinel, uint8_t kind); /* FUN_8001ffd4 */

uint32_t AG_B17HitTick(uint32_t *parent, int mode, uint32_t *impulse)
{
    switch (mode) {
    case 0: {
        uint8_t *child = (uint8_t *)(uintptr_t)parent[0xe];
        *(int16_t *)(child + 0x42) = (int16_t)(*(int16_t *)(child + 0x42) + 0x22);
        if (impulse == NULL) return 0;
        ImpactSparks_Spawn(child);
        /* fall through to mode 3 */
    }
    case 3: {
        uint32_t *src = (uint32_t *)(uintptr_t)impulse[3];
        if (*(int8_t *)((uintptr_t)src + 4) == 3
            && *(int8_t *)(*impulse + 4) == 2
            && (parent[0] & 0x80u) != 0)
        {
            src[0] |= 0x20u;
            Object_FrameCounterBump((int)(uintptr_t)parent,
                                     (uint16_t)(*(uint16_t *)((uintptr_t)parent + 0x46)
                                               + *(uint16_t *)(uintptr_t)parent[0x18]));
            uint32_t ch = SfxChannel_Acquire();
            Audio_PlaySfxAtPosVar(ch,
                                  *(uint32_t *)(parent[0x16] + 8),
                                  2,
                                  parent + 0x12);
            uint32_t *evt = Object_FastList_Insert_TypedId(0x80065a18, 0x71);
            if (evt != NULL) {
                uint32_t srcVA = *impulse;
                *((uint8_t *)evt + 8) = 2;
                uint32_t aiTarget = *(uint32_t *)(srcVA + 0xe4);
                if (aiTarget == 0) aiTarget = srcVA;
                evt[0x29] = aiTarget;
                evt[0] &= 0xffffffddu;
            }
        }
        return 0;
    }
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- AIRGRAVE.DLL FUN_801014d0  (from analysis/dll/AIRGRAVE/decomp/801014d0.c) --- */
// addr: 0x801014d0  name: FUN_801014d0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_801014d0(uint *param_1,undefined4 param_2,uint *param_3)

{
  char cVar1;
  undefined4 uVar2;
  uint uVar3;
  int iVar4;
  uint *puVar5;
  uint uVar6;
  
  switch(param_2) {
  case 0:
    *(short *)(param_1[0xe] + 0x42) = *(short *)(param_1[0xe] + 0x42) + 0x22;
    if (param_3 == (uint *)0x0) {
      return 0;
    }
    FUN_8001d708/*0x8001d708*/(param_1[0xe]);
  case 3:
    puVar5 = (uint *)param_3[3];
    if ((((char)puVar5[1] == '\x03') && (*(char *)(*param_3 + 4) == '\x02')) &&
       ((*param_1 & 0x80) != 0)) {
      *puVar5 = *puVar5 | 0x20;
      FUN_8001f9cc/*0x8001f9cc*/(param_1,(uint)*(ushort *)((int)param_1 + 0x46) +
                              (uint)*(ushort *)param_1[0x18]);
      uVar2 = FUN_8004410c/*0x8004410c*/();
      FUN_800447e8/*0x800447e8*/(uVar2,*(undefined4 *)(param_1[0x16] + 8),2,param_1 + 0x12);
      puVar5 = (uint *)FUN_8001ffd4/*0x8001ffd4*/(0x80065a18,0x71);
      if (puVar5 != (uint *)0x0) {
        uVar3 = *param_3;
        *(undefined1 *)(puVar5 + 2) = 2;
        uVar6 = *(uint *)(uVar3 + 0xe4);
        if (uVar6 == 0) {
          uVar6 = uVar3;
        }
        puVar5[0x29] = uVar6;
        *puVar5 = *puVar5 & 0xffffffdd;
        func_0x80020844(puVar5);
        if ((*puVar5 & 0x80) == 0) {
          cVar1 = FUN_8004410c/*0x8004410c*/();
          *(char *)((int)puVar5 + 5) = cVar1;
          FUN_800443c8/*0x800443c8*/((int)cVar1,*(undefined4 *)(puVar5[0x16] + 8),1,0);
          FUN_80020744/*0x80020744*/(puVar5);
        }
      }
      *(undefined1 *)(param_1 + 2) = 1;
    }
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
switchD_80101510_caseD_8:
    iVar4 = FUN_80022320/*0x80022320*/(param_1,param_3);
    if (iVar4 != 0) {
      FUN_80020778/*0x80020778*/(param_1);
      func_0x80020844(param_1);
switchD_80101510_caseD_2:
      puVar5 = param_1;
      if ((*param_1 & 0x80) != 0) {
        **(uint **)(param_1[0xe] + 0x34) = **(uint **)(param_1[0xe] + 0x34) | 0x20;
        *(undefined1 *)(param_1 + 2) = 0;
        FUN_80020778/*0x80020778*/(param_1);
        FUN_8001ac08/*0x8001ac08*/(param_1);
        FUN_8001f9cc/*0x8001f9cc*/(param_1,(int)_DAT_800659d0);
        puVar5 = (uint *)0x1;
      }
      **(uint **)(param_1[0xe] + 0x34) = **(uint **)(param_1[0xe] + 0x34) & 0xffffffdf;
      FUN_80020744/*0x80020744*/(puVar5);
      **(ushort **)(param_1[0xe] + 0x30) = **(ushort **)(param_1[0xe] + 0x30) ^ 5;
      FUN_80020890/*0x80020890*/(param_1,0x708);
      goto switchD_80101510_caseD_1;
    }
    break;
  case 1:
switchD_80101510_caseD_1:
    *(undefined1 *)(*(int *)(param_1[0xe] + 0x34) + 4) = 3;
    FUN_80020890/*0x80020890*/(param_1,0x708);
    FUN_8001ac08/*0x8001ac08*/(param_1);
    FUN_8001f9cc/*0x8001f9cc*/(param_1,(int)_DAT_800659d0);
    break;
  case 2:
    goto switchD_80101510_caseD_2;
  default:
    break;
  case 8:
    goto switchD_80101510_caseD_8;
  }
  return 0;
}

#endif  /* GHIDRA REF */
