/* control_tower.c -- AirGrave control_tower_1 impact.
 *
 * Source: AIRGRAVE.DLL  FUN_80100c18.
 *
 * Byte-identical body to WW_BonfireImpact (Wild West) -- another
 * instance of inlined-across-DLLs convenience code. On non-zero,
 * non-5 mode, set scratch slot _DAT_00000029 to (obj.posY - 0x5f5)
 * (= "spark emit at this Y"), then unconditionally invoke
 * Damage_Apply.
 *
 * HIGH.
 */
#include <stdint.h>

extern void Damage_Apply(void *obj);
extern int8_t _DAT_00000029;

uint32_t AG_ControlTowerImpact(int obj, int mode)
{
    if (mode != 0) {
        if (mode == 5) goto handle;
        obj = 1;
    }
    _DAT_00000029 = (int8_t)(*(int *)(obj + 0x28) - 0x5f5);
handle:
    Damage_Apply((void *)(intptr_t)obj);
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- AIRGRAVE.DLL FUN_80100c18  (from analysis/dll/AIRGRAVE/decomp/80100c18.c) --- */
// addr: 0x80100c18  name: FUN_80100c18

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100c18(int param_1,int param_2)

{
  if (param_2 != 0) {
    if (param_2 == 5) goto LAB_80100c4c;
    param_1 = 1;
  }
  _DAT_00000029 = *(int *)(param_1 + 0x28) + -0x5f5;
LAB_80100c4c:
  FUN_800205f8/*0x800205f8*/();
  return 0;
}

#endif  /* GHIDRA REF */
