/* bridge_collapse.c -- Wild West bridge plank collapse handler.
 *
 * Source: WILDWEST.DLL  FUN_801010a8.
 *
 * Per-plank impact handler. On impact (kind==7) and damage tier
 * exceeded (self+3 lower 7 bits < imp+0xc damage), drop the plank's
 * physics constraint: allocate a free-rigid body via FUN_8003ff28,
 * zero its impulse/gravity except Y=-0xbeb (3.0 in 4.12 down), spawn
 * a debris projectile (kind 0x29) tied to the bridge bin, set its
 * post-tick callback to 0x8003cb64.
 *
 * State transitions:
 *   case 0  -- per-tick: if HP exhausted (self+0xc == 0) retire.
 *   case 3  -- impact event.
 *   case 2  -- after impact, if self+0x29 (chain link counter) == 0
 *              detach the submodel via SubModel_Detach.
 *   case 6, 1, default -- no-op (handled elsewhere).
 *   case 8, 9 -- routed targets.
 *
 * MED.
 */
#include <stdint.h>

extern void Object_RetireDeferred(uint32_t *self);
extern int  RigidBody_Alloc(void);                                /* FUN_8003ff28 */
extern uint32_t Pool_AllocProjectile(void);
extern void Pool_LaunchProjectile(uint32_t h, uint32_t bin, int kind, void *xyz);
extern void Damage_StandardVehicle(uint32_t *self, void *imp);    /* func_0x80022320 */
extern void Damage_Apply_AgainstSelf(void *self, void *param);
extern void SubModel_Detach(uint32_t *self);
extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern uint32_t _DAT_800658fc;
extern int LAB_8003cb64(int obj, int event, int param3);

uint32_t WW_BridgeCollapse(uint32_t *self, uint32_t mode, int *arg)
{
    int *imp = arg;
    switch (mode) {
    case 0:
        if (self[0xc] == 0) Object_RetireDeferred(self);
        /* fall through */
    case 3:
        if (*(char *)(*imp + 4) == 7) {
            if (self[0xe] != 0 &&
                ((uint16_t)self[3] & 0x7f) < *(uint16_t *)(*imp + 0xc))
            {
                int rb = RigidBody_Alloc();
                *(uint16_t *)(rb + 0xc) = 0;
                *(uint32_t *)(rb + 0x88) = 0;
                *(uint32_t *)(rb + 0x8c) = 0xfffff415u;  /* -0xbeb */
                *(uint32_t *)(rb + 0x90) = 0;
                uint32_t h = Pool_AllocProjectile();
                Pool_LaunchProjectile(h, _DAT_800658fc, 0x29, (void *)(intptr_t)(rb + 0x24));
                Object_SetCallbackPsxSlot((void *)(uintptr_t)rb, (uintptr_t)&LAB_8003cb64);
            }
            Damage_StandardVehicle(self, (void *)(intptr_t)*(uint16_t *)(*imp + 0xc));
        }
        if ((*self & 1) == 0 && (uint32_t *)imp[3] != self) {
            int rb = RigidBody_Alloc();
            Object_SetCallbackPsxSlot((void *)(uintptr_t)rb, (uintptr_t)&LAB_8003cb64);
            *(uint16_t *)(rb + 0xc)  = 0;
            Damage_Apply_AgainstSelf(self, (void *)(intptr_t)300);
            /* fall to case 8 */
        case 8:
            Damage_StandardVehicle(self, imp);
            /* fall to case 2 */
        case 2:
            if (self[0x29] == 0) {
                SubModel_Detach(self);
        case 9:
                if (*(int16_t *)((char *)imp + 6) == *(int16_t *)((char *)self + 6))
                    *self |= 0x10000u;
            }
        }
        break;
    case 6: case 1: default: break;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- WILDWEST.DLL FUN_801010a8  (from analysis/dll/WILDWEST/decomp/801010a8.c) --- */
// addr: 0x801010a8  name: FUN_801010a8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_801010a8(uint *param_1,undefined4 param_2,int *param_3)

{
  int iVar1;
  undefined4 uVar2;
  int *piVar3;
  
  piVar3 = param_3;
  switch(param_2) {
  case 0:
    if (param_1[0xc] == 0) {
      FUN_800205f8/*0x800205f8*/(param_1);
      piVar3 = param_3;
    }
  case 3:
    param_3 = piVar3;
    if (*(char *)(*piVar3 + 4) == '\a') {
      if ((param_1[0xe] != 0) && (((ushort)param_1[3] & 0x7f) < *(ushort *)(*piVar3 + 0xc))) {
        iVar1 = FUN_8003ff28/*0x8003ff28*/();
        *(undefined2 *)(iVar1 + 0xc) = 0;
        *(undefined4 *)(iVar1 + 0x88) = 0;
        *(undefined4 *)(iVar1 + 0x8c) = 0xfffff415;
        *(undefined4 *)(iVar1 + 0x90) = 0;
        uVar2 = FUN_8004410c/*0x8004410c*/();
        param_3 = (int *)&DAT_00000029;
        FUN_8004483c/*0x8004483c*/(uVar2,_DAT_800658fc,0x29,iVar1 + 0x24);
        *(undefined4 *)(iVar1 + 100) = 0x8003cb64;
      }
      FUN_80022320/*0x80022320*/(param_1,*(undefined2 *)(*piVar3 + 0xc));
    }
    if (((*param_1 & 1) == 0) && ((uint *)param_3[3] != param_1)) {
      iVar1 = FUN_8003ff28/*0x8003ff28*/(param_1[0xe]);
      *(undefined4 *)(iVar1 + 100) = 0x8003cb64;
      *(undefined2 *)(iVar1 + 0xc) = 0;
      FUN_80020890/*0x80020890*/(param_1,300);
switchD_801010e0_caseD_8:
      FUN_80022320/*0x80022320*/(param_1,param_3);
switchD_801010e0_caseD_2:
      if (param_1[0x29] == 0) {
        FUN_8003fc50/*0x8003fc50*/(param_1);
switchD_801010e0_caseD_9:
        if (*(short *)((int)param_3 + 6) == *(short *)((int)param_1 + 6)) {
          *param_1 = *param_1 | 0x10000;
switchD_801010e0_caseD_6:
          goto switchD_801010e0_caseD_1;
        }
      }
    }
    break;
  case 1:
switchD_801010e0_caseD_1:
  default:
    break;
  case 2:
    goto switchD_801010e0_caseD_2;
  case 6:
    goto switchD_801010e0_caseD_6;
  case 8:
    goto switchD_801010e0_caseD_8;
  case 9:
    goto switchD_801010e0_caseD_9;
  }
  return 0;
}

#endif  /* GHIDRA REF */
