/* bridge.c -- Wild West TBridge_1 / Gallow_1 destroy-on-impact handler.
 *
 * Source: WILDWEST.DLL  FUN_801003ec.
 *
 * Triggered when a vehicle / projectile collides with the level
 * object. The dispatch:
 *
 *   - mode == 3 (collision with bullet/missile): try a quick
 *     ground-check via func_0x8002239c (HIGH-confidence: collision
 *     test against terrain heightmap); if that fails, try a circular
 *     overlap via func_0x80022320.
 *   - mode == 1: passthrough.
 *   - mode == 8: forced impact; equivalent to falling into the
 *     terrain-check.
 *
 * On any successful hit, write 0x14 into obj.flagsB.+0x28 (signal
 * destroyed) and queue a particle effect via func_0x80042cdc (likely
 * Effects_QueueParticles).
 *
 * MED confidence.
 */
#include <stdint.h>

extern int  Collision_AgainstTerrain(int obj, int impact);    /* func_0x8002239c */
extern int  Collision_Circular     (int obj, int impact);    /* func_0x80022320 */
extern void *Effects_QueueParticles(int posXyzAddr, int);    /* func_0x80042cdc */

uint32_t WW_BridgeDestroyTick(int obj, uint32_t mode, void *impactCtx)
{
    int  collisionPosAddr;
    int  hit;

    if (mode == 3) {
        hit = Collision_AgainstTerrain(obj, (int)(intptr_t)impactCtx);
        collisionPosAddr = obj + 0x48;
        if (hit != 0) goto fired;
        hit = Collision_Circular(obj, (int)(intptr_t)impactCtx);
        if (hit != 0) goto fired;
    } else if (mode > 3 || mode == 1) {
        if (mode != 8) {
            hit = Collision_AgainstTerrain(obj, (int)(intptr_t)impactCtx);
            collisionPosAddr = obj + 0x48;
            if (hit != 0) goto fired;
        }
        hit = Collision_Circular(obj, (int)(intptr_t)impactCtx);
        collisionPosAddr = obj + 0x48;
        if (hit != 0) goto fired;
    }
    collisionPosAddr = 1;
    *(uint16_t *)(*(int *)(obj + 0x30) + 0x28) = 0x14;

fired: {
    void *fx = Effects_QueueParticles(collisionPosAddr, 0);
    *(uint16_t *)((uint8_t *)fx + 8) = 0xffff;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- WILDWEST.DLL FUN_801003ec  (from analysis/dll/WILDWEST/decomp/801003ec.c) --- */
// addr: 0x801003ec  name: FUN_801003ec

undefined4 FUN_801003ec(int param_1,uint param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  
  if (param_2 == 3) {
LAB_80100434:
    iVar1 = FUN_8002239c/*0x8002239c*/(param_1,param_3);
    iVar2 = param_1 + 0x48;
    if (iVar1 != 0) goto LAB_8010047c;
LAB_80100450:
    iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
    iVar2 = param_1 + 0x48;
    if (iVar1 != 0) goto LAB_8010047c;
  }
  else if ((3 < param_2) || (param_2 != 1)) {
    if (param_2 != 8) goto LAB_80100434;
    goto LAB_80100450;
  }
  iVar2 = 1;
  *(undefined2 *)(*(int *)(param_1 + 0x30) + 0x28) = 0x14;
LAB_8010047c:
  iVar1 = FUN_80042cdc/*0x80042cdc*/(iVar2,0);
  *(undefined2 *)(iVar1 + 8) = 0xffff;
  return 0;
}

#endif  /* GHIDRA REF */
