/* gallow.c -- Wild West Gallow_1 destruction + event broadcast.
 *
 * Source: WILDWEST.DLL  FUN_80100fa4.
 *
 * Multi-mode handler:
 *   mode 0 (tick): if obj.health == 0 (already destroyed), apply
 *     damage to self; fall into damage processing.
 *   mode 3 (weapon hit): Damage_FromImpulse.
 *   mode 8 (forced hit): same as 3 sans the impulse check.
 *   Mode 2: Effects_SpawnExplosion(self) + broadcast.
 *   mode 9: when broadcast lands on us, set flag 0x10000 if id matches.
 *   mode 1 / 6: pass-through.
 *
 * Confirms the +0xc field as health (zero == dead).
 *
 * MED.
 */
#include <stdint.h>

extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern void Damage_Apply(void *obj);
extern int  Object_DispatchList(void *listHead, uint32_t event, uint32_t arg);
extern int  Effects_SpawnExplosion(int obj);
extern uint8_t DAT_80065a18[];

uint32_t WW_GallowTick(uint32_t *self, uint32_t mode, uint32_t *impulse)
{
    switch (mode) {
    case 0:
        if (self[0xc] == 0) Damage_Apply(self);
        /* fall through */
    case 3:
        Damage_FromImpulse(self, (int *)impulse);
        /* fall through */
    case 8: {
        int hit = Damage_AccumulateOrFire(self, (uint16_t)(uintptr_t)impulse);
        if (hit != 0) {
            impulse = self;
            Object_DispatchList(DAT_80065a18, 9, 0);
            goto case2;
        }
        break;
    }
case2:
    case 2:
        Effects_SpawnExplosion((int)(uintptr_t)self);
        goto case9;
case9:
    case 9:
        if (*(int16_t *)((uintptr_t)impulse + 6) != *(int16_t *)((uintptr_t)self + 6)) return 0;
        self[0] |= 0x10000u;
        break;
    case 6:
    case 1:
    default:
        break;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- WILDWEST.DLL FUN_80100fa4  (from analysis/dll/WILDWEST/decomp/80100fa4.c) --- */
// addr: 0x80100fa4  name: FUN_80100fa4

undefined4 FUN_80100fa4(uint *param_1,undefined4 param_2,uint *param_3)

{
  int iVar1;
  
  switch(param_2) {
  case 0:
    if (param_1[0xc] == 0) {
      FUN_800205f8/*0x800205f8*/(param_1);
    }
  case 3:
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
switchD_80100fd4_caseD_8:
    iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
    if (iVar1 != 0) {
      param_3 = param_1;
      FUN_8002002c/*0x8002002c*/(0x80065a18,9);
switchD_80100fd4_caseD_2:
      FUN_8003fc50/*0x8003fc50*/(param_1);
      goto switchD_80100fd4_caseD_9;
    }
    break;
  case 2:
    goto switchD_80100fd4_caseD_2;
  default:
    break;
  case 8:
    goto switchD_80100fd4_caseD_8;
  case 9:
switchD_80100fd4_caseD_9:
    if (*(short *)((int)param_3 + 6) != *(short *)((int)param_1 + 6)) {
      return 0;
    }
    *param_1 = *param_1 | 0x10000;
  case 6:
  case 1:
  }
  return 0;
}

#endif  /* GHIDRA REF */
