/* misc.c -- Wild West small object handlers.
 *
 * Source: WILDWEST.DLL
 *   FUN_80100950 -- WW_BonfireImpact: on mode-5 cue, calls Damage_Apply
 *                   with a hardcoded address +0x29 hold-over from the
 *                   adjacent slot's posY. Otherwise sets _DAT_00000029
 *                   (scratchpad slot) to obj.posY - 0x5f5 (a Y offset
 *                   for sparks).
 *   FUN_8010035c -- WW_HotelHit: collision-based damage broadcast --
 *                   if circular collision succeeds, finds the paired
 *                   spawn-id object via Object_FindByIdPlusOffset and
 *                   calls Object_SetState(found, 0x8f80) -- the "in
 *                   ruins" appearance state.
 *
 * MED.
 */
#include <stdint.h>

extern void Damage_Apply(void *obj);
extern uint32_t FUN_80022320(uint32_t *self, uint32_t amount);
extern int  Object_FindByIdPlusOffset(int spawnId);
extern void Object_SetState(int obj, int state);
extern int8_t _DAT_00000029;

uint32_t WW_BonfireImpact(int obj, int mode)
{
    if (mode != 0) {
        if (mode == 5) goto handle;
        obj = 1;   /* preserved sentinel-clobber pattern */
    }
    _DAT_00000029 = (int8_t)(*(int *)(obj + 0x28) - 0x5f5);
handle:
    Damage_Apply((void *)(intptr_t)obj);
    return 0;
}

uint32_t FUN_80100950(int obj, int mode)
{
    return WW_BonfireImpact(obj, mode);
}

uint32_t WW_HotelHit(int obj, uint32_t mode, int *impulse)
{
    if (mode != 8) {
        if (*(int8_t *)(*impulse + 4) != 7) return 0;
        impulse = (int *)(uintptr_t)*(uint16_t *)(*impulse + 0xc);
    }
    int hit = FUN_80022320((uint32_t *)(uintptr_t)(uint32_t)obj, (uint32_t)(uintptr_t)impulse);
    if (hit == 0) return 0;
    int paired = Object_FindByIdPlusOffset(*(int16_t *)(obj + 6));
    if (paired != 0) Object_SetState(paired + 0xc, 0x8f80);
    return 0xffffffffu;
}

uint32_t FUN_8010035c(int obj, uint32_t mode, int *impulse)
{
    return WW_HotelHit(obj, mode, impulse);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80100950  (from analysis/dll/WILDWEST/decomp/80100950.c) --- */
// addr: 0x80100950  name: FUN_80100950

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100950(int param_1,int param_2)

{
  if (param_2 != 0) {
    if (param_2 == 5) goto LAB_80100984;
    param_1 = 1;
  }
  _DAT_00000029 = *(int *)(param_1 + 0x28) + -0x5f5;
LAB_80100984:
  FUN_800205f8/*0x800205f8*/();
  return 0;
}

/* --- ? FUN_8010035c  (from analysis/dll/WILDWEST/decomp/8010035c.c) --- */
// addr: 0x8010035c  name: FUN_8010035c

undefined4 FUN_8010035c(int param_1,int param_2,int *param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    if (*(char *)(*param_3 + 4) != '\a') {
      return 0;
    }
    param_3 = (int *)(uint)*(ushort *)(*param_3 + 0xc);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  uVar2 = 0;
  if (iVar1 != 0) {
    iVar1 = FUN_8001fd9c/*0x8001fd9c*/((int)*(short *)(param_1 + 6));
    if (iVar1 != 0) {
      FUN_80024718/*0x80024718*/(iVar1 + 0xc,0x8f80);
    }
    uVar2 = 0xffffffff;
  }
  return uVar2;
}

#endif  /* GHIDRA REF */
