/* saloon_destruct.c -- Wild West saloon destructible facade.
 *
 * Source: WILDWEST.DLL  FUN_8010178c.
 *
 * Multi-piece destructible western-town facade. Each panel piece is
 * a child at self+0xe linked via +0x34. Damage propagates left to
 * right: a hit triggers the immediate piece + the two adjacent ones,
 * spawning splinter debris (object id 0x2bb) at the joint locations.
 *
 * Per-tick walks chain bumping piece anim phases. On vehicle hit
 * (kind==7) crumbles via Damage_StandardVehicle; on death detaches
 * pieces and retires.
 *
 * mode: 0=tick, 1=spawn-finalize, 2=retire, 3=impact, 4=silence FX.
 *
 * MED. Same crumble idiom as wildwest/bridge_collapse.c but multi-
 * piece chain.
 */
#include <stdint.h>

extern void Damage_StandardVehicle(uint32_t *self, void *imp);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t a);
extern void SubModel_Detach(uint32_t *self);
extern void Object_RetireDeferred(uint32_t *self);
extern void Object_RefitAABB(uint32_t *self);
extern uint32_t Object_SpawnFromBank(uint32_t bin, int kind, int prio, int flag);
extern void Object_Suspend(void);
extern int  Rand255(void);
extern uint8_t Pool_AllocSFX(void);
extern void Pool_BindFXOnObject(uint8_t h, uint32_t bin, int slot, int aux);
extern void SFX_StopWorld(int h);
extern uint8_t SFX_PlayWorldXY(uint32_t *xyz);
extern void SFX_Update(int h, int posVoxel);
extern uint32_t _DAT_80065310;

uint32_t WW_SaloonDestruct(uint32_t *self, uint32_t mode, int *imp)
{
    switch (mode) {
    case 0: {
        /* Per-tick: animate each piece's phase. */
        for (uintptr_t c = self[0xe]; c != 0; c = *(uint32_t *)(c + 0x34))
            if (*(int16_t *)(c + 6) == 0)
                *(int16_t *)(c + 0x40) += 0x10;
        if ((_DAT_80065310 & 0xf) == 0)
            for (uintptr_t c = self[0xe]; c != 0; c = *(uint32_t *)(c + 0x34))
                Object_RefitAABB((uint32_t *)c);
        SFX_Update((int)*((char *)self + 5), SFX_PlayWorldXY(self + 9));
        return 0;
    }
    case 1: {
        uint8_t h = Pool_AllocSFX();
        *((char *)self + 5) = (char)h;
        Pool_BindFXOnObject(h, *(uint32_t *)(self[0x16] + 8), 4, 0);
        return 0;
    }
    case 2:
        SubModel_Detach(self);
        Object_RetireDeferred(self);
        return 0;
    case 3: {
        int impObj = *imp;
        if (*(uint8_t *)(impObj + 4) != 7) return 0;
        Damage_StandardVehicle(self, (void *)(intptr_t)*(uint16_t *)(impObj + 0xc));
        if (Damage_AccumulateOrFire(self, 0)) {
            /* Spawn splinter debris at random child piece. */
            uint32_t bin = self[0x16];
            uint32_t *deb = (uint32_t *)Object_SpawnFromBank(bin, 0x2bb, 0x80, 8);
            *deb = 0x34u;
            int r = Rand255();
            deb[0x12] = self[9]  + (r * 0x4000 >> 15) - 0x2000;
            deb[0x13] = self[10];
            deb[0x14] = self[0xb] + (r * 0x4000 >> 15) - 0x2000;
            deb[0x19] = 0x8003e80cu;
            Object_Suspend();
        }
        return 0;
    }
    case 4:
        SFX_StopWorld((int)*((char *)self + 5));
        return 0;
    default: return 0;
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- WILDWEST.DLL FUN_8010178c  (from analysis/dll/WILDWEST/decomp/8010178c.c) --- */
// addr: 0x8010178c  name: FUN_8010178c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_8010178c(uint *param_1,undefined4 param_2,int *param_3)

{
  int iVar1;
  uint uVar2;
  undefined4 uVar3;
  int iVar4;
  int iVar5;
  int extraout_v1;
  int iVar6;
  uint *puVar7;
  uint uVar8;
  uint uVar9;
  uint local_40;
  int local_3c;
  uint local_38;
  short local_30;
  short local_2e;
  short local_2c;
  int local_20;
  int local_1c;
  int local_18;
  
  switch(param_2) {
  case 0:
    if (param_1[0xf] != 0) {
      return 0;
    }
    local_40 = param_1[9];
    local_3c = param_1[10] + param_1[0x15];
    local_38 = param_1[0xb];
    iVar4 = FUN_8001d748/*0x8001d748*/(param_1,&local_40,&local_30,0);
    if (iVar4 < local_3c + 0x800) {
      iVar6 = (int)local_30;
      uVar2 = param_1[0x20];
      iVar1 = uVar2 * iVar6 + param_1[0x21] * (int)local_2e + param_1[0x22] * (int)local_2c;
      if (iVar1 < 0) {
        iVar1 = iVar1 + 0x7ff;
      }
      iVar1 = iVar1 >> 0xb;
      iVar5 = iVar6 << 1;
      if (iVar1 < 0) {
        iVar6 = iVar1 * iVar6;
        if (iVar6 < 0) {
          iVar6 = iVar6 + 0xfff;
        }
        param_1[0x20] = uVar2 - (iVar6 >> 0xc);
        iVar6 = iVar1 * local_2e;
        if (iVar6 < 0) {
          iVar6 = iVar6 + 0xfff;
        }
        iVar6 = (param_1[0x21] - (iVar6 >> 0xc)) * 3;
        if (iVar6 < 0) {
          iVar6 = iVar6 + 3;
        }
        param_1[0x21] = iVar6 >> 2;
        iVar6 = iVar1 * local_2c;
        if (iVar6 < 0) {
          iVar6 = iVar6 + 0xfff;
        }
        param_1[0x22] = param_1[0x22] - (iVar6 >> 0xc);
        param_1[10] = iVar4 - param_1[0x15];
        if (iVar1 < -0x1c9) {
          iVar6 = 3;
          func_0x80044ac8(*(undefined4 *)(param_1[0x16] + 8),3,param_1 + 9);
          iVar5 = extraout_v1;
          goto LAB_80101958;
        }
      }
      else {
LAB_80101958:
        iVar4 = (iVar5 + iVar6) * 0x1e;
        if (iVar4 < 0) {
          iVar4 = iVar4 + 0xfff;
        }
        param_1[0x20] = uVar2 + (iVar4 >> 0xc);
        iVar4 = local_2c * 0x5a;
        if (iVar4 < 0) {
          iVar4 = iVar4 + 0xfff;
        }
        param_1[0x22] = param_1[0x22] + (iVar4 >> 0xc);
      }
      iVar4 = -param_1[0x22] * (uint)(ushort)param_1[0x25];
      if (iVar4 < 0) {
        iVar4 = iVar4 + 0xfff;
      }
      iVar6 = param_1[0x20] * (uint)(ushort)param_1[0x25];
      *(short *)(param_1 + 0x23) = (short)(iVar4 >> 0xc);
      if (iVar6 < 0) {
        iVar6 = iVar6 + 0xfff;
      }
      *(short *)(param_1 + 0x24) = (short)(iVar6 >> 0xc);
      iVar4 = param_1[0x20] * 0xf;
      if (iVar4 < 0) {
        iVar4 = iVar4 + 0xf;
      }
      param_1[0x20] = iVar4 >> 4;
      iVar4 = param_1[0x21] * 0xf;
      if (iVar4 < 0) {
        iVar4 = iVar4 + 0xf;
      }
      param_1[0x21] = iVar4 >> 4;
    }
    iVar4 = param_1[0x20] * 0x1f;
    param_1[0x21] = param_1[0x21] + 0x5a;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0x1f;
    }
    param_1[0x20] = iVar4 >> 5;
    iVar4 = param_1[0x21] * 0x1f;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0x1f;
    }
    param_1[0x21] = iVar4 >> 5;
    iVar4 = param_1[0x22] * 0x1f;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0x1f;
    }
    param_1[0x22] = iVar4 >> 5;
    puVar7 = param_1 + 4;
    func_0x800172b4(puVar7,puVar7,param_1 + 0x23);
    param_3 = (int *)(param_1[0x22] - 0x80);
    uVar2 = _DAT_80065310 - (uint)*(byte *)((int)param_1 + 9);
    param_1[9] = param_1[9] + param_1[0x20];
    param_1[10] = param_1[10] + param_1[0x21];
    param_1[0xb] = param_1[0xb] + param_1[0x22];
    param_1[0x22] = (uint)param_3;
    if ((uVar2 & 0xf) == 0) {
      MatrixNormal/*0x8004c934*/(puVar7,puVar7);
    }
    if (_DAT_80065b3c <= param_1[0xb]) {
      return 0;
    }
    FUN_8001d708/*0x8001d708*/(param_1);
    param_1[0x20] = 0;
    param_1[0x21] = 0;
    param_1[0x22] = 0;
    *(undefined2 *)(param_1 + 0x23) = 0;
    *(undefined2 *)((int)param_1 + 0x8e) = 0;
    *(undefined2 *)(param_1 + 0x24) = 0;
  case 3:
    iVar4 = *param_3;
    puVar7 = param_1;
    if ((*(char *)(iVar4 + 4) == '\x02') && ((*param_1 & 1) == 0)) {
      local_20 = param_1[9] - *(int *)(iVar4 + 0x24);
      param_3 = &local_20;
      local_1c = param_1[10] - *(int *)(iVar4 + 0x28);
      local_18 = param_1[0xb] - *(int *)(iVar4 + 0x2c);
      GTE_LoadMatrixPacked/*0x8004366c*/(iVar4 + 0x10);
      GTE_RotateLong/*0x80043248*/(param_3,param_1 + 9);
      MulRotMatrix0/*0x8004cdc4*/(param_1 + 4,param_1 + 4);
      FUN_8001fe8c/*0x8001fe8c*/(0x80065a18,param_1);
      FUN_8001d4f0/*0x8001d4f0*/(iVar4,param_1);
      *(int *)(iVar4 + 0xdc) = *(int *)(iVar4 + 0xdc) << 2;
      iVar4 = FUN_80017160/*0x80017160*/();
      FUN_80020890/*0x80020890*/(param_1,(iVar4 * 0x168 >> 0xf) + 0x168);
      puVar7 = (uint *)0x1;
    }
    FUN_8001f5a0/*0x8001f5a0*/(puVar7,param_3);
    iVar4 = param_1[0x20] * (int)(short)param_3[8] +
            param_1[0x21] * (int)*(short *)((int)param_3 + 0x22) +
            param_1[0x22] * (int)(short)param_3[9];
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0x7ff;
    }
    iVar4 = iVar4 >> 0xb;
    if (iVar4 < 0) {
      uVar2 = FUN_80017160/*0x80017160*/();
      iVar6 = iVar4 * ((int)(short)param_3[8] + (uVar2 & 0xff));
      if (iVar6 < 0) {
        iVar6 = iVar6 + 0xfff;
      }
      param_1[0x20] = param_1[0x20] - (iVar6 >> 0xc);
      iVar6 = iVar4 * *(short *)((int)param_3 + 0x22);
      if (iVar6 < 0) {
        iVar6 = iVar6 + 0xfff;
      }
      param_1[0x21] = param_1[0x21] - (iVar6 >> 0xc);
      iVar4 = iVar4 * (short)param_3[9];
      if (iVar4 < 0) {
        iVar4 = iVar4 + 0xfff;
      }
      param_1[0x22] = param_1[0x22] - (iVar4 >> 0xc);
    }
switchD_801017c4_caseD_2:
    if (param_1[0xf] != 0) {
      iVar4 = FUN_8001d5a0/*0x8001d5a0*/(param_1);
      iVar6 = *(int *)(iVar4 + 0xdc);
      if (iVar6 < 0) {
        iVar6 = iVar6 + 3;
      }
      *(int *)(iVar4 + 0xdc) = iVar6 >> 2;
      puVar7 = (uint *)FUN_8001d624/*0x8001d624*/(param_1);
      uVar2 = puVar7[1];
      uVar8 = puVar7[2];
      uVar9 = puVar7[3];
      param_1[4] = *puVar7;
      param_1[5] = uVar2;
      param_1[6] = uVar8;
      param_1[7] = uVar9;
      uVar2 = puVar7[5];
      uVar8 = puVar7[6];
      uVar9 = puVar7[7];
      param_1[8] = puVar7[4];
      param_1[9] = uVar2;
      param_1[10] = uVar8;
      param_1[0xb] = uVar9;
      uVar3 = FUN_8001d564/*0x8001d564*/(param_1);
      FUN_8001fe50/*0x8001fe50*/(0x80065a18,uVar3);
      FUN_80020890/*0x80020890*/(param_1,0x78);
switchD_801017c4_caseD_6:
      goto switchD_801017c4_caseD_1;
    }
    break;
  case 1:
switchD_801017c4_caseD_1:
    iVar4 = param_1[0x15] * 0x93c;
    *param_1 = *param_1 | 0x80;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xfff;
    }
    param_1[0x15] = iVar4 >> 0xc;
    iVar4 = (iVar4 >> 0xc) * 0x3243;
    if (iVar4 < 0) {
      iVar4 = iVar4 + 0xfff;
    }
    *(short *)(param_1 + 0x25) = (short)(0x1000000 / (iVar4 >> 0xc));
  default:
    break;
  case 2:
    goto switchD_801017c4_caseD_2;
  case 6:
    goto switchD_801017c4_caseD_6;
  }
  return 0;
}

#endif  /* GHIDRA REF */
