/* conveyor.c -- Sand Factory M2_Conveyor & M2_elevator motion tick.
 *
 * Source: SANDFACT.DLL  FUN_80100c6c.
 *
 * Integrates a position vector (u32[9..11] -> world x,y,z) by a
 * velocity vector (u32[0x20..0x22]) scaled by 1/128. Mode 2 skips
 * the integration but still runs the release/transition tail.
 *
 * Used by the Sand Factory's slow moving conveyor and elevator
 * platforms -- velocity is shallow enough that 7-bit fractional
 * precision is sufficient for visible smoothness.
 *
 * Bit-exact: the +0x7f / >>7 sequence is preserved.
 *
 * HIGH-MED confidence: source control flow and the release tail are
 * preserved from SANDFACT.DLL.
 */
#include <stdint.h>

extern void FUN_8001d708(uint32_t *obj);
extern void FUN_80020890(uint32_t *obj, int timer);
extern uint32_t FUN_8004410c(void);
extern void FUN_800447e8(uint32_t voice, uint32_t bank, int slot, uint32_t *xyz);
extern void gap_80031294(uint32_t *self);
extern uint32_t _DAT_800737e8;

static int32_t mips_addu_i32(int32_t a, int32_t b)
{
    return (int32_t)((uint32_t)a + (uint32_t)b);
}

static int32_t mips_mult_lo_i32(int32_t a, int32_t b)
{
    return (int32_t)((uint32_t)((int64_t)a * (int64_t)b));
}

static int32_t rtz_shift_i32(int32_t v, unsigned sh, int32_t bias)
{
    if (v < 0) v = mips_addu_i32(v, bias);
    return v >> sh;
}

uint32_t SF_ConveyorTick(uint32_t *obj, int mode)
{
    if (mode != 2) {
        obj[9]  = (uint32_t)mips_addu_i32((int32_t)obj[9],  rtz_shift_i32((int32_t)obj[0x20], 7, 0x7f));
        obj[10] = (uint32_t)mips_addu_i32((int32_t)obj[10], rtz_shift_i32((int32_t)obj[0x21], 7, 0x7f));
        obj[11] = (uint32_t)mips_addu_i32((int32_t)obj[11], rtz_shift_i32((int32_t)obj[0x22], 7, 0x7f));
    }

    uint32_t flags = obj[0];
    if ((flags & 2u) != 0) {
        obj[0] = flags & 0xfefffffdu;
        FUN_8001d708(obj);
        obj[0x20] = (uint32_t)rtz_shift_i32(mips_mult_lo_i32(*(int16_t *)(obj + 5), 0x4786), 5, 0x1f);
        obj[0x21] = (uint32_t)rtz_shift_i32(mips_mult_lo_i32(*(int16_t *)((uint8_t *)obj + 0x1a), 0x4786), 5, 0x1f);
        obj[0x22] = (uint32_t)rtz_shift_i32(mips_mult_lo_i32(*(int16_t *)(obj + 8), 0x4786), 5, 0x1f);
        if (obj[0x38] != 0)
            FUN_80020890((uint32_t *)(uintptr_t)obj[0x38], 0x3c);
        FUN_80020890(obj, 0x1e);
        uint32_t voice = FUN_8004410c();
        FUN_800447e8(voice, *(uint32_t *)(uintptr_t)(_DAT_800737e8 + 8), 4, obj + 9);
        flags = obj[0];
    }
    obj[0] = flags & 0xffffffdfu;
    gap_80031294(obj);
    return 0;
}

uint32_t FUN_80100c6c(uint32_t *obj, int mode)
{
    return SF_ConveyorTick(obj, mode);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SANDFACT.DLL FUN_80100c6c  (from analysis/dll/SANDFACT/decomp/80100c6c.c) --- */
// addr: 0x80100c6c  name: FUN_80100c6c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100c6c(uint *param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  uint uVar3;
  uint extraout_v1;
  uint uVar4;
  
  if ((param_2 == 0) || (param_2 != 2)) {
    uVar3 = param_1[0x20];
    if ((int)uVar3 < 0) {
      uVar3 = uVar3 + 0x7f;
    }
    uVar4 = param_1[0x21];
    param_1[9] = param_1[9] + ((int)uVar3 >> 7);
    if ((int)uVar4 < 0) {
      uVar4 = uVar4 + 0x7f;
    }
    uVar3 = param_1[0x22];
    param_1[10] = param_1[10] + ((int)uVar4 >> 7);
    if ((int)uVar3 < 0) {
      uVar3 = uVar3 + 0x7f;
    }
    param_1[0xb] = param_1[0xb] + ((int)uVar3 >> 7);
  }
  uVar3 = *param_1;
  if ((uVar3 & 2) != 0) {
    *param_1 = uVar3 & 0xfefffffd;
    FUN_8001d708/*0x8001d708*/(param_1);
    iVar1 = (short)param_1[5] * 0x4786;
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0x1f;
    }
    param_1[0x20] = iVar1 >> 5;
    iVar1 = *(short *)((int)param_1 + 0x1a) * 0x4786;
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0x1f;
    }
    param_1[0x21] = iVar1 >> 5;
    iVar1 = (short)param_1[8] * 0x4786;
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0x1f;
    }
    param_1[0x22] = iVar1 >> 5;
    if (param_1[0x38] != 0) {
      FUN_80020890/*0x80020890*/(param_1[0x38],0x3c);
    }
    FUN_80020890/*0x80020890*/(param_1,0x1e);
    uVar2 = FUN_8004410c/*0x8004410c*/();
    FUN_800447e8/*0x800447e8*/(uVar2,*(undefined4 *)(_DAT_800737e8 + 8),4,param_1 + 9);
    uVar3 = extraout_v1;
  }
  *param_1 = uVar3 & 0xffffffdf;
  func_0x80031294(param_1);
  return 0;
}

#endif  /* GHIDRA REF */
