/* elevator.c -- Sand Factory M2_elevator continuous SFX manager.
 *
 * Source: SANDFACT.DLL  FUN_80100b34.
 *
 * Each tick:
 *   - If mode == 0 or 2 (running): if a voice was already playing,
 *     update its volume; clear back-buffer pending bit (FUN_80020778)
 *     to keep the sound aligned with the parity buffer; force sub-state
 *     0x78 (= "running"); release the voice; clear the slot.
 *   - Then re-acquire a fresh voice for the next pan computation. If a
 *     stale voice slot was found (should be 0 after the clear), trip
 *     the OOM trap -- this is a sanity check that catches double-bind.
 *   - Re-bind the voice, register for post-update.
 *   - Sub-state always set to 0x78 + obj+0x9 (the elevator's "doors
 *     opening" animation phase).
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t SfxPan_For3DPos(void *posXyz);
extern void SPU_VoiceVolume_Set(int ch, uint32_t lr);
extern uint32_t SfxChannel_Acquire(void);
extern void Audio_PlaySfx_inner(int ch, uint32_t bank, int sfxId, uint32_t pan);
extern void Audio_VoiceStop(int ch);
extern void Stream_FatalOom(const char *msg);
extern uint32_t Object_ClearBackBufferFlag(uint32_t *obj);
extern void Object_SetSubState(int obj, int sub);
extern void Object_RegisterPostUpdate(uint32_t *obj);
extern void Object_DefaultDispatch(int obj, int mode, uint32_t arg);
extern char s_PROB__801000d0[];

uint32_t SF_ElevatorTick(int obj, int mode)
{
    if (mode == 1) goto applyAnim;

    if (mode == 0 || mode == 2) {
        uint32_t pan = SfxPan_For3DPos((void *)(intptr_t)(obj + 0x48));
        if (pan != 0) SPU_VoiceVolume_Set((int)*(int8_t *)(obj + 5), pan);
        Object_ClearBackBufferFlag((uint32_t *)(intptr_t)obj);
        Object_SetSubState(obj, 0x78);
        Audio_VoiceStop((int)*(int8_t *)(obj + 5));
        *(int8_t *)(obj + 5) = 0;
    }

    /* Re-acquire and play. */
    uint32_t pan2 = SfxPan_For3DPos((void *)(intptr_t)(obj + 0x48));
    if (pan2 != 0) {
        if (*(int8_t *)(obj + 5) != 0) Stream_FatalOom(s_PROB__801000d0);
        int ch = (int)(int8_t)SfxChannel_Acquire();
        *(int8_t *)(obj + 5) = (int8_t)ch;
        Audio_PlaySfx_inner(ch, *(uint32_t *)(*(int *)(obj + 0x58) + 8), 0, pan2);
        Object_RegisterPostUpdate((uint32_t *)(intptr_t)obj);
    }
    Object_SetSubState(obj, 0x78);
applyAnim:
    Object_SetSubState(obj, (*(uint8_t *)(obj + 9)) + 0x78);
    Object_DefaultDispatch(obj, mode, 0);
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SANDFACT.DLL FUN_80100b34  (from analysis/dll/SANDFACT/decomp/80100b34.c) --- */
// addr: 0x80100b34  name: FUN_80100b34

undefined4 FUN_80100b34(int param_1,int param_2)

{
  char cVar1;
  int iVar2;
  
  if (param_2 != 1) {
    if ((param_2 == 0) || (param_2 != 2)) {
      iVar2 = FUN_800449bc/*0x800449bc*/(param_1 + 0x48);
      if (iVar2 != 0) {
        FUN_80044574/*0x80044574*/((int)*(char *)(param_1 + 5),iVar2);
      }
      FUN_80020778/*0x80020778*/(param_1);
      FUN_80020890/*0x80020890*/(param_1,0x78);
      FUN_800441c8/*0x800441c8*/((int)*(char *)(param_1 + 5));
      *(undefined1 *)(param_1 + 5) = 0;
    }
    iVar2 = FUN_800449bc/*0x800449bc*/(param_1 + 0x48);
    if (iVar2 != 0) {
      if (*(char *)(param_1 + 5) != '\0') {
        Stream_FatalOom/*0x80015368*/(s_PROB__801000d0);
      }
      cVar1 = FUN_8004410c/*0x8004410c*/();
      *(char *)(param_1 + 5) = cVar1;
      FUN_800443c8/*0x800443c8*/((int)cVar1,*(undefined4 *)(*(int *)(param_1 + 0x58) + 8),0,iVar2);
      FUN_80020744/*0x80020744*/(param_1);
    }
    FUN_80020890/*0x80020890*/(param_1,0x78);
  }
  FUN_80020890/*0x80020890*/(param_1,*(byte *)(param_1 + 9) + 0x78);
  func_0x800223dc(param_1);
  return 0;
}

#endif  /* GHIDRA REF */
