/* factory_collide.c -- Sand Factory generic terrain-collide stub.
 *
 * Source: SANDFACT.DLL  FUN_801010c4.
 *
 * The shortest possible per-object handler. On any mode != 3, the obj
 * pointer is clobbered to 1 (the preserved sentinel-as-fake-obj idiom
 * we've seen elsewhere) before falling through to the universal
 * terrain-collision test. On mode 3, the real obj is passed.
 *
 * Used by `factory_door` and the small static fixtures that need only
 * the terrain test (no spin, no damage broadcast).
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern int Collision_AgainstTerrain(int obj, int impact);   /* func_0x8002239c */

void SF_TerrainOnlyImpact(int obj, int mode, int impact)
{
    if (mode != 3) obj = 1;
    Collision_AgainstTerrain(obj, impact);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SANDFACT.DLL FUN_801010c4  (from analysis/dll/SANDFACT/decomp/801010c4.c) --- */
// addr: 0x801010c4  name: FUN_801010c4

void FUN_801010c4(undefined4 param_1,int param_2,undefined4 param_3)

{
  if (param_2 != 3) {
    param_1 = 1;
  }
  FUN_8002239c/*0x8002239c*/(param_1,param_3);
  return;
}

#endif  /* GHIDRA REF */
