/* pump.c -- Valley Farms pump_1 / silo_1 collision + countdown.
 *
 * Source: VALLYFRM.DLL  FUN_80101220.
 *
 * On collision (mode 3, 1, 8) tests against terrain + circular hit;
 * on success, queues a snow effect (Effects_QueueSnow) and stores
 * the count into +0x8. Each tick decrements +0x8 by 1; on hitting 1,
 * if a global concurrency counter DAT_80101308 is < 2, increments it
 * and broadcasts event 1000 via func_0x80021d6c (Object_BroadcastTreeEvent).
 *
 * Used by the pump_1 and silo_1 destructibles -- limits the number
 * of simultaneous "explosion sequence in progress" to 2.
 *
 * MED confidence.
 */
#include <stdint.h>

extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern uint8_t Effects_QueueSnow(int obj);    /* FUN_8003fc94 */
extern intptr_t Object_BroadcastTreeEvent(uint32_t event);  /* func_0x80021d6c */
extern uint32_t FUN_8002036c(uint32_t *obj);
extern int32_t DAT_80101308;

uint32_t VF_PumpTick(int obj, uint32_t mode, void *impact)
{
    int hit = 0;
    if (mode == 3 || mode == 1 || mode == 8) {
        if (mode == 8) goto circularOnly;
        if ((hit = Damage_FromImpulse((uint32_t *)(intptr_t)obj, (int *)impact)) != 0) goto fired;
        circularOnly:
        if ((hit = Damage_AccumulateOrFire((uint32_t *)(intptr_t)obj, (uint16_t)(uintptr_t)impact)) != 0) goto fired;
    }
    *(uint8_t *)(uintptr_t)(obj + 8) = Effects_QueueSnow(obj);
fired:
    {
        int8_t counter = *(int8_t *)(uintptr_t)(obj + 8);
        *(int8_t *)(uintptr_t)(obj + 8) = (int8_t)(counter - 1);
        if (counter == 1 && DAT_80101308 < 2) {
            DAT_80101308++;
            {
                intptr_t spawned = Object_BroadcastTreeEvent(1000);
                if (spawned != 0)
                    FUN_8002036c((uint32_t *)(uintptr_t)spawned);
            }
        }
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- VALLYFRM.DLL FUN_80101220  (from analysis/dll/VALLYFRM/decomp/80101220.c) --- */
// addr: 0x80101220  name: FUN_80101220

undefined4 FUN_80101220(int param_1,uint param_2,undefined4 param_3)

{
  char cVar1;
  undefined1 uVar2;
  int iVar3;
  undefined4 uVar4;
  
  if (param_2 == 3) {
LAB_80101268:
    iVar3 = FUN_8002239c/*0x8002239c*/(param_1,param_3);
    if (iVar3 != 0) goto LAB_801012b0;
LAB_80101284:
    iVar3 = FUN_80022320/*0x80022320*/(param_1,param_3);
    if (iVar3 != 0) goto LAB_801012b0;
  }
  else if ((3 < param_2) || (param_2 != 1)) {
    if (param_2 != 8) goto LAB_80101268;
    goto LAB_80101284;
  }
  uVar2 = FUN_8003fc94/*0x8003fc94*/(param_1);
  *(undefined1 *)(param_1 + 8) = uVar2;
LAB_801012b0:
  cVar1 = *(char *)(param_1 + 8);
  *(char *)(param_1 + 8) = cVar1 + -1;
  if (cVar1 == '\x01' && DAT_80101308 < 2) {
    DAT_80101308 = DAT_80101308 + 1;
    uVar4 = func_0x80021d6c(1000);
    FUN_8002036c/*0x8002036c*/(uVar4);
  }
  return 0;
}

#endif  /* GHIDRA REF */
