/* silo_rotate.c -- Valley Farms silo rotate + AAA-fire target pick.
 *
 * Source: VALLYFRM.DLL  FUN_80100964.
 *
 * Per-tick rotates the silo dish at obj+0x38, +0x44 by +0x44 per
 * frame. On impactor event (kind 3/8), forwards damage; on damage
 * success, picks nearest hostile target from _DAT_80065a18 list,
 * preferring "high-priority" targets (object+6 > 0). Allocates a
 * 0x98-byte projectile (FUN_80045134 realloc), copies the muzzle
 * transform from world space, sets velocity = 2 * facing, binds FX
 * channel 1, marks kind 7 (AAA round) with 100-frame fuse and tick
 * callback FUN_801005e8.
 *
 * mode dispatch:
 *   0  -- tick rotate + (optional) damage propagate
 *   1  -- post-spawn: seed dish angle via Rand255
 *   3  -- damage event from impactor
 *   8  -- forwarded variant
 *
 * MED.
 */
#include <stdint.h>

extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern void Object_RefitAABB(int sub);
extern void Damage_FromImpulse(int self, int *imp);
extern int  Damage_StandardVehicle(int self, int *imp);
extern uint32_t Object_LocalToWorldPos(int sub);
extern int  Math_Distance(int xy, int target);
extern uint32_t Object_BuildLocalCoords(int sub);                  /* FUN_8001d564 */
extern void *Heap_Realloc(uint32_t base, uint32_t newSize);
extern void Object_BindLifecycle(uint32_t *self);
extern uint8_t Pool_AllocSFX(void);
extern void Pool_BindFXOnObject(uint32_t h, uint32_t bin, int slot, uint32_t *xyz);
extern int  Rand255(void);
extern int *_DAT_80065a18;
extern uint32_t FUN_801005e8;

uint32_t VF_SiloRotate(int self, int mode, int param3)
{
    if (mode == 1) goto seed_angle;
    if (mode == 0) {
        *(int16_t *)(*(int *)(self + 0x38) + 0x44) += 0x44;
        if (param3 == 0) return 0;
        Object_RefitAABB(*(int *)(self + 0x38));
    }
    if (mode == 3 || mode == 8 || mode == 0) {
        if (mode == 3) Damage_FromImpulse(self, (int *)(intptr_t)param3);
        if (Damage_StandardVehicle((mode == 3 ? 1 : self), (int *)(intptr_t)param3) == 0)
            return 0;
        /* Pick target. */
        uint32_t *muzzle = (uint32_t *)Object_LocalToWorldPos(*(int *)(self + 0x38));
        int    fallback = 0;
        int    primary  = 0;
        uint32_t bestF  = 0xffffffffu;
        uint32_t bestP  = 0xffffffffu;
        int *cur  = (int *)*_DAT_80065a18;
        int *prev = _DAT_80065a18;
        while (cur != NULL) {
            int cand = prev[2];
            if (*(char *)(cand + 4) == 2 && *(int16_t *)(cand + 0xc) != 0) {
                uint32_t d = (uint32_t)Math_Distance(self + 0x48, cand + 0x48);
                if (*(int16_t *)(cand + 6) > 0 && d < bestP) {
                    bestP   = 1;
                    primary = cand;
                }
                if (d < bestF) { bestF = d; fallback = cand; }
            }
            prev = cur;
            cur  = (int *)*cur;
        }
        int target = (primary != 0) ? primary : fallback;
        uint32_t lc = Object_BuildLocalCoords(*(int *)(self + 0x38));
        uint32_t *p = (uint32_t *)Heap_Realloc(lc, 0x98);
        p[0x21] = (uint32_t)target;
        *(int16_t *)((char *)p + 6) = *(int16_t *)(self + 6);
        for (int i = 0; i < 4; i++) p[4 + i]    = muzzle[i];
        for (int i = 0; i < 4; i++) p[8 + i]    = muzzle[4 + i];
        for (int i = 0; i < 3; i++) p[0x12 + i] = muzzle[5 + i];
        *(uint8_t *)(p + 1) = 7;
        *p = 0x80u;
        *(int16_t *)(p + 3) = 100;
        Object_SetCallbackPsxSlot(p, (uintptr_t)&FUN_801005e8);
        Object_BindLifecycle(p);
        p[0x22] = (int)*(int16_t *)(p + 5) << 1;
        p[0x23] = (int)*(int16_t *)((char *)p + 0x1a) << 1;
        p[0x24] = (int)*(int16_t *)(p + 8) << 1;
        char h = (char)Pool_AllocSFX();
        *((char *)p + 5) = h;
        Pool_BindFXOnObject(h, *(uint32_t *)(*(int *)(self + 0x58) + 8), 1, p + 9);
    }
seed_angle:
    *(uint16_t *)(*(int *)(self + 0x38) + 0x44) = (uint16_t)Rand255();
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- VALLYFRM.DLL FUN_80100964  (from analysis/dll/VALLYFRM/decomp/80100964.c) --- */
// addr: 0x80100964  name: FUN_80100964

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80100964(int param_1,int param_2,int param_3)

{
  int *piVar1;
  int *piVar2;
  int *piVar3;
  char cVar4;
  undefined2 uVar5;
  int iVar6;
  undefined4 *puVar7;
  uint uVar8;
  undefined4 uVar9;
  undefined4 *puVar10;
  undefined4 uVar11;
  undefined4 uVar12;
  int iVar13;
  uint uVar14;
  uint uVar15;
  int iVar16;
  
  iVar6 = param_1;
  if (param_2 == 1) goto LAB_80100bd8;
  if (param_2 == 0) {
LAB_801009b8:
    *(short *)(*(int *)(param_1 + 0x38) + 0x44) = *(short *)(*(int *)(param_1 + 0x38) + 0x44) + 0x44
    ;
    if (param_3 == 0) {
      return 0;
    }
    FUN_8001d708/*0x8001d708*/(*(undefined4 *)(param_1 + 0x38));
LAB_801009e8:
    iVar6 = FUN_8002239c/*0x8002239c*/(param_1,param_3);
    if (iVar6 == 0) {
      return 0;
    }
    iVar6 = 1;
  }
  else {
    if (param_2 == 3) goto LAB_801009e8;
    if (param_2 != 8) goto LAB_801009b8;
  }
  iVar6 = FUN_80022320/*0x80022320*/(iVar6,param_3);
  if (iVar6 == 0) {
    return 0;
  }
  iVar6 = 0;
  puVar7 = (undefined4 *)FUN_8001d624/*0x8001d624*/(*(undefined4 *)(param_1 + 0x38));
  iVar16 = 0;
  uVar15 = 0xffffffff;
  uVar14 = 0xffffffff;
  piVar3 = (int *)*_DAT_80065a18;
  piVar2 = _DAT_80065a18;
  while (piVar1 = piVar3, piVar1 != (int *)0x0) {
    iVar13 = piVar2[2];
    if ((*(char *)(iVar13 + 4) == '\x02') && (*(short *)(iVar13 + 0xc) != 0)) {
      uVar8 = FUN_80016aac/*0x80016aac*/(param_1 + 0x48,iVar13 + 0x48);
      if ((0 < *(short *)(iVar13 + 6)) && (uVar8 < uVar14)) {
        uVar8 = 1;
        uVar14 = uVar8;
        iVar16 = iVar13;
      }
      if (uVar8 < uVar15) {
        uVar15 = uVar8;
        iVar6 = iVar13;
      }
    }
    piVar2 = piVar1;
    piVar3 = (int *)*piVar1;
  }
  if (iVar16 == 0) {
    iVar16 = iVar6;
  }
  uVar9 = FUN_8001d564/*0x8001d564*/(*(undefined4 *)(param_1 + 0x38));
  puVar10 = (undefined4 *)Heap_Realloc/*0x80045134*/(uVar9,0x98);
  puVar10[0x21] = iVar16;
  *(undefined2 *)((int)puVar10 + 6) = *(undefined2 *)(param_1 + 6);
  uVar9 = puVar7[1];
  uVar11 = puVar7[2];
  uVar12 = puVar7[3];
  puVar10[4] = *puVar7;
  puVar10[5] = uVar9;
  puVar10[6] = uVar11;
  puVar10[7] = uVar12;
  uVar9 = puVar7[5];
  uVar11 = puVar7[6];
  uVar12 = puVar7[7];
  puVar10[8] = puVar7[4];
  puVar10[9] = uVar9;
  puVar10[10] = uVar11;
  puVar10[0xb] = uVar12;
  uVar9 = puVar7[6];
  uVar11 = puVar7[7];
  puVar10[0x12] = puVar7[5];
  puVar10[0x13] = uVar9;
  puVar10[0x14] = uVar11;
  *(undefined1 *)(puVar10 + 1) = 7;
  *puVar10 = 0x80;
  *(undefined2 *)(puVar10 + 3) = 100;
  puVar10[0x19] = FUN_801005e8;
  FUN_800202f4/*0x800202f4*/(puVar10);
  puVar10[0x22] = (int)*(short *)(puVar10 + 5) << 1;
  puVar10[0x23] = (int)*(short *)((int)puVar10 + 0x1a) << 1;
  puVar10[0x24] = (int)*(short *)(puVar10 + 8) << 1;
  cVar4 = FUN_8004410c/*0x8004410c*/();
  *(char *)((int)puVar10 + 5) = cVar4;
  FUN_8004483c/*0x8004483c*/((int)cVar4,*(undefined4 *)(*(int *)(param_1 + 0x58) + 8),1,puVar10 + 9);
  iVar6 = 1;
LAB_80100bd8:
  uVar5 = FUN_80017160/*0x80017160*/(iVar6);
  *(undefined2 *)(*(int *)(param_1 + 0x38) + 0x44) = uVar5;
  return 0;
}

#endif  /* GHIDRA REF */
