/* silo_cleanup.c -- Valley Farms generic cleanup hook.
 *
 * Source: VALLYFRM.DLL  FUN_801002c4.
 *
 * Same idiom as HD_TransformerCleanup / CC_GenericCleanup -- mode 7
 * stashes the obj into the FX pool slot at _DAT_800659fc+0x58 and
 * allocates a 0x80-byte effect prim. All other modes (except 1)
 * Heap_Free the obj.
 *
 * Confirms this is THE shared "generic cleanup" pattern used by every
 * destructible level object across overlays. Pass 3 should hoist into
 * a shared helper in src/gameplay/object_cleanup.c.
 *
 * HIGH.
 */
#include <stdint.h>

extern void *Object_Pool_Alloc(uint32_t size);
extern void  Heap_Free(void *p);
extern int8_t *_DAT_800659fc;

uint32_t VF_GenericCleanup(void *obj, int mode)
{
    if (mode != 1) {
        if (mode != 7) return 0;
        *(void **)(_DAT_800659fc + 0x58) = obj;
        Object_Pool_Alloc(0x80);
    }
    Heap_Free(obj);
    return 0xffffffffu;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- VALLYFRM.DLL FUN_801002c4  (from analysis/dll/VALLYFRM/decomp/801002c4.c) --- */
// addr: 0x801002c4  name: FUN_801002c4

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_801002c4(undefined4 param_1,int param_2)

{
  undefined4 extraout_v1;
  
  if (param_2 != 1) {
    if (param_2 != 7) {
      return 0;
    }
    *(undefined4 *)(_DAT_800659fc + 0x58) = param_1;
    FUN_8001d470/*0x8001d470*/(0x80);
    param_1 = extraout_v1;
  }
  Heap_Free/*0x80045088*/(param_1);
  return 0xffffffff;
}

#endif  /* GHIDRA REF */
