/* windmill.c -- Valley Farms windmill spin tick.
 *
 * Source: VALLYFRM.DLL  FUN_801005e8.
 *
 * The Windmill_1 object spins around an axis: each tick it adds 0x88
 * to its angular velocity field at +0x44 (cast as i16) and -- when
 * not impulsed (state bit 0 clear) -- also accumulates that into
 * angles at +0x48 (yaw) and +0x4c (pitch). The two destination
 * angles share the same velocity register (obj[0x22/0x23] = vx/vy at
 * +0x88/+0x8c), so the windmill blades rotate around a tilted axis.
 *
 * MED confidence.
 */
#include <stdint.h>

uint32_t VF_WindmillTick(uint32_t *obj, int mode)
{
    if (mode == 2) return 0;
    if (mode != 0 && mode != 2 && mode != 3) return 0;

    *(int16_t *)(obj + 0x11) = (int16_t)((int16_t)obj[0x11] + 0x88);

    if ((obj[0] & 1) == 0) {
        obj[0x12] += obj[0x22];
        obj[0x13] += obj[0x23];
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- VALLYFRM.DLL FUN_801005e8  (from analysis/dll/VALLYFRM/decomp/801005e8.c) --- */
// addr: 0x801005e8  name: FUN_801005e8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_801005e8(uint *param_1,uint param_2,uint *param_3)

{
  longlong lVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  undefined4 uVar5;
  uint uVar6;
  int local_28;
  int local_24;
  int local_20;
  longlong local_18;
  
  if (param_2 != 2) {
    uVar2 = 3;
    if (((2 < param_2) || (uVar2 = 0, param_2 != 0)) && (param_2 == uVar2)) goto LAB_80100868;
    *(short *)(param_1 + 0x11) = (short)param_1[0x11] + 0x88;
    if ((*param_1 & 1) == 0) {
      param_1[0x12] = param_1[0x12] + param_1[0x22];
      param_1[0x13] = param_1[0x13] + param_1[0x23];
      param_1[0x14] = param_1[0x14] + param_1[0x24];
      uVar2 = param_1[0x21];
      param_1[0x23] = param_1[0x23] + 0x38;
      if (uVar2 != 0) {
        local_28 = *(int *)(uVar2 + 0x48) - param_1[0x12];
        local_24 = *(int *)(uVar2 + 0x4c) - param_1[0x13];
        local_20 = *(int *)(uVar2 + 0x50) - param_1[0x14];
        local_18 = (longlong)local_20 * (longlong)local_20;
        lVar1 = (longlong)local_28 * (longlong)local_28 + local_18;
        FUN_800170c8/*0x800170c8*/((int)lVar1,(int)((ulonglong)lVar1 >> 0x20));
        local_18 = (longlong)(int)param_1[0x23] * (longlong)(int)param_1[0x23];
        lVar1 = local_18 + local_24 * 0x70;
        iVar3 = FUN_800170c8/*0x800170c8*/((int)lVar1,(int)((ulonglong)lVar1 >> 0x20));
        iVar3 = iVar3 - param_1[0x23];
        if (iVar3 != 0) {
          iVar4 = (local_28 * 0x38) / iVar3 - param_1[0x22];
          if (iVar4 < 0) {
            iVar4 = iVar4 + 0xf;
          }
          param_1[0x22] = param_1[0x22] + (iVar4 >> 4);
          iVar3 = (local_20 * 0x38) / iVar3 - param_1[0x24];
          if (iVar3 < 0) {
            iVar3 = iVar3 + 0xf;
          }
          param_1[0x24] = param_1[0x24] + (iVar3 >> 4);
        }
      }
    }
    FUN_8001d708/*0x8001d708*/(param_1);
    iVar3 = Terrain_HeightAt/*0x80025400*/(param_1[9],param_1[0xb]);
    if ((int)param_1[10] < iVar3) {
      return 0;
    }
  }
  param_3 = param_1 + 9;
  FUN_8003fd24/*0x8003fd24*/(param_3,0x11);
  FUN_8004483c/*0x8004483c*/((int)*(char *)((int)param_1 + 5),_DAT_800658fc,0xc,param_3);
  FUN_800205f8/*0x800205f8*/(param_1);
LAB_80100868:
  if (*(char *)(*param_3 + 4) != '\x01') {
    FUN_800441c8/*0x800441c8*/((int)*(char *)((int)param_1 + 5));
    uVar2 = *param_3;
    if (*(char *)(uVar2 + 4) == '\x02') {
      uVar6 = ((uint)(ushort)param_1[3] << 0xb) / (uint)*(ushort *)(uVar2 + 0xa2);
      local_28 = param_1[0x22] * uVar6;
      local_24 = param_1[0x23] * uVar6;
      local_20 = param_1[0x24] * uVar6;
      FUN_800176f8/*0x800176f8*/(uVar2,&local_28,param_1 + 9);
    }
    uVar5 = FUN_8004410c/*0x8004410c*/();
    FUN_8004483c/*0x8004483c*/(uVar5,*(undefined4 *)(param_1[0x16] + 8),0,param_1 + 9);
    FUN_8003fea8/*0x8003fea8*/(param_1 + 9,0x8000040);
    *param_1 = *param_1 | 0x20;
    FUN_80020890/*0x80020890*/(param_1,0x1e);
  }
  return 0;
}

#endif  /* GHIDRA REF */
