/* ai_target.c -- AI target acquisition.
 *
 * Source: SLUS_005.10  FUN_80022e90.
 *
 * Each in-game tick, every AI-driven vehicle that meets the "experience
 * >= 6" gate (vehicle.controlFlags @ +0xd0) attempts to acquire a new
 * target within a ~1024-world-unit (0xfa000) cube around its current
 * position. Steps:
 *
 *   1. Gate on g_matchMode != 0 (must be in active match).
 *   2. Gate on self.controlFlags @ +0xd0 >= 6 (AI skill threshold).
 *   3. Pick a candidate type from a per-damage-state table at self+0x110
 *      keyed by self.damageBits (+0xb3). The 4-byte stride suggests a
 *      table of u32 type-id pointers.
 *   4. If the candidate's state byte is 0x04 (= "alive AI-able"), do
 *      an AABB-sweep against the world kd-tree (uRam000006fc) within
 *      ±0xfa000 cube, with screen-projection bounds sRam000006f0 /
 *      sRam000007dc as the frustum predicate.
 *   5. If the closest hit is itself within 0xfa000 in every axis of
 *      self's current target (so target switch is "smooth"), store the
 *      new target into self+0xe4 (currentTarget) and dispatch event
 *      11 (= "I'm-targeting-you") via the candidate's per-tick callback.
 *   6. Then a V8_RandNext() roll for further behavior (state machine
 *      branches continue past this excerpt).
 *
 * MED confidence (top half; tail-state machine is pass-3 work).
 *
 * NEW STRUCT FIELD CONFIRMATION:
 *   - Vehicle.+0xb3 (damageBits): used as index into the per-damage
 *     candidate table at +0x110.
 *   - Vehicle.+0xd0 (controlFlags): the AI skill / experience byte.
 *   - Vehicle.+0xe4 (currentTarget): the acquired target pointer.
 *
 * These promote 3 previously-LOW fields to HIGH.
 */
#include <stdint.h>
#include "structs.h"

extern uint32_t V8_RandNext(void);
extern int  TreeAABB_FirstHit(uintptr_t treeRoot, int16_t screenW, int16_t screenH, int32_t *bbox4);  /* FUN_80021a30 */
extern int8_t cRam00000015;          /* g_matchMode */
extern int16_t sRam000006f0;         /* per-frame screen X bound */
extern int16_t sRam000007dc;         /* per-frame screen Y bound */
extern uintptr_t uRam000006fc;        /* world kd-tree root */

#define VEHICLE_AI_GATE   6
#define AI_TARGET_RADIUS  0xfa000

int Vehicle_TryAcquireTarget(uint8_t *self)
{
    if (cRam00000015 == 0)                return 0;
    if (((uint8_t *)self)[0xd0] < VEHICLE_AI_GATE) return 0;

    /* candidate = self.candidateTable[self.damageBits] */
    int candidate = *(int *)(self + ((uint8_t *)self)[0xb3] * 4 + 0x110);
    if (candidate == 0)                   return 0;
    if (*(int8_t *)(candidate + 8) != 4)  return 0;

    /* AABB sweep within ±0xfa000 of self.pos. */
    int32_t bbox[4] = {
        *(int32_t *)(self + 0x24) - AI_TARGET_RADIUS,
        *(int32_t *)(self + 0x24) + AI_TARGET_RADIUS,
        *(int32_t *)(self + 0x2c) - AI_TARGET_RADIUS,
        *(int32_t *)(self + 0x2c) + AI_TARGET_RADIUS,
    };
    int hit = TreeAABB_FirstHit(uRam000006fc, sRam000006f0, sRam000007dc, bbox);
    if (hit == 0) return 0;

    /* "Smooth-switch" gate: new target must be within ±0xfa000 of
     * current-target's pos in every axis. */
    int curTarget = *(int *)(self + 0xe4);
    for (int axisOff = 0x24; axisOff <= 0x2c; axisOff += 4) {
        int32_t d = *(int32_t *)(hit + axisOff) - *(int32_t *)(curTarget + axisOff);
        if (d < 0) d = -d;
        if (d >= AI_TARGET_RADIUS) return 0;
    }
    *(int *)(self + 0xe4) = hit;       /* commit new target */

    /* Dispatch event 11 to the new target. */
    typedef int16_t (*TickFn)(int obj, int event, void *arg);
    TickFn fn = *(TickFn *)(candidate + 100);
    if (fn != NULL) fn(candidate, 0xb, self);

    (void)V8_RandNext();   /* RNG advance (consumer not shown in excerpt) */
    return 1;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80022e90  (from analysis/SLUS_005.10/decomp/80022e90.c) --- */
// addr: 0x80022e90  name: FUN_80022e90

undefined4 FUN_80022e90(int param_1)

{
  short sVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int local_28;
  int local_24;
  int local_20;
  int local_1c;
  
  if (cRam00000015 == '\0') {
    if (*(byte *)(param_1 + 0xd0) < 6) {
      return 0;
    }
    iVar5 = *(int *)(param_1 + (uint)*(byte *)(param_1 + 0xb3) * 4 + 0x110);
    if (iVar5 != 0) {
      if (*(char *)(iVar5 + 8) != '\x04') {
        return 0;
      }
      local_28 = *(int *)(param_1 + 0x24) + -0xfa000;
      local_24 = *(int *)(param_1 + 0x24) + 0xfa000;
      local_20 = *(int *)(param_1 + 0x2c) + -0xfa000;
      local_1c = *(int *)(param_1 + 0x2c) + 0xfa000;
      iVar2 = FUN_80021a30(uRam000006fc,(int)sRam000006f0,(int)sRam000007dc,&local_28);
      if (iVar2 != 0) {
        iVar4 = *(int *)(param_1 + 0xe4);
        iVar3 = *(int *)(iVar2 + 0x24) - *(int *)(iVar4 + 0x24);
        if (iVar3 < 0) {
          iVar3 = -iVar3;
        }
        if (0xf9fff < iVar3) {
          return 0;
        }
        iVar3 = *(int *)(iVar2 + 0x28) - *(int *)(iVar4 + 0x28);
        if (iVar3 < 0) {
          iVar3 = -iVar3;
        }
        if (0xf9fff < iVar3) {
          return 0;
        }
        iVar3 = *(int *)(iVar2 + 0x2c) - *(int *)(iVar4 + 0x2c);
        if (iVar3 < 0) {
          iVar3 = -iVar3;
        }
        if (0xf9fff < iVar3) {
          return 0;
        }
        *(int *)(param_1 + 0xe4) = iVar2;
        if (*(code **)(iVar5 + 100) == (code *)0x0) {
          sVar1 = 0;
        }
        else {
          sVar1 = (**(code **)(iVar5 + 100))(iVar5,0xb,param_1);
        }
        iVar2 = FUN_80017160();
        *(short *)(iVar5 + 6) = sVar1 + (short)(iVar2 * 0x80 * (2 - cRam00000016) >> 0xf);
        *(int *)(param_1 + 0xe4) = iVar4;
        return 1;
      }
    }
  }
  return 0;
}

#endif  /* GHIDRA REF */
