/* bone_findfree.c -- find the first free bone slot.
 *
 * Source: SLUS_005.10  FUN_8003fbc8.
 *
 * Walks an object's bone-template chain (rooted at template+0x36,
 * chained via +0x34) and returns the index of the first bone whose
 * kind field has the high byte 0xff (the "free slot" marker) AND
 * is not 0xffff (the end-of-chain sentinel).
 *
 * HIGH confidence.
 */
#include <stdint.h>

static inline uintptr_t obj_ptr32(uintptr_t base, uint32_t off)
{
    return (uintptr_t)*(uint32_t *)(base + off);
}

uint32_t Bone_FindFreeSlot(int obj)
{
    uintptr_t bank = obj_ptr32((uintptr_t)obj, 0x58);
    uintptr_t templateBody = obj_ptr32(bank, 0);
    uint16_t idx = *(uint16_t *)(templateBody
                                + *(uint16_t *)(uintptr_t)(obj + 10) * 0x1c + 0x36);
    while (idx != 0xffff) {
        uint16_t kind = *(uint16_t *)(templateBody + idx * 0x1c + 0x1c);
        if ((kind >> 8) == 0xff && kind != 0xffff) return idx;
        idx = *(uint16_t *)(templateBody + idx * 0x1c + 0x34);
    }
    return 0;
}

/* Hex-name alias (vehicle_kill.c, wheel_ticks.c, collision_apply.c callers). */
uint32_t FUN_8003fbc8(int obj) { return Bone_FindFreeSlot(obj); }

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8003fbc8  (from analysis/SLUS_005.10/decomp/8003fbc8.c) --- */
// addr: 0x8003fbc8  name: FUN_8003fbc8

uint FUN_8003fbc8(int param_1)

{
  ushort uVar1;
  uint uVar2;
  int iVar3;
  
  iVar3 = **(int **)(param_1 + 0x58);
  uVar1 = *(ushort *)(iVar3 + (uint)*(ushort *)(param_1 + 10) * 0x1c + 0x36);
  while( true ) {
    uVar2 = (uint)uVar1;
    if (uVar2 == 0xffff) {
      return 0;
    }
    uVar1 = *(ushort *)(iVar3 + uVar2 * 0x1c + 0x1c);
    if ((uVar1 >> 8 == 0xff) && (uVar1 != 0xffff)) break;
    uVar1 = *(ushort *)(iVar3 + uVar2 * 0x1c + 0x34);
  }
  return uVar2;
}

#endif  /* GHIDRA REF */
