/* buffer.c -- per-frame draw-buffer ordering table + deferred-free lists.
 *
 * Source: SLUS_005.10
 *   FUN_800119c0 -- Buffer_StartOTag(parity)
 *   FUN_80011914 -- Buffer_FlushDeferredFree(parity)
 *   FUN_800118b4 -- Buffer_DeferFree(ptr)
 *
 * V8 uses standard PSX double-buffered rendering. Two 0x4400-byte
 * ordering-table arenas live at UNK_800664a0 and that+0x4400. A
 * deferred-free list head/tail/sentinel triple lives at
 * DAT_8006eca0 (parity 0) and DAT_8006eca0 + 12 (parity 1).
 *
 * Lifecycle per frame:
 *   1. game-tick code calls Buffer_DeferFree(p) for any heap blocks
 *      that hold draw-list-referenced data this frame.
 *   2. at frame boundary the renderer drains the OT and we flip parity.
 *   3. Buffer_StartOTag(newParity) clears the new arena and calls
 *      Buffer_FlushDeferredFree(newParity), releasing everything
 *      pinned by the *previous-frame-of-this-parity* draw.
 *
 * Bit-exact: this is renderer-adjacent (puRam0000060c points at the OT
 * the renderer consumes). The renderer is rewritten per CLAUDE.md so
 * the new layer can use any OT format; what matters for 1:1 is when
 * the deferred frees fire -- preserve that timing exactly.
 */
#include <stdint.h>

extern void *Heap_Free(void *p);            /* FUN_80045088 */
extern void *Heap_AllocOrRetry(uint32_t n); /* FUN_800116f4 */
extern void  ClearOTagR(uint32_t *otag, int n);

extern int32_t   iRam00000004;     /* current display buffer parity (0/1) */
extern uint32_t *puRam0000060c;    /* per-frame OT base */
extern uint8_t   UNK_800664a0[];   /* OT arena base (4400 bytes per parity) */
extern uint32_t  DAT_8006eca0[];   /* deferred-free triples: head, tail, sentinel x 2 */

typedef struct DeferredFreeNode {
    struct DeferredFreeNode *next;
    struct DeferredFreeNode *sentinelOrPrev;
    void                    *payload;
} DeferredFreeNode;

/* HIGH: drain and free all deferred-free entries for `parity`. */
void Buffer_FlushDeferredFree(int parity)
{
    DeferredFreeNode *cur  = (DeferredFreeNode *)DAT_8006eca0[parity * 3];
    DeferredFreeNode *next = (DeferredFreeNode *)cur->next;
    while (next != NULL) {
        Heap_Free(cur->payload);
        Heap_Free(cur);
        cur  = next;
        next = (DeferredFreeNode *)next->next;
    }
    /* Reinitialise: head -> sentinel, sentinel -> NULL, tail -> &head. */
    DAT_8006eca0[parity * 3 + 0] = (uint32_t)&DAT_8006eca0[parity * 3 + 1];
    DAT_8006eca0[parity * 3 + 1] = 0;
    DAT_8006eca0[parity * 3 + 2] = (uint32_t)&DAT_8006eca0[parity * 3 + 0];
}

/* HIGH: enqueue `payload` for free at the end of the current draw frame. */
void Buffer_DeferFree(void *payload)
{
    DeferredFreeNode *n = (DeferredFreeNode *)Heap_AllocOrRetry(12);
    n->payload = payload;
    int parity = iRam00000004;
    DeferredFreeNode *tail = (DeferredFreeNode *)DAT_8006eca0[parity * 3 + 2];
    DAT_8006eca0[parity * 3 + 2] = (uint32_t)n;
    tail->next = n;
    n->sentinelOrPrev = tail;
    n->next = (DeferredFreeNode *)&DAT_8006eca0[parity * 3 + 1];
}

/* HIGH: start a new frame on `parity` -- swap OT arena, flush deferred frees. */
void Buffer_StartOTag(int parity)
{
    puRam0000060c = (uint32_t *)(UNK_800664a0 + parity * 0x4400);
    iRam00000004  = parity;
    ClearOTagR(puRam0000060c, 0x1000);
    Buffer_FlushDeferredFree(parity);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800119c0  (from analysis/SLUS_005.10/decomp/800119c0.c) --- */
// addr: 0x800119c0  name: FUN_800119c0

void FUN_800119c0(int param_1)

{
  puRam0000060c = (u_long *)(&UNK_800664a0 + param_1 * 0x4400);
  iRam00000004 = param_1;
  ClearOTagR(puRam0000060c,0x1000);
  FUN_80011914(param_1);
  return;
}

/* --- SLUS_005.10 FUN_80011914  (from analysis/SLUS_005.10/decomp/80011914.c) --- */
// addr: 0x80011914  name: FUN_80011914

void FUN_80011914(int param_1)

{
  int *piVar1;
  int *piVar2;
  
  piVar1 = (int *)(&DAT_8006eca0)[param_1 * 3];
  for (piVar2 = (int *)*(int *)(&DAT_8006eca0)[param_1 * 3]; piVar2 != (int *)0x0;
      piVar2 = (int *)*piVar2) {
    FUN_80045088(piVar1[2]);
    FUN_80045088(piVar1);
    piVar1 = piVar2;
  }
  (&DAT_8006eca0)[param_1 * 3] = &DAT_8006eca4 + param_1 * 3;
  (&DAT_8006eca4)[param_1 * 3] = 0;
  (&DAT_8006eca8)[param_1 * 3] = &DAT_8006eca0 + param_1 * 3;
  return;
}

/* --- SLUS_005.10 FUN_800118b4  (from analysis/SLUS_005.10/decomp/800118b4.c) --- */
// addr: 0x800118b4  name: FUN_800118b4

void FUN_800118b4(undefined4 param_1)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  
  puVar2 = (undefined4 *)FUN_800116f4(0xc);
  iVar1 = iRam00000004;
  puVar2[2] = param_1;
  puVar3 = (undefined4 *)(&DAT_8006eca8)[iVar1 * 3];
  (&DAT_8006eca8)[iVar1 * 3] = puVar2;
  *puVar3 = puVar2;
  puVar2[1] = puVar3;
  *puVar2 = &DAT_8006eca4 + iVar1 * 3;
  return;
}

/* --- SLUS_005.10 FUN_80045088  (from analysis/SLUS_005.10/decomp/80045088.c) --- */
// addr: 0x80045088  name: FUN_80045088

void FUN_80045088(int param_1)

{
  int iVar1;
  uint *puVar2;
  uint *puVar3;
  uint uVar4;
  
  puVar2 = (uint *)(param_1 + -8);
  puVar3 = DAT_8005ed4c;
  do {
    DAT_8005ed4c = puVar3;
    puVar3 = (uint *)*DAT_8005ed4c;
    if ((DAT_8005ed4c < puVar2) && (puVar2 < puVar3)) break;
  } while ((DAT_8005ed4c < puVar3) || ((puVar2 <= DAT_8005ed4c && (puVar3 <= puVar2))));
  iVar1 = *(int *)(param_1 + -4);
  if ((puVar2 + iVar1 * 2 == puVar3) && (iVar1 = iVar1 + puVar3[1], puVar3[1] != 0)) {
    puVar3 = (uint *)*puVar3;
    *(int *)(param_1 + -4) = iVar1;
  }
  uVar4 = DAT_8005ed4c[1];
  *puVar2 = (uint)puVar3;
  if (DAT_8005ed4c + uVar4 * 2 == puVar2) {
    DAT_8005ed4c[1] = iVar1 + uVar4;
    puVar2 = puVar3;
  }
  *DAT_8005ed4c = (uint)puVar2;
  return;
}

/* --- SLUS_005.10 FUN_800116f4  (from analysis/SLUS_005.10/decomp/800116f4.c) --- */
// addr: 0x800116f4  name: FUN_800116f4

int FUN_800116f4(int param_1)

{
  int iVar1;
  
  iVar1 = FUN_80045004();
  if ((iVar1 == 0) && (param_1 != 0)) {
    DrawSync(0);
    FUN_80011914(1 - iRam00000004);
    FUN_800165cc(1);
    do {
      iVar1 = FUN_80045004(param_1);
      if (iVar1 != 0) {
        return iVar1;
      }
      iVar1 = FUN_80020d3c();
    } while (iVar1 != 0);
    _boot();
    iVar1 = 0;
  }
  return iVar1;
}

#endif  /* GHIDRA REF */
