/* buffer_defer_free.c -- enqueue a pointer for free at end-of-frame.
 *
 * Source: SLUS_005.10  FUN_800118b4.
 *
 * Allocates a 12-byte deferred-free node, links it onto the tail of
 * the per-parity deferred-free chain (head/sentinel/tail triple at
 * DAT_8006eca0[parity * 3]), then stores `payload` in the new node's
 * payload slot. The chain is drained by Buffer_FlushDeferredFree.
 *
 * Used during draw to free heap memory that the renderer is still
 * reading; the actual free happens after the renderer flips parity.
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern void *Heap_AllocOrRetry(uint32_t n);   /* FUN_800116f4 */
extern int32_t iRam00000004;                   /* g_dispBufIndex */
extern void   *DAT_8006eca0;                   /* deferred-free anchor (3-tuple x 2 parities) */
extern void   *DAT_8006eca4;
extern void   *DAT_8006eca8;

void Buffer_DeferFree(void *payload)
{
    /* node[0]=next sentinel, node[1]=back-link, node[2]=payload */
    uint32_t *node = (uint32_t *)Heap_AllocOrRetry(0xc);
    int parity = (int)iRam00000004;
    node[2] = (uintptr_t)payload;

    uint32_t **anchorBase = (uint32_t **)&DAT_8006eca0;
    uint32_t *prevTail = anchorBase[parity * 3 + 2];   /* tail */
    anchorBase[parity * 3 + 2] = node;
    *prevTail = (uintptr_t)node;
    node[1] = (uintptr_t)prevTail;
    node[0] = (uintptr_t)&((uint32_t **)anchorBase)[parity * 3 + 1];   /* sentinel */
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800118b4  (from analysis/SLUS_005.10/decomp/800118b4.c) --- */
// addr: 0x800118b4  name: FUN_800118b4

void FUN_800118b4(undefined4 param_1)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  
  puVar2 = (undefined4 *)FUN_800116f4(0xc);
  iVar1 = iRam00000004;
  puVar2[2] = param_1;
  puVar3 = (undefined4 *)(&DAT_8006eca8)[iVar1 * 3];
  (&DAT_8006eca8)[iVar1 * 3] = puVar2;
  *puVar3 = puVar2;
  puVar2[1] = puVar3;
  *puVar2 = &DAT_8006eca4 + iVar1 * 3;
  return;
}

#endif  /* GHIDRA REF */
