/* callback_dispatch.c -- safe invocation of an object's per-tick callback.
 *
 * Source: SLUS_005.10  FUN_8001e120.
 *
 * Thin wrapper: if `obj->callback @ +0x64` is non-NULL, save the BIOS
 * scratchpad fields used for stack unwinding (DAT_1f8003f8, +4) and
 * invoke the callback. Returns whatever it returns, or 0 if no callback.
 *
 * Used as the canonical "tick this object" call site -- replaces ~20
 * places where the same pattern appears.
 *
 * Bit-exact: the scratchpad save (DAT_1f8003f8) is a PSX BIOS trick to
 * facilitate the optional restart from an exception in the callee.
 * Don't simplify.
 *
 * HIGH confidence.
 */
#include <stdint.h>

/* DAT_1f8003f8 / DAT_1f8003fc: PSX BIOS scratchpad stack-unwind slots.
 * On host: written but never read (exception path never taken).
 * DAT_1f8003f8 is a uintptr (stores return address).
 * DAT_1f8003fc is a pointer (stores frame pointer / $fp).
 * Defined here to avoid link errors from the extern declarations. */
uintptr_t DAT_1f8003f8 = 0;
uint8_t  *DAT_1f8003fc = 0;

/* __builtin_return_address / __builtin_frame_address are GCC intrinsics.
 * Provide MSVC-compatible equivalents that return something safe. */
#if defined(_MSC_VER) && !defined(__builtin_return_address)
#  include <intrin.h>
#  define __builtin_return_address(n) _ReturnAddress()
#  define __builtin_frame_address(n)  _AddressOfReturnAddress()
#endif

uintptr_t Object_CallbackFromPsxSlot(const void *obj)
{
    uint32_t low;

    if (obj == 0)
        return 0;
    low = *(const uint32_t *)((const uint8_t *)obj + 0x64);
    if (low == 0)
        return 0;
    return ((uintptr_t)&Object_CallbackFromPsxSlot & ~(uintptr_t)0xffffffffu) |
           (uintptr_t)low;
}

void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback)
{
    if (obj != 0)
        *(uint32_t *)((uint8_t *)obj + 0x64) = (uint32_t)callback;
}

uint32_t Object_TickCallback(intptr_t obj, int mode, intptr_t arg2, intptr_t arg3)
{
    typedef uint32_t (*TickFn)(intptr_t, int, intptr_t, intptr_t);
    TickFn fn = (TickFn)Object_CallbackFromPsxSlot((const void *)obj);
    if (fn == NULL) return 0;
    /* Stack-save aliases for re-entry (PSX BIOS trick; no-op on host). */
    DAT_1f8003f8 = (uintptr_t)__builtin_return_address(0);
    DAT_1f8003fc = (uint8_t *)__builtin_frame_address(0);
    return fn(obj, mode, arg2, arg3);
}

/* Hex-name alias. */
uint32_t FUN_8001e120(intptr_t param_1, int mode, intptr_t arg2)
{
    return Object_TickCallback(param_1, mode, arg2, 0);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001e120  (from analysis/SLUS_005.10/decomp/8001e120.c) --- */
// addr: 0x8001e120  name: FUN_8001e120

undefined4 FUN_8001e120(int param_1)

{
  undefined4 uVar1;
  undefined4 unaff_retaddr;
  undefined1 auStackX_0 [16];
  
  if (*(code **)(param_1 + 100) != (code *)0x0) {
    DAT_1f8003f8 = unaff_retaddr;
    DAT_1f8003fc = (undefined1 *)register0x00000074;
    uVar1 = (**(code **)(param_1 + 100))();
    return uVar1;
  }
  return 0;
}

#endif  /* GHIDRA REF */
