/* callback_dispatch.c -- safe invocation of an object's per-tick callback.
 *
 * Source: SLUS_005.10  FUN_8001e120.
 *
 * Thin wrapper: if `obj->callback @ +0x64` is non-NULL, save the BIOS
 * scratchpad fields used for stack unwinding (DAT_1f8003f8, +4) and
 * invoke the callback. Returns whatever it returns, or 0 if no callback.
 *
 * Used as the canonical "tick this object" call site -- replaces ~20
 * places where the same pattern appears.
 *
 * Bit-exact: the scratchpad save (DAT_1f8003f8) is a PSX BIOS trick to
 * facilitate the optional restart from an exception in the callee.
 * Don't simplify.
 *
 * HIGH confidence.
 */
#include <stdint.h>
#include <stdio.h>

/* __builtin_return_address / __builtin_frame_address are GCC intrinsics.
 * Provide MSVC-compatible equivalents that return something safe. */
#if defined(_MSC_VER) && !defined(__builtin_return_address)
#  include <intrin.h>
#  define __builtin_return_address(n) _ReturnAddress()
#  define __builtin_frame_address(n)  _AddressOfReturnAddress()
#endif

extern int32_t iRam0000000c;

/* DAT_1f8003f8 / DAT_1f8003fc: PSX BIOS scratchpad stack-unwind slots.
 * On host: written but never read (exception path never taken).
 * DAT_1f8003f8 is a uintptr (stores return address).
 * DAT_1f8003fc is a pointer (stores frame pointer / $fp).
 * Defined here to avoid link errors from the extern declarations. */
uintptr_t DAT_1f8003f8 = 0;
uint8_t  *DAT_1f8003fc = 0;

typedef struct {
    const void *obj;
    uint32_t  psxSlot;
    uintptr_t nativeFn;
} CallbackMapEntry;

#define CALLBACK_MAP_CAP 4096
static CallbackMapEntry s_callbackMap[CALLBACK_MAP_CAP];
static int s_callbackMapCount = 0;
static int s_unresolvedCallbackWarns = 0;

static void Callback_RegisterNative(const void *obj, uintptr_t callback)
{
    uint32_t low;
    int i;

    if (obj == 0)
        return;
    if (callback == 0)
        return;

    low = (uint32_t)callback;
    if (low == 0)
        return;

    for (i = 0; i < s_callbackMapCount; i++) {
        if (s_callbackMap[i].obj == obj) {
            s_callbackMap[i].psxSlot = low;
            s_callbackMap[i].nativeFn = callback;
            return;
        }
    }

    if (s_callbackMapCount < CALLBACK_MAP_CAP) {
        s_callbackMap[s_callbackMapCount].obj = obj;
        s_callbackMap[s_callbackMapCount].psxSlot = low;
        s_callbackMap[s_callbackMapCount].nativeFn = callback;
        s_callbackMapCount++;
    }
}

static uintptr_t Callback_LookupNative(const void *obj, uint32_t low)
{
    int i;

    for (i = 0; i < s_callbackMapCount; i++) {
        if (s_callbackMap[i].obj == obj && s_callbackMap[i].psxSlot == low)
            return s_callbackMap[i].nativeFn;
    }
    return 0;
}

uintptr_t Object_CallbackFromPsxSlot(const void *obj)
{
    uint32_t low;

    if (obj == 0)
        return 0;
    low = *(const uint32_t *)((const uint8_t *)obj + 0x64);
    if (low == 0)
        return 0;
    {
        uintptr_t nativeFn = Callback_LookupNative(obj, low);
        if (nativeFn != 0)
            return nativeFn;
    }
    if (s_unresolvedCallbackWarns < 16) {
        fprintf(stderr,
                "v8: unresolved object callback slot obj=%p low=0x%08x\n",
                obj, low);
        s_unresolvedCallbackWarns++;
    }
    return 0;
}

void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback)
{
    if (obj != 0) {
        *(uint32_t *)((uint8_t *)obj + 0x64) = (uint32_t)callback;
        Callback_RegisterNative(obj, callback);
    }
}

uint32_t Object_TickCallback(intptr_t obj, int mode, intptr_t arg2, intptr_t arg3)
{
    typedef uint32_t (*TickFn)(intptr_t, int, intptr_t, intptr_t);
    TickFn fn = (TickFn)Object_CallbackFromPsxSlot((const void *)obj);
    if (fn == NULL) return 0;
    /* Stack-save aliases for re-entry (PSX BIOS trick; no-op on host). */
    DAT_1f8003f8 = (uintptr_t)__builtin_return_address(0);
    DAT_1f8003fc = (uint8_t *)__builtin_frame_address(0);
    return fn(obj, mode, arg2, arg3);
}

/* Hex-name alias. */
uint32_t FUN_8001e120(intptr_t param_1, int mode, intptr_t arg2)
{
    return Object_TickCallback(param_1, mode, arg2, 0);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001e120  (from analysis/SLUS_005.10/decomp/8001e120.c) --- */
// addr: 0x8001e120  name: FUN_8001e120

undefined4 FUN_8001e120(int param_1)

{
  undefined4 uVar1;
  undefined4 unaff_retaddr;
  undefined1 auStackX_0 [16];
  
  if (*(code **)(param_1 + 100) != (code *)0x0) {
    DAT_1f8003f8 = unaff_retaddr;
    DAT_1f8003fc = (undefined1 *)register0x00000074;
    uVar1 = (**(code **)(param_1 + 100))();
    return uVar1;
  }
  return 0;
}

#endif  /* GHIDRA REF */
