/* collision_apply.c -- the core damage-on-collision arbiter.
 *
 * Source: SLUS_005.10  (gap-recovered)
 *   FUN_80022320  -- Damage_AccumulateOrFire
 *   FUN_8002239c  -- Damage_FromImpulse
 *
 * Every per-level destructible callback ends in a call to either
 * Damage_FromImpulse(self, impulse) or Damage_AccumulateOrFire(self,
 * amount).
 *
 * Damage_AccumulateOrFire(self, amount):
 *   - if self has the "invulnerable" bit 0x8000 set, ignore.
 *   - else if accumulated damage (`self.health` @ +0xc, i16) is less
 *     than `amount` (the new hit), reset health back to its max
 *     (stored at +0xe) and fire the explosion via Effects_SpawnExplosion;
 *     on success, broadcast event 0x11 on the world callback (`pcRam00000730`)
 *     and return 1 (destroyed).
 *   - else subtract `amount` from `self.health` and return 0.
 *
 * Damage_FromImpulse(self, impulse):
 *   - The impulse object's state byte at +4 must be 7 (= "weapon hit"
 *     state). The damage value is the i16 at impulse+0xc (weapon
 *     strength); pass through to Damage_AccumulateOrFire.
 *   - Returns true iff the destructible was killed.
 *
 * HIGH confidence: this closes the universal collision contract used
 * by every level's bridge/turret/transformer/etc. handler in pass 2.
 *
 * Vehicle struct updates: +0xc is now confirmed as the `health` field
 * (we previously had it as `statusFlags` LOW); +0xe is its max-health.
 * Pass 3 should rename Vehicle.statusFlags accordingly.
 */
#include <stdint.h>

extern int  Effects_SpawnExplosion(int obj);                /* FUN_8003fc50 */
extern void (*pcRam00000730)(void *self, int eventId, int);  /* world callback */

int Damage_AccumulateOrFire(uint32_t *self, uint16_t amount)
{
    if ((self[0] & 0x8000u) != 0) return 0;

    uint16_t hp = ((uint16_t *)self)[6];        /* +0xc, lo u16 of self[3] */
    if (hp < amount) {
        /* Reset to max -- self[3] high half = max-hp at +0xe */
        ((uint16_t *)self)[6] = ((uint16_t *)self)[7];
        if (Effects_SpawnExplosion((int)(intptr_t)self) != 0) {
            pcRam00000730(self, 0x11, 0);
            return 1;
        }
    } else {
        ((uint16_t *)self)[6] = (uint16_t)(hp - amount);
    }
    return 0;
}

int Damage_FromImpulse(uint32_t *self, int *impulse)
{
    if (*(int8_t *)(*impulse + 4) != 7) return 0;
    uint16_t weaponStrength = *(uint16_t *)(*impulse + 0xc);
    return Damage_AccumulateOrFire(self, weaponStrength);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80022320  (from analysis/SLUS_005.10/decomp/80022320.c) --- */
// addr: 0x80022320  name: FUN_80022320

undefined4 FUN_80022320(uint *param_1,uint param_2)

{
  int iVar1;
  
  if ((*param_1 & 0x8000) == 0) {
    if ((ushort)param_1[3] < param_2) {
      *(undefined2 *)(param_1 + 3) = *(undefined2 *)((int)param_1 + 0xe);
      iVar1 = FUN_8003fc50();
      if (iVar1 != 0) {
        (*pcRam00000730)(param_1,0x11,0);
        return 1;
      }
    }
    else {
      *(ushort *)(param_1 + 3) = (ushort)param_1[3] - (short)param_2;
    }
  }
  return 0;
}

/* --- SLUS_005.10 FUN_8002239c  (from analysis/SLUS_005.10/decomp/8002239c.c) --- */
// addr: 0x8002239c  name: FUN_8002239c

bool FUN_8002239c(undefined4 param_1,int *param_2)

{
  int iVar1;
  bool bVar2;
  
  bVar2 = false;
  if (*(char *)(*param_2 + 4) == '\a') {
    iVar1 = FUN_80022320(param_1,*(undefined2 *)(*param_2 + 0xc));
    bVar2 = iVar1 != 0;
  }
  return bVar2;
}

/* --- SLUS_005.10 FUN_8003fc50  (from analysis/SLUS_005.10/decomp/8003fc50.c) --- */
// addr: 0x8003fc50  name: FUN_8003fc50

bool FUN_8003fc50(int param_1)

{
  uint uVar1;
  
  uVar1 = FUN_8003fbc8();
  if (uVar1 != 0) {
    FUN_8003fac4(param_1,*(undefined4 *)(param_1 + 0x58),uVar1 & 0xffff);
  }
  return uVar1 != 0;
}

#endif  /* GHIDRA REF */
