/* debris_pool_init.c -- initialize the per-frame screen-space debris pool.
 *
 * Source: SLUS_005.10  FUN_80029dec.
 *
 * Two parity-paired arrays of 16 sprite-prim records at UNK_800a1e24
 * and UNK_800a2324 (offset 0x500 apart) get their per-frame defaults
 * written:
 *   prim[i].mode   = 2          // GP0 sprite mode
 *   prim[i].size   = 0x68       // 104-byte stride for trailing data
 *   prim[i].rgb    = 0xff,ff,ff // white
 *
 * Called once per frame at the start of debris emission. Renderer-
 * adjacent but stays on the gameplay side because the stride and
 * white-color initialisation are visible-state contract.
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern uint8_t UNK_800a1e24[];   /* parity 0 debris pool */
extern uint8_t UNK_800a2324[];   /* parity 1 debris pool, 0x500 bytes later */

#define DEBRIS_COUNT_PER_PARITY  16
#define DEBRIS_PRIM_STRIDE       0x14
#define DEBRIS_PARITY_STRIDE     0x500

void Debris_Pool_InitFrame(void)
{
    for (int parity = 0; parity < 2; parity++) {
        uint8_t *p = (parity == 0) ? UNK_800a1e24 : UNK_800a2324;
        for (int i = 0; i < DEBRIS_COUNT_PER_PARITY; i++) {
            p[3] = 2;      /* GP0 mode */
            p[7] = 0x68;   /* trailing-data stride */
            p[4] = 0xff;
            p[5] = 0xff;
            p[6] = 0xff;
            p += DEBRIS_PRIM_STRIDE;
        }
        (void)DEBRIS_PARITY_STRIDE;
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80029dec  (from analysis/SLUS_005.10/decomp/80029dec.c) --- */
// addr: 0x80029dec  name: FUN_80029dec

void FUN_80029dec(void)

{
  undefined *puVar1;
  int iVar2;
  undefined *puVar3;
  int iVar4;
  
  iVar4 = 0;
  puVar3 = &UNK_800a1e24;
  do {
    iVar2 = 0;
    puVar1 = puVar3;
    do {
      puVar1[3] = 2;
      puVar1[7] = 0x68;
      puVar1[4] = 0xff;
      puVar1[5] = 0xff;
      puVar1[6] = 0xff;
      iVar2 = iVar2 + 1;
      puVar1 = puVar1 + 0x14;
    } while (iVar2 < 0x10);
    iVar4 = iVar4 + 1;
    puVar3 = puVar3 + 0x504;
  } while (iVar4 < 2);
  return;
}

#endif  /* GHIDRA REF */
