/* frame.c -- VSync wait / frame counter helpers.
 *
 * Source: SLUS_005.10
 *   FUN_800156d4 -- V8_WaitVsync.  Spins until the IRQ-incremented counter
 *                   (g_vsyncCounter @ iRam000006a8) differs from the
 *                   last-latched value (g_vsyncLatched @ iRam000006a4),
 *                   then latches and returns the prior latched value.
 *   FUN_8001714c -- V8_SeedRng (see src/gameplay/rng.c)
 *
 * V8 ticks at the standard NTSC 60Hz. The IRQ handler at LAB_80014ff0
 * (installed by OpenEvent in main()) increments g_vsyncCounter every
 * field. Game code calls V8_WaitVsync at the end of each tick to
 * advance.
 *
 * Bit-exact note: a busy-wait spin is preserved verbatim. Replacing
 * it with a host sleep/condvar would shift timing observably in
 * code that polls g_vsyncCounter without going through this helper.
 */
#include <stdint.h>

extern volatile int32_t g_vsyncCounter;   /* iRam000006a8, updated by IRQ */
extern volatile int32_t g_vsyncLatched;   /* iRam000006a4 */

int32_t V8_WaitVsync(void)
{
    int32_t prev = g_vsyncLatched;
    while (g_vsyncCounter == g_vsyncLatched) {
        /* spin */
    }
    g_vsyncLatched = g_vsyncCounter;
    return prev;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800156d4  (from analysis/SLUS_005.10/decomp/800156d4.c) --- */
// addr: 0x800156d4  name: FUN_800156d4

int FUN_800156d4(void)

{
  int iVar1;
  
  iVar1 = iRam000006a4;
  do {
  } while (iRam000006a8 == iRam000006a4);
  iRam000006a4 = iRam000006a8;
  return iVar1;
}

/* --- SLUS_005.10 FUN_8001714c  (from analysis/SLUS_005.10/decomp/8001714c.c) --- */
// addr: 0x8001714c  name: FUN_8001714c

void FUN_8001714c(undefined4 param_1)

{
  DAT_800568d4 = param_1;
  DAT_800568d8 = 0;
  return;
}

#endif  /* GHIDRA REF */
