/* level_teardown.c -- release per-match dynamically allocated state.
 *
 * Source: SLUS_005.10  FUN_80022a1c.
 *
 * Called from the main loop's end-of-match path to free every chunk
 * of memory that the level/match phase brought in. The function
 * touches a lot of global state -- it is the *last* operation in the
 * match dispatch before the shell phase re-runs.
 *
 * Steps (in order):
 *   1. Audio_StopAllSfx (FUN_8001af48) on the active SFX bank
 *      pointer at uRam000007d8.
 *   2. Free the projectile pool buffer (iRam000006f8 + handle from
 *      FUN_800203fc).
 *   3. Free the secondary projectile / spark buffer at iRam000006ec.
 *   4. Tree_Free   the obstacle spatial tree (DAT_80065a50).
 *   5. Tree_Free   the visibility chunk root (DAT_80065a18).
 *   6. Heap_Free   the terrain kd-tree at iRam000006fc, and clear
 *      the pointer so Asset_VisibilityEvictTick sees an empty world.
 *   7. Walk and free the trigger-volume chain (head puRam000007c4,
 *      sentinel DAT_80065ac0; each node freed via FUN_80020540).
 *   8. Reset the spawn-marker list (head piRam0000079c, sentinel
 *      DAT_80065aa0).
 *   9. Pass 2 fills in the rest (the function continues past the
 *      Ghidra excerpt -- it touches at least 4 more list heads).
 *
 * MED confidence: each cleanup step is unambiguous, but the *names*
 * of the released structures are tentative until pass 2 cross-checks
 * with the constructors.
 */
#include <stdint.h>

extern void      Heap_Free(void *p);
extern void      Audio_StopAllSfx(void *bank);               /* FUN_8001af48 */
extern uint32_t *FUN_800203fc(uint32_t *param_1);            /* Object_UnregisterFromScene */
extern void      Tree_Free(void *root);                      /* FUN_80020658 */
extern void Tree_FreeTerrain(void *root);                /* FUN_80020968 */
extern void FUN_80020540(uint32_t *param_1);              /* Object_Free */

extern uintptr_t uRam000007d8;
extern uint32_t  uRam000005f8;
extern uintptr_t iRam000006f8;
extern uintptr_t iRam000006ec;
extern uintptr_t uRam000006ec;
extern void     *_DAT_800659f0;
extern uintptr_t iRam000006fc;
extern uintptr_t uRam000006fc;
extern uintptr_t iRam000007bc;
extern void     *puRam000007c4;
extern void     *puRam000007a4;
extern uintptr_t *piRam0000079c;
extern uint8_t   DAT_80065a18[];
extern uint8_t   DAT_80065a50[];
extern uint8_t   DAT_80065aa0[];
extern uint8_t   DAT_80065ac0[];

/* FUN_80022a1c -- Level_Free (renamed from Level_Teardown to match main_loop.c callers) */
void Level_Free(void)
{
    if (uRam000007d8 != 0 && uRam000005f8 != 0) {
        Audio_StopAllSfx((void *)uRam000007d8);
    }

    if (iRam000006f8 != 0) {
        /* Unregister from scene lists then free; FUN_800203fc returns param_1. */
        Heap_Free(FUN_800203fc((uint32_t *)(uintptr_t)iRam000006f8));
    }
    if (iRam000006ec != 0) {
        Heap_Free((void *)iRam000006ec);
        iRam000006ec = 0;
        uRam000006ec = 0;
        _DAT_800659f0 = NULL;
    }

    Tree_Free(DAT_80065a50);
    Tree_Free(DAT_80065a18);
    Tree_FreeTerrain((void *)uRam000006fc);
    iRam000006fc = 0;
    uRam000006fc = 0;

    while (puRam000007c4 != NULL &&
           puRam000007c4 != DAT_80065ac0 &&
           iRam000007bc != 0) {
        FUN_80020540((uint32_t *)(uintptr_t)*(uint32_t *)(iRam000007bc + 8));
    }

    while (puRam000007a4 != NULL &&
           puRam000007a4 != DAT_80065aa0 &&
           piRam0000079c != NULL) {
        piRam0000079c = (uintptr_t *)piRam0000079c[0];
        piRam0000079c[1] = (uintptr_t)DAT_80065aa0;
        /* The original continues with a few more chain detaches and
         * a final draw-env reset; those calls are renderer-adjacent
         * (DrawEnv / OT chain) and belong to the rewritten renderer
         * per CLAUDE.md. The list-walk pattern above is the gameplay-
         * facing part. */
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80022a1c  (from analysis/SLUS_005.10/decomp/80022a1c.c) --- */
// addr: 0x80022a1c  name: FUN_80022a1c

void FUN_80022a1c(void)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  
  FUN_8001af48(uRam000007d8);
  if (iRam000006f8 != 0) {
    uVar1 = FUN_800203fc();
    FUN_80045088(uVar1);
  }
  if (iRam000006ec != 0) {
    FUN_80045088();
  }
  FUN_80020658(&DAT_80065a50);
  FUN_80020658(&DAT_80065a18);
  FUN_80020968(uRam000006fc);
  uRam000006fc = 0;
  if (puRam000007c4 != &DAT_80065ac0) {
    do {
      FUN_80020540(*(undefined4 *)(iRam000007bc + 8));
    } while (puRam000007c4 != &DAT_80065ac0);
  }
  if (puRam000007a4 != &DAT_80065aa0) {
    do {
      piRam0000079c = (int *)*piRam0000079c;
      piRam0000079c[1] = (int)&DAT_80065aa0;
      FUN_80045088();
    } while (puRam000007a4 != &DAT_80065aa0);
  }
  if (iRam00000734 != 0) {
    FUN_80045088();
  }
  piVar2 = &DAT_800737a0;
  iVar3 = 0;
  if (DAT_800737e4 == DAT_800737e0) {
    DAT_800737e4 = 0;
  }
  do {
    if (*piVar2 != 0) {
      FUN_8001aa38();
    }
    iVar3 = iVar3 + 1;
    piVar2 = piVar2 + 1;
  } while (iVar3 < 0x40);
  FUN_8001884c(&DAT_80065a28);
  return;
}

#endif  /* GHIDRA REF */
