/* list_walkers.c -- generic walker helpers for the object linked lists.
 *
 * Source: SLUS_005.10
 *   FUN_8001fcb4  -- Object_FrameCounterBump (pre-tick recursion)
 *   FUN_80020658  -- ObjList_FreeAllAndRetire
 *   FUN_80020968  -- Tree_FreeRecursive
 *   FUN_800206f0  -- ObjList_ApplyDestroy
 *   FUN_800200b8  -- ObjList_FindWithPredicate
 *
 * These small helpers underpin the tree traversal in object_tree.c.
 * Each walks a different chain anchored at a sentinel and either
 * frees nodes or invokes a per-node callback.
 *
 * HIGH confidence (each is a tight specialised loop).
 */
#include <stdint.h>
#include <stddef.h>

extern int  Object_PreTickRecurse(int payload, uint16_t arg);   /* FUN_8001f9cc */
extern void Object_PreTickChildren(int chainHead, uint16_t arg); /* FUN_8001fc38 */
extern void Object_Free(uint32_t *obj);                         /* FUN_80020540 */
extern void Object_Destroy(int payload);                        /* FUN_8001de08 */
extern int32_t **piRam00000774;

/* HIGH: recursive object pre-tick. Applies the per-object pre-tick to
 * the node, then if its child list is populated recurses into them. */
void Object_FrameCounterBump(int payload, uint16_t arg)
{
    int r = Object_PreTickRecurse(payload, arg);
    if (r < 0 || *(int *)(payload + 0x38) == 0) return;
    Object_PreTickChildren(*(int *)(payload + 0x38), arg);
}

/* HIGH: walk an object list, freeing each payload and re-linking the
 * node onto the dead chain. */
extern uint8_t DAT_80065a74[];
void ObjList_FreeAllAndRetire(int **listSentinel)
{
    int *next = (int *)listSentinel[2];
    while (next != (int *)listSentinel) {
        int *node = (int *)*listSentinel;
        Object_Free((uint32_t *)(intptr_t)node[2]);
        int32_t *prev = (int32_t *)node[1];
        int32_t  back = node[0];
        *(int32_t **)(back + 4) = prev;
        *prev = back;

        int32_t **deadTail = piRam00000774;
        piRam00000774 = (int32_t **)node;
        *prev = (int32_t)(intptr_t)node;
        next = (int *)listSentinel[2];
        (void)deadTail;
    }
}

/* HIGH: free a whole kd-tree, including the per-leaf object lists. */
void Tree_FreeRecursive(int *node)
{
    if (node == NULL) return;
    if (node[0] == 0) {
        ObjList_FreeAllAndRetire((int **)(node + 1));
    } else {
        Tree_FreeRecursive((int *)(intptr_t)node[2]);
        Tree_FreeRecursive((int *)(intptr_t)node[3]);
    }
    extern void Heap_Free(void *p);
    Heap_Free(node);
}

/* HIGH: walk a list, calling Object_Destroy on each payload. */
void ObjList_ApplyDestroy(int **listSentinel)
{
    int *node = (int *)listSentinel[0];
    int *next = (int *)*(int *)listSentinel[0];
    for (; next != NULL; next = (int *)*next) {
        Object_Destroy(node[2]);
        node = next;
    }
}

/* HIGH: walk a list, applying a predicate; stop at first non-zero
 * return. (`ObjList_FindWithPredicate` family used by Tree_Apply.) */
int ObjList_FindWithPredicate(int **listSentinel,
                              int (*pred)(int *node, uint32_t arg),
                              uint32_t arg)
{
    int *node = (int *)listSentinel[0];
    int *next = (int *)*(int *)listSentinel[0];
    while (next != NULL) {
        int r = pred(node, arg);
        if (r != 0) return r;
        node = next;
        next = (int *)*next;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001fcb4  (from analysis/SLUS_005.10/decomp/8001fcb4.c) --- */
// addr: 0x8001fcb4  name: FUN_8001fcb4

void FUN_8001fcb4(int param_1,undefined2 param_2)

{
  int iVar1;
  
  iVar1 = FUN_8001f9cc(param_1,param_2);
  if ((-1 < iVar1) && (*(int *)(param_1 + 0x38) != 0)) {
    FUN_8001fc38(*(int *)(param_1 + 0x38),param_2);
  }
  return;
}

/* --- SLUS_005.10 FUN_80020658  (from analysis/SLUS_005.10/decomp/80020658.c) --- */
// addr: 0x80020658  name: FUN_80020658

void FUN_80020658(undefined4 *param_1)

{
  int *piVar1;
  undefined4 *puVar2;
  int iVar3;
  int *piVar4;
  int *piVar5;
  
  puVar2 = (undefined4 *)param_1[2];
  while (puVar2 != param_1) {
    piVar5 = (int *)*param_1;
    FUN_80020540(piVar5[2]);
    piVar4 = (int *)piVar5[1];
    iVar3 = *piVar5;
    *(int **)(iVar3 + 4) = piVar4;
    *piVar4 = iVar3;
    piVar4 = piRam00000774;
    piVar1 = piVar5;
    *piRam00000774 = (int)piVar5;
    piRam00000774 = piVar1;
    piVar5[1] = (int)piVar4;
    *piVar5 = (int)&DAT_80065a74;
    piVar5[2] = 0;
    puVar2 = (undefined4 *)param_1[2];
  }
  return;
}

/* --- SLUS_005.10 FUN_80020968  (from analysis/SLUS_005.10/decomp/80020968.c) --- */
// addr: 0x80020968  name: FUN_80020968

void FUN_80020968(int *param_1)

{
  if (param_1 != (int *)0x0) {
    if (*param_1 == 0) {
      FUN_80020658(param_1 + 1);
    }
    else {
      FUN_80020968(param_1[2]);
      FUN_80020968(param_1[3]);
    }
    FUN_80045088(param_1);
  }
  return;
}

/* --- SLUS_005.10 FUN_800206f0  (from analysis/SLUS_005.10/decomp/800206f0.c) --- */
// addr: 0x800206f0  name: FUN_800206f0

void FUN_800206f0(int *param_1)

{
  int *piVar1;
  int *piVar2;
  
  piVar1 = (int *)*param_1;
  for (piVar2 = (int *)*(int *)*param_1; piVar2 != (int *)0x0; piVar2 = (int *)*piVar2) {
    FUN_8001de08(piVar1[2]);
    piVar1 = piVar2;
  }
  return;
}

/* --- SLUS_005.10 FUN_800200b8  (from analysis/SLUS_005.10/decomp/800200b8.c) --- */
// addr: 0x800200b8  name: FUN_800200b8

void FUN_800200b8(int *param_1,code *param_2,undefined4 param_3)

{
  int *piVar1;
  int *piVar2;
  int iVar3;
  
  piVar1 = (int *)*param_1;
  piVar2 = (int *)*(int *)*param_1;
  while ((piVar2 != (int *)0x0 && (iVar3 = (*param_2)(piVar1,param_3), iVar3 == 0))) {
    piVar1 = piVar2;
    piVar2 = (int *)*piVar2;
  }
  return;
}

/* --- SLUS_005.10 FUN_8001f9cc  (from analysis/SLUS_005.10/decomp/8001f9cc.c) --- */
// addr: 0x8001f9cc  name: FUN_8001f9cc

undefined4 FUN_8001f9cc(int param_1,short param_2)

{
  short sVar1;
  bool bVar2;
  int iVar3;
  undefined4 uVar4;
  short *psVar5;
  uint in_t0;
  uint uVar6;
  uint uVar7;
  uint *puVar8;
  uint *puVar9;
  uint uVar10;
  uint *puVar11;
  
  if (*(ushort **)(param_1 + 0x60) != (ushort *)0x0) {
    if ((ushort)(param_2 - *(short *)(param_1 + 0x46)) < **(ushort **)(param_1 + 0x60)) {
      return 0;
    }
    bVar2 = false;
    puVar11 = (uint *)0x0;
    do {
      psVar5 = *(short **)(param_1 + 0x60);
      uVar10 = (uint)psVar5[1];
      puVar8 = (uint *)(psVar5 + 2);
      if ((int)uVar10 < 0) {
        *(short *)(param_1 + 0x46) = *(short *)(param_1 + 0x46) + *psVar5;
        *(uint *)(param_1 + 0x60) = *(int *)(param_1 + 0x60) + uVar10;
        if (*(code **)(param_1 + 100) == (code *)0x0) {
          iVar3 = 0;
        }
        else {
          iVar3 = (**(code **)(param_1 + 100))(param_1,5,0);
        }
        if (iVar3 < 0) {
          return 0xffffffff;
        }
      }
      else {
        if ((uVar10 & 1) != 0) {
          uVar6 = (int)psVar5 + 7U & 3;
          uVar7 = (uint)(psVar5 + 2) & 3;
          in_t0 = (*(int *)(((int)psVar5 + 7U) - uVar6) << (3 - uVar6) * 8 |
                  in_t0 & 0xffffffffU >> (uVar6 + 1) * 8) & -1 << (4 - uVar7) * 8 |
                  *(uint *)((int)(psVar5 + 2) - uVar7) >> uVar7 * 8;
          sVar1 = psVar5[4];
          uVar6 = param_1 + 0x43U & 3;
          puVar8 = (uint *)((param_1 + 0x43U) - uVar6);
          *puVar8 = *puVar8 & -1 << (uVar6 + 1) * 8 | in_t0 >> (3 - uVar6) * 8;
          uVar6 = param_1 + 0x40U & 3;
          puVar8 = (uint *)((param_1 + 0x40U) - uVar6);
          *puVar8 = *puVar8 & 0xffffffffU >> (4 - uVar6) * 8 | in_t0 << uVar6 * 8;
          *(short *)(param_1 + 0x44) = sVar1;
          puVar8 = (uint *)(psVar5 + 6);
          bVar2 = true;
        }
        if ((uVar10 & 2) != 0) {
          in_t0 = *puVar8;
          uVar6 = puVar8[1];
          uVar7 = puVar8[2];
          *(uint *)(param_1 + 0x48) = in_t0;
          *(uint *)(param_1 + 0x4c) = uVar6;
          *(uint *)(param_1 + 0x50) = uVar7;
          puVar8 = puVar8 + 3;
          bVar2 = true;
        }
        if ((uVar10 & 8) != 0) {
          *(int *)(param_1 + 0x48) = *(int *)(param_1 + 0x48) + (int)(short)(ushort)*puVar8;
          *(int *)(param_1 + 0x4c) =
               *(int *)(param_1 + 0x4c) + (int)(short)*(ushort *)((int)puVar8 + 2);
          puVar9 = puVar8 + 1;
          bVar2 = true;
          puVar8 = puVar8 + 2;
          *(int *)(param_1 + 0x50) = *(int *)(param_1 + 0x50) + (int)(short)(ushort)*puVar9;
        }
        if ((uVar10 & 0x10) != 0) {
          do {
            uVar6 = *puVar8;
            uVar4 = FUN_8001b36c(*(undefined4 *)(param_1 + 0x58),
                                 *(short *)(*(int *)(param_1 + 0x30) + 0x2a) +
                                 *(ushort *)((int)puVar8 + 2));
            puVar8 = puVar8 + 1;
            *(undefined4 *)(*(int *)(param_1 + 0x30) + ((ushort)uVar6 & 0x7fff) * 4 + 0x2c) = uVar4;
          } while (-1 < (int)((uint)(ushort)uVar6 << 0x10));
        }
        puVar9 = puVar8;
        if ((uVar10 & 0x20) != 0) {
          puVar9 = puVar8 + 2;
          bVar2 = true;
          puVar11 = puVar8;
        }
        if ((uVar10 & 0x40) != 0) {
          *(uint **)(*(int *)(param_1 + 0x30) + 8) = puVar9 + 1;
          puVar9 = puVar9 + *puVar9 * 2 + 1;
        }
        *(uint **)(param_1 + 0x60) = puVar9;
      }
    } while (**(ushort **)(param_1 + 0x60) <= (ushort)(param_2 - *(short *)(param_1 + 0x46)));
    if (!bVar2) {
      return 0;
    }
    FUN_8001d708(param_1);
    if (puVar11 != (uint *)0x0) {
      FUN_80043864(param_1 + 0x10,puVar11,param_1 + 0x10);
      *(ushort *)(param_1 + 0x22) = (ushort)*puVar11;
    }
  }
  return 0;
}

/* --- SLUS_005.10 FUN_8001fc38  (from analysis/SLUS_005.10/decomp/8001fc38.c) --- */
// addr: 0x8001fc38  name: FUN_8001fc38

void FUN_8001fc38(uint *param_1,undefined2 param_2)

{
  int iVar1;
  uint *puVar2;
  
  do {
    puVar2 = (uint *)param_1[0xd];
    if ((((*param_1 & 4) == 0) && (iVar1 = FUN_8001f9cc(param_1,param_2), -1 < iVar1)) &&
       (param_1[0xe] != 0)) {
      FUN_8001fc38(param_1[0xe],param_2);
    }
    param_1 = puVar2;
  } while (puVar2 != (uint *)0x0);
  return;
}

/* --- SLUS_005.10 FUN_80020540  (from analysis/SLUS_005.10/decomp/80020540.c) --- */
// addr: 0x80020540  name: FUN_80020540

void FUN_80020540(uint *param_1)

{
  if (param_1[0x1a] != 0) {
    FUN_8001bddc();
  }
  if ((*param_1 & 8) != 0) {
    FUN_8003e2c4(param_1[0x1c]);
  }
  FUN_800204dc(param_1);
  return;
}

/* --- SLUS_005.10 FUN_8001de08  (from analysis/SLUS_005.10/decomp/8001de08.c) --- */
// addr: 0x8001de08  name: FUN_8001de08

void FUN_8001de08(uint *param_1)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  MATRIX *m2;
  MATRIX local_50;
  MATRIX local_30;
  
  if ((*param_1 & 2) == 0) {
    iVar1 = FUN_8001db54(param_1 + 9,param_1[0x15]);
    m2 = &local_50;
    if ((iVar1 != 0) &&
       (CompMatrixLV((MATRIX *)&DAT_8006f680,(MATRIX *)(param_1 + 4),m2), local_50.t[2] < 0x400000))
    {
      if ((*param_1 & 0x10) != 0) {
        if ((*param_1 & 0x400) == 0) {
          if (*(short *)((int)param_1 + 0x22) == 0) {
            local_50.m[0][0] = (short)DAT_8006f660;
            local_50.m[0][1] = DAT_8006f660._2_2_;
            local_50.m[0][2] = (short)DAT_8006f664;
            local_50.m[1][0] = DAT_8006f664._2_2_;
            local_50.m[1][1] = (short)DAT_8006f668;
            local_50.m[1][2] = DAT_8006f668._2_2_;
            local_50.m[2][0] = (short)DAT_8006f66c;
            local_50.m[2][1] = DAT_8006f66c._2_2_;
            local_50.m[2][2] = DAT_8006f670;
          }
          else {
            FUN_80016e64(m2);
          }
        }
        else {
          local_30.m[0]._0_4_ = param_1[4];
          local_30.m._4_4_ = param_1[5];
          local_30.m[1]._2_4_ = param_1[6];
          local_30.m[2]._0_4_ = param_1[7];
          local_30.m[2][2] = (short)param_1[8];
          local_30.t[0] = local_50.t[0];
          local_30.t[1] = local_50.t[1];
          local_30.t[2] = local_50.t[2];
          m2 = &local_30;
        }
      }
      uVar2 = 0x40;
      if ((*param_1 & 0x2000) != 0) {
        uVar2 = param_1[0x12];
        if ((int)uVar2 < 0) {
          uVar2 = uVar2 + 0xffff;
        }
        uVar3 = param_1[0x14];
        if ((int)uVar3 < 0) {
          uVar3 = uVar3 + 0xffff;
        }
        uVar2 = (*(ushort *)
                  ((&DAT_800911a0)
                   [((uint)((int)uVar2 >> 0x10) >> 6) * 0x20 + ((uint)((int)uVar3 >> 0x10) >> 6)] +
                  ((int)uVar3 >> 0x10 & 0x3fU) * 2 + ((int)uVar2 >> 0x10 & 0x3fU) * 0x80) & 0xf800)
                >> 8;
      }
      SetBackColor(uVar2,uVar2,uVar2);
      if ((param_1[0x1b] == 0) || (local_50.t[2] <= (int)param_1[0x1b])) {
        if (param_1[0xc] != 0) {
          FUN_8001be5c(param_1[0xc],m2,uRam0000060c);
        }
        if (param_1[0xe] != 0) {
          FUN_8001dcc8(param_1[0xe],&local_50);
        }
      }
      else if (param_1[0x1a] != 0) {
        if ((*param_1 & 0x1010) == 0x1000) {
          if ((*param_1 & 0x400) == 0) {
            if (*(short *)((int)param_1 + 0x22) == 0) {
              local_50.m[0][0] = (short)DAT_8006f660;
              local_50.m[0][1] = DAT_8006f660._2_2_;
              local_50.m[0][2] = (short)DAT_8006f664;
              local_50.m[1][0] = DAT_8006f664._2_2_;
              local_50.m[1][1] = (short)DAT_8006f668;
              local_50.m[1][2] = DAT_8006f668._2_2_;
              local_50.m[2][0] = (short)DAT_8006f66c;
              local_50.m[2][1] = DAT_8006f66c._2_2_;
              local_50.m[2][2] = DAT_8006f670;
            }
            else {
              FUN_80016e64(&local_50);
            }
          }
          else {
            local_50.m[0][0] = 0x1000;
            local_50.m[0][1] = 0;
            local_50.m[0][2] = 0;
            local_50.m[1][0] = 0;
            local_50.m[1][1] = 0x1000;
            local_50.m[1][2] = 0;
            local_50.m[2][0] = 0;
            local_50.m[2][1] = 0;
            local_50.m[2][2] = 0x1000;
          }
        }
        FUN_8001be5c(param_1[0x1a],m2,uRam0000060c);
      }
      if ((*param_1 & 8) != 0) {
        if ((*param_1 & 0x200) == 0) {
          FUN_8003e2fc(param_1);
        }
        FUN_8003e520(param_1[0x1c]);
      }
    }
  }
  return;
}

#endif  /* GHIDRA REF */
