/* match_score.c -- compute and format the post-match score line.
 *
 * Source: SLUS_005.10  FUN_800136c4.
 *
 * Computes a final score for the just-finished match and sprintf's
 * it onto the end of the result-screen string.
 *
 * Score formula:
 *   timeFactor = min(g_matchElapsedTicks, vehicle.weight * 300
 *                                          + g_quest * 0xa8c
 *                                          + vehicle.skill * 600)
 *   score = (g_matchMode == 0)  // quest mode
 *           ? (timeFactor * 0x55) / g_matchElapsedTicks   // /128 base
 *             + (cheats_enabled ? 0xf : 0)
 *           : (timeFactor * 100) / g_matchElapsedTicks    // %  base
 *
 * Then appends the formatted line:
 *   "<minutes>:<seconds>  <vehicle.weight>:<vehicle.skill>  <quest>"
 * via sprintf with format DAT_80010084.
 *
 * Vehicle struct fields used:
 *   +0xba  u8  weight
 *   +0xbb  u8  skill
 *
 * Promotes 2 more Vehicle fields. Pass 3 should add these to structs.h.
 *
 * MED-HIGH confidence.
 */
#include <stdint.h>

extern int  Util_StrLen(const char *s);   /* FUN_80052544 */
extern int  sprintf(char *dst, const char *fmt, ...);
extern char DAT_80010084[];      /* "%d:%02d  %d:%d  %d" format string */
extern int8_t  cRam00000015;     /* g_matchMode */
extern int8_t  cRam0000067c;     /* g_currentQuest */
extern int32_t iRam0000000c;     /* g_matchElapsedTicks */
extern int32_t iRam00000620;     /* g_cheatsActive flag */

void MatchScore_AppendLine(char *resultStr, int vehicle)
{
    uint8_t weight = *(uint8_t *)(vehicle + 0xba);
    uint8_t skill  = *(uint8_t *)(vehicle + 0xbb);
    int     elapsed = iRam0000000c;
    int     cap     = (int)weight * 300
                    + (int)cRam0000067c * 0xa8c
                    + (int)skill  * 600;
    int     timeFactor = (cap < elapsed) ? cap : elapsed;

    int score;
    if (cRam00000015 == 0) {
        score = (timeFactor * 0x55) / elapsed;
        if (iRam00000620 != 0) score += 0xf;
    } else {
        score = (timeFactor * 100) / elapsed;
    }
    (void)score;

    int len = Util_StrLen(resultStr);
    int minutes = elapsed / 0xe10;
    int seconds = (elapsed / 0x3c) - minutes * 0x3c;
    sprintf(resultStr + len, DAT_80010084,
            minutes, seconds, (uint32_t)weight, (uint32_t)skill, (int)cRam0000067c);
    /* The original continues appending more fields based on g_matchMode --
     * pass 3 finishes the tail formatting. */
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800136c4  (from analysis/SLUS_005.10/decomp/800136c4.c) --- */
// addr: 0x800136c4  name: FUN_800136c4

void FUN_800136c4(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  undefined *puVar5;
  uint uVar6;
  int iVar7;
  
  iVar2 = (uint)*(byte *)(param_2 + 0xba) * 300 + cRam0000067c * 0xa8c +
          (uint)*(byte *)(param_2 + 0xbb) * 600;
  iVar7 = iRam0000000c;
  if (iVar2 < iRam0000000c) {
    iVar7 = iVar2;
  }
  if (cRam00000015 == '\0') {
    iVar7 = (iVar7 * 0x55) / iRam0000000c;
    if (iRam00000620 != 0) {
      iVar7 = iVar7 + 0xf;
    }
  }
  else {
    iVar7 = (iVar7 * 100) / iRam0000000c;
  }
  iVar2 = FUN_80052544(param_1);
  uVar3 = (uint)*(byte *)(param_2 + 0xba);
  iVar4 = (int)cRam0000067c;
  uVar6 = (uint)*(byte *)(param_2 + 0xbb);
  sprintf((char *)(param_1 + iVar2),&DAT_80010084,iRam0000000c / 0xe10,
          iRam0000000c / 0x3c + (iRam0000000c / 0xe10) * -0x3c,uVar3,uVar6,iVar4);
  if (cRam00000015 == '\0') {
    iVar2 = FUN_80052544(param_1);
    puVar5 = &DAT_80065468;
    if (iRam00000620 != 0) {
      puVar5 = &DAT_80065464;
    }
    sprintf((char *)(param_1 + iVar2),&DAT_800100cc,puVar5);
  }
  iVar2 = FUN_80052544(param_1);
  if ((*(char *)(param_2 + 0xd0) == '\f') || (cRam00000015 == '\x04')) {
    puVar5 = &DAT_80065344;
  }
  else {
    iVar1 = (iVar7 < 0x1a ^ 1) + (iVar7 < 0x29 ^ 1) + (iVar7 < 0x3d ^ 1) + (iVar7 < 0x4c ^ 1);
    if (0x5a < iVar7) {
      iVar1 = iVar1 + 1;
    }
    iVar1 = iVar1 * 4;
    if (5 < *(byte *)(param_2 + 0xd0)) {
      iVar1 = iVar1 + 0x18;
    }
    puVar5 = *(undefined **)((int)&PTR_s_Civilian_80056884 + iVar1);
  }
  sprintf((char *)(param_1 + iVar2),&DAT_800100e4,iVar7,puVar5,uVar3,uVar6,iVar4);
  return;
}

#endif  /* GHIDRA REF */
