/* match_slots.c -- per-slot record setters used by character select.
 *
 * Source: SLUS_005.10  FUN_80012028, FUN_80012050, FUN_80012068.
 *
 * The match-slot table at DAT_80065944 is an array of 8-byte records.
 * The setters expose offsets 0..3 of each record by name. The slot
 * size of 8 lines up with g_playerSlotIdx (also 8 entries) but the
 * layout per slot is different:
 *
 *   +0 character       (the vehicle / pilot id)
 *   +1 color           (paint / palette index)
 *   +2 secondaryA
 *   +3 secondaryB
 *
 * HIGH on layout (offset 0 vs 1..3 is unambiguous from FUN_80012050 vs
 * FUN_80012068). MED on field names -- pass 2 should cross-reference
 * with the char-select UI.
 */
#include <stdint.h>

extern uint8_t DAT_80065944[];  /* slot array base, 8 bytes per slot */

void MatchSlot_SetAll(int slot, uint8_t character, uint8_t color,
                      uint8_t secondaryA, uint8_t secondaryB)
{
    uint8_t *r = DAT_80065944 + slot * 8;
    r[0] = character;
    r[1] = color;
    r[2] = secondaryA;
    r[3] = secondaryB;
}

void MatchSlot_SetCharacter(int slot, uint8_t character)
{
    DAT_80065944[slot * 8] = character;
}

void MatchSlot_SetTrim(int slot, uint8_t color, uint8_t secondaryA, uint8_t secondaryB)
{
    uint8_t *r = DAT_80065944 + slot * 8;
    r[1] = color;
    r[2] = secondaryA;
    r[3] = secondaryB;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80012028  (from analysis/SLUS_005.10/decomp/80012028.c) --- */
// addr: 0x80012028  name: FUN_80012028

void FUN_80012028(int param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4,
                 undefined1 param_5)

{
  param_1 = param_1 * 8;
  (&DAT_80065944)[param_1] = param_2;
  (&DAT_80065945)[param_1] = param_3;
  (&DAT_80065946)[param_1] = param_4;
  (&DAT_80065947)[param_1] = param_5;
  return;
}

#endif  /* GHIDRA REF */
