/* object_teardown.c -- safe Heap_Free for objects that own parity-paired
 * front/back-buffer payloads.
 *
 * Source: SLUS_005.10  FUN_8001bddc.
 *
 * V8's draw-prim handle struct holds two parity-paired buffer pointers
 * at offsets +0x1c (front) and +0x20 (back). When freeing such a
 * handle, only the parity not currently being read by the renderer
 * (= 1 - g_dispBufIndex) is safe to free immediately; the other goes
 * through Buffer_DeferFree so the renderer finishes its current pass
 * first.
 *
 * After both parity slots are handled, the handle itself is freed.
 *
 * HIGH confidence: matches the canonical "free a parity-paired buffer
 * handle" idiom seen across the binary.
 */
#include <stdint.h>

extern void Heap_Free(void *p);
extern void Buffer_DeferFree(void *p);   /* FUN_800118b4 */
extern int32_t iRam00000004;             /* g_dispBufIndex */

void Object_FreeAndUnhook(void *handle)
{
    if (handle == NULL) return;
    uint8_t *h = (uint8_t *)handle;
    if (*(void **)(h + iRam00000004 * 4 + 0x1c) != NULL) {
        Buffer_DeferFree(*(void **)(h + iRam00000004 * 4 + 0x1c));
    }
    if (*(void **)(h + (1 - iRam00000004) * 4 + 0x1c) != NULL) {
        Heap_Free(*(void **)(h + (1 - iRam00000004) * 4 + 0x1c));
    }
    Heap_Free(handle);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001bddc  (from analysis/SLUS_005.10/decomp/8001bddc.c) --- */
// addr: 0x8001bddc  name: FUN_8001bddc

void FUN_8001bddc(int param_1)

{
  if (param_1 != 0) {
    if (*(int *)(param_1 + iRam00000004 * 4 + 0x1c) != 0) {
      FUN_800118b4();
    }
    if (*(int *)(param_1 + (1 - iRam00000004) * 4 + 0x1c) != 0) {
      FUN_80045088();
    }
    FUN_80045088(param_1);
  }
  return;
}

#endif  /* GHIDRA REF */
