/* object_broadcast.c -- per-object event broadcast helpers.
 *
 * Source: SLUS_005.10
 *   FUN_8002185c  -- Object_BroadcastToTree
 *   FUN_80021924  -- Object_BroadcastWorldOrTree
 *   FUN_80022c54  -- Object_AppendToScratchList
 *
 * Object_BroadcastToTree:
 *   Walks the level kd-tree (uRam000006fc) and invokes the per-object
 *   dispatch (FUN_800211a4 -- still in pass-3 backlog) on every node
 *   whose payload matches the given event.
 *
 * Object_BroadcastWorldOrTree:
 *   First tries the world list (DAT_80065a18); only on miss falls
 *   through to the tree walk. This is the *fast-path* version used by
 *   handlers that expect the event recipient to be a top-level world
 *   object.
 *
 * Object_AppendToScratchList:
 *   Push a single object payload onto the head of piRam0000076c (the
 *   per-frame scratch list). 12-byte node layout: back-link, payload,
 *   reserved.
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern void Object_DispatchTree(uintptr_t treeRoot, uint32_t event, uint32_t arg);  /* FUN_800211a4 */
extern int  Object_DispatchList(void *listHead, uint32_t event, uint32_t arg);      /* FUN_8002002c */
extern uintptr_t uRam000006fc;
extern uint8_t   DAT_80065a18[];
extern uint8_t   DAT_80065a70[];
extern int32_t **piRam0000076c;

void Object_BroadcastToTree(uint32_t event, uint32_t arg)
{
    Object_DispatchTree(uRam000006fc, event, arg);
}

void Object_BroadcastWorldOrTree(uint32_t event, uint32_t arg)
{
    if (Object_DispatchList(DAT_80065a18, event, arg) == 0) {
        Object_DispatchTree(uRam000006fc, event, arg);
    }
}

void Object_AppendToScratchList(int payload)
{
    int32_t *node = *piRam0000076c;
    *(int32_t **)((uintptr_t)node + 4) = (int32_t *)DAT_80065a70;
    piRam0000076c = (int32_t **)node;
    node[2] = payload;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8002185c  (from analysis/SLUS_005.10/decomp/8002185c.c) --- */
// addr: 0x8002185c  name: FUN_8002185c

void FUN_8002185c(undefined4 param_1,undefined4 param_2)

{
  FUN_800211a4(uRam000006fc,param_1,param_2);
  return;
}

/* --- SLUS_005.10 FUN_80021924  (from analysis/SLUS_005.10/decomp/80021924.c) --- */
// addr: 0x80021924  name: FUN_80021924

void FUN_80021924(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  
  iVar1 = FUN_8002002c(&DAT_80065a18,param_1,param_2);
  if (iVar1 == 0) {
    FUN_800211a4(uRam000006fc,param_1,param_2);
  }
  return;
}

/* --- SLUS_005.10 FUN_80022c54  (from analysis/SLUS_005.10/decomp/80022c54.c) --- */
// addr: 0x80022c54  name: FUN_80022c54

void FUN_80022c54(int param_1)

{
  int *piVar1;
  int iVar2;
  
  iVar2 = *piRam0000076c;
  *(undefined **)(iVar2 + 4) = &DAT_80065a70;
  piVar1 = piRam0000076c + 2;
  piRam0000076c = (int *)iVar2;
  *piVar1 = param_1;
  return;
}

/* --- SLUS_005.10 FUN_800211a4  (from analysis/SLUS_005.10/decomp/800211a4.c) --- */
// addr: 0x800211a4  name: FUN_800211a4

undefined4 FUN_800211a4(uint *param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  int iVar2;
  
  if (*param_1 == 0) {
    uVar1 = FUN_8002002c(param_1 + 1);
  }
  else {
    uVar1 = 0;
    if (*param_1 < 3) {
      iVar2 = FUN_800211a4(param_1[2],param_2,param_3);
      if ((iVar2 == 0) && (iVar2 = FUN_800211a4(param_1[3],param_2,param_3), iVar2 == 0)) {
        return 0;
      }
      uVar1 = 1;
    }
  }
  return uVar1;
}

/* --- SLUS_005.10 FUN_8002002c  (from analysis/SLUS_005.10/decomp/8002002c.c) --- */
// addr: 0x8002002c  name: FUN_8002002c

void FUN_8002002c(int *param_1,undefined4 param_2,undefined4 param_3)

{
  int *piVar1;
  int *piVar2;
  code *pcVar3;
  int iVar4;
  
  piVar1 = (int *)*param_1;
  piVar2 = (int *)*(int *)*param_1;
  while( true ) {
    if (piVar2 == (int *)0x0) {
      return;
    }
    pcVar3 = *(code **)(piVar1[2] + 100);
    if (pcVar3 == (code *)0x0) {
      iVar4 = 0;
    }
    else {
      iVar4 = (*pcVar3)(piVar1[2],param_2,param_3);
    }
    if (iVar4 != 0) break;
    piVar1 = piVar2;
    piVar2 = (int *)*piVar2;
  }
  return;
}

#endif  /* GHIDRA REF */
