/* object_post_update.c -- "fast insert" pool helpers + projectile post-tick.
 *
 * Source: SLUS_005.10
 *   FUN_8001fe50  -- ObjList_FastInsert
 *   FUN_80020744  -- Object_RegisterPostUpdate
 *   FUN_8003eab0  -- Projectile_GravityTick (universal callback for the
 *                    XOBF-spawned dropped projectiles across DLLs).
 *
 * ObjList_FastInsert: O(1) head insert into the chain rooted at
 * `listHead`, pulling a free node from the global scratch pool
 * piRam0000076c.
 *
 * Object_RegisterPostUpdate: set the "back-buf pending" bit (0x80)
 * on the object's flags and link it into the back-buf list at
 * DAT_80065a60. Called by every projectile spawner after the new
 * object is configured.
 *
 * Projectile_GravityTick (FUN_8003eab0): the universal "I'm a
 * gravity-affected projectile" callback used by every non-AI
 * projectile across DLLs. Each tick:
 *   1. integrate position by velocity (no scale -- already in world units)
 *   2. apply rotation via Object_ApplyAngularVelocity (small-angle GTE)
 *   3. apply gravity to vy (+0x5a/tick)
 *   4. if below terrain at (posX, posZ), return 0 to despawn
 *
 * HIGH-MED.
 */
#include <stdint.h>

extern int32_t **piRam0000076c;
extern uint8_t  DAT_80065a70[];
extern uint8_t  DAT_80065a60[];
extern void Object_ApplyAngularVelocity(uint32_t *m, int pitchRate, int yawRate, int rollRate);  /* FUN_800439b8 */
extern int  Terrain_HeightAndProbe(int self, int *posXyz, int u1, int u2);    /* FUN_8001d748 */

/* HIGH: head-insert `payload` into `listSentinel`'s chain. */
void ObjList_FastInsert(int listSentinel, int payload)
{
    int32_t *node = *piRam0000076c;
    int32_t  scratchHead = (int32_t)(uintptr_t)node;
    *(int32_t **)(scratchHead + 4) = (int32_t *)DAT_80065a70;
    piRam0000076c = (int32_t **)node;
    node[2] = payload;

    int32_t **chainTail = *(int32_t ***)(listSentinel + 8);
    *(int32_t ***)(listSentinel + 8) = (int32_t **)scratchHead;
    *chainTail = (int32_t *)scratchHead;
    *(int32_t **)(scratchHead + 4) = (int32_t *)chainTail;
    *(int32_t *)scratchHead       = listSentinel + 4;
}

void Object_RegisterPostUpdate(uint32_t *obj)
{
    obj[0] |= 0x80u;
    ObjList_FastInsert((int)(uintptr_t)DAT_80065a60, (int)(uintptr_t)obj);
}

/* HIGH-MED: gravity + rotation + terrain-collide per-tick. */
uint32_t Projectile_GravityTick(uint8_t *obj, int mode, int *unused)
{
    if (mode != 0) return 0xffffffffu;

    *(int32_t *)(obj + 0x24) += *(int32_t *)(obj + 0x88);
    *(int32_t *)(obj + 0x28) += *(int32_t *)(obj + 0x8c);
    *(int32_t *)(obj + 0x2c) += *(int32_t *)(obj + 0x90);

    Object_ApplyAngularVelocity((uint32_t *)(obj + 0x10),
                                (int)*(int16_t *)(obj + 0x80),
                                (int)*(int16_t *)(obj + 0x82),
                                (int)*(int16_t *)(obj + 0x84));

    int32_t vy = *(int32_t *)(obj + 0x8c) + 0x5a;
    *(int32_t *)(obj + 0x8c) = vy;
    if (vy > 0) {
        int32_t terrainY = Terrain_HeightAndProbe((int)(intptr_t)obj, (int *)(obj + 0x24), 0, 0);
        if (*(int32_t *)(obj + 0x28) > terrainY) return 0;   /* below ground = despawn */
    }
    (void)unused;
    return 0xffffffffu;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001fe50  (from analysis/SLUS_005.10/decomp/8001fe50.c) --- */
// addr: 0x8001fe50  name: FUN_8001fe50

void FUN_8001fe50(int param_1,int param_2)

{
  int *piVar1;
  int *piVar2;
  int iVar3;
  
  piVar1 = piRam0000076c;
  iVar3 = *piRam0000076c;
  *(undefined **)(iVar3 + 4) = &DAT_80065a70;
  piVar2 = piRam0000076c + 2;
  piRam0000076c = (int *)iVar3;
  *piVar2 = param_2;
  piVar2 = *(int **)(param_1 + 8);
  *(int **)(param_1 + 8) = piVar1;
  *piVar2 = (int)piVar1;
  piVar1[1] = (int)piVar2;
  *piVar1 = param_1 + 4;
  return;
}

/* --- SLUS_005.10 FUN_80020744  (from analysis/SLUS_005.10/decomp/80020744.c) --- */
// addr: 0x80020744  name: FUN_80020744

void FUN_80020744(uint *param_1)

{
  *param_1 = *param_1 | 0x80;
  FUN_8001fe50(&DAT_80065a60);
  return;
}

/* --- SLUS_005.10 FUN_8003eab0  (from analysis/SLUS_005.10/decomp/8003eab0.c) --- */
// addr: 0x8003eab0  name: FUN_8003eab0

undefined4 FUN_8003eab0(int param_1,int param_2,int *param_3)

{
  int iVar1;
  char cVar2;
  int iVar3;
  int local_28;
  int local_24;
  int local_20;
  
  if (param_2 == 0) {
    *(int *)(param_1 + 0x24) = *(int *)(param_1 + 0x24) + *(int *)(param_1 + 0x88);
    *(int *)(param_1 + 0x28) = *(int *)(param_1 + 0x28) + *(int *)(param_1 + 0x8c);
    *(int *)(param_1 + 0x2c) = *(int *)(param_1 + 0x2c) + *(int *)(param_1 + 0x90);
    FUN_800439b8(param_1 + 0x10,(int)*(short *)(param_1 + 0x80),(int)*(short *)(param_1 + 0x82),
                 (int)*(short *)(param_1 + 0x84));
    iVar3 = *(int *)(param_1 + 0x8c) + 0x5a;
    *(int *)(param_1 + 0x8c) = iVar3;
    if (0 < iVar3) {
      iVar3 = FUN_8001d748(param_1,param_1 + 0x24,0,0);
      if (*(int *)(param_1 + 0x28) <= iVar3) {
        return 0;
      }
      *(int *)(param_1 + 0x28) = iVar3;
      cVar2 = *(char *)(param_1 + 0x87) + -1;
      *(char *)(param_1 + 0x87) = cVar2;
      *(int *)(param_1 + 0x8c) = -*(int *)(param_1 + 0x8c) / 2;
      if (cVar2 == '\0') {
        FUN_800205f8(param_1);
        return 0xffffffff;
      }
    }
  }
  else {
    if (param_2 != 3) {
      return 0;
    }
    iVar3 = *param_3;
    if (*(char *)(iVar3 + 4) != '\x02') {
      return 0;
    }
    FUN_8001f5a0(param_1,param_3);
    iVar1 = *(int *)(param_1 + 0x88) * (int)(short)param_3[8] +
            *(int *)(param_1 + 0x8c) * (int)*(short *)((int)param_3 + 0x22) +
            *(int *)(param_1 + 0x90) * (int)(short)param_3[9];
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0x7ff;
    }
    iVar1 = iVar1 >> 0xb;
    if (-1 < iVar1) {
      return 0;
    }
    local_28 = *(int *)(param_1 + 0x88) << 7;
    local_24 = *(int *)(param_1 + 0x8c) << 7;
    local_20 = *(int *)(param_1 + 0x90) << 7;
    FUN_800176f8(iVar3,&local_28,param_1 + 0x24);
    if (*(short *)(iVar3 + 6) < 0) {
      FUN_80012068(~(int)*(short *)(iVar3 + 6),0xff,2,0x80);
    }
    iVar3 = iVar1 * (short)param_3[8];
    if (iVar3 < 0) {
      iVar3 = iVar3 + 0xfff;
    }
    *(int *)(param_1 + 0x88) = *(int *)(param_1 + 0x88) - (iVar3 >> 0xc);
    iVar3 = iVar1 * *(short *)((int)param_3 + 0x22);
    if (iVar3 < 0) {
      iVar3 = iVar3 + 0xfff;
    }
    *(int *)(param_1 + 0x8c) = *(int *)(param_1 + 0x8c) - (iVar3 >> 0xc);
    iVar1 = iVar1 * (short)param_3[9];
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0xfff;
    }
    *(int *)(param_1 + 0x90) = *(int *)(param_1 + 0x90) - (iVar1 >> 0xc);
  }
  return 0;
}

/* --- SLUS_005.10 FUN_800439b8  (from analysis/SLUS_005.10/decomp/800439b8.c) --- */
// addr: 0x800439b8  name: FUN_800439b8

void FUN_800439b8(undefined4 *param_1,int param_2,int param_3,int param_4)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  
  gte_ldR11R12(*param_1);
  gte_ldR13R21(param_1[1]);
  gte_ldR22R23(param_1[2]);
  gte_ldR31R32(param_1[3]);
  gte_ldR33(param_1[4]);
  gte_ldIR1(0x1000);
  gte_ldIR2(param_4);
  gte_ldIR3(-param_3);
  gte_rtir_b();
  uVar1 = gte_stIR1();
  uVar2 = gte_stIR2();
  uVar3 = gte_stIR3();
  gte_ldsv_(-param_4,0x1000,param_2);
  gte_rtir_b();
  *(short *)param_1 = (short)uVar1;
  *(short *)((int)param_1 + 6) = (short)uVar2;
  *(short *)(param_1 + 3) = (short)uVar3;
  uVar1 = gte_stIR1();
  uVar2 = gte_stIR2();
  uVar3 = gte_stIR3();
  gte_ldsv_(param_3,-param_2,0x1000);
  gte_rtir_b();
  *(short *)((int)param_1 + 2) = (short)uVar1;
  *(short *)(param_1 + 2) = (short)uVar2;
  *(short *)((int)param_1 + 0xe) = (short)uVar3;
  uVar1 = gte_stIR1();
  uVar2 = gte_stIR2();
  uVar3 = gte_stIR3();
  *(short *)(param_1 + 1) = (short)uVar1;
  *(short *)((int)param_1 + 10) = (short)uVar2;
  *(short *)(param_1 + 4) = (short)uVar3;
  return;
}

/* --- SLUS_005.10 FUN_8001d748  (from analysis/SLUS_005.10/decomp/8001d748.c) --- */
// addr: 0x8001d748  name: FUN_8001d748

int FUN_8001d748(int param_1,undefined4 *param_2,SVECTOR *param_3,undefined4 *param_4)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  
  iVar1 = FUN_80025400(*param_2,param_2[2]);
  if ((*(int *)(param_1 + 0x74) == 0) ||
     ((iVar2 = FUN_8001f51c(*(int *)(param_1 + 0x74),iVar1,param_2,param_3), iVar2 == 0 &&
      ((*(int *)(param_1 + 0x78) == 0 ||
       (iVar2 = FUN_8001f51c(*(int *)(param_1 + 0x78),iVar1,param_2,param_3), iVar2 == 0)))))) {
    if (param_3 != (SVECTOR *)0x0) {
      FUN_80025648(*param_2,param_2[2],param_3);
      VectorNormalSS(param_3,param_3);
    }
    if (param_4 != (undefined4 *)0x0) {
      uVar3 = FUN_800255f4(*param_2,param_2[2]);
      *param_4 = uVar3;
    }
  }
  else {
    iVar1 = iVar2;
    if (param_4 != (undefined4 *)0x0) {
      *param_4 = 0;
    }
  }
  return iVar1;
}

#endif  /* GHIDRA REF */
