/* object_state.c -- object state-change broadcast helpers.
 *
 * Source: SLUS_005.10
 *   FUN_80024718 -- Object_SetState
 *   FUN_80021888 -- Object_BroadcastEventWorld
 *
 * Object_SetState routes through FUN_80024520 (still in pass-3 backlog)
 * which is the 6-arg state-transition primitive. The trailing args
 * (uRam000006ec, 0, 0, 0x800) are: { effect pool, flag1=0, flag2=0,
 * effect mask 0x800 (= "destroyed -> spawn debris cloud") }.
 *
 * Object_BroadcastEventWorld is the world-or-tree event broadcaster
 * with arg2=0 baked in (used by the simpler event dispatchers in the
 * level DLLs).
 *
 * HIGH.
 */
#include <stdint.h>

extern void Object_TransitionState(int obj, int state, uintptr_t effectPool,
                                   int flag1, int flag2, int effectMask);  /* FUN_80024520 */
extern int  Object_DispatchList(void *listHead, uint32_t event, uint32_t arg);  /* FUN_80020000 */
extern void Object_DispatchTree2(uintptr_t treeRoot, uint32_t event, uint32_t arg);  /* FUN_8002111c */

extern uintptr_t uRam000006ec;
extern uintptr_t uRam000006fc;
extern uint8_t   DAT_80065a18[];

void Object_SetState(int obj, int newState)
{
    Object_TransitionState(obj, newState, uRam000006ec, 0, 0, 0x800);
}

void Object_BroadcastEventWorld(uint32_t event)
{
    if (Object_DispatchList(DAT_80065a18, event, 0) == 0) {
        Object_DispatchTree2(uRam000006fc, event, 0);
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80024718  (from analysis/SLUS_005.10/decomp/80024718.c) --- */
// addr: 0x80024718  name: FUN_80024718

void FUN_80024718(undefined4 param_1,undefined4 param_2)

{
  FUN_80024520(param_1,param_2,uRam000006ec,0,0,0x800);
  return;
}

/* --- SLUS_005.10 FUN_80021888  (from analysis/SLUS_005.10/decomp/80021888.c) --- */
// addr: 0x80021888  name: FUN_80021888

void FUN_80021888(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = FUN_80020000(&DAT_80065a18,param_1,0);
  if (iVar1 == 0) {
    FUN_8002111c(uRam000006fc,param_1,0);
  }
  return;
}

/* --- SLUS_005.10 FUN_80024520  (from analysis/SLUS_005.10/decomp/80024520.c) --- */
// addr: 0x80024520  name: FUN_80024520

void FUN_80024520(short *param_1,undefined4 param_2,int param_3,int param_4,int param_5,int param_6)

{
  ushort uVar1;
  undefined2 uVar2;
  
  param_6 = param_6 >> 1;
  uVar2 = (undefined2)param_2;
  if ((int)param_1[1] < param_5 + param_6) {
    if ((int)*param_1 < param_4 + param_6) {
      uVar1 = *(ushort *)(param_3 + 2);
      if ((uVar1 == 0) || ((uVar1 & 0x8000) != 0)) {
        *(undefined2 *)(param_3 + 2) = uVar2;
      }
      else {
        FUN_80024520(param_1,param_2,param_3 + (uint)uVar1 * 10,param_4,param_5,param_6);
      }
    }
    if (param_4 + param_6 < (int)*param_1 + (int)param_1[2]) {
      uVar1 = *(ushort *)(param_3 + 4);
      if ((uVar1 == 0) || ((uVar1 & 0x8000) != 0)) {
        *(undefined2 *)(param_3 + 4) = uVar2;
      }
      else {
        FUN_80024520(param_1,param_2,param_3 + (uint)uVar1 * 10,param_4 + param_6,param_5,param_6);
      }
    }
  }
  if (param_5 + param_6 < (int)param_1[1] + (int)param_1[3]) {
    if ((int)*param_1 < param_4 + param_6) {
      uVar1 = *(ushort *)(param_3 + 6);
      if ((uVar1 == 0) || ((uVar1 & 0x8000) != 0)) {
        *(undefined2 *)(param_3 + 6) = uVar2;
      }
      else {
        FUN_80024520(param_1,param_2,param_3 + (uint)uVar1 * 10,param_4,param_5 + param_6,param_6);
      }
    }
    if (param_4 + param_6 < (int)*param_1 + (int)param_1[2]) {
      uVar1 = *(ushort *)(param_3 + 8);
      if ((uVar1 == 0) || ((uVar1 & 0x8000) != 0)) {
        *(undefined2 *)(param_3 + 8) = uVar2;
      }
      else {
        FUN_80024520(param_1,param_2,param_3 + (uint)uVar1 * 10,param_4 + param_6,param_5 + param_6,
                     param_6);
      }
    }
  }
  return;
}

/* --- SLUS_005.10 FUN_80020000  (from analysis/SLUS_005.10/decomp/80020000.c) --- */
// addr: 0x80020000  name: FUN_80020000

undefined4 FUN_80020000(void)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_8001ff58();
  uVar2 = 0;
  if (iVar1 != 0) {
    uVar2 = *(undefined4 *)(iVar1 + 8);
  }
  return uVar2;
}

/* --- SLUS_005.10 FUN_8002111c  (from analysis/SLUS_005.10/decomp/8002111c.c) --- */
// addr: 0x8002111c  name: FUN_8002111c

void FUN_8002111c(uint *param_1,undefined4 param_2,undefined4 param_3)

{
  int iVar1;
  
  while( true ) {
    if (*param_1 == 0) {
      FUN_80020000(param_1 + 1,param_2,param_3);
      return;
    }
    if (2 < *param_1) break;
    iVar1 = FUN_8002111c(param_1[2],param_2,param_3);
    if (iVar1 != 0) {
      return;
    }
    param_1 = (uint *)param_1[3];
  }
  return;
}

#endif  /* GHIDRA REF */
