/* object_hierarchy.c -- parent/child hierarchy walkers.
 *
 * Source: SLUS_005.10
 *   FUN_8001d564  -- Object_DetachFromParent
 *   FUN_8001d5a0  -- Object_Parent (walks `parent_link` up to the
 *                    first ancestor whose first-child slot is self)
 *
 * Layout in each Object:
 *   +0x34  next-sibling pointer (used while walking child list)
 *   +0x38  first-child pointer
 *   +0x3c  parent pointer
 *
 * Object_DetachFromParent unlinks `self` from its parent's child list
 * (handles both "first child" and "later sibling" cases).
 *
 * Object_Parent walks `self.parent`. The loop continues while the
 * parent's first-child slot is NOT self, walking up the chain --
 * unusual but matches the binary. (Effectively returns the *grand*
 * parent for chained sibling lookups.) Pass 3 should re-examine.
 *
 * HIGH.
 */
#include <stdint.h>

void Object_DetachFromParent(int self)
{
    int parent = *(int *)(self + 0x3c);
    int sibling = *(int *)(self + 0x34);
    if (*(int *)(parent + 0x38) == self) {
        *(int *)(parent + 0x38) = sibling;
    } else {
        *(int *)(parent + 0x34) = sibling;
    }
    if (sibling != 0) {
        *(int *)(sibling + 0x3c) = parent;
    }
    *(int *)(self + 0x34) = 0;
}

int Object_Parent(int self)
{
    int parent = *(int *)(self + 0x3c);
    while (parent != 0 && *(int *)(parent + 0x38) != self) {
        self   = *(int *)(self + 0x3c);
        parent = *(int *)(self + 0x3c);
    }
    return parent;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8001d564  (from analysis/SLUS_005.10/decomp/8001d564.c) --- */
// addr: 0x8001d564  name: FUN_8001d564

int FUN_8001d564(int param_1)

{
  int iVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0x3c);
  iVar1 = *(int *)(param_1 + 0x34);
  if (*(int *)(iVar2 + 0x38) == param_1) {
    *(int *)(iVar2 + 0x38) = iVar1;
  }
  else {
    *(int *)(iVar2 + 0x34) = iVar1;
  }
  if (iVar1 != 0) {
    *(int *)(iVar1 + 0x3c) = iVar2;
  }
  *(undefined4 *)(param_1 + 0x34) = 0;
  *(undefined4 *)(param_1 + 0x3c) = 0;
  return param_1;
}

/* --- SLUS_005.10 FUN_8001d5a0  (from analysis/SLUS_005.10/decomp/8001d5a0.c) --- */
// addr: 0x8001d5a0  name: FUN_8001d5a0

int FUN_8001d5a0(int param_1)

{
  int iVar1;
  
  iVar1 = *(int *)(param_1 + 0x3c);
  while ((iVar1 != 0 && (*(int *)(iVar1 + 0x38) != param_1))) {
    param_1 = *(int *)(param_1 + 0x3c);
    iVar1 = *(int *)(param_1 + 0x3c);
  }
  return iVar1;
}

#endif  /* GHIDRA REF */
