/* objlist_count.c -- count list length.
 *
 * Source: SLUS_005.10  FUN_800166dc.
 *
 * Walks a singly-linked list (next-pointer at +0) starting at
 * `*headPtr`, returns the count.
 *
 * HIGH.
 */
#include <stdint.h>

int ObjList_Length(int **headPtr)
{
    int count = 0;
    int *node = (int *)*headPtr;
    while (node != NULL) {
        count++;
        node = (int *)*node;
    }
    return count;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800166dc  (from analysis/SLUS_005.10/decomp/800166dc.c) --- */
// addr: 0x800166dc  name: FUN_800166dc

int FUN_800166dc(undefined4 *param_1)

{
  int *piVar1;
  int iVar2;
  
  iVar2 = 0;
  for (piVar1 = *(int **)*param_1; piVar1 != (int *)0x0; piVar1 = (int *)*piVar1) {
    iVar2 = iVar2 + 1;
  }
  return iVar2;
}

#endif  /* GHIDRA REF */
