/* proximity_dispatch.c -- broadcast event to objects within a Chebyshev radius.
 *
 * Source: SLUS_005.10  FUN_800422d8.
 *
 * Walks the per-frame object chain at piRam000008c4. For each node,
 * computes the Chebyshev (max) distance between (param_1, param_2)
 * and the node's (+3, +5) position fields. If that distance is less
 * than (+6 + param_3) (the per-object radius + caller's tolerance),
 * dispatches to FUN_800420f4 (the per-frame audio / trigger handler).
 *
 * Used for proximity-based audio cues (engine echo, wind tunnel, etc).
 *
 * HIGH.
 */
#include <stdint.h>

extern int FUN_80025400(int x, int z);
extern uintptr_t DAT_800911a0[];
extern uintptr_t *piRam000008c4;
void FUN_800420f4(int param_1);

void Proximity_DispatchInRange(int posX, int posZ, int tolerance)
{
    uintptr_t *node = (uintptr_t *)piRam000008c4[0];
    uintptr_t *prev = piRam000008c4;
    while (node != NULL) {
        int32_t dx = (int32_t)prev[3] - posX;
        int32_t dz = (int32_t)prev[5] - posZ;
        if (dx < 0) dx = -dx;
        if (dz < 0) dz = -dz;
        int32_t cheby = (dx > dz) ? dx : dz;
        if (cheby < (int32_t)prev[6] + tolerance) {
            FUN_800420f4((int)(uintptr_t)prev);
        }
        prev = node;
        node = (uintptr_t *)*node;
    }
}

void FUN_800420f4(int param_1)
{
    uint8_t *base = (uint8_t *)(uintptr_t)(uint32_t)param_1;
    int32_t count = *(int32_t *)(base + 0x1c);

    if (count < 0)
        return;

    for (int32_t i = 0; i <= count; i++) {
        uint8_t *slot0 = base + i * 0x10;
        uint8_t *slot1 = slot0 + 8;

        int32_t x0 = *(int32_t *)(base + 0x0c) +
                     (int16_t)*(uint16_t *)(slot0 + 0x20) * 0x100;
        int32_t z0 = *(int32_t *)(base + 0x14) +
                     (int16_t)*(uint16_t *)(slot0 + 0x24) * 0x100;
        int32_t h0 = FUN_80025400(x0, z0);
        *(uint16_t *)(slot0 + 0x22) =
            (uint16_t)((h0 - *(int32_t *)(base + 0x10)) >> 8);

        int32_t sx0 = (x0 < 0) ? (x0 + 0xffff) : x0;
        int32_t sz0 = (z0 < 0) ? (z0 + 0xffff) : z0;
        uint32_t cx0 = (uint32_t)(sx0 >> 16);
        uint32_t cz0 = (uint32_t)(sz0 >> 16);
        uintptr_t chunk0 = DAT_800911a0[((cz0 >> 6) * 0x20u) + (cx0 >> 6)];
        if (chunk0 != 0) {
            uint32_t off0 = ((cz0 & 0x3fu) << 1) + ((cx0 & 0x3fu) << 7);
            *(uint16_t *)(slot0 + 0x26) =
                (uint16_t)(((*(uint16_t *)(chunk0 + off0)) >> 11) << 2);
        }

        int32_t x1 = *(int32_t *)(base + 0x0c) +
                     (int16_t)*(uint16_t *)(slot1 + 0x20) * 0x100;
        int32_t z1 = *(int32_t *)(base + 0x14) +
                     (int16_t)*(uint16_t *)(slot1 + 0x24) * 0x100;
        int32_t h1 = FUN_80025400(x1, z1);
        *(uint16_t *)(slot1 + 0x22) =
            (uint16_t)((h1 - *(int32_t *)(base + 0x10)) >> 8);

        int32_t sx1 = (x1 < 0) ? (x1 + 0xffff) : x1;
        int32_t sz1 = (z1 < 0) ? (z1 + 0xffff) : z1;
        uint32_t cx1 = (uint32_t)(sx1 >> 16);
        uint32_t cz1 = (uint32_t)(sz1 >> 16);
        uintptr_t chunk1 = DAT_800911a0[((cz1 >> 6) * 0x20u) + (cx1 >> 6)];
        if (chunk1 != 0) {
            uint32_t off1 = ((cz1 & 0x3fu) << 1) + ((cx1 & 0x3fu) << 7);
            *(uint16_t *)(slot1 + 0x26) =
                (uint16_t)(((*(uint16_t *)(chunk1 + off1)) >> 11) << 2);
        }
    }
}

void FUN_800422d8(int param_1, int param_2, int param_3)
{
    Proximity_DispatchInRange(param_1, param_2, param_3);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800422d8  (from analysis/SLUS_005.10/decomp/800422d8.c) --- */
// addr: 0x800422d8  name: FUN_800422d8

void FUN_800422d8(int param_1,int param_2,int param_3)

{
  int *piVar1;
  int *piVar2;
  int *piVar3;
  int iVar4;
  int iVar5;
  
  piVar3 = (int *)*piRam000008c4;
  piVar2 = piRam000008c4;
  while (piVar1 = piVar3, piVar1 != (int *)0x0) {
    iVar4 = piVar2[5] - param_2;
    if (iVar4 < 0) {
      iVar4 = -iVar4;
    }
    iVar5 = piVar2[3] - param_1;
    if (iVar5 < 0) {
      iVar5 = -iVar5;
    }
    if (iVar4 < iVar5) {
      iVar4 = iVar5;
    }
    if (iVar4 < piVar2[6] + param_3) {
      FUN_800420f4();
    }
    piVar2 = piVar1;
    piVar3 = (int *)*piVar1;
  }
  return;
}

#endif  /* GHIDRA REF */
