/* proximity_dispatch.c -- broadcast event to objects within a Chebyshev radius.
 *
 * Source: SLUS_005.10  FUN_800422d8.
 *
 * Walks the per-frame object chain at piRam000008c4. For each node,
 * computes the Chebyshev (max) distance between (param_1, param_2)
 * and the node's (+3, +5) position fields. If that distance is less
 * than (+6 + param_3) (the per-object radius + caller's tolerance),
 * dispatches to FUN_800420f4 (the per-frame audio / trigger handler).
 *
 * Used for proximity-based audio cues (engine echo, wind tunnel, etc).
 *
 * HIGH.
 */
#include <stdint.h>

extern void Proximity_Trigger(void);   /* FUN_800420f4 */
extern int32_t **piRam000008c4;

void Proximity_DispatchInRange(int posX, int posZ, int tolerance)
{
    int32_t *node = (int32_t *)piRam000008c4[0];
    int32_t **prev = piRam000008c4;
    while (node != NULL) {
        int32_t dx = prev[3] - posX;
        int32_t dz = prev[5] - posZ;
        if (dx < 0) dx = -dx;
        if (dz < 0) dz = -dz;
        int32_t cheby = (dx > dz) ? dx : dz;
        if (cheby < (int32_t)prev[6] + tolerance) {
            Proximity_Trigger();
        }
        prev = (int32_t **)node;
        node = (int32_t *)*node;
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800422d8  (from analysis/SLUS_005.10/decomp/800422d8.c) --- */
// addr: 0x800422d8  name: FUN_800422d8

void FUN_800422d8(int param_1,int param_2,int param_3)

{
  int *piVar1;
  int *piVar2;
  int *piVar3;
  int iVar4;
  int iVar5;
  
  piVar3 = (int *)*piRam000008c4;
  piVar2 = piRam000008c4;
  while (piVar1 = piVar3, piVar1 != (int *)0x0) {
    iVar4 = piVar2[5] - param_2;
    if (iVar4 < 0) {
      iVar4 = -iVar4;
    }
    iVar5 = piVar2[3] - param_1;
    if (iVar5 < 0) {
      iVar5 = -iVar5;
    }
    if (iVar4 < iVar5) {
      iVar4 = iVar5;
    }
    if (iVar4 < piVar2[6] + param_3) {
      FUN_800420f4();
    }
    piVar2 = piVar1;
    piVar3 = (int *)*piVar1;
  }
  return;
}

#endif  /* GHIDRA REF */
