/* shell_misc.c -- tiny SHELL.DLL helpers cleaned in pass 2.
 *
 * Source: SHELL.DLL
 *   FUN_80102174  -- ShellEvent_Empty (placeholder stub).
 *   FUN_801021a0  -- ShellEvent_Empty2 (another stub).
 *   FUN_801021d4  -- Shell_WaitForStartPress -- spin-poll Pad_Tick
 *                    until the global event bitmask DAT_80065c28
 *                    crosses 2 (the "Start pressed" sentinel).
 *   FUN_8010223c  -- Shell_RealignCursor (calls Layout_AlignNext on
 *                    DAT_8010043c, a fixed UI screen-coord pair).
 *   FUN_8010754c  -- ShellEvent_Empty3 (third empty placeholder).
 *
 * The empty functions are deliberately empty in the original -- V8
 * uses a "function table of event handlers" pattern, and the empties
 * are no-op slots reserved for events that didn't ship with handlers.
 *
 * HIGH confidence on the no-ops, MED on the spin (`DAT_80065c28 < 2`
 * threshold meaning).
 */
#include <stdint.h>

extern void  Pad_Tick(void);                  /* FUN_800120d4 (main EXE) */
extern void  Layout_AlignNext(void *xy, int mode);   /* FUN_8001a0ac */
extern int16_t DAT_80065c28;
extern int16_t DAT_8010043c[2];

void ShellEvent_Empty (void) { /* no-op slot */ }
void ShellEvent_Empty2(void) { /* no-op slot */ }
void ShellEvent_Empty3(void) { /* no-op slot */ }
void ShellEvent_Empty4(void) { /* no-op slot @ 0x80101d6c */ }

void Shell_WaitForStartPress(void)
{
    Pad_Tick();
    while (DAT_80065c28 < 2) {
        Pad_Tick();
    }
}

void Shell_RealignCursor(void)
{
    Layout_AlignNext(DAT_8010043c, 0);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80102174  (from analysis/dll/SHELL/decomp/80102174.c) --- */
// addr: 0x80102174  name: FUN_80102174

void FUN_80102174(void)

{
  return;
}

/* --- ? FUN_801021a0  (from analysis/dll/SHELL/decomp/801021a0.c) --- */
// addr: 0x801021a0  name: FUN_801021a0

void FUN_801021a0(void)

{
  return;
}

/* --- ? FUN_801021d4  (from analysis/dll/SHELL/decomp/801021d4.c) --- */
// addr: 0x801021d4  name: FUN_801021d4

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801021d4(void)

{
  Pad_Tick/*0x800120d4*/();
  while (_DAT_80065c28 < 2) {
    Pad_Tick/*0x800120d4*/();
  }
  return;
}

/* --- ? FUN_8010223c  (from analysis/dll/SHELL/decomp/8010223c.c) --- */
// addr: 0x8010223c  name: FUN_8010223c

void FUN_8010223c(void)

{
  FUN_8001a0ac/*0x8001a0ac*/(&DAT_8010043c,0);
  return;
}

/* --- ? FUN_8010754c  (from analysis/dll/SHELL/decomp/8010754c.c) --- */
// addr: 0x8010754c  name: FUN_8010754c

void FUN_8010754c(void)

{
  return;
}

#endif  /* GHIDRA REF */
