/* splash.c -- boot splash + fatal-error trap.
 *
 * Source: SLUS_005.10
 *   FUN_80015164 -- Splash_InitDisplay
 *   FUN_80015288 -- Splash_DrawLine
 *   FUN_80015368 -- Stream_FatalOom (and friends)
 *
 * Splash_InitDisplay sets up the studio-logo display: low-res 320x240
 * (or 640x480 hi-res when `hires` is non-zero), loads `Misc\Kong.fnt`,
 * allocates an atlas, and clears the screen via SetDefDispEnv /
 * SetDefDrawEnv with dfe=1 (clear-on-flip), tpage=0x20.
 *
 * Splash_DrawLine appends a line of text to the splash screen, tracking
 * line height in iRam00000688/0x68c/0x690 and wrapping at iRam00000694.
 *
 * Stream_FatalOom (FUN_80015368) is the "Out of SPU RAM" / general
 * fatal trap: it sets up the splash display and dies in an infinite
 * loop. Functions in the asset pipeline call it when they can't
 * recover.
 *
 * MED confidence: control flow is clear; field names for the per-line
 * tracker (line height, padding) are inferred.
 */
#include <stdint.h>

extern void  PutDrawEnv(void *drawEnv);
extern void  PutDispEnv(void *dispEnv);
extern void  SetDispMask(int mode);
extern void *SetDefDispEnv(void *de, int x, int y, int w, int h);
extern void *SetDefDrawEnv(void *de, int x, int y, int w, int h);
extern void *Asset_LoadFile(void);            /* FUN_80015948 */
extern uint32_t Font_AllocAtlas(void *fnt, int slot);  /* FUN_80019034 */
extern void  Iso_LatchPathArg(const char *p);          /* sets the next Iso_OpenPath name */
extern void  Splash_AlignNext(void *xy, int mode);     /* FUN_8001a0ac */

extern uint32_t uRam00000684;          /* font atlas handle */
extern int32_t  iRam00000688;          /* current Y */
extern int32_t  iRam0000068c;          /* current X */
extern int32_t  iRam00000690;          /* current line max-height */
extern int32_t  iRam00000694;          /* y limit */

typedef struct { int16_t x, y; int16_t w, h; } DRAWENV_min;
typedef struct { int16_t x, y; int16_t w, h; } DISPENV_min;

void Splash_InitDisplay(int hires)
{
    int16_t w = 0x140, h = 0xf0;
    if (hires) { w = 0x280; h = 0x1e0; }

    extern void Render_SetTexpageMode(int mode);   /* FUN_80017fd4 */
    Render_SetTexpageMode(0);

    uint32_t fnt = (uint32_t)Asset_LoadFile();    /* "Misc\\Kong.fnt" -- caller latches name */
    uRam00000684 = Font_AllocAtlas((void *)fnt, 0);

    uint8_t  disp[0x14];
    uint8_t  draw[0x5c];
    SetDefDispEnv(disp, 0, 0, w, h);
    SetDefDrawEnv(draw, 0, 0, w, h);
    *(int8_t *)(draw + 5) = 1;          /* dfe (clear-on-display-flip) */
    *(int16_t *)(draw + 6) = 0x20;      /* tpage */
    PutDrawEnv(draw);
    PutDispEnv(disp);

    int16_t xy[2] = { 0, 0 };
    Splash_AlignNext(&xy, 0);
    iRam00000694  = h - 0x20;
    SetDispMask(1);
    iRam0000068c  = 0x20;
    iRam00000688  = 0x20;
    iRam00000690  = 0;
}

extern void Font_DrawText(void *font, const char *s, int x, int y);   /* FUN_80019960 */
extern int  Font_MeasureText(void *font, const char *s);              /* FUN_80019138 */
extern uint8_t *piRam00000684;

void Splash_DrawLine(const char *s)
{
    Font_DrawText(piRam00000684, s, iRam00000688, iRam0000068c);
    int line = Font_MeasureText(piRam00000684, s);
    if (line < iRam00000690) line = iRam00000690;
    iRam0000068c += *(uint8_t *)(*(uintptr_t *)piRam00000684 + 6);  /* line height */
    iRam00000690 = line;
    if (iRam0000068c + *(uint8_t *)(*(uintptr_t *)piRam00000684 + 6) > iRam00000694) {
        iRam0000068c = 0x20;
        iRam00000690 = 0;
        iRam00000688 += 8 + line;
    }
}

/* Stream_FatalOom: print the error and freeze. The "do{}while(true)"
 * preserves the binary's intentional spin -- in a release build the
 * user sees the message and the system is hung. */
void Stream_FatalOom(const char *msg)
{
    Splash_InitDisplay(0);
    Splash_DrawLine(msg);
    for (;;) { /* hang */ }
}

/* FUN_80015368: PSX address alias for Stream_FatalOom.
 * Called directly by cd_stream.c with a PSX string pointer (uint32_t).
 * MIPS: jal FUN_80015164(0), jal FUN_80015288(param_1), j $self.
 * HIGH: exact translation -- same control flow as Stream_FatalOom above. */
void FUN_80015368(uint32_t param_1)
{
    Splash_InitDisplay(0);
    Splash_DrawLine((const char *)(uintptr_t)param_1);
    for (;;) {}
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80015164  (from analysis/SLUS_005.10/decomp/80015164.c) --- */
// addr: 0x80015164  name: FUN_80015164

void FUN_80015164(int param_1)

{
  undefined4 uVar1;
  DISPENV DStack_88;
  DRAWENV DStack_70;
  undefined2 local_10;
  undefined2 local_e;
  short local_c;
  short local_a;
  
  local_c = 0x140;
  local_10 = 0;
  local_e = 0;
  local_a = 0xf0;
  FUN_80017fd4(0);
  if (param_1 != 0) {
    local_c = 0x280;
    local_a = 0x1e0;
  }
  uVar1 = FUN_80015948("Misc\\Kong.fnt");
  uRam00000684 = FUN_80019034(uVar1,0);
  SetDefDispEnv(&DStack_88,0,0,(int)local_c,(int)local_a);
  SetDefDrawEnv(&DStack_70,0,0,(int)local_c,(int)local_a);
  DStack_70.dfe = '\x01';
  DStack_70.tpage = 0x20;
  PutDrawEnv(&DStack_70);
  PutDispEnv(&DStack_88);
  FUN_8001a0ac(&local_10,0);
  iRam00000694 = local_a + -0x20;
  SetDispMask(1);
  uRam0000068c = 0x20;
  uRam00000688 = 0x20;
  uRam00000690 = 0;
  return;
}

/* --- SLUS_005.10 FUN_80015288  (from analysis/SLUS_005.10/decomp/80015288.c) --- */
// addr: 0x80015288  name: FUN_80015288

void FUN_80015288(undefined4 param_1)

{
  int iVar1;
  int iVar2;
  
  FUN_80019960(piRam00000684,param_1,iRam00000688,iRam0000068c);
  iVar1 = iRam00000690;
  iVar2 = FUN_80019138(piRam00000684,param_1);
  if (iVar2 < iVar1) {
    iVar2 = iVar1;
  }
  iRam0000068c = iRam0000068c + (uint)*(byte *)(*piRam00000684 + 6);
  iRam00000690 = iVar2;
  if (iRam00000694 < (int)(iRam0000068c + (uint)*(byte *)(*piRam00000684 + 6))) {
    iRam0000068c = 0x20;
    iRam00000690 = 0;
    iRam00000688 = iRam00000688 + 8 + iVar2;
  }
  return;
}

/* --- SLUS_005.10 FUN_80015368  (from analysis/SLUS_005.10/decomp/80015368.c) --- */
// addr: 0x80015368  name: FUN_80015368

void FUN_80015368(uint32_t param_1)

{
  FUN_80015164(0);
  FUN_80015288(param_1);
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}

/* --- SLUS_005.10 FUN_80015948  (from analysis/SLUS_005.10/decomp/80015948.c) --- */
// addr: 0x80015948  name: FUN_80015948

undefined4 FUN_80015948(void)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_800157d4();
  if (iVar1 == 0) {
    uVar2 = 0;
  }
  else {
    uVar2 = FUN_800116f4(*(int *)(iVar1 + 0x10) + 0x7ffU & 0xfffff800);
    uVar2 = FUN_800154f4(uVar2,*(undefined4 *)(iVar1 + 0xc),*(int *)(iVar1 + 0x10) + 0x7ffU >> 0xb);
    uVar2 = FUN_80045134(uVar2,*(undefined4 *)(iVar1 + 0x10));
  }
  return uVar2;
}

/* --- SLUS_005.10 FUN_80019034  (from analysis/SLUS_005.10/decomp/80019034.c) --- */
// addr: 0x80019034  name: FUN_80019034

int * FUN_80019034(int *param_1,undefined4 param_2)

{
  int *piVar1;
  
  piVar1 = (int *)FUN_800116f4(0x14);
  FUN_800187e4((int)param_1 + *param_1,piVar1 + 2);
  *piVar1 = (int)param_1;
  *(undefined1 *)(piVar1 + 1) = 0x80;
  *(undefined1 *)((int)piVar1 + 5) = 0x80;
  *(undefined1 *)((int)piVar1 + 6) = 0x80;
  FUN_80019010(piVar1,param_2);
  return piVar1;
}

/* --- SLUS_005.10 FUN_8001a0ac  (from analysis/SLUS_005.10/decomp/8001a0ac.c) --- */
// addr: 0x8001a0ac  name: FUN_8001a0ac

void FUN_8001a0ac(undefined2 *param_1,undefined4 param_2)

{
  undefined1 auStack_18 [3];
  undefined1 local_15;
  undefined1 local_14;
  undefined1 local_13;
  undefined1 local_12;
  undefined1 local_11;
  undefined2 local_10;
  undefined2 local_e;
  undefined2 local_c;
  undefined2 local_a;
  
  local_15 = 3;
  local_11 = 0x60;
  local_14 = (undefined1)param_2;
  local_13 = (undefined1)((uint)param_2 >> 8);
  local_12 = (undefined1)((uint)param_2 >> 0x10);
  local_10 = *param_1;
  local_e = param_1[1];
  local_c = param_1[2];
  local_a = param_1[3];
  DrawPrim(auStack_18);
  return;
}

/* --- SLUS_005.10 FUN_80017fd4  (from analysis/SLUS_005.10/decomp/80017fd4.c) --- */
// addr: 0x80017fd4  name: FUN_80017fd4

void FUN_80017fd4(int param_1)

{
  int iVar1;
  
  if (param_1 != 0) {
    FUN_80017d5c();
  }
  if (iRam000006c4 != 0) {
    FUN_80017e0c();
  }
  iRam000006c4 = FUN_80017e3c(0,0,0,0,0x400,0x200);
  FUN_80017ec4(iRam000006c4,0x140);
  FUN_80017f4c(*(undefined4 *)(iRam000006c4 + 0x10),0x1e0);
  iVar1 = iRam000006c4;
  *(undefined4 *)(*(int *)(*(int *)(iRam000006c4 + 0x10) + 0x10) + 8) = 1;
  FUN_80017f4c(*(undefined4 *)(iVar1 + 0x14),0x100);
  return;
}

/* --- SLUS_005.10 FUN_80019960  (from analysis/SLUS_005.10/decomp/80019960.c) --- */
// addr: 0x80019960  name: FUN_80019960

void FUN_80019960(int *param_1,char *param_2,undefined4 param_3,int param_4)

{
  char cVar1;
  undefined4 uVar2;
  char *pcVar3;
  undefined1 auStack_40 [32];
  
  cVar1 = *param_2;
  uVar2 = param_3;
  while (cVar1 != '\0') {
    pcVar3 = param_2 + 1;
    if (cVar1 == '\n') {
      param_4 = param_4 + (uint)*(byte *)(*param_1 + 7);
      uVar2 = param_3;
    }
    else if (cVar1 == '\x01') {
      *(char *)(param_1 + 1) = *pcVar3;
      *(char *)((int)param_1 + 5) = param_2[2];
      pcVar3 = param_2 + 4;
      *(char *)((int)param_1 + 6) = param_2[3];
    }
    else {
      DrawSync(0);
      uVar2 = FUN_80019370(param_1,auStack_40,cVar1,uVar2,param_4);
      DrawPrim(auStack_40);
    }
    param_2 = pcVar3;
    cVar1 = *pcVar3;
  }
  return;
}

/* --- SLUS_005.10 FUN_80019138  (from analysis/SLUS_005.10/decomp/80019138.c) --- */
// addr: 0x80019138  name: FUN_80019138

int FUN_80019138(int *param_1,byte *param_2)

{
  byte bVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  
  iVar4 = 0;
  iVar3 = 0;
  bVar1 = *param_2;
  while (uVar2 = (uint)bVar1, uVar2 != 0) {
    param_2 = param_2 + 1;
    if (uVar2 < 0x20) {
      param_2 = param_2 + (byte)(&DAT_800568dc)[uVar2];
    }
    else {
      iVar3 = *param_1 + (uVar2 - *(byte *)(*param_1 + 5)) * 5 + 8;
      iVar4 = iVar4 + (uint)*(byte *)(iVar3 + 3);
    }
    bVar1 = *param_2;
  }
  if (iVar3 != 0) {
    return (iVar4 - (uint)*(byte *)(iVar3 + 3)) + (int)*(char *)(iVar3 + 4) +
           (uint)*(byte *)(iVar3 + 2);
  }
  return iVar4;
}

#endif  /* GHIDRA REF */
