/* stub_misc.c -- the smallest one-liner glue functions.
 *
 * Source: SLUS_005.10
 *   FUN_800116ec  -- C runtime placeholder (empty).
 *   FUN_80040e18  -- Heap_Free wrapper.
 *   FUN_8003d898  -- ScreenHalf_Configure(obj): toggle obj+0x8c / +0x90
 *                   based on g_splitScreenMode (1P vs 2P horizontal).
 *
 * HIGH confidence (each is trivial).
 */
#include <stdint.h>

extern void Heap_Free(void *p);
extern int32_t iRam00000010;   /* g_splitScreenMode */

void Bootstrap_C_Init(void) { /* deliberately empty -- matches binary */ }

void FreeHelper_80040e18(void *p) { Heap_Free(p); }

void ScreenHalf_Configure(uint8_t *obj)
{
    /* +0x8c i16: aspect-correct screen half y origin (0xff00 = -256, 0xff60 = -160).
     * +0x90 i16: half-height (0xa0=160 for 1P, 0x50=80 for 2P horizontal). */
    int twoP = (iRam00000010 == 1);
    *(int16_t *)(obj + 0x8c) = twoP ? (int16_t)0xff60 : (int16_t)0xff00;
    *(int16_t *)(obj + 0x90) = twoP ? (int16_t)0x50   : (int16_t)0xa0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800116ec  (from analysis/SLUS_005.10/decomp/800116ec.c) --- */
// addr: 0x800116ec  name: FUN_800116ec

void FUN_800116ec(void)

{
  return;
}

/* --- SLUS_005.10 FUN_80040e18  (from analysis/SLUS_005.10/decomp/80040e18.c) --- */
// addr: 0x80040e18  name: FUN_80040e18

void FUN_80040e18(void)

{
  FUN_80045088();
  return;
}

/* --- SLUS_005.10 FUN_8003d898  (from analysis/SLUS_005.10/decomp/8003d898.c) --- */
// addr: 0x8003d898  name: FUN_8003d898

void FUN_8003d898(int param_1)

{
  int iVar1;
  undefined2 uVar2;
  
  iVar1 = iRam00000010;
  uVar2 = 0xff00;
  if (iRam00000010 == 1) {
    uVar2 = 0xff60;
  }
  *(undefined2 *)(param_1 + 0x8c) = uVar2;
  uVar2 = 0xa0;
  if (iVar1 == 1) {
    uVar2 = 0x50;
  }
  *(undefined2 *)(param_1 + 0x90) = uVar2;
  return;
}

#endif  /* GHIDRA REF */
