/* tick_misc.c -- small per-frame helpers and resetters.
 *
 * Source: SLUS_005.10
 *   FUN_80011a10 -- Buffer_StartOTagOther     (other parity)
 *   FUN_80015010 -- Tick_GetFrameCounter      (combined RCnt + frame epoch)
 *   FUN_800128bc -- Tick_WaitIrqAck           (spin on iRam00000168)
 *   FUN_80012980 -- Quest_Free                (release loaded Quest.bin)
 *
 * HIGH confidence: each is tiny and unambiguous.
 */
#include <stdint.h>

extern void Buffer_StartOTag(int parity);
extern int  GetRCnt(uint32_t spec);
extern void Heap_Free(void *p);

extern int32_t  iRam00000004;        /* current display parity */
extern uint16_t DAT_800102f2;        /* high-half frame counter (incremented on hi-roll) */
extern volatile int32_t iRam00000168; /* IRQ ack-flag */
extern uintptr_t iRam00000608;        /* loaded Quest.bin pointer */

void Buffer_StartOTagOther(void)
{
    Buffer_StartOTag(1 - iRam00000004);
}

/* Returns a 32-bit absolute frame counter: low 16 bits from the timer
 * counter, high 16 from an epoch advanced by the IRQ handler when the
 * lower counter wraps. */
uint32_t Tick_GetFrameCounter(void)
{
    uint32_t lo = (uint32_t)GetRCnt(0xf2000002);
    return lo | ((uint32_t)DAT_800102f2 << 16);
}

void Tick_WaitIrqAck(void)
{
    while (iRam00000168 == 0) { /* spin until IRQ posts */ }
}

void Quest_Free(void)
{
    if (iRam00000608 != 0) {
        Heap_Free((void *)iRam00000608);
        iRam00000608 = 0;
    }
}

/* Hex-name aliases for these helpers (callers reference by PSX address).
 * FUN_80015010 and FUN_80012980 are defined in timer_tick.c / quest_data.c. */
void FUN_80011a10(void)        { Buffer_StartOTagOther(); }
void FUN_800128bc(void)        { Tick_WaitIrqAck(); }

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80011a10  (from analysis/SLUS_005.10/decomp/80011a10.c) --- */
// addr: 0x80011a10  name: FUN_80011a10

void FUN_80011a10(void)

{
  FUN_800119c0(1 - iRam00000004);
  return;
}

/* --- SLUS_005.10 FUN_80015010  (from analysis/SLUS_005.10/decomp/80015010.c) --- */
// addr: 0x80015010  name: FUN_80015010

uint FUN_80015010(void)

{
  uint uVar1;
  
  uVar1 = GetRCnt(0xf2000002);
  return uVar1 | (uint)DAT_800102f2 << 0x10;
}

/* --- SLUS_005.10 FUN_800128bc  (from analysis/SLUS_005.10/decomp/800128bc.c) --- */
// addr: 0x800128bc  name: FUN_800128bc

void FUN_800128bc(void)

{
  do {
  } while (iRam00000168 == 0);
  return;
}

/* --- SLUS_005.10 FUN_80012980  (from analysis/SLUS_005.10/decomp/80012980.c) --- */
// addr: 0x80012980  name: FUN_80012980

void FUN_80012980(void)

{
  if (iRam00000608 != 0) {
    FUN_80045088();
    iRam00000608 = 0;
  }
  return;
}

#endif  /* GHIDRA REF */
