"""Retain original V8 GTE angular integration verbatim, without float substitutes."""
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[2]
source=(ROOT/'reference/generated/recompiled/main.cs').read_text(encoding='utf-8-sig')
match=re.search(r'    public static void FUN_800439b8\(CpuContext c, IMemory m\)\n    \{.*?\n    \}',source,re.S)
if match is None: raise RuntimeError('original V8 angular integrator missing')
body=match.group().replace('FUN_800439b8','ApplyAngularVelocity')
output='''// Generated by tools/recompone-v8-2/port_v8_vehicle_math.py.
// Source: original SLUS_005.10 FUN_800439b8; cleaned C in src/physics/object_integrate.c.
// Preserve instruction order and GTE saturation/flags. No V8:2 object offsets here.
using RecompOne.Runtime.Context;
using RecompOne.Runtime.Memory;
namespace RecompOne.Runtime.Sdk;
internal static class V8VehicleMath
{
'''+body+'\n}\n'
path=ROOT/'tools/recompone-reference/RecompOne.Runtime/sdk/V8VehicleMath.cs'
path.write_text(output,encoding='utf-8')
print(path)
