/* catwalk.c -- Secret Base catwalk bounding-box update.
 *
 * Source: SCRTBASE.DLL  FUN_80100624.
 *
 * Each tick, computes a 4-corner i16 AABB by adding the parent's
 * position to the per-frame offset slots from a linked child struct
 * (at obj+0x5c), rounds to 16.16, then writes the 4 i16 corner
 * coordinates into a local for the bounds-check code in the caller.
 *
 * Used by `catwalk_1` which has movable segments; the precomputed
 * bounding box accelerates point-in-rect tests for vehicles walking
 * across it.
 *
 * HIGH-MED confidence.
 */
#include <stdint.h>

void SB_CatwalkBounds(int obj)
{
    int *child = *(int **)(obj + 0x5c);

    int32_t x0 = *(int32_t *)(obj + 0x48) + child[1];
    int32_t z0 = *(int32_t *)(obj + 0x50) + child[3];
    int32_t x1 = *(int32_t *)(obj + 0x48) + child[4];
    int32_t z1 = *(int32_t *)(obj + 0x50) + child[5];

    if (x0 < 0) x0 += 0xffff;
    if (z0 < 0) z0 += 0xffff;
    if (x1 < 0) x1 += 0xffff;
    if (z1 < 0) z1 += 0xffff;

    int16_t cornerX0 = (int16_t)((uint32_t)x0 >> 16);
    int16_t cornerZ0 = (int16_t)((uint32_t)z0 >> 16);
    int16_t cornerX1 = (int16_t)((uint32_t)x1 >> 16);
    int16_t cornerZ1 = (int16_t)((uint32_t)z1 >> 16);
    (void)cornerX0; (void)cornerZ0; (void)cornerX1; (void)cornerZ1;
    /* Original continues -- writes the 4 corners to a contiguous u16
     * block on the stack and likely passes the pointer to a bounds-
     * test helper. Pass 3 finalises the caller chain. */
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_80100624  (from analysis/dll/SCRTBASE/decomp/80100624.c) --- */
// addr: 0x80100624  name: FUN_80100624

void FUN_80100624(int param_1)

{
  int iVar1;
  int iVar2;
  int iVar3;
  short local_10;
  short local_e;
  short local_c;
  short local_a;
  
  iVar3 = *(int *)(param_1 + 0x5c);
  iVar2 = *(int *)(param_1 + 0x48) + *(int *)(iVar3 + 4);
  if (iVar2 < 0) {
    iVar2 = iVar2 + 0xffff;
  }
  local_10 = (short)((uint)iVar2 >> 0x10);
  iVar2 = *(int *)(param_1 + 0x50) + *(int *)(iVar3 + 0xc);
  if (iVar2 < 0) {
    iVar2 = iVar2 + 0xffff;
  }
  local_e = (short)((uint)iVar2 >> 0x10);
  iVar2 = *(int *)(param_1 + 0x48) + *(int *)(iVar3 + 0x10);
  iVar1 = iVar2 + 0xffff;
  if (iVar1 < 0) {
    iVar1 = iVar2 + 0x1fffe;
  }
  local_c = (short)((uint)iVar1 >> 0x10) - local_10;
  iVar2 = *(int *)(param_1 + 0x50) + *(int *)(iVar3 + 0x18);
  iVar3 = iVar2 + 0xffff;
  if (iVar3 < 0) {
    iVar3 = iVar2 + 0x1fffe;
  }
  local_a = (short)((uint)iVar3 >> 0x10) - local_e;
  FUN_80024718/*0x80024718*/(&local_10);
  return;
}

#endif  /* GHIDRA REF */
