/* drone_tick.c -- Secret Base proto-saucer / aurora drone tick.
 *
 * Source: SCRTBASE.DLL  FUN_8010100c.
 *
 * Drift-and-decay tick: position += velocity, velocity *= 0.969
 * (= 0xf80/0x1000 in 4.12), heading += yawRate. Then spawn impact
 * sparks each tick (FUN_8001d708) and call Damage_Apply.
 *
 * Used by the protoSaucer and aurora_1 -- both are slowly-decaying
 * drones that emit sparks and self-damage until destroyed.
 *
 * MED.
 */
#include <stdint.h>

extern void ImpactSparks_Spawn(void *obj);    /* FUN_8001d708 */
extern void Damage_Apply(void *obj);

uint32_t SB_DroneTick(int obj, int mode)
{
    if (mode == 0 || mode != 5) {
        *(int32_t *)(obj + 0x48) += *(int32_t *)(obj + 0x88);
        *(int32_t *)(obj + 0x4c) += *(int32_t *)(obj + 0x8c);
        *(int32_t *)(obj + 0x50) += *(int32_t *)(obj + 0x90);
        *(int32_t *)(obj + 0x88) = *(int32_t *)(obj + 0x88) * 0xf80 >> 12;
        *(int32_t *)(obj + 0x8c) = *(int32_t *)(obj + 0x8c) * 0xf80 >> 12;
        *(int32_t *)(obj + 0x90) = *(int32_t *)(obj + 0x90) * 0xf80 >> 12;
        *(int16_t *)(obj + 0x44) = (int16_t)(*(int16_t *)(obj + 0x44)
                                             + *(int16_t *)(obj + 0x96));
        ImpactSparks_Spawn((void *)(intptr_t)obj);
    }
    Damage_Apply((void *)(intptr_t)obj);
    return 0xffffffffu;
}

uint32_t FUN_8010100c(int obj, int mode)
{
    return SB_DroneTick(obj, mode);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_8010100c  (from analysis/dll/SCRTBASE/decomp/8010100c.c) --- */
// addr: 0x8010100c  name: FUN_8010100c

undefined4 FUN_8010100c(int param_1,int param_2)

{
  if ((param_2 == 0) || (param_2 != 5)) {
    *(int *)(param_1 + 0x48) = *(int *)(param_1 + 0x48) + *(int *)(param_1 + 0x88);
    *(int *)(param_1 + 0x4c) = *(int *)(param_1 + 0x4c) + *(int *)(param_1 + 0x8c);
    *(int *)(param_1 + 0x50) = *(int *)(param_1 + 0x50) + *(int *)(param_1 + 0x90);
    *(int *)(param_1 + 0x88) = *(int *)(param_1 + 0x88) * 0xf80 >> 0xc;
    *(int *)(param_1 + 0x8c) = *(int *)(param_1 + 0x8c) * 0xf80 >> 0xc;
    *(int *)(param_1 + 0x90) = *(int *)(param_1 + 0x90) * 0xf80 >> 0xc;
    *(short *)(param_1 + 0x44) = *(short *)(param_1 + 0x44) + *(short *)(param_1 + 0x96);
    FUN_8001d708/*0x8001d708*/();
  }
  FUN_800205f8/*0x800205f8*/(param_1);
  return 0xffffffff;
}

#endif  /* GHIDRA REF */
