/* fence_hit.c -- Secret Base fence_left / fence_right hit + bell-rope.
 *
 * Source: SCRTBASE.DLL  FUN_80101acc.
 *
 * On collision with a missile or vehicle:
 *   - mode 3/8: look up paired object by sub-state at impulse:
 *       if obj.posX@+0x80 is negative -> bell-rope id 0x74
 *       else                          -> 0x75
 *   - Mark paired as "hit" (state 1, sub-state 600, flag 0x20).
 *   - Play sfx 0x14 at impulse pos+0x24.
 *   - Run Damage_FromImpulse + Damage_AccumulateOrFire.
 *   - On kill: invoke func_0x80020844 (FX teardown).
 *   - At end: clear back-buffer bit on child @+0x38, set state byte
 *     in obj+0x38+4.
 *
 * MED.
 */
#include <stdint.h>

extern int  Damage_FromImpulse(uint32_t *self, int *impulse);
extern int  Damage_AccumulateOrFire(uint32_t *self, uint16_t amount);
extern uint32_t Object_FindByPairedSpawnId(uint32_t sid);   /* func_0x80021808 */
extern int  Object_FrameCounterBump(int payload, uint16_t arg);
extern void Object_SetSubState(int obj, int sub);
extern uint32_t SfxChannel_Acquire(void);
extern void Audio_PlaySfxAtPosVar(uint32_t ch, uint32_t bank, int sfxId, void *pos);
extern void FX_Teardown(int obj);   /* func_0x80020844 */
extern uint32_t _DAT_800658fc;

uint32_t SB_FenceHit(int self, uint32_t mode, int *impulse)
{
    uint32_t *paired = NULL;
    if (mode == 2) goto clearBit;
    if (mode < 3 && mode == 1) goto applyState;
    if (mode != 3 && mode != 8) goto applyState;

    paired = (uint32_t *)(uintptr_t)impulse[3];
    int impulser = *impulse;
    if ((uint8_t)((uintptr_t)paired >> 8) == mode
        && *(int8_t *)(impulser + 4) == 2)
    {
        uint32_t sid = (*(int32_t *)(impulser + 0x80) < 0) ? 0x74 : 0x75;
        uint32_t pairedObj = Object_FindByPairedSpawnId(sid);
        Object_FrameCounterBump((int)pairedObj, *(uint16_t *)(*(int *)(pairedObj + 0x60)));
        *(int8_t *)(pairedObj + 8) = 1;
        Object_SetSubState((int)pairedObj, 600);
        Object_SetSubState(self, 600);
        paired[0] |= 0x20u;

        uint32_t ch = SfxChannel_Acquire();
        Audio_PlaySfxAtPosVar(ch, _DAT_800658fc, 0x14, (void *)(intptr_t)(impulser + 0x24));
        self = 1;
    }
    Damage_FromImpulse((uint32_t *)(intptr_t)self, impulse);
    self = 1;

applyState: {
        int killed = Damage_AccumulateOrFire((uint32_t *)(intptr_t)self, (uint16_t)(uintptr_t)impulse);
        if (killed == 0) return 0;
        FX_Teardown(self);
    }
clearBit: {
        uint32_t *child = *(uint32_t **)(self + 0x38);
        child[0] &= ~0x20u;
        if (paired != NULL) {
            *(int8_t *)(*(int *)(self + 0x38) + 4) = (int8_t)(uintptr_t)paired;
        }
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_80101acc  (from analysis/dll/SCRTBASE/decomp/80101acc.c) --- */
// addr: 0x80101acc  name: FUN_80101acc

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80101acc(int param_1,uint param_2,int *param_3)

{
  uint *puVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  
  if (param_2 != 2) {
    if ((param_2 < 3) && (puVar1 = (uint *)0x3, param_2 == 1)) goto LAB_80101c2c;
    if ((param_2 == 3) || (iVar2 = param_1, param_2 != 8)) {
      puVar1 = (uint *)param_3[3];
      iVar2 = param_1;
      if (((byte)puVar1[1] == param_2) && (iVar4 = *param_3, *(char *)(iVar4 + 4) == '\x02')) {
        uVar3 = 0x74;
        if (*(int *)(iVar4 + 0x80) < 0) {
          uVar3 = 0x75;
        }
        iVar2 = func_0x80021808(uVar3);
        FUN_8001f9cc/*0x8001f9cc*/(iVar2,**(undefined2 **)(iVar2 + 0x60));
        *(undefined1 *)(iVar2 + 8) = 1;
        FUN_80020890/*0x80020890*/(iVar2,600);
        FUN_80020890/*0x80020890*/(param_1,600);
        *puVar1 = *puVar1 | 0x20;
        uVar3 = FUN_8004410c/*0x8004410c*/();
        param_3 = (int *)0x14;
        FUN_800447e8/*0x800447e8*/(uVar3,_DAT_800658fc,0x14,iVar4 + 0x24);
        iVar2 = 1;
      }
      FUN_8002239c/*0x8002239c*/(iVar2,param_3);
      iVar2 = 1;
    }
    iVar2 = FUN_80022320/*0x80022320*/(iVar2,param_3);
    if (iVar2 == 0) {
      return 0;
    }
    func_0x80020844(param_1);
  }
  puVar1 = *(uint **)(param_1 + 0x38);
  *puVar1 = *puVar1 & 0xffffffdf;
LAB_80101c2c:
  *(char *)(*(int *)(param_1 + 0x38) + 4) = (char)puVar1;
  return 0;
}

#endif  /* GHIDRA REF */
