/* misc.c -- Secret Base small collision handlers.
 *
 * Source: SCRTBASE.DLL
 *   FUN_801006f4 -- SB_FenceImpact: terrain + circular collision tests.
 *                   Always returns -1 (destroyed/handled).
 *   FUN_801025ec -- SB_TurretHit: on collision with mode-7 impulse,
 *                   broadcast event id 9 to the linked spawn id.
 *
 * HIGH-MED confidence.
 */
#include <stdint.h>

extern int  Collision_AgainstTerrain(int obj, int impact);    /* func_0x8002239c */
extern int  Collision_Circular     (int obj, int impact);    /* func_0x80022320 */
extern void Object_BroadcastEvent  (int eventId, int spawnId); /* func_0x8002185c */

uint32_t SB_FenceImpact(int obj, uint32_t mode, void *impact)
{
    if (mode == 3 || mode == 8) Collision_AgainstTerrain(obj, (int)(intptr_t)impact);
    Collision_Circular(obj, (int)(intptr_t)impact);
    return 0xffffffffu;
}

uint32_t SB_TurretHit(int obj, uint32_t mode, int *impulse)
{
    if (mode == 3 || mode == 8) {
        if (*(int8_t *)(*impulse + 4) != 7) return 0;
        impulse = (int *)(uintptr_t)*(uint16_t *)(*impulse + 0xc);
    }
    int hit = Collision_Circular(obj, (int)(intptr_t)impulse);
    if (hit != 0) Object_BroadcastEvent(9, *(int16_t *)(obj + 6));
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_801006f4  (from analysis/dll/SCRTBASE/decomp/801006f4.c) --- */
// addr: 0x801006f4  name: FUN_801006f4

undefined4 FUN_801006f4(undefined4 param_1,int param_2,undefined4 param_3)

{
  if ((param_2 == 3) || (param_2 != 8)) {
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
  }
  FUN_80022320/*0x80022320*/(param_1,param_3);
  return 0xffffffff;
}

/* --- ? FUN_801025ec  (from analysis/dll/SCRTBASE/decomp/801025ec.c) --- */
// addr: 0x801025ec  name: FUN_801025ec

undefined4 FUN_801025ec(int param_1,int param_2,int *param_3)

{
  int iVar1;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    if (*(char *)(*param_3 + 4) != '\a') {
      return 0;
    }
    param_3 = (int *)(uint)*(ushort *)(*param_3 + 0xc);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  if (iVar1 != 0) {
    FUN_8002185c/*0x8002185c*/(9,(int)*(short *)(param_1 + 6));
  }
  return 0;
}

#endif  /* GHIDRA REF */
