/* missile_chain.c -- SCRTBASE multi-stage missile chain spawner.
 *
 * Source: SCRTBASE.DLL  FUN_8010076c.
 *
 * Recursive multi-stage projectile that fires one child per countdown
 * expiry, decrementing a remaining-stage counter at obj+0x4a (i16).
 * Each stage:
 *   - Decrement counter at obj+0x96 each tick.
 *   - On reaching 1: if obj+0x4a (stages left) is non-zero, spawn a
 *     child of kind 0x1e1 (same type) chained recursively to this
 *     function as its tick callback.
 *   - Decrement stages-left counter at obj+0x4a on each spawn.
 *
 * The "self-recursive callback" pattern creates a chain reaction:
 *   missile 1 -> missile 2 -> ... -> missile N
 * each firing 0x96 ticks after the previous.
 *
 * MED.
 */
#include <stdint.h>

extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int size, int flags);
extern intptr_t Bone_AllocSlot(int parent, uint16_t slotKey);
extern void Object_PostUpdate2(uint32_t obj);
extern void GTE_RotateLongMatTrans(uint32_t *mat, int32_t *src, uint32_t *dst);
extern uint32_t *FUN_80040234(uint32_t *param_1);
extern uint32_t FUN_8004410c(void);
extern void FUN_8004483c(uint32_t voice, uint32_t bank, int sfx, uint32_t *xyz);
extern uint32_t *FUN_8003fea8(uint32_t *xyz, uint32_t color);
extern void FUN_80012050(int param_1, uint8_t param_2);
extern void FUN_800205f8(uint32_t *obj);
extern uint32_t _DAT_800658fc;

static int16_t mips_addiu_i16(int16_t a, int16_t b)
{
    return (int16_t)((uint16_t)a + (uint16_t)b);
}

uint32_t FUN_8010076c(uint32_t *self, uint32_t mode, int *impulse);

uint32_t SB_MissileChain(uint32_t *self, uint32_t mode, int *impulse)
{
    if (mode == 5)
        goto retire;

    if (mode != 3) {
        if (mode != 0)
            goto done;

        int16_t *cd = (int16_t *)((uint8_t *)self + 0x96);
        int16_t prev = *cd;
        *cd = mips_addiu_i16(prev, -1);
        if (prev != 1) return 0;
        if (*(int16_t *)(self + 0x25) == 0) return 0;

        /* Spawn next stage. */
        uint32_t *child = Object_Pool_AllocFromBank(
            (void *)(uintptr_t)self[0x16], 0x1e1, 0x98, 8);
        intptr_t slot = Bone_AllocSlot((int)(uintptr_t)self, 0x8000);

        *((int8_t *)child + 4) = 7;
        child[0]    = 0x84;
        *((uint16_t *)child + 6) = *(uint16_t *)((uint8_t *)self + 6);
        *(int16_t *)(child + 3)   = (int16_t)self[3];
        Object_SetCallbackPsxSlot(child, (uintptr_t)FUN_8010076c);       /* recursive */

        Object_PostUpdate2((uint32_t)(uintptr_t)child);

        *(int16_t *)((uint8_t *)child + 0x96) = 4;
        *(int16_t *)(child + 0x25) = mips_addiu_i16((int16_t)self[0x25], -1);

        child[0x22] = self[0x22];
        child[0x23] = self[0x23];
        child[0x24] = self[0x24];

        child[4] = self[4];
        child[5] = self[5];
        child[6] = self[6];
        child[7] = self[7];
        child[8] = self[8];
        child[9] = self[9];
        child[10] = self[10];
        child[11] = self[11];
        if (slot != 0)
            GTE_RotateLongMatTrans(self + 4, (int32_t *)(slot + 4), child + 9);
    }

    FUN_80040234(self + 0x12);
    self[0] |= 0x20u;
    FUN_8004483c(FUN_8004410c(), _DAT_800658fc, 0x41, self + 9);
    FUN_8003fea8(self + 9, 0x08c0c000u);

    if (impulse != NULL) {
        int impObj = *impulse;
        if (*(uint8_t *)(uintptr_t)(impObj + 4) == 2) {
            int16_t status = *(int16_t *)(uintptr_t)(impObj + 6);
            if (status < 0)
                FUN_80012050(~(int)status, 0x14);
        }
    }

done:
    return 0;

retire:
    FUN_800205f8(self);
    return 0;
}

uint32_t FUN_8010076c(uint32_t *self, uint32_t mode, int *impulse)
{
    return SB_MissileChain(self, mode, impulse);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_8010076c  (from analysis/dll/SCRTBASE/decomp/8010076c.c) --- */
// addr: 0x8010076c  name: FUN_8010076c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_8010076c(uint *param_1,uint param_2,int *param_3)

{
  short sVar1;
  undefined2 uVar2;
  uint uVar3;
  undefined4 *puVar4;
  undefined4 uVar5;
  uint uVar6;
  uint uVar7;
  
  if (param_2 != 3) {
    uVar3 = 5;
    if (((3 < param_2) || (uVar3 = 0, param_2 != 0)) && (param_2 == uVar3)) goto LAB_80100944;
    sVar1 = *(short *)((int)param_1 + 0x96);
    *(short *)((int)param_1 + 0x96) = sVar1 + -1;
    if (sVar1 != 1) {
      return 0;
    }
    if ((short)param_1[0x25] == 0) {
      return 0;
    }
    puVar4 = (undefined4 *)FUN_8001ac44/*0x8001ac44*/(param_1[0x16],0x1e1,0x98,8);
    param_3 = (int *)FUN_8001b038/*0x8001b038*/(param_1,0x8000);
    uVar2 = *(undefined2 *)((int)param_1 + 6);
    *(undefined1 *)(puVar4 + 1) = 7;
    *puVar4 = 0x84;
    *(undefined2 *)((int)puVar4 + 6) = uVar2;
    uVar3 = param_1[3];
    puVar4[0x19] = FUN_8010076c;
    *(short *)(puVar4 + 3) = (short)uVar3;
    FUN_8002036c/*0x8002036c*/(puVar4);
    uVar3 = param_1[0x25];
    *(undefined2 *)((int)puVar4 + 0x96) = 4;
    *(short *)(puVar4 + 0x25) = (short)uVar3 + -1;
    uVar3 = param_1[0x23];
    uVar6 = param_1[0x24];
    puVar4[0x22] = param_1[0x22];
    puVar4[0x23] = uVar3;
    puVar4[0x24] = uVar6;
    uVar3 = param_1[5];
    uVar6 = param_1[6];
    uVar7 = param_1[7];
    puVar4[4] = param_1[4];
    puVar4[5] = uVar3;
    puVar4[6] = uVar6;
    puVar4[7] = uVar7;
    uVar3 = param_1[9];
    uVar6 = param_1[10];
    uVar7 = param_1[0xb];
    puVar4[8] = param_1[8];
    puVar4[9] = uVar3;
    puVar4[10] = uVar6;
    puVar4[0xb] = uVar7;
    GTE_RotateLongMatTrans/*0x80043408*/(param_1 + 4,param_3 + 1,puVar4 + 9);
  }
  FUN_80040234/*0x80040234*/(param_1 + 0x12);
  *param_1 = *param_1 | 0x20;
  uVar5 = FUN_8004410c/*0x8004410c*/();
  FUN_8004483c/*0x8004483c*/(uVar5,_DAT_800658fc,0x41,param_1 + 9);
  FUN_8003fea8/*0x8003fea8*/(param_1 + 9,0x8c0c000);
  if (*(char *)(*param_3 + 4) != '\x02') {
    return 0;
  }
  uVar3 = (uint)*(short *)(*param_3 + 6);
  if (-1 < (int)uVar3) {
    return 0;
  }
  MatchSlot_SetCharacter/*0x80012050*/(~uVar3,0x14);
LAB_80100944:
  FUN_800205f8/*0x800205f8*/(param_1);
  return 0;
}

#endif  /* GHIDRA REF */
