/* radar.c -- Secret Base radar dish per-tick spin.
 *
 * Source: SCRTBASE.DLL  FUN_801004a8.
 *
 * The Secret Base level features a rotating radar dish (`radar_1`).
 * Its per-tick callback increments the dish's child-object roll
 * (object referenced at obj[0xe] = a sub-object pointer) by 0x11 each
 * tick, producing a slow spin. When an external impulse arrives
 * (param_3 != NULL), spawns impact sparks (FUN_8001d708) at the
 * child's position and, if the top-level flag bit 0x80 is set, runs a
 * brief secondary effect.
 *
 * Sub-object layout (offset within the child @obj[0xe]):
 *   +0x42  i16  roll angle (the dish's spin)
 *
 * Cases 3 (impact) and 4 (retire) are handled by the level main
 * dispatcher in radar_sweep.c (FUN_80100200); the per-dish handler
 * itself only spins.
 *
 * MED confidence.
 */
#include <stdint.h>

extern void ImpactSparks_Spawn(void *obj);    /* FUN_8001d708 */

uint32_t SCRT_RadarTick(uint32_t *obj, int mode, int *impulse)
{
    switch (mode) {
    case 0: {
        uint8_t *child = (uint8_t *)(uintptr_t)obj[0xe];
        *(int16_t *)(child + 0x42) = (int16_t)(*(int16_t *)(child + 0x42) + 0x11);
        if (impulse == NULL) return 0;
        ImpactSparks_Spawn(child);
        if ((*obj & 0x80) == 0) return 0;
        /* fall through to a small effect step (state 3/4 in original) */
        break;
    }
    case 3:
        /* impactor event -- forwarded to the SB damage dispatcher in
         * radar_sweep.c (FUN_80100200). This dish handler only spins;
         * damage routes through the level's main handler. */
        break;
    case 4:
        /* silent retire -- nothing to free; the spinning dish has no
         * heap or FX allocation of its own. */
        break;
    default: break;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_801004a8  (from analysis/dll/SCRTBASE/decomp/801004a8.c) --- */
// addr: 0x801004a8  name: FUN_801004a8

undefined4 FUN_801004a8(uint *param_1,undefined4 param_2,int *param_3)

{
  int iVar1;
  
  switch(param_2) {
  case 0:
    *(short *)(param_1[0xe] + 0x42) = *(short *)(param_1[0xe] + 0x42) + 0x11;
    if (param_3 == (int *)0x0) {
      return 0;
    }
    FUN_8001d708/*0x8001d708*/(param_1[0xe]);
    if ((*param_1 & 0x80) == 0) {
      return 0;
    }
    param_3 = (int *)0x1;
    break;
  default:
    goto switchD_801004e0_caseD_1;
  case 3:
    goto switchD_801004e0_caseD_3;
  case 4:
    goto switchD_801004e0_caseD_4;
  case 8:
    goto switchD_801004e0_caseD_8;
  case 9:
    break;
  }
  if ((param_3 == (int *)0x0) || (param_3 != (int *)0x1)) {
    FUN_80020778/*0x80020778*/(param_1);
    FUN_800441c8/*0x800441c8*/((int)*(char *)((int)param_1 + 5));
    *(undefined1 *)((int)param_1 + 5) = 0;
  }
  if ((*param_1 & 0x80) != 0) {
    Stream_FatalOom/*0x80015368*/(&DAT_80100074);
  }
  if (param_1[0xe] != 0) {
    FUN_80020744/*0x80020744*/(param_1);
    **(ushort **)(param_1[0xe] + 0x30) = **(ushort **)(param_1[0xe] + 0x30) & 0xfffb | 1;
switchD_801004e0_caseD_3:
    if (*(char *)(*param_3 + 4) == '\a') {
      param_3 = (int *)(uint)*(ushort *)(*param_3 + 0xc);
switchD_801004e0_caseD_8:
      iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
      if (iVar1 != 0) {
        FUN_80020778/*0x80020778*/(param_1);
switchD_801004e0_caseD_4:
        FUN_800441c8/*0x800441c8*/((int)*(char *)((int)param_1 + 5));
      }
    }
  }
switchD_801004e0_caseD_1:
  return 0;
}

#endif  /* GHIDRA REF */
