/* terrain_deform.c -- SCRTBASE MSilo destruction terrain deformation.
 *
 * Source: SCRTBASE.DLL  FUN_80100ca0.
 *
 * When the Secret Base's missile silo (MSilo) is destroyed, the
 * terrain around it deforms (crater). This function:
 *
 *   1. Reads the object's center (x, z) at obj+0x48 / +0x50, applies
 *      the standard +0xffff round-down for negative coords.
 *   2. Walks a 32x32 sample grid (-16..+15 around the center, +0x10
 *      cell stride) -- 0x400 (1024) cells total.
 *   3. For each cell: reads a stored delta from obj+0x884 (a
 *      pre-computed crater profile), negates it, and ADDS to the
 *      heightmap entry at that (cellX, cellZ) -- which lowers the
 *      terrain by the profile depth. After applying, the stored
 *      delta at obj+0x84 is zeroed so the deformation isn't applied
 *      twice.
 *   4. After both grids are walked, returns to caller (presumably to
 *      finish the damage state machine).
 *
 * Bit-exact: the heightmap deformation happens directly in
 * DAT_800911a0's chunked grid -- the same memory Terrain_HeightAt
 * reads. Once written, the crater persists across the rest of the
 * match.
 *
 * HIGH (mechanism); MED (the exact 0x884/0x84 stride needs confirmation).
 */
#include <stdint.h>

extern uintptr_t DAT_800911a0[];

void SB_TerrainDeform_FromCrater(int obj, int onComplete)
{
    if (!onComplete) return;

    int32_t cx = *(int32_t *)(obj + 0x48);
    int32_t cz = *(int32_t *)(obj + 0x50);
    if (cx < 0) cx += 0xffff;
    if (cz < 0) cz += 0xffff;

    for (int dx = 0; dx < 0x20; dx++) {
        for (int dz = 0; dz < 0x20; dz++) {
            uint8_t *cell = (uint8_t *)(intptr_t)(obj + dz * 2 + dx * 0x40);
            int16_t delta = *(int16_t *)(cell + 0x884);
            *(uint16_t *)(cell + 0x84) = 0;        /* mark consumed */
            if (delta == 0) continue;

            uint32_t cellX = (uint32_t)((cx >> 16) - 0x10 + dx);
            uint32_t cellZ = (uint32_t)((cz >> 16) - 0x10 + dz);
            uintptr_t chunkBase =
                DAT_800911a0[(cellX >> 6) * 32 + (cellZ >> 6)];
            int16_t *hp = (int16_t *)(chunkBase + (cellX & 0x3f) * 0x80 + (cellZ & 0x3f) * 2);
            *hp = (int16_t)(*hp + -delta);          /* sink terrain */
        }
    }
    /* The original continues with a 2nd pass updating obj+0x84 -- the
     * outgoing "in-flight" delta table. Pass 3 finalises. */
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_80100ca0  (from analysis/dll/SCRTBASE/decomp/80100ca0.c) --- */
// addr: 0x80100ca0  name: FUN_80100ca0

undefined4 FUN_80100ca0(int param_1,int param_2,int param_3)

{
  short sVar1;
  undefined1 uVar2;
  int iVar3;
  undefined4 *puVar4;
  int iVar5;
  uint uVar6;
  short *psVar7;
  undefined4 *puVar8;
  int iVar9;
  uint uVar10;
  int iVar11;
  int iVar12;
  undefined4 uVar13;
  undefined4 uVar14;
  undefined4 uVar15;
  
  if ((param_2 == 0) || (param_2 != 1)) {
    if (param_3 != 0) {
      iVar5 = *(int *)(param_1 + 0x48);
      if (iVar5 < 0) {
        iVar5 = iVar5 + 0xffff;
      }
      iVar9 = *(int *)(param_1 + 0x50);
      if (iVar9 < 0) {
        iVar9 = iVar9 + 0xffff;
      }
      iVar12 = 0;
      do {
        iVar11 = 0;
        uVar6 = (iVar5 >> 0x10) + -0x10 + iVar12;
        do {
          iVar3 = param_1 + iVar11 * 2 + iVar12 * 0x40;
          *(undefined2 *)(iVar3 + 0x84) = 0;
          iVar3 = -(int)*(short *)(iVar3 + 0x884);
          uVar10 = (iVar9 >> 0x10) + -0x10 + iVar11;
          if (iVar3 != 0) {
            psVar7 = (short *)(*(int *)((uVar10 >> 6) * 4 + (uVar6 >> 6) * 0x80 + -0x7ff6ee60) +
                               (uVar6 & 0x3f) * 0x80 + (uVar10 & 0x3f) * 2);
            *psVar7 = *psVar7 + (short)iVar3;
          }
          iVar11 = iVar11 + 1;
        } while (iVar11 < 0x20);
        iVar12 = iVar12 + 1;
      } while (iVar12 < 0x20);
      puVar4 = (undefined4 *)(param_1 + 0x84);
      puVar8 = (undefined4 *)(param_1 + 0x884);
      do {
        uVar13 = puVar4[1];
        uVar14 = puVar4[2];
        uVar15 = puVar4[3];
        *puVar8 = *puVar4;
        puVar8[1] = uVar13;
        puVar8[2] = uVar14;
        puVar8[3] = uVar15;
        puVar4 = puVar4 + 4;
        puVar8 = puVar8 + 4;
      } while (puVar4 != (undefined4 *)(param_1 + 0x884));
    }
    iVar5 = *(int *)(param_1 + 0x80) + 1;
    *(int *)(param_1 + 0x80) = iVar5;
    if (iVar5 != 0x101) {
      return 0;
    }
    iVar5 = *(int *)(param_1 + 0x48);
    if (iVar5 < 0) {
      iVar5 = iVar5 + 0xffff;
    }
    iVar9 = *(int *)(param_1 + 0x50);
    if (iVar9 < 0) {
      iVar9 = iVar9 + 0xffff;
    }
    iVar12 = 0;
    do {
      iVar3 = 0;
      uVar6 = (iVar5 >> 0x10) + -0x10 + iVar12;
      iVar11 = iVar12 << 6;
      do {
        sVar1 = *(short *)(param_1 + iVar11 + 0x884);
        uVar10 = (iVar9 >> 0x10) + -0x10 + iVar3;
        if (sVar1 != 0) {
          psVar7 = (short *)(*(int *)((uVar10 >> 6) * 4 + (uVar6 >> 6) * 0x80 + -0x7ff6ee60) +
                             (uVar6 & 0x3f) * 0x80 + (uVar10 & 0x3f) * 2);
          *psVar7 = *psVar7 - sVar1;
        }
        iVar3 = iVar3 + 1;
        iVar11 = iVar11 + 2;
      } while (iVar3 < 0x20);
      iVar12 = iVar12 + 1;
    } while (iVar12 < 0x20);
    FUN_800205f8/*0x800205f8*/(param_1);
  }
  iVar5 = -0x10;
  iVar9 = 0x10;
  do {
    iVar11 = -0x10;
    iVar12 = 0x100;
    do {
      uVar2 = SquareRoot0/*0x8004c6e4*/((iVar5 * iVar5 + iVar12) * 0x40);
      *(undefined1 *)(param_1 + iVar11 + iVar9 + 0x1084) = uVar2;
      iVar11 = iVar11 + 1;
      iVar12 = iVar11 * iVar11;
    } while (iVar11 < 0x10);
    iVar5 = iVar5 + 1;
    iVar9 = iVar9 + 0x20;
  } while (iVar5 < 0x10);
  return 0;
}

#endif  /* GHIDRA REF */
