/* turret_spawn.c -- SCRTBASE turret child-projectile spawner.
 *
 * Source: SCRTBASE.DLL  FUN_8010183c.
 *
 * Spawns a 0x98-byte projectile of kind 0x1b7 attached to a bone slot
 * on the parent. Sets initial pos = bone pos, state = 0x84, sub-state
 * = 7, tick callback = FUN_801010f4 (level-local projectile physics).
 *
 * The target slot at puVar2[0x21] is set to the attacker's currentTarget
 * (+0xe4) if non-NULL, else the attacker itself -- i.e., the missile
 * tracks whomever the turret was already aiming at, falling back to
 * the attacker that hit us.
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int size, int flags);
extern int Bone_AllocSlot(int parent, uint16_t slotKey);
extern void Object_CopyMatrixFromBone(void *outMatrix, int parent, int bonePtr);
extern void Object_PostUpdate2(uint32_t obj);
extern void *FUN_801010f4;

uint32_t *SB_TurretSpawn(int self, int attacker)
{
    uint32_t *p = Object_Pool_AllocFromBank(
        (void *)(uintptr_t)*(uint32_t *)(self + 0x58), 0x1b7, 0x98, 8);
    int slot = Bone_AllocSlot(self, 0x8000);
    Object_CopyMatrixFromBone(p + 4, self, slot);

    p[0x12] = p[9];
    p[0x13] = p[10];
    p[0x14] = p[11];
    p[0]    = 0x84;
    *((int8_t *)p + 4) = 7;
    *((uint16_t *)p + 6) = *(uint16_t *)(self + 6);
    *(uint16_t *)(p + 3) = 0;
    p[0x19] = (uintptr_t)&FUN_801010f4;

    int target = *(int *)(attacker + 0xe4);
    if (target == 0) target = attacker;
    p[0x21] = (uint32_t)target;

    Object_PostUpdate2((uint32_t)(uintptr_t)p);
    return p;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_8010183c  (from analysis/dll/SCRTBASE/decomp/8010183c.c) --- */
// addr: 0x8010183c  name: FUN_8010183c

undefined4 * FUN_8010183c(int param_1,int param_2)

{
  undefined2 uVar1;
  undefined4 *puVar2;
  undefined4 uVar3;
  int iVar4;
  
  puVar2 = (undefined4 *)FUN_8001ac44/*0x8001ac44*/(*(undefined4 *)(param_1 + 0x58),0x1b7,0x98,8);
  uVar3 = FUN_8001b038/*0x8001b038*/(param_1,0x8000);
  FUN_8001d68c/*0x8001d68c*/(puVar2 + 4,param_1,uVar3);
  puVar2[0x12] = puVar2[9];
  puVar2[0x13] = puVar2[10];
  puVar2[0x14] = puVar2[0xb];
  *puVar2 = 0x84;
  *(undefined1 *)(puVar2 + 1) = 7;
  uVar1 = *(undefined2 *)(param_1 + 6);
  *(undefined2 *)(puVar2 + 3) = 0;
  puVar2[0x19] = FUN_801010f4;
  *(undefined2 *)((int)puVar2 + 6) = uVar1;
  iVar4 = *(int *)(param_2 + 0xe4);
  if (*(int *)(param_2 + 0xe4) == 0) {
    iVar4 = param_2;
  }
  puVar2[0x21] = iVar4;
  FUN_8002036c/*0x8002036c*/(puVar2);
  return puVar2;
}

#endif  /* GHIDRA REF */
