/* turret_sfx.c -- SCRTBASE turret/MSilo continuous SFX manager.
 *
 * Source: SCRTBASE.DLL  FUN_801003f4.
 *
 * Each tick, computes the 3D sound pan for `obj+0x48` (the turret's
 * world pos). If the resulting volume is non-zero (the listener can
 * hear it), updates the SPU voice volume (if already playing) and
 * calls Audio_PlaySfxAtPos(stream=2) with the current pan. Otherwise,
 * if the voice was playing, stops it via Audio_VoiceStop.
 *
 * The mid-tick `param_1+5` byte tracks the currently-assigned SPU
 * voice channel (0 = "not playing").
 *
 * MED confidence.
 */
#include <stdint.h>

extern uint32_t SfxPan_For3DPos(void *posXyz);                   /* FUN_800449bc */
extern void SPU_VoiceVolume_Set(int ch, uint32_t lr);            /* FUN_80044574 */
extern uint32_t SfxChannel_Acquire(void);                        /* FUN_8004410c */
extern void Audio_PlaySfx_inner(int ch, uint32_t bank, int sfxId, uint32_t pan);  /* FUN_800443c8 */
extern void Audio_VoiceStop(int ch);                             /* FUN_800441c8 */

void SB_TurretSfxTick(int obj, int sfxId)
{
    uint32_t pan = SfxPan_For3DPos((void *)(intptr_t)(obj + 0x48));
    if (pan != 0) {
        int8_t ch = *(int8_t *)(obj + 5);
        if (ch != 0) SPU_VoiceVolume_Set(ch, pan);
        ch = (int8_t)SfxChannel_Acquire();
        *(int8_t *)(obj + 5) = ch;
        Audio_PlaySfx_inner(ch, *(uint32_t *)(*(int *)(obj + 0x58) + 8), sfxId, pan);
    }
    if (*(int8_t *)(obj + 5) != 0) {
        Audio_VoiceStop(*(int8_t *)(obj + 5));
        *(int8_t *)(obj + 5) = 0;
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SCRTBASE.DLL FUN_801003f4  (from analysis/dll/SCRTBASE/decomp/801003f4.c) --- */
// addr: 0x801003f4  name: FUN_801003f4

void FUN_801003f4(int param_1,undefined4 param_2)

{
  char cVar1;
  int iVar2;
  int iVar3;
  
  iVar2 = FUN_800449bc/*0x800449bc*/(param_1 + 0x48);
  if (iVar2 != 0) {
    iVar3 = (int)*(char *)(param_1 + 5);
    if (iVar3 != 0) {
      FUN_80044574/*0x80044574*/(iVar3,iVar2);
    }
    cVar1 = FUN_8004410c/*0x8004410c*/(iVar3 != 0);
    *(char *)(param_1 + 5) = cVar1;
    FUN_800443c8/*0x800443c8*/((int)cVar1,*(undefined4 *)(*(int *)(param_1 + 0x58) + 8),param_2,iVar2);
  }
  if (*(char *)(param_1 + 5) != '\0') {
    FUN_800441c8/*0x800441c8*/();
    *(undefined1 *)(param_1 + 5) = 0;
  }
  return;
}

#endif  /* GHIDRA REF */
