/* misc.c -- Hoover Dam tiny collision/destruction handlers.
 *
 * Source: HOOVRDAM.DLL
 *   FUN_8010036c -- HD_TransformerCleanup(obj, mode)
 *                   On mode 7, stash the obj pointer into a global pool
 *                   slot (+0x58 of _DAT_800659fc) and queue a 0x80-byte
 *                   FX prim via FUN_8001d470. Always Heap_Free's the
 *                   passed object pointer.
 *   FUN_801013e0 -- HD_TransformerDestroy(obj, mode, impact)
 *                   On collision (mode 3 or 8) checks terrain, then
 *                   broadcasts the destruction by signalling the
 *                   paired object via FUN_8001fd9c with offset 1000.
 *   FUN_8010135c -- HD_PipeOutDestroy(obj, mode, impact)
 *                   Same shape; on hit invokes Damage_Apply on the
 *                   paired object.
 *   FUN_80101118 -- HD_ArchTransfImpact(obj, mode, impact)
 *                   On heavy collision spawns an audio cue via
 *                   FUN_8004483c (Audio_PlaySfxAtPos: param=6).
 *
 * HIGH-MED confidence across all four.
 */
#include <stdint.h>

extern void  Heap_Free(void *p);
extern void *Object_Pool_Alloc(uint32_t size);   /* FUN_8001d470 */
extern void  Damage_Apply(void *obj);
extern int   Collision_AgainstTerrain(int obj, int impact);    /* func_0x8002239c */
extern int   Collision_Circular     (int obj, int impact);    /* func_0x80022320 */
extern int   Object_FindByIdPlusOffset(int spawnId);            /* func_0x8001fd9c */
extern int   Object_FindByIdPlusOffset2(int spawnId);           /* func_0x80021888 */
extern void  Object_SetState(int obj, int state);               /* func_0x80024718 */
extern uint32_t SfxChannel_Acquire(void);                       /* FUN_8004410c */
extern void  Audio_PlaySfxAtPos(uint32_t ch, uint32_t bank, int sfxId, int posXyzAddr);  /* FUN_8004483c */

extern int8_t *_DAT_800659fc;

uint32_t HD_TransformerCleanup(void *obj, int mode)
{
    if (mode != 1) {
        if (mode != 7) return 0;
        *(void **)(_DAT_800659fc + 0x58) = obj;
        Object_Pool_Alloc(0x80);
        /* Ghidra noted obj is reloaded from $v1; we preserve the alias. */
    }
    Heap_Free(obj);
    return 0xffffffffu;
}

uint32_t HD_TransformerDestroy(int obj, uint32_t mode, void *impactCtx)
{
    if (mode == 3 || mode == 8) {
        Collision_AgainstTerrain(obj, (int)(intptr_t)impactCtx);
    }
    int hit = Collision_Circular(obj, (int)(intptr_t)impactCtx);
    if (hit == 0) return 0;
    int paired = Object_FindByIdPlusOffset(*(int16_t *)(obj + 6) + 1000);
    if (paired != 0) Object_SetState(paired + 0xc, 0);
    return 0xffffffffu;
}

uint32_t HD_PipeOutDestroy(int obj, uint32_t mode, void *impactCtx)
{
    if (mode == 3 || mode == 8) {
        Collision_AgainstTerrain(obj, (int)(intptr_t)impactCtx);
    }
    int hit = Collision_Circular(obj, (int)(intptr_t)impactCtx);
    if (hit == 0) return 0;
    int paired = Object_FindByIdPlusOffset2(*(int16_t *)(obj + 6) + 1000);
    if (paired == 0) return 0;
    Damage_Apply((void *)(intptr_t)paired);
    return 0;
}

uint32_t HD_ArchTransfImpact(int obj, uint32_t mode, int *impulse)
{
    if (mode == 3 || mode == 8) {
        if (*(int8_t *)(*impulse + 4) != 7) return 0;
        impulse = (int *)(uintptr_t)*(uint16_t *)(*impulse + 0xc);
    }
    int hit = Collision_Circular(obj, (int)(intptr_t)impulse);
    if (hit != 0) {
        uint32_t ch = SfxChannel_Acquire();
        Audio_PlaySfxAtPos(ch,
                           *(uint32_t *)(*(int *)(obj + 0x58) + 8),
                           6,
                           obj + 0x24);
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_8010036c  (from analysis/dll/HOOVRDAM/decomp/8010036c.c) --- */
// addr: 0x8010036c  name: FUN_8010036c

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_8010036c(undefined4 param_1,int param_2)

{
  undefined4 extraout_v1;
  
  if (param_2 != 1) {
    if (param_2 != 7) {
      return 0;
    }
    *(undefined4 *)(_DAT_800659fc + 0x58) = param_1;
    FUN_8001d470/*0x8001d470*/(0x80);
    param_1 = extraout_v1;
  }
  Heap_Free/*0x80045088*/(param_1);
  return 0xffffffff;
}

/* --- ? FUN_801013e0  (from analysis/dll/HOOVRDAM/decomp/801013e0.c) --- */
// addr: 0x801013e0  name: FUN_801013e0

undefined4 FUN_801013e0(int param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  uVar2 = 0;
  if (iVar1 != 0) {
    iVar1 = FUN_8001fd9c/*0x8001fd9c*/(*(short *)(param_1 + 6) + 1000);
    if (iVar1 != 0) {
      FUN_80024718/*0x80024718*/(iVar1 + 0xc,0);
    }
    uVar2 = 0xffffffff;
  }
  return uVar2;
}

/* --- ? FUN_8010135c  (from analysis/dll/HOOVRDAM/decomp/8010135c.c) --- */
// addr: 0x8010135c  name: FUN_8010135c

undefined4 FUN_8010135c(int param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    FUN_8002239c/*0x8002239c*/(param_1,param_3);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  uVar2 = 0;
  if (iVar1 != 0) {
    iVar1 = FUN_80021888/*0x80021888*/(*(short *)(param_1 + 6) + 1000);
    uVar2 = 0;
    if (iVar1 != 0) {
      uVar2 = FUN_800205f8/*0x800205f8*/(iVar1);
    }
  }
  return uVar2;
}

/* --- ? FUN_80101118  (from analysis/dll/HOOVRDAM/decomp/80101118.c) --- */
// addr: 0x80101118  name: FUN_80101118

undefined4 FUN_80101118(int param_1,int param_2,int *param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  if ((param_2 == 3) || (param_2 != 8)) {
    if (*(char *)(*param_3 + 4) != '\a') {
      return 0;
    }
    param_3 = (int *)(uint)*(ushort *)(*param_3 + 0xc);
  }
  iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3);
  if (iVar1 != 0) {
    uVar2 = FUN_8004410c/*0x8004410c*/();
    FUN_8004483c/*0x8004483c*/(uVar2,*(undefined4 *)(*(int *)(param_1 + 0x58) + 8),6,param_1 + 0x24);
  }
  return 0;
}

#endif  /* GHIDRA REF */
