/* misc2.c -- more Hoover Dam handlers.
 *
 * Source: HOOVRDAM.DLL
 *   FUN_80101a98 -- HD_TransfBoxBroadcast: on Damage event, compute
 *                   the destructible's grid cell (i16 of posX/Z high
 *                   half via the standard +0xffff round, then 1x1 cell
 *                   size) and Object_SetState(cellRect, 0x8f80).
 *                   This is the "powerline transformer collapses ->
 *                   surrounding area goes dark" effect trigger.
 *   FUN_80100b40 -- HD_PipeChildSpawn: small generic projectile/child
 *                   spawner with explicit (bank, kind, pos, animSlot,
 *                   spriteSlot, lifetimeMaybe) args. Sets state 0xa4,
 *                   tick = FUN_80100a18 (HD's standard projectile tick).
 *
 * MED-HIGH confidence.
 */
#include <stdint.h>

extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern int  FUN_8002239c(uint32_t *self, int32_t *impulse);
extern uint32_t FUN_80022320(uint32_t *self, uint32_t amount);
extern void Object_SetState(int obj, int state);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int u, int flags);
extern void Object_RandomizeRotation(uint32_t *obj);   /* FUN_80016da8 */
extern void Object_RegisterInScene(uint32_t *obj);     /* FUN_800202f4 */
extern void FUN_80020890(uint32_t *obj, int timer);
extern int  FUN_8004410c(void);
extern void FUN_800447e8(int voice, uint32_t bank, int sfx, const void *pos);
extern uint32_t HD_ScatterTick(int obj, uint32_t mode);  /* FUN_80100a18 */

uint32_t HD_TransfBoxBroadcast(int obj, uint32_t mode, void *impactCtx)
{
    int hit = 0;
    if (mode != 8 && (hit = FUN_8002239c((uint32_t *)(uintptr_t)(uint32_t)obj, (int32_t *)impactCtx)) != 0) {
        goto fire;
    }
    if ((hit = (int)FUN_80022320((uint32_t *)(uintptr_t)(uint32_t)obj, (uint32_t)(uintptr_t)impactCtx)) == 0) return 0;
fire:
    {
        int32_t px = *(int32_t *)(obj + 0x48);
        int32_t pz = *(int32_t *)(obj + 0x50);
        if (px < 0) px += 0xffff;
        if (pz < 0) pz += 0xffff;
        int16_t rect[4] = {
            (int16_t)((uint32_t)px >> 16),
            (int16_t)((uint32_t)pz >> 16),
            1, 1,
        };
        Object_SetState((int)(uintptr_t)rect, 0x8f80);
    }
    return 0;
}

uint32_t FUN_80101a98(int obj, uint32_t mode, void *impactCtx)
{
    return HD_TransfBoxBroadcast(obj, mode, impactCtx);
}

uint32_t *HD_PipeChildSpawn(uint32_t *parentPos, uint32_t bank, uint16_t kind,
                            uint16_t animSlot, uint16_t spriteSlot, uint32_t lifetime)
{
    uint32_t *c = Object_Pool_AllocFromBank((void *)(uintptr_t)bank, kind, 0x9c, 8);
    Object_RandomizeRotation(c + 4);
    c[9]  = parentPos[0];
    c[10] = parentPos[1];
    c[11] = parentPos[2];
    Object_SetCallbackPsxSlot(c, (uintptr_t)&HD_ScatterTick);
    c[0x15] = 0x8000;
    c[0x26] = bank;
    *(uint16_t *)((uint8_t *)c + 0x96) = animSlot;
    c[0] |= 0xa4u;
    *(uint16_t *)((uint8_t *)c + 0x82) = spriteSlot;
    Object_RegisterInScene(c);
    FUN_80020890(c, (int)lifetime);
    FUN_800447e8(FUN_8004410c(), *(uint32_t *)(uintptr_t)(bank + 8), 0, parentPos);
    return c;
}

uint32_t *FUN_80100b40(uint32_t *parentPos, uint32_t bank, uint16_t kind,
                       uint16_t animSlot, uint16_t spriteSlot, uint32_t lifetime)
{
    return HD_PipeChildSpawn(parentPos, bank, kind, animSlot, spriteSlot, lifetime);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80101a98  (from analysis/dll/HOOVRDAM/decomp/80101a98.c) --- */
// addr: 0x80101a98  name: FUN_80101a98

undefined4 FUN_80101a98(int param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  undefined2 local_10;
  undefined2 local_e;
  undefined2 local_c;
  undefined2 local_a;
  
  if ((((param_2 == 3) || (param_2 != 8)) && (iVar1 = FUN_8002239c/*0x8002239c*/(param_1,param_3), iVar1 != 0))
     || (iVar1 = FUN_80022320/*0x80022320*/(param_1,param_3), iVar1 != 0)) {
    iVar1 = *(int *)(param_1 + 0x48);
    local_10 = (undefined2)((uint)iVar1 >> 0x10);
    if (iVar1 < 0) {
      local_10 = (undefined2)((uint)(iVar1 + 0xffff) >> 0x10);
    }
    iVar1 = *(int *)(param_1 + 0x50);
    if (iVar1 < 0) {
      iVar1 = iVar1 + 0xffff;
    }
    local_e = (undefined2)((uint)iVar1 >> 0x10);
    local_c = 1;
    local_a = 1;
    FUN_80024718/*0x80024718*/(&local_10,0x8f80);
  }
  return 0;
}

/* --- ? FUN_80100b40  (from analysis/dll/HOOVRDAM/decomp/80100b40.c) --- */
// addr: 0x80100b40  name: FUN_80100b40

uint * FUN_80100b40(uint *param_1,uint param_2,undefined2 param_3,undefined2 param_4,
                   undefined2 param_5,undefined4 param_6)

{
  uint *puVar1;
  undefined4 uVar2;
  uint uVar3;
  uint uVar4;
  
  puVar1 = (uint *)FUN_8001ac44/*0x8001ac44*/(param_2,param_3,0x9c,8);
  FUN_80016da8/*0x80016da8*/(puVar1 + 4);
  uVar3 = param_1[1];
  uVar4 = param_1[2];
  puVar1[9] = *param_1;
  puVar1[10] = uVar3;
  puVar1[0xb] = uVar4;
  puVar1[0x19] = (uint)FUN_80100a18;
  puVar1[0x15] = 0x8000;
  puVar1[0x26] = param_2;
  *(undefined2 *)((int)puVar1 + 0x96) = param_4;
  *puVar1 = *puVar1 | 0xa4;
  *(undefined2 *)((int)puVar1 + 0x82) = param_5;
  FUN_800202f4/*0x800202f4*/(puVar1);
  FUN_80020890/*0x80020890*/(puVar1,param_6);
  uVar2 = FUN_8004410c/*0x8004410c*/();
  FUN_800447e8/*0x800447e8*/(uVar2,*(undefined4 *)(param_2 + 8),0,param_1);
  return puVar1;
}

/* --- ? FUN_80100a18  (from analysis/dll/HOOVRDAM/decomp/80100a18.c) --- */
// addr: 0x80100a18  name: FUN_80100a18

undefined4 FUN_80100a18(int param_1,uint param_2)

{
  short sVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  
  if (param_2 != 2) {
    uVar2 = 5;
    if (((param_2 < 3) && (uVar2 = 0, param_2 == 0)) || (param_2 != uVar2)) {
      sVar1 = *(short *)(param_1 + 0x80) + -1;
      *(short *)(param_1 + 0x80) = sVar1;
      if (sVar1 == -1) {
        iVar3 = FUN_8001ac44/*0x8001ac44*/(*(undefined4 *)(param_1 + 0x98),*(undefined2 *)(param_1 + 0x96),0x80
                                ,8);
        iVar4 = FUN_80017160/*0x80017160*/();
        iVar5 = *(int *)(param_1 + 0x54);
        *(undefined4 *)(iVar3 + 0x28) = 0;
        *(int *)(iVar3 + 0x24) = (iVar4 * 2 * iVar5 >> 0xf) - iVar5;
        iVar4 = FUN_80017160/*0x80017160*/();
        iVar5 = *(int *)(param_1 + 0x54);
        *(undefined4 *)(iVar3 + 100) = 0x8003e80c;
        *(int *)(iVar3 + 0x2c) = (iVar4 * 2 * iVar5 >> 0xf) - iVar5;
        FUN_8001d4f0/*0x8001d4f0*/(param_1);
        *(undefined2 *)(param_1 + 0x80) = *(undefined2 *)(param_1 + 0x82);
      }
      if (*(int *)(param_1 + 0x38) != 0) {
        return 0;
      }
      FUN_800205f8/*0x800205f8*/(param_1);
    }
    *(undefined4 *)(param_1 + 0x60) = 0;
  }
  *(undefined2 *)(param_1 + 0x80) = 0xffff;
  return 0;
}

#endif  /* GHIDRA REF */
