/* powerline.c -- Hoover Dam PowerPlant_L/R fall + sparks.
 *
 * Source: HOOVRDAM.DLL  FUN_80101464.
 *
 * Tick-mode state machine:
 *   mode 0 (idle drop): subtract 0x3b9a from posZ each tick (slow fall).
 *     If hit by impulse, update 3D sfx pan.
 *   mode 3 (collision): if impulser is in state 2, set vy = 0xfff70f80
 *     (= -0xf080, sharp downward), call Water_FloodAtPos at impulse
 *     pos+0x24, play sfx 0x41, fall through to mode 2.
 *   mode 1 (init / re-init): acquire a voice + play sfx 2 looped.
 *   mode 2 (destroyed): Damage_Apply on the impulser, then init.
 *   mode 4 (teardown): stop the voice.
 *
 * Used by PowerPlant_L / PowerPlant_R -- the power-plant towers that
 * topple when struck.
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t SfxPan_For3DPos(void *posXyz);
extern void SPU_VoiceVolume_Set(int ch, uint32_t lr);
extern uint32_t SfxChannel_Acquire(void);
extern void Audio_PlaySfxAtPos(uint32_t ch, uint32_t bank, int sfxId, int posXyzAddr);
extern void Audio_PlaySfx_inner(int ch, uint32_t bank, int sfxId, uint32_t pan);
extern void Audio_VoiceStop(int ch);
extern void Water_FloodAtPos(int posXyzAddr);
extern void Damage_Apply(void *obj);
extern uint32_t _DAT_800658fc;

uint32_t HD_PowerlineTick(int obj, uint32_t mode, int *impulse)
{
    int chOwner = obj;

    switch (mode) {
    case 0:
        *(int32_t *)(obj + 0x2c) -= 0x3b9a;
        if (impulse == NULL) return 0;
        {
            uint32_t pan = SfxPan_For3DPos((void *)(intptr_t)(obj + 0x24));
            SPU_VoiceVolume_Set((int)*(int8_t *)(obj + 5), pan);
        }
        /* fall through */
    case 3: {
        int hitObj = *impulse;
        if (*(int8_t *)(hitObj + 4) == 2) {
            chOwner = hitObj + 0x24;
            *(uint32_t *)(hitObj + 0x84) = 0xfff70f80u;
            Water_FloodAtPos(chOwner);
            uint32_t ch = SfxChannel_Acquire();
            Audio_PlaySfxAtPos(ch, _DAT_800658fc, 0x41, chOwner);
            goto case2;
        }
        break;
    }
case2:
    case 2:
        Damage_Apply((void *)(intptr_t)chOwner);
        obj = 1;
        /* fall through */
    case 1: {
        int8_t ch = (int8_t)SfxChannel_Acquire();
        *(int8_t *)(chOwner + 5) = ch;
        Audio_PlaySfx_inner(ch, *(uint32_t *)(*(int *)(chOwner + 0x58) + 8), 2, 0);
        /* fall through */
    }
    case 4:
        Audio_VoiceStop((int)*(int8_t *)(chOwner + 5));
        break;
    default:
        break;
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- HOOVRDAM.DLL FUN_80101464  (from analysis/dll/HOOVRDAM/decomp/80101464.c) --- */
// addr: 0x80101464  name: FUN_80101464

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_80101464(int param_1,undefined4 param_2,int *param_3)

{
  char cVar1;
  undefined4 uVar2;
  int iVar3;
  int iVar4;
  
  iVar4 = param_1;
  switch(param_2) {
  case 0:
    *(int *)(param_1 + 0x2c) = *(int *)(param_1 + 0x2c) + -0x3b9a;
    if (param_3 == (int *)0x0) {
      return 0;
    }
    uVar2 = FUN_800449bc/*0x800449bc*/(param_1 + 0x24);
    FUN_80044574/*0x80044574*/((int)*(char *)(param_1 + 5),uVar2);
  case 3:
    iVar3 = *param_3;
    if (*(char *)(iVar3 + 4) == '\x02') {
      iVar4 = iVar3 + 0x24;
      *(undefined4 *)(iVar3 + 0x84) = 0xfff70f80;
      FUN_80040234/*0x80040234*/(iVar4);
      uVar2 = FUN_8004410c/*0x8004410c*/();
      FUN_8004483c/*0x8004483c*/(uVar2,_DAT_800658fc,0x41,iVar4);
switchD_80101494_caseD_2:
      FUN_800205f8/*0x800205f8*/(iVar4);
      param_1 = 1;
      goto switchD_80101494_caseD_1;
    }
    break;
  case 1:
switchD_80101494_caseD_1:
    cVar1 = FUN_8004410c/*0x8004410c*/(param_1);
    *(char *)(iVar4 + 5) = cVar1;
    FUN_800443c8/*0x800443c8*/((int)cVar1,*(undefined4 *)(*(int *)(iVar4 + 0x58) + 8),2,0);
  case 4:
    FUN_800441c8/*0x800441c8*/((int)*(char *)(iVar4 + 5));
    break;
  case 2:
    goto switchD_80101494_caseD_2;
  default:
    break;
  }
  return 0;
}

#endif  /* GHIDRA REF */
