/* scatter.c -- Hoover Dam parking_meter/transformer scatter (same idiom
 * as CC_RandomScatterTick).
 *
 * Source: HOOVRDAM.DLL  FUN_80100a18.
 *
 * Identical body to CC_RandomScatterTick (CASNOCTY.DLL spawner2.c):
 * decrement obj+0x80 countdown; on -1 spawn random-position child
 * in obj+0x54 cube; reload countdown. Plus extra guard: returns
 * early if obj has children at +0x38, else cascades to
 * Damage_Apply(self) and clears the child-bone slot at +0x60.
 *
 * MED.
 */
#include <stdint.h>

extern uint32_t V8_RandNext(void);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int u, int flags);
extern void Object_SetCallbackPsxSlot(void *obj, uintptr_t callback);
extern void Object_BumpSubstate_Or_FX(int obj);     /* FUN_8001d4f0 */
extern void Damage_Apply(void *obj);
extern int LAB_8003e80c(int obj, int event, int param3);

uint32_t HD_ScatterTick(int obj, uint32_t mode)
{
    if (mode == 2) goto applyTermFlag;
    if (mode != 5 && mode != 0) goto clearChildSlot;

    int16_t *countdown = (int16_t *)(intptr_t)(obj + 0x80);
    int16_t prev = *countdown;
    *countdown = (int16_t)(prev - 1);
    if (prev == 0) {
        uint32_t *child = Object_Pool_AllocFromBank(
            (void *)(uintptr_t)*(uint32_t *)(obj + 0x98),
            *(uint16_t *)(obj + 0x96), 0x80, 8);
        int32_t r = *(int32_t *)(obj + 0x54);
        int32_t rx = ((int)V8_RandNext() * 2 * r >> 15) - r;
        int32_t rz = ((int)V8_RandNext() * 2 * r >> 15) - r;
        *(int32_t *)((uint8_t *)child + 0x28) = 0;
        *(int32_t *)((uint8_t *)child + 0x24) = rx;
        *(int32_t *)((uint8_t *)child + 0x2c) = rz;
        Object_SetCallbackPsxSlot(child, (uintptr_t)&LAB_8003e80c);
        Object_BumpSubstate_Or_FX(obj);
        *countdown = *(int16_t *)(obj + 0x82);
    }
    if (*(int *)(obj + 0x38) != 0) return 0;
    Damage_Apply((void *)(intptr_t)obj);

clearChildSlot:
    *(int *)(obj + 0x60) = 0;
applyTermFlag:
    *(uint16_t *)(obj + 0x80) = 0xffff;
    return 0;
}

uint32_t FUN_80100a18(int obj, uint32_t mode)
{
    return HD_ScatterTick(obj, mode);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- HOOVRDAM.DLL FUN_80100a18  (from analysis/dll/HOOVRDAM/decomp/80100a18.c) --- */
// addr: 0x80100a18  name: FUN_80100a18

undefined4 FUN_80100a18(int param_1,uint param_2)

{
  short sVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  
  if (param_2 != 2) {
    uVar2 = 5;
    if (((param_2 < 3) && (uVar2 = 0, param_2 == 0)) || (param_2 != uVar2)) {
      sVar1 = *(short *)(param_1 + 0x80) + -1;
      *(short *)(param_1 + 0x80) = sVar1;
      if (sVar1 == -1) {
        iVar3 = FUN_8001ac44/*0x8001ac44*/(*(undefined4 *)(param_1 + 0x98),*(undefined2 *)(param_1 + 0x96),0x80
                                ,8);
        iVar4 = FUN_80017160/*0x80017160*/();
        iVar5 = *(int *)(param_1 + 0x54);
        *(undefined4 *)(iVar3 + 0x28) = 0;
        *(int *)(iVar3 + 0x24) = (iVar4 * 2 * iVar5 >> 0xf) - iVar5;
        iVar4 = FUN_80017160/*0x80017160*/();
        iVar5 = *(int *)(param_1 + 0x54);
        *(undefined4 *)(iVar3 + 100) = 0x8003e80c;
        *(int *)(iVar3 + 0x2c) = (iVar4 * 2 * iVar5 >> 0xf) - iVar5;
        FUN_8001d4f0/*0x8001d4f0*/(param_1);
        *(undefined2 *)(param_1 + 0x80) = *(undefined2 *)(param_1 + 0x82);
      }
      if (*(int *)(param_1 + 0x38) != 0) {
        return 0;
      }
      FUN_800205f8/*0x800205f8*/(param_1);
    }
    *(undefined4 *)(param_1 + 0x60) = 0;
  }
  *(undefined2 *)(param_1 + 0x80) = 0xffff;
  return 0;
}

#endif  /* GHIDRA REF */
