/* transformer.c -- Hoover Dam transformer aim + collapse.
 *
 * Source: HOOVRDAM.DLL  FUN_801003c4.
 *
 * Aims a transformer at the camera (the player view). Each tick:
 *   1. Compute camera-space delta: (obj.pos - camera_pos) / N
 *      where N is a divisor from param_3, with offsets +0x5f5
 *      and +0x1dcd along x/y to compensate for the dam's tilt.
 *   2. Project that vector through the world->camera matrix at
 *      DAT_8006f680 to get screen-space direction.
 *   3. Build a YXZ rotation matrix pointing at the camera.
 *   4. Walk the obj.children chain (+0xe -> next +0x34) and write
 *      that rotation into each child's +0x10 matrix slot, plus
 *      adjust their +0x2c (Z) to wrap modulo 0x40000 (= +0x20000
 *      half-range).
 *   5. After visiting all children, alloc an effect prim (0x80 bytes)
 *      tied to obj at +0x58, slot at +0xa = param_3 ("event index").
 *   6. If difficulty > 2, Heap_Free obj (= "transformer destroyed at
 *      hard difficulty" sub-clause -- the entire transformer goes
 *      away rather than just toppling).
 *   7. Sets flag 0xa0 on obj.
 *   8. Spawn 0x40 (64) random debris particles, each with random
 *      direction (V8_RandNext, << 17 >> 13 = scale into world units).
 *
 * MED.
 */
#include <stdint.h>

extern int32_t  GTE_RotateLongMat(uint32_t mAddr, int32_t *src, int32_t *dst);
extern long ratan2(int y, int x);
extern void RotMatrixYXZ_gte(void *euler, void *m);
extern uint32_t *Object_Pool_Alloc(uint32_t size);
extern uint32_t *Object_Pool_AllocFromBank(void *bank, uint16_t kind, int size, int flags);
extern uint32_t V8_RandNext(void);
extern void ImpactSparks_Spawn(void *obj);
extern void Object_BumpSubstate_Or_FX(void *parent, void *child);   /* FUN_8001d4f0 */
extern void Heap_Free(void *p);
extern int32_t DAT_8006f6f4, DAT_8006f6f8, DAT_8006f6fc;
extern int32_t DAT_8006f6e4, DAT_8006f6ea, DAT_8006f6f0;
extern int8_t  DAT_80065319;     /* g_difficulty */

uint32_t HD_TransformerAim(uint32_t *self, int mode, int divisor)
{
    if (mode == 1) goto spawn;
    if (mode != 0 && mode != 7) goto spawn;
    if (divisor == 0) return 0;

    uint32_t cx = (uint32_t)(DAT_8006f6f4 + DAT_8006f6e4 * 0x40);
    uint32_t cy = (uint32_t)(DAT_8006f6f8 + DAT_8006f6ea * 0x40);
    uint32_t cz = (uint32_t)(DAT_8006f6fc + DAT_8006f6f0 * 0x40);

    int32_t local[4];
    local[0] = ((int32_t)(self[9]  - cx) + divisor * 0x5f5) / divisor;
    local[1] = ((int32_t)(self[10] - cy) + divisor * 0x1dcd) / divisor;
    local[2] = ((int32_t)(self[11] - cz)) / divisor;

    GTE_RotateLongMat(0x8006f680u, local, local);
    self[9]  = cx;
    self[10] = cy;
    self[11] = cz;

    int16_t euler[3];
    euler[0] = (int16_t)ratan2(local[2], local[1]);
    euler[1] = 0;
    euler[2] = (int16_t)-ratan2(local[0], local[1]);

    uint32_t m[8];
    RotMatrixYXZ_gte(euler, m);

    /* Walk children -- write rotation, wrap Z. */
    uint32_t child = self[0xe];
    if (child != 0) {
        do {
            *(uint32_t *)(child + 0x10) = m[0];
            *(uint32_t *)(child + 0x14) = m[1];
            *(uint32_t *)(child + 0x18) = m[2];
            *(uint32_t *)(child + 0x1c) = m[3];
            *(uint16_t *)(child + 0x20) = (uint16_t)m[4];
            *(uint32_t *)(child + 0x2c) =
                ((*(uint32_t *)(child + 0x2c) + (uint32_t)local[2] + 0x20000) & 0x3ffff) - 0x20000;
            child = *(uint32_t *)(child + 0x34);
        } while (child != 0);
    }

    /* Spawn effect prim. */
    uint32_t *fx = Object_Pool_Alloc(0x80);
    *(uint32_t **)((uintptr_t)fx + 0x58) = self;
    *(int16_t *)((uintptr_t)fx + 0xa) = (int16_t)divisor;

spawn:
    if (DAT_80065319 > 2) {
        Heap_Free(self);
        return 0;
    }
    self[0] |= 0xa0u;

    for (int i = 0; i < 0x40; i++) {
        uint32_t *p = Object_Pool_AllocFromBank((void *)(uintptr_t)self[0x16],
            *(uint16_t *)((uintptr_t)self + 0xa), 0x80, 0);
        p[0] |= 0x410u;
        int r0 = (int)V8_RandNext(); p[0x12] = (uint32_t)((r0 << 17) >> 13);
        int r1 = (int)V8_RandNext(); p[0x13] = (uint32_t)((r1 << 17) >> 13);
        int r2 = (int)V8_RandNext(); p[0x14] = (uint32_t)((r2 << 17) >> 13);
        *(uint16_t *)(p[0xc] + 0x28) = 0x40;
        ImpactSparks_Spawn(p);
        Object_BumpSubstate_Or_FX(self, p);
    }
    return 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- HOOVRDAM.DLL FUN_801003c4  (from analysis/dll/HOOVRDAM/decomp/801003c4.c) --- */
// addr: 0x801003c4  name: FUN_801003c4

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_801003c4(uint *param_1,int param_2,int param_3)

{
  uint *puVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  undefined2 local_60;
  undefined2 local_5e;
  short local_5c;
  int local_58;
  int local_54;
  int local_50;
  undefined4 local_48;
  undefined4 local_44;
  undefined4 local_40;
  undefined4 local_3c;
  undefined2 local_38;
  
  if (param_2 != 1) {
    if ((param_2 == 0) || (param_2 != 7)) {
      if (param_3 == 0) {
        return 0;
      }
      uVar4 = _DAT_8006f6f4 + _DAT_8006f6e4 * 0x40;
      iVar7 = (param_1[9] - uVar4) + param_3 * 0x5f5;
      local_58 = iVar7 / param_3;
      uVar3 = _DAT_8006f6f8 + _DAT_8006f6ea * 0x40;
      iVar6 = (param_1[10] - uVar3) + param_3 * 0x1dcd;
      local_54 = iVar6 / param_3;
      uVar2 = _DAT_8006f6fc + _DAT_8006f6f0 * 0x40;
      iVar5 = param_1[0xb] - uVar2;
      local_50 = iVar5 / param_3;
      GTE_RotateLongMat/*0x80043358*/(0x8006f680,&local_58,&local_58);
      param_1[9] = uVar4;
      param_1[10] = uVar3;
      param_1[0xb] = uVar2;
      local_60 = ratan2/*0x8004ecd4*/(local_50,local_54);
      local_5e = 0;
      local_5c = ratan2/*0x8004ecd4*/(local_58,local_54);
      local_5c = -local_5c;
      RotMatrixYXZ_gte/*0x8004dab4*/(&local_60,&local_48);
      uVar2 = param_1[0xe];
      if (uVar2 == 0) {
        return 0;
      }
      do {
        *(undefined4 *)(uVar2 + 0x10) = local_48;
        *(undefined4 *)(uVar2 + 0x14) = local_44;
        *(undefined4 *)(uVar2 + 0x18) = local_40;
        *(undefined4 *)(uVar2 + 0x1c) = local_3c;
        *(undefined2 *)(uVar2 + 0x20) = local_38;
        *(uint *)(uVar2 + 0x24) = (*(int *)(uVar2 + 0x24) + iVar7 + 0x20000U & 0x3ffff) - 0x20000;
        *(uint *)(uVar2 + 0x28) = (*(int *)(uVar2 + 0x28) + iVar6 + 0x20000U & 0x3ffff) - 0x20000;
        *(uint *)(uVar2 + 0x2c) = (*(int *)(uVar2 + 0x2c) + iVar5 + 0x20000U & 0x3ffff) - 0x20000;
        uVar2 = *(uint *)(uVar2 + 0x34);
      } while (uVar2 != 0);
    }
    iVar5 = FUN_8001d470/*0x8001d470*/(0x80);
    *(uint **)(iVar5 + 0x58) = param_1;
    *(short *)(iVar5 + 10) = (short)param_3;
  }
  iVar5 = 0;
  if ('\x02' < DAT_80065319) {
    Heap_Free/*0x80045088*/(param_1);
  }
  *param_1 = *param_1 | 0xa0;
  do {
    puVar1 = (uint *)FUN_8001ac44/*0x8001ac44*/(param_1[0x16],*(undefined2 *)((int)param_1 + 10),0x80,0);
    *puVar1 = *puVar1 | 0x410;
    iVar6 = FUN_80017160/*0x80017160*/();
    puVar1[0x12] = (iVar6 << 0x11) >> 0xd;
    iVar6 = FUN_80017160/*0x80017160*/();
    puVar1[0x13] = (iVar6 << 0x11) >> 0xd;
    iVar6 = FUN_80017160/*0x80017160*/();
    iVar5 = iVar5 + 1;
    puVar1[0x14] = (iVar6 << 0x11) >> 0xd;
    *(undefined2 *)(puVar1[0xc] + 0x28) = 0x40;
    FUN_8001d708/*0x8001d708*/(puVar1);
    FUN_8001d4f0/*0x8001d4f0*/(param_1,puVar1);
  } while (iVar5 < 0x40);
  return 0;
}

#endif  /* GHIDRA REF */
