/* asset_load_ordie.c -- Asset_LoadFile + fatal trap on failure.
 *
 * Source: SLUS_005.10  FUN_80015f80.
 *
 * The "named" variant of Asset_LoadFile. Callers latch the path name
 * via Iso_LatchPathArg(name) (or pass the name in as the first arg --
 * Ghidra loses argument visibility for thin one-liner wrappers); this
 * function calls the no-arg Asset_LoadFile and triggers the splash
 * fatal trap if the load returns NULL.
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern void *Asset_LoadFile(void);
extern void  Stream_FatalOom(const char *msg);

void *Asset_LoadFileOrDie(const char *pathArg)
{
    void *p = Asset_LoadFile();
    if (p == NULL) Stream_FatalOom(pathArg);
    return p;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80015f80  (from analysis/SLUS_005.10/decomp/80015f80.c) --- */
// addr: 0x80015f80  name: FUN_80015f80

void FUN_80015f80(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = FUN_80015948();
  if (iVar1 == 0) {
    FUN_80015368(param_1);
  }
  return;
}

#endif  /* GHIDRA REF */
