/* boot_init.c -- boot-time CD/heap initialization.
 *
 * Source: SLUS_005.10  FUN_80015e8c.
 *
 * Boot sequence:
 *   1. CdInit() -- bring up the CD-ROM hardware.
 *   2. Read sector 0x10 (the ISO9660 Primary Volume Descriptor) into a
 *      2 KiB scratch buffer.
 *   3. Cache the first 32 bytes of the PVD into DAT_8006f608..624 for
 *      future "same disc?" checks (Iso_VerifyOriginalDisc).
 *   4. Pull the root-directory location and length out of the PVD
 *      (PVD offset 0x9c contains the root directory record; bytes
 *      +2..+9 are the LBA and size, both as the standard ISO9660
 *      both-endian pair -- only the LE half is consumed here).
 *   5. Allocate a 0x514-byte DirRecord and call Iso_ReadDir to walk
 *      the entire on-disc directory tree into RAM.
 *
 * After this returns, `iRam000006b4` points at the root DirRecord, and
 * Iso_OpenPath can resolve any file by name.
 *
 * The unaligned-read gymnastics in the Ghidra pseudo-C are caused by
 * the PVD record being a packed structure: the root-dir record sits at
 * a non-aligned offset inside the 2 KiB sector buffer. We expose the
 * intent (read u32 startSector / u32 sizeBytes from the root-dir
 * record) instead of the bit-shift dance.
 *
 * HIGH confidence on the high-level shape; MED on the exact PVD offsets
 * (0x9c+2 / 0x9c+10) -- the ISO9660 spec fixes them, but pass 2 should
 * cross-check against the actual sector layout dumped from disc.
 */
#include <stdint.h>

extern void  CdInit(void);
extern void *V8_CdReadSectors(void *buf, int sector, int mode);
extern void *Iso_ReadDir(void *parent, int startSector, int dirSize);
extern void *Heap_AllocOrRetry(uint32_t n);
extern void *V8_MemCopy(void *dst, const void *src, int n);

extern uintptr_t iRam000006b4;    /* root DirRecord pointer */
extern uint8_t   DAT_8006f608[32]; /* cached PVD signature for "same disc?" */

#define PVD_SECTOR              0x10
#define PVD_ROOT_DIR_RECORD_OFF 0x9c   /* 156-byte preamble per ISO9660 */

void Boot_Init(void)
{
    CdInit();

    /* Read the PVD sector into a 2 KiB stack buffer. */
    uint8_t sector[0x800] __attribute__((aligned(4)));
    V8_CdReadSectors(sector, PVD_SECTOR, 1);

    /* Cache the first 32 bytes (the volume signature: "CD001" + version
     * + system identifier prefix) for later disc-swap detection. */
    V8_MemCopy(DAT_8006f608, sector + 8, 32);

    /* Pull root LBA + size from the PVD's root dir record. The record
     * starts at sector + 0x9c; LBA(LE) is at +2, size(LE) at +10. */
    const uint8_t *rdr = sector + PVD_ROOT_DIR_RECORD_OFF;
    uint32_t rootLBA;  V8_MemCopy(&rootLBA, rdr + 2,  4);
    uint32_t rootSize; V8_MemCopy(&rootSize, rdr + 10, 4);

    void *root = Heap_AllocOrRetry(0x514);
    iRam000006b4 = (uintptr_t)Iso_ReadDir(root, (int)rootLBA, (int)rootSize);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80015e8c  (from analysis/SLUS_005.10/decomp/80015e8c.c) --- */
// addr: 0x80015e8c  name: FUN_80015e8c

void FUN_80015e8c(void)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  undefined4 uVar9;
  uint unaff_s1;
  undefined1 auStack_810 [40];
  undefined4 uStack_7e8;
  undefined4 uStack_7e4;
  undefined4 uStack_7e0;
  undefined4 uStack_7dc;
  undefined4 uStack_7d8;
  undefined4 uStack_7d4;
  uint uStack_7d0;
  undefined4 uStack_7cc;
  undefined1 auStack_772 [8];
  undefined1 auStack_76a [1882];
  
  CdInit();
  FUN_800154f4(auStack_810,0x10,1);
  DAT_8006f608 = uStack_7e8;
  DAT_8006f60c = uStack_7e4;
  DAT_8006f610 = uStack_7e0;
  DAT_8006f614 = uStack_7dc;
  DAT_8006f618 = uStack_7d8;
  DAT_8006f61c = uStack_7d4;
  DAT_8006f620 = uStack_7d0;
  DAT_8006f624 = uStack_7cc;
  uVar1 = (uint)(auStack_76a + 3) & 3;
  iVar3 = *(int *)(auStack_76a + 3 + -uVar1);
  uVar5 = (uint)auStack_76a & 3;
  uVar7 = *(uint *)(auStack_76a + -uVar5);
  uVar2 = (uint)(auStack_772 + 3) & 3;
  iVar4 = *(int *)(auStack_772 + 3 + -uVar2);
  uVar6 = (uint)auStack_772 & 3;
  uVar8 = *(uint *)(auStack_772 + -uVar6);
  uVar9 = FUN_800116f4(0x514);
  uRam000006b4 = FUN_80015c68(uVar9,(iVar4 << (3 - uVar2) * 8 |
                                    unaff_s1 & 0xffffffffU >> (uVar2 + 1) * 8) &
                                    -1 << (4 - uVar6) * 8 | uVar8 >> uVar6 * 8,
                              (iVar3 << (3 - uVar1) * 8 |
                              uStack_7d0 & 0xffffffffU >> (uVar1 + 1) * 8) & -1 << (4 - uVar5) * 8 |
                              uVar7 >> uVar5 * 8);
  return;
}

#endif  /* GHIDRA REF */
