/* cd_toc.c -- read the CD table of contents into the per-track position table.
 *
 * Source: SLUS_005.10  FUN_80043a74.
 *
 * Busy-polls CdGetToc until it returns a non-zero track count (the BIOS
 * is asynchronous; the first call may return 0 while it waits for the
 * drive). Pops the per-track start position from the BIOS into the
 * fixed table at DAT_800a3090 (which is read by CD_PlayTrack).
 *
 * The trailing "-2 if the disc has a data + audio mix" tweak (subtract
 * the data-track count from the track count) makes the disc-type=4
 * (PSX with audio) numbering line up with the disc-type=3 (PSX only)
 * numbering used by the rest of the audio code.
 *
 * HIGH confidence.
 */
#include <stdint.h>
#include "structs.h"

extern int    CdGetToc   (CdlLOC *tocBuf);
extern int    CdPosToInt (const CdlLOC *pos);
extern void   CdIntToPos (int sector, CdlLOC *pos);
extern CdlLOC DAT_800a3090[];   /* track-position table (track 0 = first index) */
extern uint8_t bRam000008f8;     /* track count latch */
extern uint8_t uRam000005ac;     /* disc-type code (see cd_audio.c) */

void Audio_RefreshKeyState(void)
{
    uint32_t n;
    do {
        n = (uint32_t)CdGetToc(DAT_800a3090);
        bRam000008f8 = (uint8_t)n;
    } while ((n & 0xff) == 0);

    /* DAT_800a3090[0] is the leadout position; convert to int sector,
     * subtract the 150-sector lead-in offset, and store back into the
     * "leadout" slot (just past the actual tracks). */
    int leadoutSec = CdPosToInt(&DAT_800a3090[0]) - 0x96;
    CdIntToPos(leadoutSec, &DAT_800a3090[bRam000008f8]);

    /* Compensate for the data track on mixed-mode discs. */
    bRam000008f8 = (uint8_t)(bRam000008f8 - (uRam000005ac > 2 ? 1 : 0));
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80043a74  (from analysis/SLUS_005.10/decomp/80043a74.c) --- */
// addr: 0x80043a74  name: FUN_80043a74

void FUN_80043a74(void)

{
  uint uVar1;
  int iVar2;
  
  do {
    uVar1 = CdGetToc((CdlLOC *)&DAT_800a3090);
    bRam000008f8 = (byte)uVar1;
  } while ((uVar1 & 0xff) == 0);
  iVar2 = CdPosToInt((CdlLOC *)&DAT_800a3090);
  CdIntToPos(iVar2 + -0x96,(CdlLOC *)(&UNK_800a3094 + (uint)bRam000008f8 * 4));
  bRam000008f8 = bRam000008f8 - (2 < uRam000005ac);
  return;
}

#endif  /* GHIDRA REF */
