/* file_loader.c -- top-level file loader: locate by name, read into heap.
 *
 * Source: SLUS_005.10
 *   FUN_80015948  -- Asset_LoadFile(no-arg form; uses last-opened name)
 *   FUN_800116f4  -- Heap_AllocOrRetry  (malloc + OOM recovery)
 *
 * The descriptor returned by Asset_OpenFile (FUN_800157d4 -- not yet
 * decomp'd, lives in src/assets/auto/) carries the on-disc start sector
 * at +0xc and the byte length at +0x10. Asset_LoadFile rounds the byte
 * length up to a multiple of 0x800 (the PSX CD sector size), allocates
 * a buffer of that size, reads the whole file in one CdRead call, then
 * realloc-shrinks the buffer to the true length to free the read pad.
 *
 * HIGH confidence: clean two-step pattern (alloc + read + trim) matches
 * standard PSY-Q sample code.
 */
#include <stdint.h>
#include "structs.h"

extern void *Asset_OpenFile(void);                        /* FUN_800157d4 */
extern void *Heap_AllocOrRetry(uint32_t n);               /* FUN_800116f4 */
extern void *Heap_Realloc(void *p, uint32_t n);
extern void *V8_CdReadSectors(void *buf, int sector, int mode);

void *Asset_LoadFile(void)
{
    /* Descriptor: { ..., u32 startSector @+0xc, u32 fileSize @+0x10, ... }. */
    uint8_t *desc = (uint8_t *)Asset_OpenFile();
    if (desc == NULL) return NULL;

    uint32_t startSector = *(uint32_t *)(desc + 0x0c);
    uint32_t fileSize    = *(uint32_t *)(desc + 0x10);

    uint32_t paddedBytes = (fileSize + 0x7ffu) & 0xfffff800u;
    uint32_t nSectors    = (fileSize + 0x7ffu) >> 11;

    void *buf = Heap_AllocOrRetry(paddedBytes);
    V8_CdReadSectors(buf, (int)startSector, (int)nSectors);
    return Heap_Realloc(buf, fileSize);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80015948  (from analysis/SLUS_005.10/decomp/80015948.c) --- */
// addr: 0x80015948  name: FUN_80015948

undefined4 FUN_80015948(void)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_800157d4();
  if (iVar1 == 0) {
    uVar2 = 0;
  }
  else {
    uVar2 = FUN_800116f4(*(int *)(iVar1 + 0x10) + 0x7ffU & 0xfffff800);
    uVar2 = FUN_800154f4(uVar2,*(undefined4 *)(iVar1 + 0xc),*(int *)(iVar1 + 0x10) + 0x7ffU >> 0xb);
    uVar2 = FUN_80045134(uVar2,*(undefined4 *)(iVar1 + 0x10));
  }
  return uVar2;
}

/* --- SLUS_005.10 FUN_800116f4  (from analysis/SLUS_005.10/decomp/800116f4.c) --- */
// addr: 0x800116f4  name: FUN_800116f4

int FUN_800116f4(int param_1)

{
  int iVar1;
  
  iVar1 = FUN_80045004();
  if ((iVar1 == 0) && (param_1 != 0)) {
    DrawSync(0);
    FUN_80011914(1 - iRam00000004);
    FUN_800165cc(1);
    do {
      iVar1 = FUN_80045004(param_1);
      if (iVar1 != 0) {
        return iVar1;
      }
      iVar1 = FUN_80020d3c();
    } while (iVar1 != 0);
    _boot();
    iVar1 = 0;
  }
  return iVar1;
}

/* --- SLUS_005.10 FUN_800157d4  (from analysis/SLUS_005.10/decomp/800157d4.c) --- */
// addr: 0x800157d4  name: FUN_800157d4

int FUN_800157d4(byte *param_1)

{
  int iVar1;
  byte bVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  byte local_28 [16];
  
  if (*param_1 == 0x5c) {
    param_1 = param_1 + 1;
  }
  if (iRam000006b4 == 0) {
    return 0;
  }
  iVar3 = 0;
  iVar5 = iRam000006b4;
LAB_8001581c:
  do {
    bVar2 = *param_1;
    param_1 = param_1 + 1;
    if (0x60 < bVar2) {
      bVar2 = bVar2 - 0x20;
    }
    if ((bVar2 != 0) && (bVar2 != 0x5c)) {
      local_28[iVar3] = bVar2;
      iVar3 = iVar3 + 1;
      if (iVar3 < 0xc) goto LAB_8001581c;
    }
    for (; iVar3 < 0xc; iVar3 = iVar3 + 1) {
      local_28[iVar3] = 0x20;
    }
    if (bVar2 != 0x5c) {
      iVar3 = 0;
      if (*(int *)(iVar5 + 0x10) < 1) {
        return 0;
      }
      iVar4 = 0x14;
      do {
        iVar1 = thunk_FUN_800523a0(iVar5 + iVar4,local_28,0xc);
        iVar3 = iVar3 + 1;
        if (iVar1 == 0) {
          return iVar5 + iVar4;
        }
        iVar4 = iVar4 + 0x14;
      } while (iVar3 < *(int *)(iVar5 + 0x10));
      return 0;
    }
    iVar5 = *(int *)(iVar5 + 8);
    while( true ) {
      if (iVar5 == 0) {
        return 0;
      }
      iVar3 = thunk_FUN_800523a0(iVar5,local_28,8);
      if (iVar3 == 0) break;
      iVar5 = *(int *)(iVar5 + 0xc);
    }
    iVar3 = 0;
    if (iVar5 == 0) {
      return 0;
    }
  } while( true );
}

#endif  /* GHIDRA REF */
