/* heap_calloc.c -- calloc-like helper.
 *
 * Source: SLUS_005.10  FUN_800451c0.
 *
 * Allocates n*size bytes via Heap_Alloc and zero-fills in 8-byte
 * chunks. Returns silently on OOM via Ghidra's "indirect jump as
 * return" -- in practice the caller checks for NULL.
 *
 * HIGH confidence: trivial multiply-alloc-bzero pattern.
 */
#include <stdint.h>

extern void *Heap_Alloc(uint32_t n);

void *Heap_Calloc(int count, int size)
{
    int total = count * size;
    uint32_t *p = (uint32_t *)Heap_Alloc((uint32_t)total);
    if (p == NULL) return NULL;
    uint32_t *q = p;
    while (total > 0) {
        q[0] = 0;
        q[1] = 0;
        total -= 8;
        q     += 2;
    }
    return p;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800451c0  (from analysis/SLUS_005.10/decomp/800451c0.c) --- */
// addr: 0x800451c0  name: FUN_800451c0

void FUN_800451c0(int param_1,int param_2)

{
  undefined4 *puVar1;
  
  param_2 = param_2 * param_1;
  puVar1 = (undefined4 *)FUN_80045004(param_2);
  if (puVar1 != (undefined4 *)0x0) {
    do {
      *puVar1 = 0;
      puVar1[1] = 0;
      param_2 = param_2 + -8;
      puVar1 = puVar1 + 2;
    } while (0 < param_2);
  }
                    /* WARNING: Treating indirect jump as return */
  return;
}

#endif  /* GHIDRA REF */
