/* iff_chunk_data.c -- read an IFF chunk's payload into a heap buffer.
 *
 * Source: SLUS_005.10  FUN_800225d4.
 *
 * Reads the next IFF chunk header via Iff_ReadChunkHeader.  If it was
 * a FORM (sentinel 0xffffffff) returns NULL -- forms have no inline
 * payload, the caller is expected to recurse into the sub-chunks.
 * Otherwise allocates a buffer (max(size, 4) bytes -- the 4-byte floor
 * is there so a zero-size chunk still produces a non-NULL handle that
 * Heap_Free can release without specialcasing) and streams the payload.
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern uint32_t Iff_ReadChunkHeader(uint32_t *hdrOut, uint32_t *parentRemaining);
extern void    *Heap_AllocOrRetry(uint32_t n);
extern void     Stream_Read(void *dst, uint32_t nBytes);

void *Iff_ReadChunkData(uint32_t *parentRemaining)
{
    uint32_t hdr[2];
    uint32_t sz = Iff_ReadChunkHeader(hdr, parentRemaining);
    if (sz == 0xffffffffu) return NULL;     /* it was a FORM; no payload */

    uint32_t alloc = (sz != 0) ? sz : 4;
    void    *buf   = Heap_AllocOrRetry(alloc);
    Stream_Read(buf, sz);
    return buf;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800225d4  (from analysis/SLUS_005.10/decomp/800225d4.c) --- */
// addr: 0x800225d4  name: FUN_800225d4

undefined4 FUN_800225d4(void)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  
  iVar1 = FUN_80022524();
  if (iVar1 == -1) {
    uVar2 = 0;
  }
  else {
    iVar3 = 4;
    if (iVar1 != 0) {
      iVar3 = iVar1;
    }
    uVar2 = FUN_800116f4(iVar3);
    FUN_80015a20(uVar2,iVar1);
  }
  return uVar2;
}

#endif  /* GHIDRA REF */
