/* iso_verify.c -- "is this the original disc?" check.
 *
 * Source: SLUS_005.10  FUN_80015610.
 *
 * Reads sector 16 (the ISO9660 Primary Volume Descriptor) into a 32-byte
 * stack buffer via FUN_8001555c (a thin sector reader), then memcmps
 * the first 32 bytes against a saved copy at DAT_8006f608 captured at
 * boot. Returns non-zero (truthy) when they match.
 *
 * The original "Insert Original CD" prompt is at @ 0x80010070 -- this
 * is the function that drives that screen.
 *
 * HIGH confidence.
 */
#include <stdint.h>

extern void *FUN_8001555c(void *dst);      /* sector-16 reader -- TBD pass 2 */
extern int   Util_MemEq(const void *a, const void *b, int n);   /* FUN_800523a0 */
extern uint8_t DAT_8006f608[];

int Iso_VerifyOriginalDisc(void)
{
    uint8_t pvd[32];
    void   *p = FUN_8001555c(pvd);
    return Util_MemEq(p, DAT_8006f608, 32) == 0;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80015610  (from analysis/SLUS_005.10/decomp/80015610.c) --- */
// addr: 0x80015610  name: FUN_80015610

bool FUN_80015610(void)

{
  undefined4 uVar1;
  int iVar2;
  undefined1 auStack_28 [32];
  
  uVar1 = FUN_8001555c(auStack_28);
  iVar2 = thunk_FUN_800523a0(uVar1,&DAT_8006f608,0x20);
  return iVar2 == 0;
}

#endif  /* GHIDRA REF */
