/* load_track_table.c -- read CD audio track-position table from disc.
 *
 * Source: LOAD.DLL  FUN_801002ac.
 *
 * The Shell\Load.tbl payload contains a header followed by an array of
 * i16 entries representing CD-DA track positions used by the music
 * sequencer. The first five i16s are header values (track count,
 * format hint, options...), and from the sixth i16 onward each entry
 * is a per-track sector offset.
 *
 * The function reads the header into five locals (only one of which
 * is currently used), then loops over `(size - 10) / 2` entries
 * (i.e. all remaining i16s after the 10-byte header) into the global
 * track table at DAT_800658e8.
 *
 * HIGH confidence on shape; MED on the meaning of the 5 header fields.
 */
#include <stdint.h>

extern int16_t XobfStream_ReadI16(void *st);   /* func_0x800224b4 */
extern int16_t DAT_800658e8[];                  /* track-position table */

void Audio_LoadTrackTable(void *stream, int payloadSize)
{
    /* 10-byte header (5 i16s) -- parse-and-discard for now. */
    int16_t h0 = XobfStream_ReadI16(stream);
    int16_t h1 = XobfStream_ReadI16(stream);
    int16_t h2 = XobfStream_ReadI16(stream);
    int16_t h3 = XobfStream_ReadI16(stream);
    int16_t h4 = XobfStream_ReadI16(stream);
    (void)h0; (void)h1; (void)h2; (void)h3; (void)h4;

    int n = (payloadSize - 10) / 2;
    for (int i = 0; i < n; i++) {
        DAT_800658e8[i] = XobfStream_ReadI16(stream);
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- LOAD.DLL FUN_801002ac  (from analysis/dll/LOAD/decomp/801002ac.c) --- */
// addr: 0x801002ac  name: FUN_801002ac

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801002ac(undefined4 param_1,int param_2)

{
  undefined2 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  undefined2 *puVar6;
  int iVar7;
  undefined4 local_res0 [4];
  
  local_res0[0] = param_1;
  uVar2 = func_0x800224b4(local_res0);
  uVar3 = func_0x800224b4(local_res0);
  uVar4 = func_0x800224b4(local_res0);
  func_0x800224b4(local_res0);
  func_0x800224b4(local_res0);
  iVar5 = (param_2 + -10) / 2;
  iVar7 = 0;
  if (0 < iVar5) {
    puVar6 = (undefined2 *)&DAT_800658e8;
    do {
      uVar1 = func_0x800224b4(local_res0);
      *puVar6 = uVar1;
      iVar7 = iVar7 + 1;
      puVar6 = puVar6 + 1;
    } while (iVar7 < iVar5);
  }
  _DAT_800658ee = (short)(((int)_DAT_800658ee << 1) >> ((int)DAT_8006531a & 0x1fU));
  Terrain_InitFlatWorld/*0x800251fc*/(uVar2);
  func_0x80041d40(uVar3,uVar4);
  return;
}

#endif  /* GHIDRA REF */
