/* load_track_table.c -- read TERR HEAD and COLS level setup records.
 *
 * Source: LOAD.DLL
 *   FUN_801002ac        -- Terrain_LoadTerrHead
 *   hidden 0x80105318   -- Terrain_LoadCols
 *
 * The top-level TERR/HEAD payload contains five big-endian i16 header words
 * followed by i16 table entries copied to DAT_800658e8. Header[0] is passed to
 * Terrain_InitFlatWorld; header[1..2] are passed to 0x80041d40. Header[3..4]
 * are consumed but otherwise discarded by the source.
 *
 * The COLS payload is a separate 28-byte color/light/fog setup record consumed
 * by hidden LOAD code at 0x80105318.
 *
 * HIGH confidence on shape; MED on the meaning of the color words.
 */
#include <stdint.h>

extern int16_t XobfStream_ReadI16(void *streamRef);  /* func_0x800224b4 */
extern int16_t DAT_800658e8[];                  /* COLS runtime table */
extern int16_t _DAT_800658ee;
extern int8_t  DAT_8006531a;
extern void Terrain_InitFlatWorld(int16_t levelId);
extern void FUN_80041d40(int16_t envA, int16_t envB);

extern uint32_t DAT_80065b58;
extern uint32_t _DAT_80065b00;
extern uint32_t DAT_80065b2c;
extern uint32_t DAT_80065b54;
extern uint32_t _DAT_80065b08;
extern uint32_t _DAT_80065b10;
extern uint32_t _DAT_80065af8;

void Terrain_LoadTerrHead(void *payload, int payloadSize)
{
    uint8_t *cursor = (uint8_t *)payload;
    int16_t h0 = XobfStream_ReadI16(&cursor);
    int16_t h1 = XobfStream_ReadI16(&cursor);
    int16_t h2 = XobfStream_ReadI16(&cursor);
    int16_t h3 = XobfStream_ReadI16(&cursor);
    int16_t h4 = XobfStream_ReadI16(&cursor);
    (void)h0; (void)h1; (void)h2; (void)h3; (void)h4;

    int n = (payloadSize - 10) / 2;
    for (int i = 0; i < n; i++) {
        DAT_800658e8[i] = XobfStream_ReadI16(&cursor);
    }

    _DAT_800658ee = (int16_t)(((int32_t)_DAT_800658ee << 1) >> (DAT_8006531a & 0x1f));
    Terrain_InitFlatWorld(h0);
    FUN_80041d40(h1, h2);
}

/* HIGH-MED: hidden LOAD 0x80105318, direct 28-byte COLS color/light copy.
 * The source also derives a few small color deltas for renderer draw-env
 * records; those renderer-side writes are intentionally omitted here.
 */
void Terrain_LoadCols(const uint8_t *payload)
{
    DAT_80065b58 = (uint32_t)payload[0] << 24 | (uint32_t)payload[1] << 16 |
                   (uint32_t)payload[2] << 8 | payload[3];
    _DAT_80065b00 = (uint32_t)payload[4] << 24 | (uint32_t)payload[5] << 16 |
                    (uint32_t)payload[6] << 8 | payload[7];
    DAT_80065b2c = (uint32_t)payload[8] << 24 | (uint32_t)payload[9] << 16 |
                   (uint32_t)payload[10] << 8 | payload[11];
    DAT_80065b54 = (uint32_t)payload[12] << 24 | (uint32_t)payload[13] << 16 |
                   (uint32_t)payload[14] << 8 | payload[15];
    _DAT_80065b08 = (uint32_t)payload[16] << 24 | (uint32_t)payload[17] << 16 |
                    (uint32_t)payload[18] << 8 | payload[19];
    _DAT_80065b10 = (uint32_t)payload[20] << 24 | (uint32_t)payload[21] << 16 |
                    (uint32_t)payload[22] << 8 | payload[23];
    _DAT_80065af8 = (uint32_t)payload[24] << 24 | (uint32_t)payload[25] << 16 |
                    (uint32_t)payload[26] << 8 | payload[27];
}

void Audio_LoadTrackTable(void *stream, int payloadSize)
{
    Terrain_LoadTerrHead(stream, payloadSize);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- LOAD.DLL FUN_801002ac  (from analysis/dll/LOAD/decomp/801002ac.c) --- */
// addr: 0x801002ac  name: FUN_801002ac

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801002ac(undefined4 param_1,int param_2)

{
  undefined2 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  undefined2 *puVar6;
  int iVar7;
  undefined4 local_res0 [4];
  
  local_res0[0] = param_1;
  uVar2 = func_0x800224b4(local_res0);
  uVar3 = func_0x800224b4(local_res0);
  uVar4 = func_0x800224b4(local_res0);
  func_0x800224b4(local_res0);
  func_0x800224b4(local_res0);
  iVar5 = (param_2 + -10) / 2;
  iVar7 = 0;
  if (0 < iVar5) {
    puVar6 = (undefined2 *)&DAT_800658e8;
    do {
      uVar1 = func_0x800224b4(local_res0);
      *puVar6 = uVar1;
      iVar7 = iVar7 + 1;
      puVar6 = puVar6 + 1;
    } while (iVar7 < iVar5);
  }
  _DAT_800658ee = (short)(((int)_DAT_800658ee << 1) >> ((int)DAT_8006531a & 0x1fU));
  Terrain_InitFlatWorld/*0x800251fc*/(uVar2);
  func_0x80041d40(uVar3,uVar4);
  return;
}

#endif  /* GHIDRA REF */
