/* mem.c -- Vigilante 8 memcpy / memset / memmove implementations.
 *
 * Source: SLUS_005.10:
 *   FUN_80044efc -- memset (byte-fill with u32 unroll)
 *   FUN_80044c44 -- memcpy (forward; unrolled 16-byte body)
 *   FUN_80044d9c -- memmove (handles overlap by choosing direction)
 *
 * HIGH confidence: standard libc / PSY-Q implementations. The unrolled
 * tail handling uses unaligned-load tricks (uses 3..0 byte shifts with
 * a 4-byte aligned access mask). Preserved verbatim because alignment
 * behavior could be observable on PSX hardware via cache or write-combine.
 *
 * The functions are exposed as V8_MemSet / V8_MemCopy / V8_MemMove because
 * PSY-Q does NOT name them memcpy/memset -- they live in the game binary as
 * inline-able locals. Keep the V8_ prefix to avoid colliding with the host
 * toolchain's libc in the eventual port.
 */
#include <stdint.h>
#include <stddef.h>

/* HIGH: byte-fill. Aligns to 4-byte boundary, then writes u32 words with
 * the byte replicated, then writes the misaligned tail with a read-mask-write.
 */
void *V8_MemSet(void *dst, int value, int n)
{
    if (n == 0) return dst;

    uint8_t  *bp   = (uint8_t *)dst;
    uint32_t  fill = (uint32_t)(value & 0xff);

    /* head: byte writes until 4-byte aligned */
    while (((uintptr_t)bp & 3u) != 0) {
        *bp++ = (uint8_t)fill;
        if (--n == 0) return dst;
    }

    fill |= fill << 8;
    fill |= fill << 16;

    uint32_t *wp = (uint32_t *)bp;
    while (n >= 4) {
        *wp++ = fill;
        n   -= 4;
    }

    /* tail: <4 bytes left, written via masked u32 read-modify-write to
     * match the original code's unaligned-store sequence. */
    if (n > 0) {
        uint8_t *tail = (uint8_t *)wp + (n - 1);
        uint32_t  off = (uintptr_t)tail & 3u;
        uint32_t *w   = (uint32_t *)((uintptr_t)tail - off);
        uint32_t  mask = 0xffffffffu << ((off + 1) * 8);   /* preserve bytes above */
        uint32_t  bits = fill         >> ((3 - off) * 8);
        *w = (*w & mask) | bits;
    }
    return dst;
}

/* HIGH: forward copy, 16-byte unrolled body. NOT safe for overlap when
 * src < dst -- use V8_MemMove for that. */
void *V8_MemCopy(void *dst, const void *src, int n)
{
    if (n == 0) return dst;

    const uint8_t *s = (const uint8_t *)src;
    uint8_t       *d = (uint8_t *)dst;

    /* head: align source to 4 by bytewise copy */
    while (((uintptr_t)s & 3u) != 0) {
        *d++ = *s++;
        if (--n == 0) return dst;
    }

    if (((uintptr_t)d & 3u) == 0) {
        const uint32_t *sw = (const uint32_t *)s;
        uint32_t       *dw = (uint32_t *)d;
        while (n >= 16) {
            dw[0] = sw[0]; dw[1] = sw[1]; dw[2] = sw[2]; dw[3] = sw[3];
            sw += 4; dw += 4; n -= 16;
        }
        while (n >= 4) {
            *dw++ = *sw++;
            n   -= 4;
        }
        s = (const uint8_t *)sw;
        d = (uint8_t *)dw;
    }

    while (n > 0) {
        *d++ = *s++;
        n--;
    }
    return dst;
}

/* HIGH: overlap-safe move. Copies backward when src precedes dst. */
void *V8_MemMove(void *dst, const void *src, int n)
{
    if (n == 0) return dst;
    if ((uintptr_t)src >= (uintptr_t)dst) {
        return V8_MemCopy(dst, src, n);
    }
    /* backward copy */
    uint8_t       *d = (uint8_t *)dst + n;
    const uint8_t *s = (const uint8_t *)src + n;
    while (n > 0) {
        *--d = *--s;
        n--;
    }
    return dst;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80044efc  (from analysis/SLUS_005.10/decomp/80044efc.c) --- */
// addr: 0x80044efc  name: FUN_80044efc

uint * FUN_80044efc(uint *param_1,uint param_2,int param_3)

{
  uint uVar1;
  uint *puVar2;
  uint *puVar3;
  undefined1 *puVar4;
  uint uVar5;
  
  puVar3 = param_1;
  while( true ) {
    if (param_3 == 0) {
      return puVar3;
    }
    uVar5 = param_2 & 0xff;
    if (((uint)param_1 & 3) == 0) break;
    *(char *)param_1 = (char)param_2;
    param_3 = param_3 + -1;
    param_1 = (uint *)((int)param_1 + 1);
    param_2 = uVar5;
  }
  uVar5 = uVar5 | uVar5 << 8;
  uVar5 = uVar5 | uVar5 << 0x10;
  while (-1 < param_3 + -4) {
    *param_1 = uVar5;
    param_1 = param_1 + 1;
    param_3 = param_3 + -4;
  }
  puVar4 = (undefined1 *)((int)param_1 + param_3 + -1);
  if (param_3 + -1 < 0) {
    return puVar3;
  }
  uVar1 = (uint)puVar4 & 3;
  puVar2 = (uint *)(puVar4 + -uVar1);
  *puVar2 = *puVar2 & -1 << (uVar1 + 1) * 8 | uVar5 >> (3 - uVar1) * 8;
  return puVar3;
}

/* --- SLUS_005.10 FUN_80044c44  (from analysis/SLUS_005.10/decomp/80044c44.c) --- */
// addr: 0x80044c44  name: FUN_80044c44

uint * FUN_80044c44(uint *param_1,uint *param_2,int param_3)

{
  uint *puVar1;
  uint *puVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  uint uVar7;
  
  puVar2 = param_1;
  if (param_3 != 0) {
    while (((uint)param_2 & 3) != 0) {
      uVar3 = *param_2;
      param_2 = (uint *)((int)param_2 + 1);
      *(char *)param_1 = (char)uVar3;
      param_3 = param_3 + -1;
      param_1 = (uint *)((int)param_1 + 1);
      if (param_3 == 0) {
        return puVar2;
      }
    }
    param_3 = param_3 + -0x10;
    if (((uint)param_1 & 3) == 0) {
      uVar3 = 0;
      for (; -1 < param_3; param_3 = param_3 + -0x10) {
        uVar3 = *param_2;
        uVar4 = param_2[1];
        uVar5 = param_2[2];
        uVar6 = param_2[3];
        *param_1 = uVar3;
        param_1[1] = uVar4;
        param_1[2] = uVar5;
        param_1[3] = uVar6;
        param_2 = param_2 + 4;
        param_1 = param_1 + 4;
      }
      for (param_3 = param_3 + 0xc; -1 < param_3; param_3 = param_3 + -4) {
        uVar3 = *param_2;
        param_2 = param_2 + 1;
        *param_1 = uVar3;
        param_1 = param_1 + 1;
      }
      param_3 = param_3 + 3;
      if (-1 < param_3) {
        uVar4 = (uint)((int)param_2 + param_3) & 3;
        uVar5 = (uint)((int)param_1 + param_3) & 3;
        puVar1 = (uint *)((undefined1 *)((int)param_1 + param_3) + -uVar5);
        *puVar1 = *puVar1 & -1 << (uVar5 + 1) * 8 |
                  (*(int *)((undefined1 *)((int)param_2 + param_3) + -uVar4) << (3 - uVar4) * 8 |
                  uVar3 & 0xffffffffU >> (uVar4 + 1) * 8) >> (3 - uVar5) * 8;
        return puVar2;
      }
    }
    else {
      for (; -1 < param_3; param_3 = param_3 + -0x10) {
        uVar4 = *param_2;
        uVar5 = param_2[1];
        uVar6 = param_2[2];
        uVar7 = param_2[3];
        uVar3 = (uint)param_1 & 3;
        *(uint *)((int)param_1 - uVar3) =
             *(uint *)((int)param_1 - uVar3) & 0xffffffffU >> (4 - uVar3) * 8 | uVar4 << uVar3 * 8;
        uVar3 = (int)param_1 + 3U & 3;
        puVar1 = (uint *)((undefined1 *)((int)param_1 + 3U) + -uVar3);
        *puVar1 = *puVar1 & -1 << (uVar3 + 1) * 8 | uVar4 >> (3 - uVar3) * 8;
        uVar3 = (uint)(param_1 + 1) & 3;
        puVar1 = (uint *)((int)(param_1 + 1) - uVar3);
        *puVar1 = *puVar1 & 0xffffffffU >> (4 - uVar3) * 8 | uVar5 << uVar3 * 8;
        uVar3 = (int)param_1 + 7U & 3;
        puVar1 = (uint *)((undefined1 *)((int)param_1 + 7U) + -uVar3);
        *puVar1 = *puVar1 & -1 << (uVar3 + 1) * 8 | uVar5 >> (3 - uVar3) * 8;
        uVar3 = (uint)(param_1 + 2) & 3;
        puVar1 = (uint *)((int)(param_1 + 2) - uVar3);
        *puVar1 = *puVar1 & 0xffffffffU >> (4 - uVar3) * 8 | uVar6 << uVar3 * 8;
        uVar3 = (int)param_1 + 0xbU & 3;
        puVar1 = (uint *)((undefined1 *)((int)param_1 + 0xbU) + -uVar3);
        *puVar1 = *puVar1 & -1 << (uVar3 + 1) * 8 | uVar6 >> (3 - uVar3) * 8;
        uVar3 = (uint)(param_1 + 3) & 3;
        puVar1 = (uint *)((int)(param_1 + 3) - uVar3);
        *puVar1 = *puVar1 & 0xffffffffU >> (4 - uVar3) * 8 | uVar7 << uVar3 * 8;
        uVar3 = (int)param_1 + 0xfU & 3;
        puVar1 = (uint *)((undefined1 *)((int)param_1 + 0xfU) + -uVar3);
        *puVar1 = *puVar1 & -1 << (uVar3 + 1) * 8 | uVar7 >> (3 - uVar3) * 8;
        param_2 = param_2 + 4;
        param_1 = param_1 + 4;
      }
      for (param_3 = param_3 + 0xc; -1 < param_3; param_3 = param_3 + -4) {
        uVar4 = *param_2;
        param_2 = param_2 + 1;
        uVar3 = (uint)param_1 & 3;
        *(uint *)((int)param_1 - uVar3) =
             *(uint *)((int)param_1 - uVar3) & 0xffffffffU >> (4 - uVar3) * 8 | uVar4 << uVar3 * 8;
        uVar3 = (int)param_1 + 3U & 3;
        puVar1 = (uint *)((undefined1 *)((int)param_1 + 3U) + -uVar3);
        *puVar1 = *puVar1 & -1 << (uVar3 + 1) * 8 | uVar4 >> (3 - uVar3) * 8;
        param_1 = param_1 + 1;
      }
      for (param_3 = param_3 + 4; param_3 != 0; param_3 = param_3 + -1) {
        uVar3 = *param_2;
        param_2 = (uint *)((int)param_2 + 1);
        *(char *)param_1 = (char)uVar3;
        param_1 = (uint *)((int)param_1 + 1);
      }
    }
  }
  return puVar2;
}

/* --- SLUS_005.10 FUN_80044d9c  (from analysis/SLUS_005.10/decomp/80044d9c.c) --- */
// addr: 0x80044d9c  name: FUN_80044d9c

uint * FUN_80044d9c(uint *param_1,uint *param_2,int param_3)

{
  undefined1 *puVar1;
  uint *puVar2;
  uint *puVar3;
  undefined1 *puVar4;
  undefined1 *puVar5;
  uint uVar6;
  uint uVar7;
  undefined4 uVar8;
  uint uVar9;
  undefined4 uVar10;
  uint uVar11;
  undefined4 uVar12;
  uint uVar13;
  
  if ((int)param_2 < (int)param_1) {
    puVar4 = (undefined1 *)((int)param_1 + param_3);
    if (param_3 != 0) {
      puVar5 = (undefined1 *)((int)param_2 + param_3);
      while (((uint)puVar5 & 3) != 0) {
        puVar1 = puVar5 + -1;
        puVar5 = puVar5 + -1;
        puVar4[-1] = *puVar1;
        param_3 = param_3 + -1;
        puVar4 = puVar4 + -1;
        if (param_3 == 0) {
          return param_1;
        }
      }
      param_3 = param_3 + -0x10;
      if (((uint)puVar4 & 3) == 0) {
        uVar6 = 0;
        for (; -1 < param_3; param_3 = param_3 + -0x10) {
          uVar6 = *(uint *)(puVar5 + -4);
          uVar8 = *(undefined4 *)(puVar5 + -8);
          uVar10 = *(undefined4 *)(puVar5 + -0xc);
          uVar12 = *(undefined4 *)(puVar5 + -0x10);
          *(uint *)(puVar4 + -4) = uVar6;
          *(undefined4 *)(puVar4 + -8) = uVar8;
          *(undefined4 *)(puVar4 + -0xc) = uVar10;
          *(undefined4 *)(puVar4 + -0x10) = uVar12;
          puVar5 = puVar5 + -0x10;
          puVar4 = puVar4 + -0x10;
        }
        for (param_3 = param_3 + 0xc; -1 < param_3; param_3 = param_3 + -4) {
          uVar6 = *(uint *)(puVar5 + -4);
          puVar5 = puVar5 + -4;
          *(uint *)(puVar4 + -4) = uVar6;
          puVar4 = puVar4 + -4;
        }
        param_3 = param_3 + 4;
        if (0 < param_3) {
          uVar7 = (int)puVar5 - param_3 & 3;
          uVar9 = (int)puVar4 - param_3 & 3;
          puVar3 = (uint *)(((int)puVar4 - param_3) - uVar9);
          *puVar3 = *puVar3 & 0xffffffffU >> (4 - uVar9) * 8 |
                    (uVar6 & -1 << (4 - uVar7) * 8 |
                    *(uint *)(((int)puVar5 - param_3) - uVar7) >> uVar7 * 8) << uVar9 * 8;
          return param_1;
        }
      }
      else {
        for (; -1 < param_3; param_3 = param_3 + -0x10) {
          uVar7 = *(uint *)(puVar5 + -4);
          uVar9 = *(uint *)(puVar5 + -8);
          uVar11 = *(uint *)(puVar5 + -0xc);
          uVar13 = *(uint *)(puVar5 + -0x10);
          puVar1 = puVar4 + -4;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar7 << uVar6 * 8;
          puVar1 = puVar4 + -1;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & -1 << (uVar6 + 1) * 8 | uVar7 >> (3 - uVar6) * 8;
          puVar1 = puVar4 + -8;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar9 << uVar6 * 8;
          puVar1 = puVar4 + -5;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & -1 << (uVar6 + 1) * 8 | uVar9 >> (3 - uVar6) * 8;
          puVar1 = puVar4 + -0xc;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar11 << uVar6 * 8;
          puVar1 = puVar4 + -9;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & -1 << (uVar6 + 1) * 8 | uVar11 >> (3 - uVar6) * 8;
          puVar1 = puVar4 + -0x10;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar13 << uVar6 * 8;
          puVar1 = puVar4 + -0xd;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & -1 << (uVar6 + 1) * 8 | uVar13 >> (3 - uVar6) * 8;
          puVar5 = puVar5 + -0x10;
          puVar4 = puVar4 + -0x10;
        }
        for (param_3 = param_3 + 0xc; -1 < param_3; param_3 = param_3 + -4) {
          uVar7 = *(uint *)(puVar5 + -4);
          puVar5 = puVar5 + -4;
          puVar1 = puVar4 + -4;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar7 << uVar6 * 8;
          puVar1 = puVar4 + -1;
          uVar6 = (uint)puVar1 & 3;
          *(uint *)(puVar1 + -uVar6) =
               *(uint *)(puVar1 + -uVar6) & -1 << (uVar6 + 1) * 8 | uVar7 >> (3 - uVar6) * 8;
          puVar4 = puVar4 + -4;
        }
        for (param_3 = param_3 + 4; param_3 != 0; param_3 = param_3 + -1) {
          puVar1 = puVar5 + -1;
          puVar5 = puVar5 + -1;
          puVar4[-1] = *puVar1;
          puVar4 = puVar4 + -1;
        }
      }
    }
    return param_1;
  }
  puVar3 = param_1;
  if (param_3 != 0) {
    while (((uint)param_2 & 3) != 0) {
      uVar6 = *param_2;
      param_2 = (uint *)((int)param_2 + 1);
      *(char *)param_1 = (char)uVar6;
      param_3 = param_3 + -1;
      param_1 = (uint *)((int)param_1 + 1);
      if (param_3 == 0) {
        return puVar3;
      }
    }
    param_3 = param_3 + -0x10;
    if (((uint)param_1 & 3) == 0) {
      uVar6 = 0;
      for (; -1 < param_3; param_3 = param_3 + -0x10) {
        uVar6 = *param_2;
        uVar7 = param_2[1];
        uVar9 = param_2[2];
        uVar11 = param_2[3];
        *param_1 = uVar6;
        param_1[1] = uVar7;
        param_1[2] = uVar9;
        param_1[3] = uVar11;
        param_2 = param_2 + 4;
        param_1 = param_1 + 4;
      }
      for (param_3 = param_3 + 0xc; -1 < param_3; param_3 = param_3 + -4) {
        uVar6 = *param_2;
        param_2 = param_2 + 1;
        *param_1 = uVar6;
        param_1 = param_1 + 1;
      }
      param_3 = param_3 + 3;
      if (-1 < param_3) {
        uVar7 = (uint)((int)param_2 + param_3) & 3;
        uVar9 = (uint)((int)param_1 + param_3) & 3;
        puVar2 = (uint *)((undefined1 *)((int)param_1 + param_3) + -uVar9);
        *puVar2 = *puVar2 & -1 << (uVar9 + 1) * 8 |
                  (*(int *)((undefined1 *)((int)param_2 + param_3) + -uVar7) << (3 - uVar7) * 8 |
                  uVar6 & 0xffffffffU >> (uVar7 + 1) * 8) >> (3 - uVar9) * 8;
        return puVar3;
      }
    }
    else {
      for (; -1 < param_3; param_3 = param_3 + -0x10) {
        uVar7 = *param_2;
        uVar9 = param_2[1];
        uVar11 = param_2[2];
        uVar13 = param_2[3];
        uVar6 = (uint)param_1 & 3;
        *(uint *)((int)param_1 - uVar6) =
             *(uint *)((int)param_1 - uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar7 << uVar6 * 8;
        uVar6 = (int)param_1 + 3U & 3;
        puVar2 = (uint *)((undefined1 *)((int)param_1 + 3U) + -uVar6);
        *puVar2 = *puVar2 & -1 << (uVar6 + 1) * 8 | uVar7 >> (3 - uVar6) * 8;
        uVar6 = (uint)(param_1 + 1) & 3;
        puVar2 = (uint *)((int)(param_1 + 1) - uVar6);
        *puVar2 = *puVar2 & 0xffffffffU >> (4 - uVar6) * 8 | uVar9 << uVar6 * 8;
        uVar6 = (int)param_1 + 7U & 3;
        puVar2 = (uint *)((undefined1 *)((int)param_1 + 7U) + -uVar6);
        *puVar2 = *puVar2 & -1 << (uVar6 + 1) * 8 | uVar9 >> (3 - uVar6) * 8;
        uVar6 = (uint)(param_1 + 2) & 3;
        puVar2 = (uint *)((int)(param_1 + 2) - uVar6);
        *puVar2 = *puVar2 & 0xffffffffU >> (4 - uVar6) * 8 | uVar11 << uVar6 * 8;
        uVar6 = (int)param_1 + 0xbU & 3;
        puVar2 = (uint *)((undefined1 *)((int)param_1 + 0xbU) + -uVar6);
        *puVar2 = *puVar2 & -1 << (uVar6 + 1) * 8 | uVar11 >> (3 - uVar6) * 8;
        uVar6 = (uint)(param_1 + 3) & 3;
        puVar2 = (uint *)((int)(param_1 + 3) - uVar6);
        *puVar2 = *puVar2 & 0xffffffffU >> (4 - uVar6) * 8 | uVar13 << uVar6 * 8;
        uVar6 = (int)param_1 + 0xfU & 3;
        puVar2 = (uint *)((undefined1 *)((int)param_1 + 0xfU) + -uVar6);
        *puVar2 = *puVar2 & -1 << (uVar6 + 1) * 8 | uVar13 >> (3 - uVar6) * 8;
        param_2 = param_2 + 4;
        param_1 = param_1 + 4;
      }
      for (param_3 = param_3 + 0xc; -1 < param_3; param_3 = param_3 + -4) {
        uVar7 = *param_2;
        param_2 = param_2 + 1;
        uVar6 = (uint)param_1 & 3;
        *(uint *)((int)param_1 - uVar6) =
             *(uint *)((int)param_1 - uVar6) & 0xffffffffU >> (4 - uVar6) * 8 | uVar7 << uVar6 * 8;
        uVar6 = (int)param_1 + 3U & 3;
        puVar2 = (uint *)((undefined1 *)((int)param_1 + 3U) + -uVar6);
        *puVar2 = *puVar2 & -1 << (uVar6 + 1) * 8 | uVar7 >> (3 - uVar6) * 8;
        param_1 = param_1 + 1;
      }
      for (param_3 = param_3 + 4; param_3 != 0; param_3 = param_3 + -1) {
        uVar6 = *param_2;
        param_2 = (uint *)((int)param_2 + 1);
        *(char *)param_1 = (char)uVar6;
        param_1 = (uint *)((int)param_1 + 1);
      }
    }
  }
  return puVar3;
}

#endif  /* GHIDRA REF */
