/* snd_loader.c -- SND sound bank loader (open / load / close pattern).
 *
 * Source: SLUS_005.10
 *   FUN_80044360  -- Sound_LoadSND  (engine name; main_loop.c uses this)
 *                    aka Audio_LoadSND in some pass-2 notes; thin
 *                    {open, parse, close} wrapper.
 *   FUN_800441f8  -- Audio_ParseSND -- the bank parser (in snd_parse.c)
 *   FUN_80044394  -- Audio_FreeSND  -- SpuFree(handle's sample bytes) + Heap_Free(handle)
 *
 * The bank handle layout (recovered from FUN_80044394):
 *   { u16 nSamples, u16 sampleSizeIn8b, i32 sampleOffs[nSamples]... }
 *      -- the SPU allocation length is *(u16 *)(handle+2) << 3.
 *
 * Runtime note: Sound_LoadSND is intentionally kept under the legacy
 * name `Audio_LoadSND` here so the link DOESN'T pull it in during the
 * smoke run.  The current host stubs for FUN_800157d4 (ISO open) and
 * FUN_80015368 ("failure-path infinite-loop trap") + SpuIsTransfer-
 * Completed do not satisfy the contract this loader expects -- wiring
 * it now would spin in the SPU DMA wait loop.  Switch to `Sound_LoadSND`
 * once the streaming/SPU stack is hooked.  See main_loop.c which still
 * declares the engine name and lets the panic stub catch the call.
 *
 * HIGH.
 */
#include <stdint.h>

extern void Stream_OpenByName(const char *path);             /* FUN_800159b4 */
extern void Stream_Close(void);                              /* FUN_80015a00 */
extern void *Audio_ParseSND(void);                           /* FUN_800441f8 */
extern void  SpuFree(uint32_t spuAddr);
extern void  Heap_Free(void *p);

void *Audio_LoadSND(const char *path)
{
    Stream_OpenByName(path);
    void *bank = Audio_ParseSND();
    Stream_Close();
    return bank;
}

void Audio_FreeSND(void *handle)
{
    uint8_t *h = (uint8_t *)handle;
    /* SPU buffer length stored in 8-byte units at +2. */
    SpuFree((uint32_t)*(uint16_t *)(h + 2) << 3);
    Heap_Free(handle);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80044360  (from analysis/SLUS_005.10/decomp/80044360.c) --- */
// addr: 0x80044360  name: FUN_80044360

undefined4 FUN_80044360(void)

{
  undefined4 uVar1;
  
  FUN_800159b4();
  uVar1 = FUN_800441f8();
  FUN_80015a00();
  return uVar1;
}

/* --- SLUS_005.10 FUN_800441f8  (from analysis/SLUS_005.10/decomp/800441f8.c) --- */
// addr: 0x800441f8  name: FUN_800441f8

short * FUN_800441f8(void)

{
  uint uVar1;
  ulong addr;
  short *psVar2;
  long lVar3;
  short *psVar4;
  ulong size;
  int iVar5;
  uint uVar6;
  short local_420;
  ushort local_41e;
  uchar auStack_418 [1024];
  
  FUN_80015a20(&local_420,4);
  addr = SpuMalloc((uint)local_41e * 8 + 0x3f & 0xffffffc0);
  if (addr == 0) {
    FUN_80015368("Out of SPU RAM");
  }
  psVar2 = (short *)FUN_800116f4(local_420 * 4 + 4);
  psVar2[1] = (short)(addr >> 3);
  *psVar2 = local_420;
  FUN_80015a20(psVar2 + 2,(int)local_420 << 2);
  iVar5 = 0;
  psVar4 = psVar2;
  if (0 < local_420) {
    do {
      psVar4[2] = psVar4[2] + psVar2[1];
      iVar5 = iVar5 + 1;
      psVar4 = psVar4 + 2;
    } while (iVar5 < local_420);
  }
  SpuSetTransferMode(0);
  SpuSetTransferStartAddr(addr);
  uVar6 = (uint)local_41e << 3;
  uVar1 = (uint)local_41e;
  while (uVar1 != 0) {
    size = 0x400;
    if ((int)uVar6 < 0x400) {
      size = uVar6;
    }
    FUN_80015a20(auStack_418);
    SpuSetTransferStartAddr(addr);
    SpuRead(auStack_418,size);
    do {
      lVar3 = SpuIsTransferCompleted(0);
    } while (lVar3 == 0);
    addr = addr + size;
    uVar6 = uVar6 - size;
    uVar1 = uVar6;
  }
  return psVar2;
}

/* --- SLUS_005.10 FUN_80044394  (from analysis/SLUS_005.10/decomp/80044394.c) --- */
// addr: 0x80044394  name: FUN_80044394

void FUN_80044394(int param_1)

{
  SpuFree((uint)*(ushort *)(param_1 + 2) << 3);
  FUN_80045088(param_1);
  return;
}

/* --- SLUS_005.10 FUN_800159b4  (from analysis/SLUS_005.10/decomp/800159b4.c) --- */
// addr: 0x800159b4  name: FUN_800159b4

undefined4 FUN_800159b4(undefined4 param_1)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_800157d4();
  if (iVar1 == 0) {
    uVar2 = FUN_80015368(param_1);
  }
  else {
    FUN_8001570c(*(undefined4 *)(iVar1 + 0xc));
    uRam000006ac = 0;
    uVar2 = 1;
  }
  return uVar2;
}

/* --- SLUS_005.10 FUN_80015a00  (from analysis/SLUS_005.10/decomp/80015a00.c) --- */
// addr: 0x80015a00  name: FUN_80015a00

undefined4 FUN_80015a00(void)

{
  FUN_80015798();
  return 1;
}

#endif  /* GHIDRA REF */
