/* snd_parse.c -- SND (sound bank) parser.
 *
 * Source: SLUS_005.10  FUN_800441f8.
 *
 * SND on-disc layout (recovered):
 *
 *   u16  nSamples         -- count of entries
 *   u16  sizeIn8b         -- total sample data length in 8-byte units
 *   struct SampleEntry samples[nSamples]:
 *     u16 offsetIn8b             -- offset within the bank's SPU region
 *     u16 pitch                  -- SPU pitch (0x1000 = source rate)
 *   u8   sampleData[sizeIn8b * 8] -- VAG/ADPCM-encoded sample payload
 *
 * The parser:
 *   1. Reads (nSamples, sizeIn8b) from the stream.
 *   2. SpuMalloc()'s `sizeIn8b*8 + 0x3f` rounded down to 64 bytes for
 *      the on-SPU buffer. OOM trips a fatal trap (Stream_FatalOom).
 *   3. Heap-allocates a small in-RAM handle of (nSamples*4 + 4) bytes:
 *        u16  nSamples;
 *        u16  spuBaseIn8b;
 *        SampleEntry samples[nSamples];
 *   4. Reads the sample table (nSamples four-byte entries).
 *   5. Adds spuBaseIn8b only to each entry's offset field, converting it
 *      from a bank-relative to an absolute SPU 8-byte-unit position. The
 *      adjacent pitch field is preserved unchanged.
 *   6. Streams sample data into SPU RAM 1 KiB at a time via SpuWrite,
 *      waiting on SpuIsTransferCompleted between chunks.
 *
 * HIGH-MED confidence: layout is unambiguous from the read sequence;
 * the +0x3f / &~0x3f rounding is the standard SPU 64-byte alignment.
 *
 * The original calls the misnomered Stream_Read of the 1024-byte
 * sample chunk into auStack_418 BEFORE setting the SPU transfer
 * address. We preserve that order; it is observable only if SpuWrite
 * is preemptable on real hardware (it isn't), so it's incidental.
 */
#include <stdint.h>

extern void Stream_Read(void *dst, uint32_t nBytes);
extern uint32_t SpuMalloc(uint32_t bytes);
extern void SpuSetTransferMode(int mode);
extern void SpuSetTransferStartAddr(uint32_t addr);
extern int  SpuRead(const void *buf, uint32_t bytes);   /* misnamed: SPU read = host->SPU write */
extern int  SpuIsTransferCompleted(int mode);
extern void Stream_FatalOom(const char *msg);            /* FUN_80015368 trap */
extern void *Heap_AllocOrRetry(uint32_t n);

typedef struct {
    uint16_t offsetIn8b;
    uint16_t pitch;
} SndSampleEntry;

typedef struct {
    uint16_t nSamples;
    uint16_t spuBaseIn8b;
    SndSampleEntry samples[1];   /* nSamples entries */
} SndBank;

void *Audio_ParseSND(void)
{
    /* Header: 2 u16s. */
    struct { uint16_t nSamples; uint16_t sizeIn8b; } hdr;
    Stream_Read(&hdr, 4);

    uint32_t spuBytes = (uint32_t)hdr.sizeIn8b * 8;
    uint32_t spuAlloc = (spuBytes + 0x3fu) & ~0x3fu;
    uint32_t addr     = SpuMalloc(spuAlloc);
    if (addr == 0) Stream_FatalOom("Out of SPU RAM");

    SndBank *bank = (SndBank *)Heap_AllocOrRetry((uint32_t)hdr.nSamples * 4 + 4);
    bank->nSamples    = hdr.nSamples;
    bank->spuBaseIn8b = (uint16_t)(addr >> 3);

    /* Sample table: relative SPU address plus playback pitch. */
    Stream_Read(bank->samples, (uint32_t)hdr.nSamples * 4);
    for (int i = 0; i < hdr.nSamples; i++) {
        bank->samples[i].offsetIn8b += bank->spuBaseIn8b;
    }

    /* Sample payload -> SPU RAM in 1 KiB chunks. */
    SpuSetTransferMode(0);
    SpuSetTransferStartAddr(addr);
    uint32_t left = spuBytes;
    while (left != 0) {
        uint32_t chunk = (left < 0x400u) ? left : 0x400u;
        uint8_t  buf[0x400];
        Stream_Read(buf, chunk);
        SpuSetTransferStartAddr(addr);
        SpuRead(buf, chunk);
        while (SpuIsTransferCompleted(0) == 0) { /* wait */ }
        addr += chunk;
        left -= chunk;
    }
    return bank;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_800441f8  (from analysis/SLUS_005.10/decomp/800441f8.c) --- */
// addr: 0x800441f8  name: FUN_800441f8

short * FUN_800441f8(void)

{
  uint uVar1;
  ulong addr;
  short *psVar2;
  long lVar3;
  short *psVar4;
  ulong size;
  int iVar5;
  uint uVar6;
  short local_420;
  ushort local_41e;
  uchar auStack_418 [1024];
  
  FUN_80015a20(&local_420,4);
  addr = SpuMalloc((uint)local_41e * 8 + 0x3f & 0xffffffc0);
  if (addr == 0) {
    FUN_80015368("Out of SPU RAM");
  }
  psVar2 = (short *)FUN_800116f4(local_420 * 4 + 4);
  psVar2[1] = (short)(addr >> 3);
  *psVar2 = local_420;
  FUN_80015a20(psVar2 + 2,(int)local_420 << 2);
  iVar5 = 0;
  psVar4 = psVar2;
  if (0 < local_420) {
    do {
      psVar4[2] = psVar4[2] + psVar2[1];
      iVar5 = iVar5 + 1;
      psVar4 = psVar4 + 2;
    } while (iVar5 < local_420);
  }
  SpuSetTransferMode(0);
  SpuSetTransferStartAddr(addr);
  uVar6 = (uint)local_41e << 3;
  uVar1 = (uint)local_41e;
  while (uVar1 != 0) {
    size = 0x400;
    if ((int)uVar6 < 0x400) {
      size = uVar6;
    }
    FUN_80015a20(auStack_418);
    SpuSetTransferStartAddr(addr);
    SpuRead(auStack_418,size);
    do {
      lVar3 = SpuIsTransferCompleted(0);
    } while (lVar3 == 0);
    addr = addr + size;
    uVar6 = uVar6 - size;
    uVar1 = uVar6;
  }
  return psVar2;
}

#endif  /* GHIDRA REF */
