/* stream_close.c -- close the active streaming CD reader.
 *
 * Source: SLUS_005.10  FUN_80015798.
 *
 * Issues CdControl(CdlPause), unhooks the CdReadyCallback, and frees
 * the 2 KiB sector ring buffer previously allocated by Stream_Open.
 *
 * HIGH confidence: standard PSY-Q CD streamer teardown.
 */
#include <stdint.h>

extern void  CdControl(unsigned char com, unsigned char *param, unsigned char *result);
extern void  CdReadyCallback(void (*cb)(int, unsigned char *));
extern void  Heap_Free(void *p);
extern void *uRam000006a0;   /* sector buffer base set by Stream_Open */

#define CdlPause  0x09

void Stream_Close(void)
{
    CdControl(CdlPause, (unsigned char *)0, (unsigned char *)0);
    CdReadyCallback((void (*)(int, unsigned char *))0);
    Heap_Free(uRam000006a0);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80015798  (from analysis/SLUS_005.10/decomp/80015798.c) --- */
// addr: 0x80015798  name: FUN_80015798

void FUN_80015798(void)

{
  CdControl('\t',(u_char *)0x0,(u_char *)0x0);
  CdReadyCallback((CdlCB)0x0);
  FUN_80045088(uRam000006a0);
  return;
}

#endif  /* GHIDRA REF */
