/* strlen.c -- V8 strlen (null-safe).
 *
 * Source: SLUS_005.10  FUN_80052544.
 *
 * Standard libc/PSY-Q strlen with one twist: returns 0 if passed a
 * NULL pointer (regular libc strlen would crash). HIGH confidence.
 */
#include <stdint.h>

int Util_StrLen(const char *s)
{
    if (s == NULL) return 0;
    int n = 0;
    while (*s != '\0') {
        s++;
        n++;
    }
    return n;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_80052544  (from analysis/SLUS_005.10/decomp/80052544.c) --- */
// addr: 0x80052544  name: FUN_80052544

/* Possible STRLEN.OBJ/strlen */

int FUN_80052544(char *param_1)

{
  char cVar1;
  int iVar2;
  int iVar3;
  
  iVar3 = 0;
  iVar2 = 0;
  if (param_1 != (char *)0x0) {
    while (iVar3 = iVar2, cVar1 = *param_1, param_1 = param_1 + 1, cVar1 != '\0') {
      iVar2 = iVar3 + 1;
    }
  }
  return iVar3;
}

#endif  /* GHIDRA REF */
