/* xobf_parse.c -- parse an XOBF object container.
 *
 * Source: SLUS_005.10  FUN_8002263c.
 *
 * XOBF is the inner format inside an EXP / FORM file that bundles
 * one model with its animation and optional sound effects. Walks
 * sub-chunks via Iff_ReadChunkHeader and dispatches on their 4cc:
 *
 *   "BIN " -- raw model bytes; alloc + Stream_Read into `model`.
 *   "ANM " -- animation track; alloc + Stream_Read into `anim`.
 *   "SND " -- sound bank; consume by SND parser, store handle in `snd`.
 *
 * When the parent's byte counter reaches zero, finalises by calling
 * `Renderer_BuildObject(model, anim)` -- FUN_8001a640 -- which returns
 * the in-memory object handle. If `chainRegister` is non-zero, the
 * object is appended to the global draw chain via FUN_8001a91c. If a
 * sound was parsed, its handle is patched into obj[+8].
 *
 * HIGH confidence: 4cc dispatch is unambiguous; per-chunk action
 * matches the SND streamer's contract.
 *
 * Used by:
 *   - VehicleExp_Load (src/assets/vehicle_exp.c) to load every
 *     character's vehicle template.
 *   - Likely also by terrain EXP loaders for level-specific objects.
 *
 * Pass 2: rename FUN_8001a640 -> Renderer_BuildObject (it's on the
 * renderer seam; the *call* stays here, but the implementation moves
 * to src/skipped/ as the new renderer's contract).
 */
#include <stdint.h>

extern uint32_t Iff_ReadChunkHeader(uint32_t *hdrOut, uint32_t *parentRemaining);
extern void    *Heap_AllocOrRetry(uint32_t n);
extern void     Stream_Read(void *dst, uint32_t n);
extern uint32_t Stream_Tell(void);
extern void     Stream_Seek(uint32_t pos, int relative);
extern void    *Audio_ParseSND(void);
extern void    *Renderer_BuildObject(void *model, void *anim);   /* FUN_8001a640 */
extern void     DrawChain_Register(void *obj);                    /* FUN_8001a91c */

#define BE_BIN   0x42494e20u   /* "BIN " */
#define BE_ANM   0x414e4d20u   /* "ANM " */
#define BE_SND   0x534e4420u   /* "SND " */

static inline uint32_t bswap32_le_to_be(uint32_t v)
{
    return (v >> 24) | ((v >> 8) & 0xff00u) | ((v & 0xff00u) << 8) | (v << 24);
}

void *XOBF_Parse(uint32_t remaining, int chainRegister)
{
    void *model = NULL;
    void *anim  = NULL;
    void *snd   = NULL;

    while (remaining != 0) {
        uint32_t hdr[2];
        uint32_t payloadSize = Iff_ReadChunkHeader(hdr, &remaining);
        uint32_t fcc = bswap32_le_to_be(hdr[0]);

        if (fcc == BE_BIN) {
            model = Heap_AllocOrRetry(payloadSize);
            Stream_Read(model, payloadSize);
        } else if (fcc == BE_ANM) {
            anim = Heap_AllocOrRetry(payloadSize);
            Stream_Read(anim, payloadSize);
        } else if (fcc == BE_SND) {
            uint32_t start = Stream_Tell();
            snd = Audio_ParseSND();
            Stream_Seek(start + payloadSize, 0);
        }
        /* unknown 4cc: implicit skip -- Iff_ReadChunkHeader has already
         * accounted for the bytes; we just don't consume the payload.
         * Strictly speaking we should Stream_Seek past, but the
         * original relies on the chunk-payload being absent for unknowns. */
    }

    void *obj = Renderer_BuildObject(model, anim);
    if (chainRegister != 0) DrawChain_Register(obj);
    if (snd != NULL) {
        *(void **)((uint8_t *)obj + 8) = snd;
    }
    return obj;
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- SLUS_005.10 FUN_8002263c  (from analysis/SLUS_005.10/decomp/8002263c.c) --- */
// addr: 0x8002263c  name: FUN_8002263c

int FUN_8002263c(int param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  uint uVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  int iVar7;
  int local_res0 [4];
  uint local_28 [2];
  
  uVar5 = 0;
  uVar6 = 0;
  iVar7 = 0;
  local_res0[0] = param_1;
joined_r0x8002266c:
  do {
    while( true ) {
      if (local_res0[0] == 0) {
        iVar1 = FUN_8001a640(uVar5,uVar6);
        if (param_2 != 0) {
          FUN_8001a91c(iVar1);
        }
        if (iVar7 != 0) {
          *(int *)(iVar1 + 8) = iVar7;
        }
        return iVar1;
      }
      iVar1 = FUN_80022524(local_28,local_res0);
      uVar4 = local_28[0] >> 0x18 | local_28[0] >> 8 & 0xff00 | (local_28[0] & 0xff00) << 8 |
              local_28[0] << 0x18;
      if (uVar4 != 0x42494e20) break;
      uVar2 = FUN_800116f4(iVar1);
      uVar5 = uVar2;
LAB_80022714:
      FUN_80015a20(uVar2,iVar1);
    }
    if (uVar4 < 0x42494e21) {
      if (uVar4 == 0x414e4d20) {
        uVar2 = FUN_800116f4(iVar1);
        uVar6 = uVar2;
        goto LAB_80022714;
      }
      goto joined_r0x8002266c;
    }
    if (uVar4 == 0x534e4420) {
      iVar3 = FUN_80015be4();
      iVar7 = FUN_800441f8();
      FUN_80015bf0(iVar3 + iVar1,0);
    }
  } while( true );
}

#endif  /* GHIDRA REF */
