/* xobf_health.c -- XOBF chunk loader: per-object health/maxHealth.
 *
 * Source: LOAD.DLL  FUN_80100d1c.
 *
 * Reads 1 or 2 i32 values from the XOBF stream (a payload-size > 4
 * means the second one is present) for health and maxHealth. If the
 * object type at +4 == 5 (= "scaled by difficulty") AND spawnId >= 0,
 * scales both values by (g_difficulty + 2)/4 = round-up integer
 * scaling. Then writes:
 *
 *   obj + 0xc = health     (matches our struct field)
 *   obj + 0xe = maxHealth  (matches our struct field)
 *
 * Also propagates parent's health to any child whose own health was
 * still 0 -- inheritance of the parent's HP when the child wasn't
 * explicitly given one.
 *
 * HIGH confidence: the +0xc / +0xe layout matches Damage_AccumulateOrFire
 * and our previously-fixed struct.
 */
#include <stdint.h>

extern int32_t XobfStream_ReadI32(void *streamRef);   /* func_0x800224ec */
extern int32_t DAT_8006531a;                        /* g_difficulty */

void XOBF_LoadHealth(int obj, void *payload, int payloadSize)
{
    uint8_t *o = (uint8_t *)(uintptr_t)obj;
    uint8_t *cursor = (uint8_t *)payload;
    int32_t health    = XobfStream_ReadI32(&cursor);
    int32_t maxHealth = health;
    if (payloadSize > 4) {
        maxHealth = XobfStream_ReadI32(&cursor);
    }

    if (*(int8_t *)(o + 4) == 5 && *(int16_t *)(o + 6) >= 0) {
        int32_t difficulty = DAT_8006531a + 2;
        int32_t v0 = health * difficulty;
        if (v0 < 0) v0 += 3;
        v0 >>= 2;
        int32_t v1 = maxHealth * difficulty;
        if (v1 < 0) v1 += 3;
        v1 >>= 2;
        health    = v0;
        maxHealth = v1;
    }

    *(int16_t *)(o + 0xc) = (int16_t)health;
    *(int16_t *)(o + 0xe) = (int16_t)maxHealth;

    /* Propagate to any child whose own health is still 0. */
    for (uint8_t *child = *(uint8_t **)(o + 0x38);
         child != NULL;
         child = *(uint8_t **)(child + 0x34)) {
        if (*(int16_t *)(child + 0xc) == 0) {
            *(int16_t *)(child + 0xc) = (int16_t)health;
        }
    }
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- LOAD.DLL FUN_80100d1c  (from analysis/dll/LOAD/decomp/80100d1c.c) --- */
// addr: 0x80100d1c  name: FUN_80100d1c

void FUN_80100d1c(int param_1,undefined4 param_2,int param_3)

{
  int iVar1;
  int iVar2;
  undefined4 local_res4 [3];
  
  local_res4[0] = param_2;
  iVar1 = func_0x800224ec(local_res4);
  if (4 < param_3) {
    func_0x800224ec(local_res4);
  }
  iVar2 = iVar1;
  if ((*(char *)(param_1 + 4) == '\x05') && (-1 < *(short *)(param_1 + 6))) {
    iVar2 = iVar1 * (DAT_8006531a + 2);
    iVar1 = iVar1 * (DAT_8006531a + 2);
    if (iVar2 < 0) {
      iVar2 = iVar2 + 3;
    }
    iVar2 = iVar2 >> 2;
    if (iVar1 < 0) {
      iVar1 = iVar1 + 3;
    }
    iVar1 = iVar1 >> 2;
  }
  *(short *)(param_1 + 0xc) = (short)iVar2;
  *(short *)(param_1 + 0xe) = (short)iVar1;
  for (iVar1 = *(int *)(param_1 + 0x38); iVar1 != 0; iVar1 = *(int *)(iVar1 + 0x34)) {
    if (*(short *)(iVar1 + 0xc) == 0) {
      *(short *)(iVar1 + 0xc) = (short)iVar2;
    }
  }
  return;
}

#endif  /* GHIDRA REF */
