/* xobf_helpers.c -- small XOBF/Object helper functions called by LOAD.DLL.
 *
 * Source: LOAD.DLL
 *   FUN_80100408  -- XOBF_AppendExtra: appends an XOBF object into the
 *                    global object table at the first free slot past
 *                    index 0x12 (so [0..0x11] = 18 slots reserved for
 *                    18 entries -- larger than the 14 vehicles; pass 2
 *                    will figure out what 14..17 are reserved for).
 *   FUN_801005e8  -- Terrain_LoadAimp: alloc+memcpy the AIMP navigation
 *                    quadtree and expose it via _DAT_800659f0 /
 *                    _DAT_800659e8 (ptr + size).
 *   FUN_80100594  -- XOBF_LoadFNT: hands the chunk body to the font
 *                    decoder (FUN_800187e4) and sets a default glyph
 *                    paint at DAT_800659d2 = 0x80.
 *   FUN_801005c0  -- Terrain_LoadBsp, implemented in load_helpers.c.
 *   FUN_8010243c  -- XOBF_AllocArray: alloc a (count * 0x10 + 0x30)-byte
 *                    record and store the count at off +0x1c. Generic
 *                    array-of-struct allocator.
 *   FUN_80100e20  -- XOBF_ReadCollisionBox: reads a 0x14-byte block at
 *                    `dst+0x80`: three i32 (cx, cy, cz) + three i16
 *                    (half-extents). Per-object collision AABB.
 *
 * HIGH-MED confidence on each.
 */
#include <stdint.h>

extern void *Heap_AllocOrRetry(uint32_t n);
extern void *V8_MemCopy(void *dst, const void *src, int n);
extern void *XOBF_Parse(uint32_t remaining, int chainRegister);
extern void  Font_DecodeFNT(void *src, void *dst);     /* FUN_800187e4 */
extern int32_t XobfStream_ReadI32(void *streamRef);     /* func_0x800224ec */
extern int16_t XobfStream_ReadI16(void *streamRef);     /* func_0x800224b4 */

extern void *DAT_800737a0[]; /* vehicle + extra-object array */
extern void *DAT_800737e8;
extern void *_DAT_800737e8;
extern void *_DAT_800659f0;
extern uint32_t _DAT_800659e8;
extern uint8_t   DAT_800659d2;
extern void    *_DAT_80065a00;
extern uint8_t   DAT_80065a28[];   /* font atlas storage */

/* HIGH: append an XOBF-parsed object after the reserved [0..0x12) slots. */
void XOBF_AppendExtra(uint32_t remaining)
{
    int idx = 0x12;
    if (DAT_800737a0[idx] != NULL) {
        /* Walk to first empty slot. */
        while (DAT_800737a0[++idx] != NULL) { /* nop */ }
    }
    DAT_800737a0[idx] = XOBF_Parse(remaining, 1);
    if (idx == 0x12) {
        DAT_800737e8 = DAT_800737a0[idx];
        _DAT_800737e8 = DAT_800737a0[idx];
    }
}

/* HIGH: LOAD 801005e8, AIMP navigation quadtree raw-copy loader. */
void Terrain_LoadAimp(const void *src, uint32_t size)
{
    _DAT_800659f0 = Heap_AllocOrRetry(size);
    V8_MemCopy(_DAT_800659f0, src, (int)size);
    _DAT_800659e8 = size;
}

/* Pass-1 name retained for old references. */
void XOBF_LoadBlob(const void *src, uint32_t size)
{
    Terrain_LoadAimp(src, size);
}

/* HIGH: pass an FNT body to the font decoder. */
void XOBF_LoadFNT(void *src)
{
    Font_DecodeFNT(src, DAT_80065a28);
    DAT_800659d2 = 0x80;
}

/* Deprecated pass-1 helper; source LOAD 801005c0 is Terrain_LoadBsp. */
void XOBF_StashReturn(uint32_t v0Latched)
{
    _DAT_80065a00 = (void *)(uintptr_t)v0Latched;
}

/* HIGH: array-of-struct allocator -- (count * 0x10 + 0x30) bytes. */
void *XOBF_AllocArray(int count)
{
    uint8_t *r = (uint8_t *)Heap_AllocOrRetry(count * 0x10 + 0x30);
    *(int *)(r + 0x1c) = count;
    return r;
}

/* HIGH: read a per-object collision AABB out of an XOBF stream into
 * the object at `+0x80..+0x91`:
 *   +0x80 i32 centerX
 *   +0x84 i32 centerY
 *   +0x88 i32 centerZ
 *   +0x8c i16 halfX
 *   +0x8e i16 halfY
 *   +0x90 i16 halfZ
 */
void XOBF_ReadCollisionBox(uint8_t *dst, void *payload)
{
    uint8_t *cursor = (uint8_t *)payload;
    *(int32_t *)(dst + 0x80) = XobfStream_ReadI32(&cursor);
    *(int32_t *)(dst + 0x84) = XobfStream_ReadI32(&cursor);
    *(int32_t *)(dst + 0x88) = XobfStream_ReadI32(&cursor);
    *(int16_t *)(dst + 0x8c) = XobfStream_ReadI16(&cursor);
    *(int16_t *)(dst + 0x8e) = XobfStream_ReadI16(&cursor);
    *(int16_t *)(dst + 0x90) = XobfStream_ReadI16(&cursor);
}

/* ============================================================
 * // GHIDRA REF (audit ground truth — DO NOT EDIT MANUALLY)
 *
 * These are the raw Ghidra pseudo-C exports for the function(s)
 * this file cleans up. Use them to audit any MED-confidence
 * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.
 * ============================================================ */
#if 0

/* --- ? FUN_80100408  (from analysis/dll/LOAD/decomp/80100408.c) --- */
// addr: 0x80100408  name: FUN_80100408

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_80100408(undefined4 param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  
  iVar3 = 0x12;
  if (_DAT_800737e8 != 0) {
    piVar2 = (int *)&DAT_800737e8;
    do {
      piVar2 = piVar2 + 1;
      iVar3 = iVar3 + 1;
    } while (*piVar2 != 0);
  }
  uVar1 = FUN_8002263c/*0x8002263c*/(param_1,1);
  *(undefined4 *)(&DAT_800737a0 + iVar3 * 4) = uVar1;
  return;
}

/* --- ? FUN_801005e8  (from analysis/dll/LOAD/decomp/801005e8.c) --- */
// addr: 0x801005e8  name: FUN_801005e8

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801005e8(undefined4 param_1,undefined4 param_2)

{
  _DAT_800659f0 = Heap_AllocOrRetry/*0x800116f4*/(param_2);
  V8_MemCopy/*0x80044c44*/(_DAT_800659f0,param_1,param_2);
  _DAT_800659e8 = param_2;
  return;
}

/* --- ? FUN_80100594  (from analysis/dll/LOAD/decomp/80100594.c) --- */
// addr: 0x80100594  name: FUN_80100594

void FUN_80100594(undefined4 param_1)

{
  FUN_800187e4/*0x800187e4*/(param_1,&DAT_80065a28);
  DAT_800659d2 = 0x80;
  return;
}

/* --- ? FUN_801005c0  (from analysis/dll/LOAD/decomp/801005c0.c) --- */
// addr: 0x801005c0  name: FUN_801005c0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_801005c0(void)

{
  undefined4 in_v0;
  
  _DAT_80065a00 = in_v0;
  return;
}

/* --- ? FUN_8010243c  (from analysis/dll/LOAD/decomp/8010243c.c) --- */
// addr: 0x8010243c  name: FUN_8010243c

void FUN_8010243c(int param_1)

{
  int iVar1;
  
  iVar1 = Heap_AllocOrRetry/*0x800116f4*/(param_1 * 0x10 + 0x30);
  *(int *)(iVar1 + 0x1c) = param_1;
  return;
}

/* --- ? FUN_80100e20  (from analysis/dll/LOAD/decomp/80100e20.c) --- */
// addr: 0x80100e20  name: FUN_80100e20

void FUN_80100e20(int param_1,undefined4 param_2)

{
  undefined2 uVar1;
  undefined4 uVar2;
  undefined4 local_res4 [3];
  
  local_res4[0] = param_2;
  uVar2 = func_0x800224ec(local_res4);
  *(undefined4 *)(param_1 + 0x80) = uVar2;
  uVar2 = func_0x800224ec(local_res4);
  *(undefined4 *)(param_1 + 0x84) = uVar2;
  uVar2 = func_0x800224ec(local_res4);
  *(undefined4 *)(param_1 + 0x88) = uVar2;
  uVar1 = func_0x800224b4(local_res4);
  *(undefined2 *)(param_1 + 0x8c) = uVar1;
  uVar1 = func_0x800224b4(local_res4);
  *(undefined2 *)(param_1 + 0x8e) = uVar1;
  uVar1 = func_0x800224b4(local_res4);
  *(undefined2 *)(param_1 + 0x90) = uVar1;
  return;
}

#endif  /* GHIDRA REF */
