#!/usr/bin/env python3
"""
restore_ghidra_refs.py -- re-attach Ghidra pseudo-C reference blocks
to MED-confidence cleaned files so they are auditable line-by-line.

Walks src/**/*.c. For each file:
  1. Look for "Source: <DLL> FUN_XXXXXXXX" or "Source: SLUS_005.10 FUN_XXXXXXXX"
     in the header comment block.
  2. Pull the matching analysis/<dll>/decomp/<addr>.c (or analysis/
     SLUS_005.10/decomp/<addr>.c) as the ground-truth pseudo-C.
  3. If the cleaned file does not already contain an `#if 0 // GHIDRA REF`
     block, append the ground truth as such a block.

This is idempotent: running twice does nothing the second time.
"""
import os
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
ANALYSIS = ROOT / "analysis"

# "Source: SLUS_005.10  FUN_8001392c" or "Source: AIRGRAVE.DLL  FUN_80100228"
SOURCE_RE = re.compile(
    r"\*\s*Source:\s*([A-Za-z0-9_.]+)(?:\.DLL)?\s+FUN_([0-9a-fA-F]+)",
    re.IGNORECASE,
)

# Catches FUN_XXXXXXXX and bare 0x80XXXXXX hex addresses in the header.
# The latter is needed for files like heap.c that say "@ 0x80044fbc".
ADDR_RE = re.compile(
    r"(?:FUN_|@\s*0x|address\s+0x|addr:\s*0x|\b0x)([0-9a-fA-F]{8})",
    re.IGNORECASE,
)

# "(AIRGRAVE)" or "(SHELL)" etc. for files that cite a DLL by name without
# the standard "Source:" prefix.
DLL_RE = re.compile(r"\b(AIRGRAVE|CANYNLND|CASNOCTY|HOOVRDAM|LOAD|OILFIELD|SANDFACT|SCRTBASE|SHELL|SKIRESRT|VALLYFRM|WILDWEST)\b")

REF_MARKER = "// GHIDRA REF (audit ground truth"


def find_analysis_file(dll_or_main: str, addr_hex: str) -> pathlib.Path | None:
    """Find the analysis/<dir>/decomp/<addr>.c for the given source tag."""
    addr = addr_hex.lower()
    # Main EXE
    if dll_or_main.upper() in ("SLUS_005.10", "SLUS00510", "SLUS"):
        p = ANALYSIS / "SLUS_005.10" / "decomp" / f"{addr}.c"
        return p if p.exists() else None

    # DLL
    name = dll_or_main.upper().replace(".DLL", "")
    p = ANALYSIS / "dll" / name / "decomp" / f"{addr}.c"
    if p.exists():
        return p

    # Fallback: search by addr only across all DLLs (some files cite a DLL
    # name informally).
    for dll_dir in (ANALYSIS / "dll").iterdir():
        cand = dll_dir / "decomp" / f"{addr}.c"
        if cand.exists():
            return cand
    return None


def already_has_ref(content: str) -> bool:
    return REF_MARKER in content


def collect_sources(content: str) -> list[tuple[str, str]]:
    """Return [(dll_or_main, addr), ...] for every cite in the file header."""
    sources = []
    # Pull first ~60 lines (the header comment is always near the top).
    head = "\n".join(content.splitlines()[:80])

    # 1. Explicit "Source: ... FUN_xxx" citations -- highest confidence.
    for m in SOURCE_RE.finditer(head):
        sources.append((m.group(1), m.group(2)))

    # 2. Bare hex addresses in the header (e.g. "@ 0x80044fbc"). Use the
    #    closest DLL marker before each addr as the source, else default
    #    to SLUS_005.10 for 0x80000000-0x800fffff range (main EXE) and
    #    use a fallback search for 0x80100000+ (overlay range).
    default_dll = "SLUS_005.10"
    if DLL_RE.search(head):
        default_dll = DLL_RE.search(head).group(1)
    for m in ADDR_RE.finditer(head):
        addr = m.group(1)
        # Skip if already added via Source: ... rule.
        if any(s[1].lower() == addr.lower() for s in sources):
            continue
        addr_int = int(addr, 16)
        if 0x80000000 <= addr_int < 0x80100000:
            sources.append(("SLUS_005.10", addr))
        else:
            sources.append((default_dll, addr))

    # de-dup, preserving order
    seen = set()
    out = []
    for s in sources:
        key = s[1].lower()
        if key not in seen:
            seen.add(key)
            out.append(s)
    return out


def build_ref_block(refs: list[tuple[pathlib.Path, str, str]]) -> str:
    parts = [
        "",
        "/* ============================================================",
        " * " + REF_MARKER + " — DO NOT EDIT MANUALLY)",
        " *",
        " * These are the raw Ghidra pseudo-C exports for the function(s)",
        " * this file cleans up. Use them to audit any MED-confidence",
        " * rewrite line-by-line. Regenerated by tools/restore_ghidra_refs.py.",
        " * ============================================================ */",
        "#if 0",
        "",
    ]
    for path, dll, addr in refs:
        rel = path.relative_to(ROOT).as_posix()
        parts.append(f"/* --- {dll} FUN_{addr.lower()}  (from {rel}) --- */")
        parts.append(path.read_text(encoding="utf-8", errors="replace").rstrip())
        parts.append("")
    parts.append("#endif  /* GHIDRA REF */")
    parts.append("")
    return "\n".join(parts)


def process_file(path: pathlib.Path) -> str:
    """Returns "skip", "attached", or "no-source"."""
    content = path.read_text(encoding="utf-8", errors="replace")
    if already_has_ref(content):
        return "skip"

    sources = collect_sources(content)
    refs = []
    for dll, addr in sources:
        a = find_analysis_file(dll, addr)
        if a:
            refs.append((a, dll, addr))

    if not refs:
        return "no-source"

    block = build_ref_block(refs)
    # Ensure trailing newline before block.
    if not content.endswith("\n"):
        content += "\n"
    new = content + block
    path.write_text(new, encoding="utf-8")
    return "attached"


def main():
    stats = {"attached": 0, "skip": 0, "no-source": 0, "total": 0}
    no_source = []
    for c in SRC.rglob("*.c"):
        # Skip the skipped/ seam docs; they don't have a single source FUN_x.
        if "skipped" in c.parts:
            continue
        stats["total"] += 1
        r = process_file(c)
        stats[r] += 1
        if r == "no-source":
            no_source.append(c.relative_to(ROOT).as_posix())

    print(f"Total C files scanned:    {stats['total']}")
    print(f"Already had ref block:    {stats['skip']}")
    print(f"Newly attached refs:      {stats['attached']}")
    print(f"No matching source found: {stats['no-source']}")
    if no_source:
        print("\nFiles with no source citation or unresolvable address:")
        for f in no_source[:30]:
            print(f"  {f}")
        if len(no_source) > 30:
            print(f"  ... and {len(no_source) - 30} more")


if __name__ == "__main__":
    main()
